import Link from 'next/link'
import { BookOpenCheck,BriefcaseBusiness,CalendarDays,HandHeart,ShieldCheck,UserCog } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { overrideCourseEnrollment,updateMemberAccessFromRecord,updateMemberBusinessFromRecord,updateMemberMinistryApplication,updateMemberProfileFromRecord } from './admin-actions'

const roleOptions={en:[['member','Member'],['group_leader','Group leader'],['ministry_leader','Ministry leader'],['minister','Minister'],['pastor','Pastor'],['church_admin','Church admin']],es:[['member','Miembro'],['group_leader','Líder de grupo'],['ministry_leader','Líder de ministerio'],['minister','Ministro'],['pastor','Pastor'],['church_admin','Administrador de iglesia']]} as const
const memberStatuses={en:[['active','Active'],['visitor','Visitor'],['pending','Pending'],['inactive','Inactive']],es:[['active','Activo'],['visitor','Visitante'],['pending','Pendiente'],['inactive','Inactivo']]} as const
const applicationStatuses={en:[['submitted','Submitted'],['qualified','Qualified'],['interview','Interview'],['accepted','Accepted'],['declined','Declined'],['withdrawn','Withdrawn']],es:[['submitted','Enviada'],['qualified','Calificado'],['interview','Entrevista'],['accepted','Aceptado'],['declined','Rechazado'],['withdrawn','Retirado']]} as const
const businessStatuses={en:[['pending','Pending review'],['active','Active'],['inactive','Inactive']],es:[['pending','Pendiente de revisión'],['active','Activo'],['inactive','Inactivo']]} as const
const date=(v?:string|null)=>v?String(v).slice(0,10):''

export async function AdminControlPanels({churchId,userId,actorRole,membership,profile,details,lang}:{churchId:string;userId:string;actorRole:string;membership:any;profile:any;details:any;lang:'en'|'es'}){
  const es=lang==='es'
  const supabase=await createClient()
  const [{data:courses},{data:enrollments},{data:applications},{data:assignments},{data:businesses}]=await Promise.all([
    supabase.from('courses').select('id,title,published').eq('church_id',churchId).order('title'),
    supabase.from('course_enrollments').select('course_id,progress,final_score,completed_at,credential_earned,admin_override_by,admin_override_at,admin_override_reason').eq('user_id',userId),
    supabase.from('ministry_applications').select('id,ministry_id,status,qualification_score,review_note,submitted_at,ministries(name,church_id)').eq('user_id',userId).order('submitted_at',{ascending:false}),
    supabase.from('team_assignments').select('id,title,starts_at,call_time,confirmed_at,ministry_id,ministries(name)').eq('church_id',churchId).eq('assigned_user_id',userId).order('starts_at',{ascending:false}).limit(10),
    supabase.from('business_listings').select('id,name,status,is_verified,is_member_business,is_sponsored,category,city,state,updated_at').eq('church_id',churchId).eq('owner_user_id',userId).order('created_at',{ascending:false})
  ])
  const courseMap=new Map((courses??[]).map((c:any)=>[c.id,c]))
  const enrollmentMap=new Map((enrollments??[]).map((e:any)=>[e.course_id,e]))
  const q=`?lang=${lang}`

  return <section style={{display:'grid',gap:14,marginBottom:18}}>
    <div className="section-heading"><div><div className="pill">{es?'CONTROLES DE LIDERAZGO':'LEADERSHIP CONTROLS'}</div><h2>{es?'Centro de Control del Miembro':'Member Control Center'}</h2></div><span className="small muted">{es?'Solo pastor / administrador':'Pastor / Church Admin only'}</span></div>

    <section className="card record-section"><div className="record-section-head"><div><ShieldCheck/><div><h2>{es?'Rol y acceso':'Role & access'}</h2><p>{es?'Corrige el rol real de la persona y su estado de acceso.':'Correct the person’s real church role and access status.'}</p></div></div><span className="verified-label">{es?'LIDERAZGO':'LEADERSHIP'}</span></div>
      <form action={updateMemberAccessFromRecord} className="record-grid"><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="user_id" value={userId}/><input type="hidden" name="membership_id" value={membership.id}/><input type="hidden" name="lang" value={lang}/>
        <label className="record-field"><span>{es?'Rol de iglesia':'Church role'}</span><select name="role" defaultValue={membership.role}>{roleOptions[lang].filter(([v])=>actorRole==='pastor'||v!=='pastor').map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
        <label className="record-field"><span>{es?'Estado de acceso':'Access status'}</span><select name="status" defaultValue={membership.status}>{memberStatuses[lang].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
        <div style={{gridColumn:'1/-1',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><span className="small muted">{actorRole==='pastor'?(es?'Puedes administrar todos los roles.':'You can manage all church roles.'):(es?'Solo un pastor puede asignar o cambiar el rol Pastor.':'Only a Pastor can assign or change the Pastor role.')}</span><button className="btn" type="submit">{es?'Guardar acceso':'Save access'}</button></div>
      </form>
    </section>

    <section className="card record-section"><div className="record-section-head"><div><UserCog/><div><h2>{es?'Corregir perfil y contacto':'Correct profile & contact'}</h2><p>{es?'Edita errores de nombre, teléfono, dirección y fechas. El correo de contacto no cambia el correo de inicio de sesión.':'Fix name, phone, address and date errors. Contact email does not change the login email.'}</p></div></div></div>
      <form action={updateMemberProfileFromRecord} className="record-grid"><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="user_id" value={userId}/><input type="hidden" name="lang" value={lang}/>
        <label className="record-field"><span>{es?'Nombre':'First name'}</span><input name="first_name" defaultValue={profile?.first_name??''}/></label><label className="record-field"><span>{es?'Apellido':'Last name'}</span><input name="last_name" defaultValue={profile?.last_name??''}/></label>
        <label className="record-field"><span>{es?'Nombre mostrado':'Display name'}</span><input name="display_name" defaultValue={profile?.display_name??''}/></label><label className="record-field"><span>{es?'Correo de contacto':'Contact email'}</span><input name="email" type="email" defaultValue={details?.email??''}/></label>
        <label className="record-field"><span>{es?'Teléfono':'Phone'}</span><input name="phone" defaultValue={details?.phone??''}/></label><label className="record-field"><span>{es?'Dirección 1':'Address line 1'}</span><input name="address_line1" defaultValue={details?.address_line1??''}/></label>
        <label className="record-field"><span>{es?'Dirección 2':'Address line 2'}</span><input name="address_line2" defaultValue={details?.address_line2??''}/></label><label className="record-field"><span>{es?'Ciudad':'City'}</span><input name="city" defaultValue={details?.city??''}/></label>
        <label className="record-field"><span>{es?'Estado':'State'}</span><input name="state" defaultValue={details?.state??''}/></label><label className="record-field"><span>{es?'Código postal':'Postal code'}</span><input name="postal_code" defaultValue={details?.postal_code??''}/></label>
        <label className="record-field"><span>{es?'Cumpleaños':'Birthday'}</span><input type="date" name="birthday" defaultValue={details?.birthday??''}/></label><label className="record-field"><span>{es?'Aniversario':'Marriage anniversary'}</span><input type="date" name="marriage_anniversary" defaultValue={details?.marriage_anniversary??''}/></label>
        <label className="record-field" style={{gridColumn:'1/-1'}}><span>Bio</span><input name="bio" defaultValue={profile?.bio??''}/></label>
        <div style={{gridColumn:'1/-1',display:'flex',justifyContent:'flex-end'}}><button className="btn">{es?'Guardar correcciones':'Save corrections'}</button></div>
      </form>
    </section>

    <section className="card record-section"><div className="record-section-head"><div><BookOpenCheck/><div><h2>{es?'Correcciones de clases':'Class corrections'}</h2><p>{es?'Usa esto solo cuando liderazgo haya verificado que el registro automático está incorrecto o que una clase fue completada fuera del sistema.':'Use this only when leadership verified the automatic record is wrong or the class was completed outside the system.'}</p></div></div><span className="verified-label">{es?'RAZÓN REQUERIDA':'REASON REQUIRED'}</span></div>
      <div style={{display:'grid',gap:10}}>{(enrollments??[]).map((e:any)=>{const c:any=courseMap.get(e.course_id);return <details className="card" style={{padding:14}} key={e.course_id}><summary style={{cursor:'pointer',fontWeight:800}}>{c?.title??(es?'Curso':'Course')} • {e.progress??0}% {e.credential_earned?(es?'• Credencial obtenida':'• Credential earned'):''}</summary><form action={overrideCourseEnrollment} className="record-grid" style={{marginTop:14}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="user_id" value={userId}/><input type="hidden" name="course_id" value={e.course_id}/><input type="hidden" name="lang" value={lang}/><label className="record-field"><span>{es?'Progreso':'Progress %'}</span><input name="progress" type="number" min="0" max="100" defaultValue={e.progress??0}/></label><label className="record-field"><span>{es?'Puntaje final':'Final score'}</span><input name="final_score" type="number" min="0" max="100" defaultValue={e.final_score??''}/></label><label className="record-field"><span>{es?'Fecha completada':'Completed date'}</span><input name="completed_at" type="date" defaultValue={date(e.completed_at)}/></label><label className="record-field"><span>{es?'Credencial':'Credential'}</span><select name="credential_earned" defaultValue={e.credential_earned?'yes':'no'}><option value="no">{es?'No obtenida':'Not earned'}</option><option value="yes">{es?'Obtenida':'Earned'}</option></select></label><label className="record-field" style={{gridColumn:'1/-1'}}><span>{es?'Razón de corrección':'Correction reason'}</span><input name="override_reason" required placeholder={es?'Ej. completó la clase presencial antes de usar Kingdom Network':'Example: completed the in-person class before Kingdom Network'}/></label>{e.admin_override_reason&&<div className="small muted" style={{gridColumn:'1/-1'}}>{es?'Última corrección manual':'Last manual correction'}: {e.admin_override_reason}</div>}<div style={{gridColumn:'1/-1',display:'flex',justifyContent:'flex-end'}}><button className="btn">{es?'Guardar corrección':'Save correction'}</button></div></form></details>})}
        <details className="card" style={{padding:14}}><summary style={{cursor:'pointer',fontWeight:800}}>{es?'Agregar o corregir otro curso':'Add or correct another course'}</summary><form action={overrideCourseEnrollment} className="record-grid" style={{marginTop:14}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="user_id" value={userId}/><input type="hidden" name="lang" value={lang}/><label className="record-field" style={{gridColumn:'1/-1'}}><span>{es?'Curso':'Course'}</span><select name="course_id" required defaultValue=""><option value="" disabled>{es?'Selecciona un curso':'Select a course'}</option>{(courses??[]).filter((c:any)=>!enrollmentMap.has(c.id)).map((c:any)=><option value={c.id} key={c.id}>{c.title}{c.published?'':' • draft'}</option>)}</select></label><label className="record-field"><span>{es?'Progreso':'Progress %'}</span><input name="progress" type="number" min="0" max="100" defaultValue="100"/></label><label className="record-field"><span>{es?'Puntaje final':'Final score'}</span><input name="final_score" type="number" min="0" max="100"/></label><label className="record-field"><span>{es?'Fecha completada':'Completed date'}</span><input name="completed_at" type="date"/></label><label className="record-field"><span>{es?'Credencial':'Credential'}</span><select name="credential_earned" defaultValue="yes"><option value="yes">{es?'Obtenida':'Earned'}</option><option value="no">{es?'No obtenida':'Not earned'}</option></select></label><label className="record-field" style={{gridColumn:'1/-1'}}><span>{es?'Razón de corrección':'Correction reason'}</span><input name="override_reason" required/></label><div style={{gridColumn:'1/-1',display:'flex',justifyContent:'flex-end'}}><button className="btn">{es?'Guardar corrección':'Save correction'}</button></div></form></details>
      </div>
    </section>

    <section className="card record-section"><div className="record-section-head"><div><HandHeart/><div><h2>{es?'Servicio y ministerio':'Service & ministry'}</h2><p>{es?'Revisa solicitudes, aceptación y asignaciones del miembro.':'Review applications, acceptance and current team assignments.'}</p></div></div><Link className="ghost" href={`/teams?member=${userId}`}>{es?'Abrir Teams →':'Open Teams →'}</Link></div>
      <div style={{display:'grid',gap:10}}>{(applications??[]).map((a:any)=>{const m:any=Array.isArray(a.ministries)?a.ministries[0]:a.ministries;return <form action={updateMemberMinistryApplication} className="card" style={{padding:14,display:'grid',gap:9}} key={a.id}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="user_id" value={userId}/><input type="hidden" name="application_id" value={a.id}/><input type="hidden" name="lang" value={lang}/><div className="row" style={{justifyContent:'space-between',flexWrap:'wrap'}}><strong>{m?.name??(es?'Ministerio':'Ministry')}</strong><span className="small muted">{es?'Calificación':'Qualification'} {a.qualification_score??0}%</span></div><div className="record-grid"><label className="record-field"><span>{es?'Estado':'Status'}</span><select name="status" defaultValue={a.status}>{applicationStatuses[lang].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="record-field"><span>{es?'Nota de revisión':'Review note'}</span><input name="review_note" defaultValue={a.review_note??''}/></label></div><div style={{display:'flex',justifyContent:'flex-end'}}><button className="ghost">{es?'Guardar ministerio':'Save ministry status'}</button></div></form>})}{!applications?.length&&<p className="small muted">{es?'No hay solicitudes de ministerio para este miembro.':'No ministry applications for this member.'}</p>}</div>
      <div style={{marginTop:14}}><div className="pill"><CalendarDays size={11}/> {es?'ASIGNACIONES RECIENTES':'RECENT ASSIGNMENTS'}</div>{(assignments??[]).map((a:any)=><div key={a.id} style={{padding:'9px 0',borderBottom:'1px solid var(--line)'}}><strong>{a.title}</strong><div className="small muted">{new Date(a.starts_at).toLocaleDateString(es?'es-US':'en-US')} • {a.confirmed_at?(es?'Confirmado':'Confirmed'):(es?'Sin confirmar':'Not confirmed')}</div></div>)}{!assignments?.length&&<p className="small muted">{es?'Sin asignaciones todavía.':'No team assignments yet.'}</p>}</div>
    </section>

    <section className="card record-section"><div className="record-section-head"><div><BriefcaseBusiness/><div><h2>{es?'Negocios del miembro':'Member businesses'}</h2><p>{es?'Liderazgo controla la verificación y si el negocio aparece activo en el directorio.':'Leadership controls verification and whether the listing is active in the directory.'}</p></div></div><Link className="ghost" href={`/business${q}`}>{es?'Abrir directorio →':'Open directory →'}</Link></div>
      <div style={{display:'grid',gap:10}}>{(businesses??[]).map((b:any)=><form action={updateMemberBusinessFromRecord} className="card" style={{padding:14}} key={b.id}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="user_id" value={userId}/><input type="hidden" name="business_id" value={b.id}/><input type="hidden" name="lang" value={lang}/><div className="row" style={{justifyContent:'space-between',flexWrap:'wrap',marginBottom:10}}><div><strong>{b.name}</strong><div className="small muted">{[b.category,b.city,b.state].filter(Boolean).join(' • ')}</div></div><span className="small muted">{b.is_verified?(es?'Verificado':'Verified'):(es?'No verificado':'Not verified')}</span></div><div className="record-grid"><label className="record-field"><span>{es?'Estado':'Status'}</span><select name="status" defaultValue={b.status}>{businessStatuses[lang].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="record-field"><span>{es?'Verificación':'Verification'}</span><select name="is_verified" defaultValue={b.is_verified?'yes':'no'}><option value="no">{es?'No verificado':'Not verified'}</option><option value="yes">{es?'Verificado por iglesia':'Church verified'}</option></select></label></div><div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><button className="ghost">{es?'Guardar negocio':'Save business'}</button></div></form>)}{!businesses?.length&&<p className="small muted">{es?'Este miembro todavía no tiene un negocio registrado.':'This member does not have a business listing yet.'}</p>}</div>
    </section>
  </section>
}
