import { ClipboardCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { saveBibleStudyPracticum } from './practicum-actions'

const areas={en:[['preparation','Preparation'],['scripture_navigation','Scripture navigation'],['biblical_accuracy','Biblical accuracy'],['clarity','Clarity'],['listening','Listening'],['stays_on_topic','Stays on topic'],['humility_respect','Humility & respect'],['checks_understanding','Checks understanding'],['follow_up_readiness','Follow-up readiness']],es:[['preparation','Preparación'],['scripture_navigation','Navegación bíblica'],['biblical_accuracy','Precisión bíblica'],['clarity','Claridad'],['listening','Escucha'],['stays_on_topic','Se mantiene en el tema'],['humility_respect','Humildad y respeto'],['checks_understanding','Comprueba comprensión'],['follow_up_readiness','Preparación para seguimiento']]} as const
const labels={en:{needs_practice:'Needs practice',partner_ready:'Ready with a partner',independent_ready:'Ready independently',approved:'Approved'},es:{needs_practice:'Necesita práctica',partner_ready:'Listo con un compañero',independent_ready:'Listo independientemente',approved:'Aprobado'}} as const

export async function BibleStudyPracticum({userId,churchId,lang='en'}:{userId:string;churchId:string;lang?:'en'|'es'}){
  const es=lang==='es'
  const supabase=await createClient()
  const {data:rows}=await supabase.from('bible_study_practicums').select('id,study_lesson,language_code,practiced_at,score_percent,recommendation,notes,evaluator_user_id,profiles:evaluator_user_id(display_name,first_name,last_name)').eq('church_id',churchId).eq('trainee_user_id',userId).order('practiced_at',{ascending:false}).limit(10)
  return <section className="card record-section" style={{marginBottom:16}}>
    <div className="record-section-head"><div><ClipboardCheck/><div><h2>{es?'Práctica de Maestro de Estudio Bíblico':'Bible Study Teacher Practicum'}</h2><p>{es?'Observe un estudio de práctica y documente la preparación antes de enseñar independientemente.':'Observe a practice study and document readiness before independent teaching.'}</p></div></div><span className="verified-label">{es?'PUNTAJE 1–5':'1–5 SCORE'}</span></div>
    <form action={saveBibleStudyPracticum} className="record-form">
      <input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="trainee_user_id" value={userId}/><input type="hidden" name="lang" value={lang}/>
      <div className="record-grid"><label className="record-field"><span>{es?'Estudio / lección practicada':'Study / lesson practiced'}</span><input name="study_lesson" placeholder={es?'ej. Lección 2 — Arrepentimiento':'e.g. Lesson 2 — Repentance'}/></label><label className="record-field"><span>{es?'Idioma':'Language'}</span><select name="language_code" defaultValue={lang}><option value="en">English</option><option value="es">Español</option></select></label></div>
      <div className="record-grid">{areas[lang].map(([name,label])=><label className="record-field" key={name}><span>{label}</span><select name={name} defaultValue="3" required><option value="1">1 — {es?'Necesita mucha orientación':'Needs major coaching'}</option><option value="2">2 — {es?'En desarrollo':'Developing'}</option><option value="3">3 — {es?'Competente':'Competent'}</option><option value="4">4 — {es?'Fuerte':'Strong'}</option><option value="5">5 — {es?'Excelente':'Excellent'}</option></select></label>)}</div>
      <div className="record-grid"><label className="record-field"><span>{es?'Recomendación':'Recommendation'}</span><select name="recommendation" defaultValue="needs_practice"><option value="needs_practice">{es?'Necesita práctica':'Needs practice'}</option><option value="partner_ready">{es?'Listo con un compañero':'Ready with a partner'}</option><option value="independent_ready">{es?'Listo independientemente':'Ready independently'}</option><option value="approved">{es?'Maestro de Estudio Bíblico aprobado':'Approved Bible Study Teacher'}</option></select></label><label className="record-field"><span>{es?'Notas de orientación':'Coaching notes'}</span><input name="notes" placeholder={es?'Fortalezas, correcciones, próxima meta de práctica…':'Strengths, corrections, next practice goal…'}/></label></div>
      <div><button className="btn" type="submit">{es?'Guardar evaluación práctica':'Save practicum scorecard'}</button></div>
    </form>
    <div style={{marginTop:18}}><div className="pill">{es?'HISTORIAL DE PRÁCTICA':'PRACTICUM HISTORY'}</div>{(rows??[]).length?<div style={{display:'grid',gap:8,marginTop:10}}>{(rows??[]).map((r:any)=>{const p=Array.isArray(r.profiles)?r.profiles[0]:r.profiles;const evaluator=p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||(es?'Liderazgo':'Leadership');return <div className="card" style={{padding:12}} key={r.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>{r.study_lesson||(es?'Estudio bíblico de práctica':'Practice Bible study')}</strong><strong>{Math.round(Number(r.score_percent))}% • {labels[lang][r.recommendation as keyof typeof labels.en]??r.recommendation}</strong></div><div className="small muted" style={{marginTop:4}}>{new Date(r.practiced_at).toLocaleDateString(es?'es-US':'en-US')} • {r.language_code==='es'?'Español':'English'} • {es?'Evaluado por':'Evaluated by'} {evaluator}</div>{r.notes&&<p style={{margin:'7px 0 0'}}>{r.notes}</p>}</div>})}</div>:<p className="small muted" style={{marginTop:10}}>{es?'Aún no hay evaluaciones prácticas.':'No practicum scorecards yet.'}</p>}</div>
  </section>
}
