import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BriefcaseBusiness,CheckCircle2,Clock3,ExternalLink,Languages,Mail,MessageSquareWarning,Phone,Plus } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'

async function addBusiness(formData:FormData){'use server';const lang=String(formData.get('lang')??'')==='es'?'es':'en';const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect(`/login?lang=${lang}`);const {data:m}=await supabase.from('church_memberships').select('church_id').eq('user_id',userId).eq('status','active').limit(1).single();if(!m?.church_id)redirect('/');const {error}=await supabase.from('business_listings').insert({church_id:m.church_id,owner_user_id:userId,name:String(formData.get('name')||'').trim(),category:String(formData.get('category')||'').trim()||null,description:String(formData.get('description')||'').trim()||null,phone:String(formData.get('phone')||'').trim()||null,email:String(formData.get('email')||'').trim()||null,website:String(formData.get('website')||'').trim()||null,city:String(formData.get('city')||'').trim()||null,state:String(formData.get('state')||'').trim()||null,is_member_business:true,is_sponsored:false,is_verified:false,status:'pending'});if(error)redirect(`/business?lang=${lang}&error=${encodeURIComponent(error.message)}`);redirect(`/business?lang=${lang}&added=1`)}

export default async function BusinessPage({searchParams}:{searchParams:Promise<{added?:string;error?:string;lang?:string}>}){
  const params=await searchParams,es=params.lang==='es',t=(en:string,sp:string)=>es?sp:en,l=(path:string)=>es?`${path}${path.includes('?')?'&':'?'}lang=es`:path
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect(l('/login'))
  const {data:m}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!m?.church_id)redirect('/')
  const [{data:listings},{data:mine}]=await Promise.all([supabase.from('business_listings').select('*').eq('church_id',m.church_id).eq('status','active').order('is_member_business',{ascending:false}).order('is_verified',{ascending:false}).order('name'),supabase.from('business_listings').select('*').eq('church_id',m.church_id).eq('owner_user_id',userId).order('created_at',{ascending:false})])
  const church:any=Array.isArray(m.churches)?m.churches[0]:m.churches,isAdmin=['pastor','church_admin'].includes(m.role)
  const listingStatus=(b:any)=>b.status==='pending'?t('Pending church review','Pendiente de revisión'):b.status==='active'?(b.is_verified?t('Active • Verified','Activo • Verificado'):t('Active','Activo')):t('Inactive','Inactivo')

  return <main className="shell"><header className="topbar"><div><div className="brand">Business <span>Partners</span></div><div className="small muted">{t('Support the people who worship and serve beside you.','Apoya a las personas que adoran y sirven contigo.')}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/business?lang=en">English</Link><Link className="ghost" href="/business?lang=es">Español</Link>{isAdmin&&<Link className="ghost" href={l('/church/member-control')}>{t('Member Control','Control de Miembros')}</Link>}<Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/>{t('Feedback','Comentarios')}</Link><Link className="ghost" href={l('/')}>← {t('Home','Inicio')}</Link></div></header>

  <section className="hero card"><div><div className="pill">{t('MEMBER FIRST','MIEMBROS PRIMERO')}</div><h1>{t('Church Business Directory','Directorio de Negocios de la Iglesia')}</h1><p>{t(`Discover businesses owned by members of ${church?.name||'your church'}. Member listings are free and receive priority.`,`Descubre negocios de miembros de ${church?.name||'tu iglesia'}. Los anuncios de miembros son gratis y tienen prioridad.`)}</p></div><BriefcaseBusiness size={42}/></section>
  {params.added&&<div className="notice success">{t('Business submitted. Church leadership will verify it before it appears publicly in the directory.','Negocio enviado. El liderazgo lo verificará antes de que aparezca públicamente en el directorio.')}</div>}{params.error&&<div className="notice error">{params.error}</div>}

  <section className="card" style={{padding:18,marginBottom:20,display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap'}}><div><div className="pill">{t('LOCAL CONNECTIONS','CONEXIONES LOCALES')}</div><h2 style={{margin:'8px 0 4px'}}>{t(`${listings?.length||0} active business${listings?.length===1?'':'es'}`,`${listings?.length||0} negocio${listings?.length===1?'':'s'} activo${listings?.length===1?'':'s'}`)}</h2><p className="small muted" style={{margin:0}}>{t('Verified member businesses appear first. Member listings always keep priority over future sponsored partners.','Los negocios verificados de miembros aparecen primero. Los miembros siempre tendrán prioridad sobre futuros patrocinadores.')}</p></div></section>

  <div style={{display:'grid',gap:14}}>{(listings??[]).map((b:any)=><article className="card" key={b.id} style={{padding:20}}><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><div className="row">{b.is_member_business&&<span className="pill">{t('CHURCH MEMBER','MIEMBRO DE LA IGLESIA')}</span>}{b.is_verified&&<span className="pill"><CheckCircle2 size={12}/> {t('VERIFIED','VERIFICADO')}</span>}</div><h2 style={{marginBottom:4}}>{b.name}</h2><div className="muted">{[b.category,b.city,b.state].filter(Boolean).join(' • ')}</div></div></div>{b.description&&<p>{b.description}</p>}<div className="row">{b.phone&&<a className="ghost" href={`tel:${b.phone}`}><Phone size={14}/> {t('Call','Llamar')}</a>}{b.email&&<a className="ghost" href={`mailto:${b.email}`}><Mail size={14}/> {t('Email','Correo')}</a>}{b.website&&<a className="ghost" href={b.website.startsWith('http')?b.website:`https://${b.website}`} target="_blank" rel="noreferrer"><ExternalLink size={14}/> {t('Website','Sitio web')}</a>}</div></article>)}{!listings?.length&&<div className="card" style={{padding:24}}><h3>{t('No active businesses yet.','Todavía no hay negocios activos.')}</h3><p className="muted">{t('Member submissions appear here after church verification.','Los negocios de miembros aparecerán aquí después de la verificación.')}</p></div>}</div>

  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14,marginTop:22}}><details className="card side"><summary style={{fontWeight:800,cursor:'pointer'}}><Plus size={14}/> {t('Add my business','Agregar mi negocio')}</summary><form action={addBusiness} style={{display:'grid',gap:10,marginTop:14}}><input type="hidden" name="lang" value={es?'es':'en'}/><h3>{t('Free member listing','Anuncio gratis para miembros')}</h3><p className="muted">{t('Submit the basics. Leadership verifies it before it appears in the directory.','Envía la información básica. Liderazgo la verifica antes de publicarla.')}</p><input name="name" placeholder={t('Business name','Nombre del negocio')} required/><input name="category" placeholder={t('What do you do?','¿Qué haces?')}/><textarea name="description" placeholder={t('Short description','Descripción breve')} rows={3}/><input name="phone" placeholder={t('Phone','Teléfono')}/><input name="email" type="email" placeholder={t('Email','Correo')}/><input name="website" placeholder={t('Website','Sitio web')}/><div className="row"><input name="city" placeholder={t('City','Ciudad')} style={{minWidth:0}}/><input name="state" placeholder={t('State','Estado')} style={{minWidth:0}}/></div><button className="btn" type="submit">{t('Submit my business','Enviar mi negocio')}</button><small className="muted">{t('Member listings are free. Sponsored listings are reserved for a future church-approved program.','Los anuncios de miembros son gratis. Los patrocinadores externos serán parte de un programa futuro aprobado por la iglesia.')}</small></form></details>

  <section className="card side"><div className="pill">{t('MY LISTINGS','MIS NEGOCIOS')}</div>{(mine??[]).map((b:any)=><div key={b.id} style={{padding:'10px 0',borderBottom:'1px solid var(--line)'}}><strong>{b.name}</strong><div className="small muted" style={{marginTop:4}}>{b.status==='pending'&&<Clock3 size={11} style={{verticalAlign:'middle',marginRight:4}}/>}{listingStatus(b)}</div></div>)}{!mine?.length&&<p className="small muted">{t('You have not submitted a business yet.','Todavía no has enviado un negocio.')}</p>}</section></section>
  </main>
}