'use client'

import { useState } from 'react'
import { Inbox,Upload } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-120)
const split=(v:FormDataEntryValue|null)=>String(v??'').split(',').map(x=>x.trim()).filter(Boolean)
const titleFromFile=(name:string)=>name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim().replace(/\b\w/g,c=>c.toUpperCase())
const inferType=(file:File)=>{const n=file.name.toLowerCase(),t=file.type.toLowerCase();if(n.includes('flyer'))return'flyer';if(n.includes('invite')||n.includes('invitation'))return'invitation';if(n.includes('sermon')&&(n.includes('cover')||n.includes('graphic')))return'sermon_cover';if(n.includes('fundraiser'))return'fundraiser';if(t.startsWith('image/'))return'photo';if(t.startsWith('video/'))return'video';if(t.startsWith('audio/'))return'audio';if(n.endsWith('.ppt')||n.endsWith('.pptx'))return'slides';return'other'}
const inferTags=(name:string)=>name.toLowerCase().replace(/\.[^.]+$/,'').split(/[^a-z0-9]+/).filter(x=>x.length>2&&!['the','and','for','with','image','photo','final','copy'].includes(x)).slice(0,8)

export function MediaUploader({churchId,userId,canApproveOfficial}:{churchId:string;userId:string;canApproveOfficial:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('')
 async function submit(formData:FormData){
  const file=formData.get('file') as File|null;if(!file||!file.size){setMessage('Choose a file first.');return}if(file.size>50*1024*1024){setMessage('File must be 50 MB or smaller.');return}
  setBusy(true);setMessage('');const supabase=createClient(),path=`${churchId}/${userId}/${crypto.randomUUID()}/${safe(file.name)}`
  const upload=await supabase.storage.from('resource-library').upload(path,file,{contentType:file.type,upsert:false});if(upload.error){setMessage(upload.error.message);setBusy(false);return}
  const providedTitle=String(formData.get('title')||'').trim(),manualType=String(formData.get('asset_type')||'auto'),assetType=manualType==='auto'?inferType(file):manualType
  const manualTags=split(formData.get('topic_tags')),tags=manualTags.length?manualTags:inferTags(file.name),organized=formData.get('organized_now')==='on',official=canApproveOfficial&&formData.get('official_source')==='on'
  const insert=await supabase.from('media_assets').insert({church_id:churchId,uploaded_by:userId,library_kind:'media',title:providedTitle||titleFromFile(file.name)||file.name,asset_type:assetType,storage_path:path,description:String(formData.get('description')||'').trim()||null,resource_type:'media_asset',language_code:String(formData.get('language_code')||'en'),ministry_area:String(formData.get('ministry_area')||'').trim()||null,topic_tags:tags,scripture_refs:[],archive_status:organized?'current':'draft',source_label:String(formData.get('source_label')||'').trim()||null,approved_for_members:organized&&formData.get('approved_for_members')==='on',can_edit_copy:organized&&formData.get('can_edit_copy')==='on',source_scope:String(formData.get('source_scope')||'local_church'),official_source:official,reviewed_by:official?userId:null,reviewed_at:official?new Date().toISOString():null,organization_status:organized?'organized':'inbox',suggested_metadata:{inferred_asset_type:inferType(file),inferred_tags:inferTags(file.name),original_filename:file.name}})
  if(insert.error){await supabase.storage.from('resource-library').remove([path]);setMessage(insert.error.message);setBusy(false);return}
  setMessage(organized?'Media saved to the library. Refreshing…':'Uploaded to Media Inbox. Refreshing…');window.location.reload()
 }
 return <form action={submit} className="card media-upload"><div className="media-upload-head"><div><div className="pill">MEDIA DROP</div><h2>Just upload it. Organize it now or later.</h2><p className="small muted">Pick the file and Kingdom Network will infer a basic type and tags. Unreviewed uploads stay in the Media Inbox until leadership organizes them.</p></div><Inbox/></div>
 <div className="media-form-grid"><label className="wide"><span>File</span><input name="file" type="file" required accept=".pdf,.ppt,.pptx,.jpg,.jpeg,.png,.webp,.mp4,.mp3"/></label><label className="wide"><span>Title (optional)</span><input name="title" placeholder="Leave blank and we will use the file name"/></label></div>
 <details style={{marginTop:12}}><summary style={{cursor:'pointer',fontWeight:800}}>Add details now (optional)</summary><div className="media-form-grid" style={{marginTop:12}}><label><span>Category</span><select name="asset_type" defaultValue="auto"><option value="auto">Auto-detect</option><option value="flyer">Flyer</option><option value="invitation">Invitation</option><option value="sermon_cover">Sermon cover</option><option value="fundraiser">Fundraiser graphic</option><option value="photo">Photo</option><option value="video">Video</option><option value="audio">Audio</option><option value="slides">Slides</option><option value="other">Other</option></select></label><label><span>Ministry / team</span><input name="ministry_area" placeholder="Youth, Worship, First Steps…"/></label><label><span>Language</span><select name="language_code" defaultValue="en"><option value="en">English</option><option value="es">Español</option><option value="bilingual">Bilingual</option></select></label><label><span>Scope</span><select name="source_scope" defaultValue="local_church"><option value="local_church">Whole church</option><option value="ministry">Ministry</option><option value="group">Friendship group</option><option value="external">External reference</option>{canApproveOfficial&&<><option value="district">District</option><option value="organization">Organization / Assembly</option></>}</select></label><label className="wide"><span>Tags</span><input name="topic_tags" placeholder="Leave blank for automatic starter tags"/></label><label className="wide"><span>Description</span><textarea name="description" rows={3}/></label><label className="wide"><span>Source / campaign label</span><input name="source_label" placeholder="Easter 2026, Youth Department…"/></label></div><label className="media-check"><input type="checkbox" name="organized_now"/><span>I have organized this asset now — move it directly into the library.</span></label><label className="media-check"><input type="checkbox" name="approved_for_members"/><span>Members may see and download this asset after organization.</span></label><label className="media-check"><input type="checkbox" name="can_edit_copy"/><span>Members may reuse or adapt this asset.</span></label>{canApproveOfficial&&<label className="media-check"><input type="checkbox" name="official_source"/><span>Mark as official church / district / organization-approved media.</span></label>}</details>
 <button className="btn" disabled={busy}><Upload size={15}/>{busy?'Uploading…':'Upload media'}</button>{message&&<div className="small muted" style={{marginTop:8}}>{message}</div>}</form>
}
