export type HelpLanguage='en'|'es'
export type HelpEntry={id:string;question:string;answer:string;href:string;cta:string;keywords:string[];aliases:string[]}

const entries:Record<HelpLanguage,HelpEntry[]>={
 en:[
  {id:'start',question:'Where should I start?',answer:'Open Start Here for the basic map, then check My Profile, My Journey and My Today. You do not need to learn every tab at once.',href:'/start',cta:'Open Start Here',keywords:['new','start','first','begin','onboarding','lost'],aliases:['i am new','what do i do first','where do i begin','how does this app work']},
  {id:'profile',question:'How do I update my profile or photo?',answer:'Open My Profile. Tap your photo or camera icon to add a headshot, then update the personal information you want your church to have.',href:'/profile',cta:'Open My Profile',keywords:['profile','photo','picture','headshot','name','birthday','anniversary'],aliases:['change my picture','edit my information','update my name']},
  {id:'password',question:'I cannot sign in or forgot my password.',answer:'On Sign in, open “Can’t get in?” and request one password reset email. Open only the newest email, choose a new password, then return to Sign in.',href:'/login?mode=signin',cta:'Go to Sign in',keywords:['password','login','sign in','reset','locked','email'],aliases:['forgot password','cant get in','cannot log in','reset my login']},
  {id:'confirm-email',question:'I made an account but never confirmed my email.',answer:'Go to Sign in, open “Can’t get in?” and choose “I never confirmed my email.” Request one fresh confirmation email, check Inbox and Spam/Junk, and open only the newest message.',href:'/login?mode=signin',cta:'Go to account help',keywords:['confirm','confirmation','email','verify','account','spam','junk'],aliases:['did not get confirmation email','email never came','confirm my account','unconfirmed email']},
  {id:'existing-account-join',question:'I already have an account. How do I join my church?',answer:'Open your church’s join link and choose Sign in instead of creating another account. After you sign in, Kingdom Network returns you to the church join page so you can finish joining with the account you already have.',href:'/login?mode=signin',cta:'Sign in to my account',keywords:['join','church','existing','account','duplicate','link','member'],aliases:['join church with existing account','already have account','do not create duplicate','church join link']},
  {id:'duplicate-account',question:'Should I create another account for a different church or invitation?',answer:'No. Keep one Kingdom Network account. If a church join page or invitation recognizes your email, sign in with your existing account. Use Forgot password if you cannot remember the password.',href:'/login?mode=signin',cta:'Use my existing account',keywords:['duplicate','second','another','account','invitation','church','email'],aliases:['make second account','new account for church','same email','already registered']},
  {id:'replaced-invite',question:'My invitation link is expired, revoked, already used, or was replaced. What should I do?',answer:'Use the newest invitation or church join link your leader sent. When a replacement link is created, an older link may intentionally stop working. If you already have a Kingdom Network account, sign in with that same account instead of creating another one.',href:'/login?mode=signin',cta:'Sign in with my account',keywords:['invitation','invite','expired','revoked','used','replaced','old link','newest link','join'],aliases:['old invite does not work','invite expired','invitation revoked','replacement invitation','new invitation link']},
  {id:'journey',question:'What is My Journey?',answer:'My Journey is your personal discipleship roadmap. It shows recorded spiritual milestones, course progress, Friendship Group connection, outreach preparation and serving steps.',href:'/journey',cta:'Open My Journey',keywords:['journey','progress','milestones','next step','spiritual','discipleship'],aliases:['how am i doing','where am i spiritually','what is my next step']},
  {id:'today',question:'What should I do today?',answer:'My Today pulls together the items that need your attention now, such as learning, assignments, reminders and next steps.',href:'/today',cta:'Open My Today',keywords:['today','task','assignment','now','todo','to do'],aliases:['what do i need to do','what matters today']},
  {id:'learning',question:'How do I take a class?',answer:'Open Learning Center, choose a course, enroll if needed, then start the next lesson. Your lesson and assessment progress is saved to your account.',href:'/learning',cta:'Open Learning Center',keywords:['class','course','lesson','learning','quiz','test','exam','enroll'],aliases:['take a class','start course','where are lessons','how do quizzes work']},
  {id:'groups',question:'How do I find my Friendship Group?',answer:'Open Friendship Groups. If you already belong to one, your group appears first with its meeting information, lesson, prayer wall and check-in tools.',href:'/groups',cta:'Open Friendship Groups',keywords:['group','friendship','cell','meeting','leader'],aliases:['my group','find group','small group','where is my friendship group']},
  {id:'group-checkin',question:'How do I check in to Friendship Group?',answer:'Open your Friendship Group on meeting day and tap Check in. Kingdom Network records the actual check-in time and marks you on-time or late based on the scheduled start.',href:'/groups',cta:'Open my group',keywords:['check in','attendance','late','present','group'],aliases:['mark me present','group attendance','i am here']},
  {id:'prayer',question:'How do I submit a prayer request?',answer:'Open Prayer. Choose Public or Private. Public requests can appear on the church message board. You can also choose to share the request with your Friendship Group.',href:'/prayer',cta:'Open Prayer',keywords:['prayer','request','private','public','pray'],aliases:['need prayer','ask for prayer','prayer wall']},
  {id:'care',question:'How do I ask for private pastoral help?',answer:'Use Private Care for sensitive pastoral support. Private Care is separate from the public prayer board and is restricted to the people authorized to respond.',href:'/help',cta:'Open Private Care',keywords:['pastor','private','care','counsel','sensitive','help'],aliases:['talk to pastor','private help','pastoral care']},
  {id:'messages',question:'How do I message someone?',answer:'Open Messages for private conversations. You can also use the Directory to find an approved church contact and begin a conversation.',href:'/messages',cta:'Open Messages',keywords:['message','contact','chat','conversation','dm'],aliases:['send a message','talk to someone','contact member']},
  {id:'directory',question:'How do I find another member?',answer:'Open Directory to find church members and the profile information they have chosen to share.',href:'/directory',cta:'Open Directory',keywords:['directory','member','person','find','profile'],aliases:['find someone','member list','church people']},
  {id:'calendar',question:'Where are church events?',answer:'Open Calendar to see upcoming church, ministry, Friendship Group and district events without hunting for them.',href:'/calendar',cta:'Open Calendar',keywords:['calendar','event','service','meeting','schedule','date'],aliases:['whats happening','next event','church schedule']},
  {id:'google-calendar',question:'How do I add a Kingdom Network event to Google Calendar?',answer:'Open the event in Calendar and choose Add to Google Calendar. Kingdom Network sends that event outward; it does not read your private Google Calendar.',href:'/calendar',cta:'Open Calendar',keywords:['google','calendar','sync','add event'],aliases:['put on google calendar','google calendar sync']},
  {id:'serve',question:'How do I get involved in ministry?',answer:'Open Serve to explore ministry opportunities, see any qualification requirements and submit your interest.',href:'/serve',cta:'Open Serve',keywords:['serve','ministry','volunteer','team','help'],aliases:['join ministry','volunteer','how can i serve']},
  {id:'notifications',question:'Where are my alerts and reminders?',answer:'Open Notifications to see account reminders, church notices and actions that need your attention.',href:'/notifications',cta:'Open Notifications',keywords:['notification','alert','reminder','notice'],aliases:['my alerts','what notified me']},
  {id:'documents',question:'Where are my certificates or church documents?',answer:'Open Documents for records that belong to your account, including approved certificates and member documents.',href:'/documents',cta:'Open Documents',keywords:['document','certificate','record','file'],aliases:['my certificate','my files']},
  {id:'resources',question:'Where do I find church resources and teaching material?',answer:'Open Resources for approved church files and teaching material. Kingdom Guide can also search member-approved resources by topic.',href:'/resources',cta:'Open Resources',keywords:['resource','file','manual','policy','form','teaching','material'],aliases:['church resources','find a form','find manual']},
  {id:'feedback',question:'How do I report something broken or suggest an idea?',answer:'Open Feedback and describe what happened or what would make Kingdom Network easier to use. Pilot feedback goes directly into the product-review queue.',href:'/feedback',cta:'Share feedback',keywords:['feedback','broken','bug','idea','suggestion','confusing'],aliases:['report problem','something is wrong','feature idea']},
  {id:'leadership',question:'I am a leader. Where do I manage church setup?',answer:'Authorized leaders can open Church Builder for pilot setup and use leadership/admin areas for members, groups, learning, outreach and calendar management.',href:'/church/launch',cta:'Open Church Builder',keywords:['leader','admin','pastor','setup','manage','church builder'],aliases:['admin tools','leader tools','manage church']},
  {id:'fresh-church-setup',question:'How do I use Fresh Church Setup without publishing unfinished material?',answer:'Open Church Builder, then Setup Inbox. Upload the church material you want to organize, review the recommended plan, and approve it only when it looks right. Approval creates or opens an unpublished Course Builder draft; review that draft before anyone publishes it.',href:'/church/setup-inbox',cta:'Open Setup Inbox',keywords:['fresh church','setup','setup inbox','church builder','upload','plan','course builder','draft','publish','unpublished'],aliases:['set up new church','upload church curriculum','approve setup plan','does setup publish course','fresh church setup']}
 ],
 es:[
  {id:'start',question:'¿Dónde debo comenzar?',answer:'Abre Empieza Aquí para ver el mapa básico, luego revisa Mi Perfil, Mi Camino y Mi Día. No necesitas aprender todas las secciones de una vez.',href:'/start',cta:'Abrir Empieza Aquí',keywords:['nuevo','comenzar','inicio','primero','perdido'],aliases:['soy nuevo','que hago primero','donde comienzo','como funciona la aplicación']},
  {id:'profile',question:'¿Cómo cambio mi perfil o foto?',answer:'Abre Mi Perfil. Toca tu foto o el icono de cámara para agregar una foto clara y actualiza los datos que quieras compartir con tu iglesia.',href:'/profile',cta:'Abrir Mi Perfil',keywords:['perfil','foto','imagen','nombre','cumpleaños','aniversario'],aliases:['cambiar foto','editar información','actualizar nombre']},
  {id:'password',question:'No puedo entrar o olvidé mi contraseña.',answer:'En Iniciar sesión, abre “¿No puedes entrar?” y solicita un solo correo para cambiar la contraseña. Abre solamente el correo más reciente.',href:'/login?mode=signin',cta:'Ir a Iniciar sesión',keywords:['contraseña','entrar','acceso','correo','restablecer'],aliases:['olvide contraseña','no puedo entrar','cambiar contraseña']},
  {id:'confirm-email',question:'Creé una cuenta pero nunca confirmé mi correo.',answer:'Ve a Iniciar sesión, abre “¿No puedes entrar?” y elige “Nunca confirmé mi correo”. Solicita un solo correo nuevo, revisa Recibidos y Spam/Correo no deseado y abre solamente el mensaje más reciente.',href:'/login?mode=signin',cta:'Ir a ayuda de la cuenta',keywords:['confirmar','confirmación','correo','verificar','cuenta','spam'],aliases:['no recibí correo de confirmación','correo no llegó','confirmar mi cuenta','correo sin confirmar']},
  {id:'existing-account-join',question:'Ya tengo una cuenta. ¿Cómo me uno a mi iglesia?',answer:'Abre el enlace para unirte a tu iglesia y elige Iniciar sesión en vez de crear otra cuenta. Después de entrar, Kingdom Network te regresa a la página de la iglesia para terminar de unirte con la cuenta que ya tienes.',href:'/login?mode=signin',cta:'Iniciar sesión con mi cuenta',keywords:['unirme','iglesia','cuenta','existente','duplicada','enlace','miembro'],aliases:['unirme con cuenta existente','ya tengo cuenta','no crear duplicado','enlace de iglesia']},
  {id:'duplicate-account',question:'¿Debo crear otra cuenta para otra iglesia o invitación?',answer:'No. Conserva una sola cuenta de Kingdom Network. Si una página para unirte o una invitación reconoce tu correo, inicia sesión con tu cuenta existente. Usa Olvidé mi contraseña si no recuerdas la contraseña.',href:'/login?mode=signin',cta:'Usar mi cuenta existente',keywords:['duplicada','segunda','otra','cuenta','invitación','iglesia','correo'],aliases:['crear segunda cuenta','nueva cuenta para iglesia','mismo correo','ya registrado']},
  {id:'replaced-invite',question:'Mi invitación venció, fue cancelada, ya se usó o fue reemplazada. ¿Qué hago?',answer:'Usa la invitación o el enlace para unirte más reciente que te envió tu líder. Cuando se crea un enlace de reemplazo, uno anterior puede dejar de funcionar a propósito. Si ya tienes una cuenta de Kingdom Network, inicia sesión con esa misma cuenta en vez de crear otra.',href:'/login?mode=signin',cta:'Iniciar sesión con mi cuenta',keywords:['invitación','venció','cancelada','usada','reemplazada','enlace viejo','enlace nuevo','unirme'],aliases:['invitación vieja no funciona','invitación vencida','invitación cancelada','invitación de reemplazo','nuevo enlace']},
  {id:'journey',question:'¿Qué es Mi Camino?',answer:'Mi Camino es tu mapa personal de discipulado. Muestra hitos espirituales, cursos, conexión con Grupo de Amistad, preparación evangelística y servicio.',href:'/journey',cta:'Abrir Mi Camino',keywords:['camino','jornada','progreso','hitos','discipulado','próximo paso'],aliases:['como voy','donde estoy espiritualmente','que sigue']},
  {id:'today',question:'¿Qué debo hacer hoy?',answer:'Mi Día reúne lo que necesita tu atención ahora: aprendizaje, tareas, recordatorios y próximos pasos.',href:'/today',cta:'Abrir Mi Día',keywords:['hoy','tarea','asignación','ahora'],aliases:['que tengo que hacer','que importa hoy']},
  {id:'learning',question:'¿Cómo tomo una clase?',answer:'Abre Centro de Aprendizaje, elige un curso, inscríbete si es necesario y comienza la próxima lección. Tu progreso queda guardado.',href:'/learning',cta:'Abrir Aprendizaje',keywords:['clase','curso','lección','aprendizaje','prueba','examen'],aliases:['tomar clase','empezar curso','donde están lecciones']},
  {id:'groups',question:'¿Cómo encuentro mi Grupo de Amistad?',answer:'Abre Grupos de Amistad. Si ya perteneces a uno, aparecerá primero con reunión, lección, muro de oración y registro de asistencia.',href:'/groups',cta:'Abrir Grupos',keywords:['grupo','amistad','reunión','líder'],aliases:['mi grupo','buscar grupo','grupo pequeño']},
  {id:'group-checkin',question:'¿Cómo registro mi asistencia al Grupo de Amistad?',answer:'Abre tu Grupo de Amistad el día de reunión y toca Registrar asistencia. Kingdom Network guarda la hora real y marca a tiempo o tarde según el horario.',href:'/groups',cta:'Abrir mi grupo',keywords:['asistencia','registrar','tarde','presente','grupo'],aliases:['estoy aquí','marcar presente']},
  {id:'prayer',question:'¿Cómo envío una petición de oración?',answer:'Abre Oración y elige Pública o Privada. Las públicas pueden aparecer en el tablero de la iglesia. También puedes compartirla con tu Grupo de Amistad.',href:'/prayer',cta:'Abrir Oración',keywords:['oración','petición','privada','pública'],aliases:['necesito oración','pedir oración','muro de oración']},
  {id:'care',question:'¿Cómo pido ayuda pastoral privada?',answer:'Usa Cuidado Privado para asuntos sensibles. Está separado del tablero público y restringido a las personas autorizadas para responder.',href:'/help',cta:'Abrir Cuidado Privado',keywords:['pastor','privado','cuidado','ayuda'],aliases:['hablar con pastor','ayuda privada']},
  {id:'messages',question:'¿Cómo envío un mensaje?',answer:'Abre Mensajes para conversaciones privadas. También puedes usar el Directorio para encontrar a una persona y comenzar una conversación.',href:'/messages',cta:'Abrir Mensajes',keywords:['mensaje','contacto','conversación'],aliases:['enviar mensaje','hablar con alguien']},
  {id:'directory',question:'¿Cómo encuentro a otro miembro?',answer:'Abre Directorio para encontrar miembros y la información de perfil que ellos decidieron compartir.',href:'/directory',cta:'Abrir Directorio',keywords:['directorio','miembro','persona','perfil'],aliases:['buscar a alguien','lista de miembros']},
  {id:'calendar',question:'¿Dónde están los eventos?',answer:'Abre Calendario para ver eventos próximos de la iglesia, ministerios, Grupos de Amistad y distrito sin tener que buscarlos por separado.',href:'/calendar',cta:'Abrir Calendario',keywords:['calendario','evento','servicio','reunión','horario'],aliases:['que está pasando','próximo evento']},
  {id:'google-calendar',question:'¿Cómo agrego un evento a Google Calendar?',answer:'Abre el evento y elige Agregar a Google Calendar. Kingdom Network envía ese evento hacia tu calendario; no lee tu calendario privado.',href:'/calendar',cta:'Abrir Calendario',keywords:['google','calendario','sincronizar','evento'],aliases:['poner en google calendar']},
  {id:'serve',question:'¿Cómo participo en un ministerio?',answer:'Abre Servir para explorar oportunidades, ver requisitos y expresar tu interés.',href:'/serve',cta:'Abrir Servir',keywords:['servir','ministerio','voluntario','equipo'],aliases:['unirme a ministerio','quiero servir']},
  {id:'notifications',question:'¿Dónde están mis alertas?',answer:'Abre Notificaciones para ver recordatorios, avisos de iglesia y acciones que necesitan tu atención.',href:'/notifications',cta:'Abrir Notificaciones',keywords:['notificación','alerta','recordatorio','aviso'],aliases:['mis alertas']},
  {id:'documents',question:'¿Dónde están mis certificados o documentos?',answer:'Abre Documentos para registros ligados a tu cuenta, incluyendo certificados aprobados y documentos de miembro.',href:'/documents',cta:'Abrir Documentos',keywords:['documento','certificado','archivo','registro'],aliases:['mi certificado','mis archivos']},
  {id:'resources',question:'¿Dónde encuentro recursos de la iglesia?',answer:'Abre Recursos para archivos y materiales aprobados. Kingdom Guide también puede buscar recursos aprobados por tema.',href:'/resources',cta:'Abrir Recursos',keywords:['recurso','archivo','manual','formulario','enseñanza'],aliases:['recursos de iglesia','buscar formulario','buscar manual']},
  {id:'feedback',question:'¿Cómo reporto algo que no funciona o doy una idea?',answer:'Abre Comentarios y explica qué pasó o qué haría Kingdom Network más sencillo. Los comentarios del piloto entran a la lista de revisión.',href:'/feedback',cta:'Compartir comentario',keywords:['comentario','error','problema','idea','confuso'],aliases:['reportar problema','algo no funciona']},
  {id:'leadership',question:'Soy líder. ¿Dónde administro la iglesia?',answer:'Los líderes autorizados pueden abrir Church Builder y usar las áreas de liderazgo para miembros, grupos, aprendizaje, evangelismo y calendario.',href:'/church/launch',cta:'Abrir Church Builder',keywords:['líder','admin','pastor','configurar','administrar'],aliases:['herramientas admin','manejar iglesia']},
  {id:'fresh-church-setup',question:'¿Cómo uso Fresh Church Setup sin publicar material sin terminar?',answer:'Abre Church Builder y después la Bandeja de Configuración. Sube el material de la iglesia que quieras organizar, revisa el plan recomendado y apruébalo solamente cuando se vea correcto. La aprobación crea o abre un borrador no publicado en Course Builder; revisa ese borrador antes de que alguien lo publique.',href:'/church/setup-inbox',cta:'Abrir Bandeja de Configuración',keywords:['iglesia nueva','configuración','bandeja','church builder','subir','plan','course builder','borrador','publicar','no publicado'],aliases:['configurar iglesia nueva','subir currículo','aprobar plan','publica curso','fresh church setup']}
 ]
}

const normalize=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()
const tokens=(v:string)=>new Set(normalize(v).split(' ').filter(x=>x.length>1))

export function searchHelp(query:string,lang:HelpLanguage){
 const q=normalize(query),qt=tokens(query),rows=entries[lang].map(entry=>{
   const hay=normalize([entry.question,entry.answer,...entry.keywords,...entry.aliases].join(' ')),ht=tokens(hay)
   let score=0
   if(hay.includes(q)&&q.length>2)score+=80
   for(const token of qt)if(ht.has(token))score+=12
   for(const alias of entry.aliases){const a=normalize(alias);if(q.includes(a)||a.includes(q))score+=45}
   if(normalize(entry.question).includes(q))score+=60
   return {...entry,score}
 }).sort((a,b)=>b.score-a.score)
 const matched=rows.filter(r=>r.score>0).slice(0,5)
 return matched.length?matched:rows.slice(0,3)
}

export function commonHelp(lang:HelpLanguage){return entries[lang].slice(0,10)}