import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CheckCircle2,FileText,Languages,Sparkles,WandSparkles } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { SetupUploader } from './setup-uploader'
import { SetupActionButton } from './setup-action-button'
import { approveSetupPlan,generateAllSetupPlans,generateSetupPlan } from './actions'

const esPlanCopy:Record<string,{title:string;summary:string;destination:string}>={
 course_draft:{title:'Crear un curso borrador con este material',summary:'Crea una estructura de curso sin publicar y conserva el archivo original. Revisa y crea las lecciones antes de publicar.',destination:'Centro de Aprendizaje'},
 branding_review:{title:'Revisar este archivo para la identidad de la iglesia',summary:'Mantén el archivo privado y revísalo antes de cambiar cualquier logotipo o color visible.',destination:'Configuración / Medios'},
 calendar_review:{title:'Revisar este archivo para eventos',summary:'Prepara este material para el Calendario. No se crearán eventos hasta confirmar las fechas y los detalles.',destination:'Calendario'},
 workflow_review:{title:'Revisar este archivo como formulario o proceso',summary:'Prepáralo para convertirlo en un formulario o lista reutilizable después de la revisión del liderazgo.',destination:'Formularios y Procesos'},
 policy_review:{title:'Revisar este archivo como política de la iglesia',summary:'Conserva la fuente y envíala a revisión del liderazgo antes de mostrarla a los miembros.',destination:'Liderazgo / Políticas'},
 certificate_review:{title:'Revisar este archivo como certificado o credencial',summary:'Envíalo al proceso de documentos y certificados. No se emitirá ninguna credencial automáticamente.',destination:'Documentos / Certificados'},
 leadership_review:{title:'Revisar este material para liderazgo',summary:'Prepáralo para registros o capacitación de liderazgo después de la aprobación del pastor o administrador.',destination:'Registros de Liderazgo'},
 media_review:{title:'Revisar este archivo para la Biblioteca de Medios',summary:'Prepara este recurso para publicarlo más adelante. Permanece privado hasta que sea aprobado.',destination:'Biblioteca de Medios'},
 resource_review:{title:'Revisar este archivo como recurso confiable',summary:'Revísalo antes de que los miembros lo vean para definir autoridad, visibilidad, tema y si está vigente.',destination:'Guía del Reino / Biblioteca de Recursos'}
}
const esStatus:Record<string,string>={received:'recibido',reviewing:'en revisión',ready:'aprobado'}
const esCategory:Record<string,string>={unsorted:'sin organizar',curriculum:'currículo',branding:'identidad',calendar:'calendario',forms:'formularios',policies:'políticas',certificates:'certificados',leadership:'liderazgo',media:'medios',resource:'recurso'}
const esConfidence:Record<string,string>={low:'BAJA',medium:'MEDIA',high:'ALTA'}
const boundedCode=(value:unknown)=>String(value||'unknown').slice(0,80)

export default async function SetupInbox({searchParams}:{searchParams:Promise<{lang?:string;error?:string}>}){
 const q=await searchParams,lang=q.lang==='es'?'es':'en',es=lang==='es',l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
 const supabase=await createClient();const {data:claims,error:claimsError}=await supabase.auth.getClaims();if(claimsError){console.error('SetupInbox claims read failed',{code:boundedCode(claimsError.code)});throw new Error('setup-inbox-load-failed')}const userId=claims?.claims?.sub;if(!userId)redirect(l('/login'))
 const {data:m,error:membershipError}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(membershipError){console.error('SetupInbox membership read failed',{userId,code:boundedCode(membershipError.code)});throw new Error('setup-inbox-load-failed')}if(!m?.church_id||!['pastor','church_admin'].includes(m.role))redirect(l('/'))
 const {data:rows,error:rowsError}=await supabase.from('church_setup_uploads').select('*').eq('church_id',m.church_id).order('created_at',{ascending:false});if(rowsError){console.error('SetupInbox records read failed',{churchId:m.church_id,code:boundedCode(rowsError.code)});throw new Error('setup-inbox-load-failed')}
 const church:any=Array.isArray(m.churches)?m.churches[0]:m.churches
 const counts={received:(rows??[]).filter((x:any)=>x.status==='received').length,reviewing:(rows??[]).filter((x:any)=>x.status==='reviewing').length,ready:(rows??[]).filter((x:any)=>x.status==='ready').length}
 const errorMessage=q.error==='access'?(es?'No pudimos verificar tu acceso de liderazgo en este momento. Nada se cambió. Recarga esta página e inténtalo otra vez.':'We could not verify your leadership access right now. Nothing was changed. Reload this page and try again.'):q.error==='approve'?(es?'No se pudo aprobar ese plan. Nada se marcó como listo. Inténtalo de nuevo.':'That plan could not be approved. Nothing was marked ready. Try again.'):q.error==='review'?(es?'No se pudo crear el plan recomendado. Inténtalo de nuevo.':'The recommended plan could not be created. Try again.'):null
 return <main className="shell"><header className="topbar"><div><Link href={l('/')} className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name||(es?'Iglesia':'Church')} • {es?'Bandeja de Configuración':'Setup Inbox'}</div></div><div className="row"><Languages size={14}/><Link className="ghost" href="/church/setup-inbox?lang=en">English</Link><Link className="ghost" href="/church/setup-inbox?lang=es">Español</Link><Link className="ghost" href={l('/church/launch')}>← {es?'Constructor de Iglesia':'Church Builder'}</Link></div></header>
 <section className="hero card"><div><div className="pill"><Sparkles size={12}/> {es?'CONFIGURACIÓN ASISTIDA':'ASSISTED SETUP'}</div><h1>{es?'Sube lo que tu iglesia ya usa.':'Upload what your church already uses.'}</h1><p>{es?'Kingdom Network propone qué hacer con cada archivo y espera tu aprobación antes de crear algo.':'Kingdom Network proposes what to do with each file and waits for your approval before creating anything.'}</p><p className="small muted">{es?'Nada se publica automáticamente. Puedes revisar cada plan antes de aprobarlo.':'Nothing is published automatically. You can review every plan before approving it.'}</p></div>{counts.received>0&&<form action={generateAllSetupPlans}><input type="hidden" name="lang" value={lang}/><SetupActionButton kind="review" lang={lang} label={es?`Revisar los ${counts.received} archivos pendientes`:`Review all ${counts.received} waiting file${counts.received===1?'':'s'}`}/><div className="small muted" style={{marginTop:8}}>{es?'Toca una vez y mantén esta página abierta hasta que termine.':'Tap once and keep this page open until it finishes.'}</div></form>}</section>
 {errorMessage&&<div className="notice error" role="alert">{errorMessage}</div>}
 <section className="stat-grid"><div className="card stat-card"><FileText/><div><strong>{rows?.length||0}</strong><span>{es?'Archivos':'Files'}</span></div></div><div className="card stat-card"><Sparkles/><div><strong>{counts.received}</strong><span>{es?'Esperando revisión':'Awaiting review'}</span></div></div><div className="card stat-card"><WandSparkles/><div><strong>{counts.reviewing}</strong><span>{es?'Planes listos':'Plans ready'}</span></div></div><div className="card stat-card"><CheckCircle2/><div><strong>{counts.ready}</strong><span>{es?'Aprobados':'Approved'}</span></div></div></section>
 <div className="content-grid"><section><div style={{display:'grid',gap:12}}>{(rows??[]).map((r:any)=>{const plan:any=r.review_plan,translated=es&&plan?esPlanCopy[String(plan.kind)] : null,confidence=es?(esConfidence[String(plan?.confidence||r.review_confidence||'')]||'') : String(plan?.confidence||r.review_confidence||'').toUpperCase();return <article className="card" key={r.id} style={{padding:18}}><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><div className="pill">{es?(esCategory[String(r.category)]||'ARCHIVO').toUpperCase():String(r.category).replaceAll('_',' ').toUpperCase()}</div><h3>{r.file_name}</h3></div><span className="pill">{es?(esStatus[String(r.status)]||'archivo'):String(r.status).replaceAll('_',' ')}</span></div><p className="muted">{translated?.destination||r.suggested_destination|| (es?'Pendiente de organización':'Awaiting organization')}</p>{r.notes&&<p>{r.notes}</p>}
 {!plan&&<form action={generateSetupPlan}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="lang" value={lang}/><SetupActionButton kind="review" lang={lang}/></form>}
 {plan&&<div className="card" style={{marginTop:12,padding:14,background:'rgba(255,255,255,.025)'}}><div className="pill">{es?'PLAN RECOMENDADO':'RECOMMENDED PLAN'}{confidence?` • ${confidence}`:''}</div><h3 style={{marginBottom:6}}>{translated?.title||plan.title}</h3><p className="muted">{translated?.summary||plan.summary}</p><div className="small muted" style={{marginBottom:10}}>{es?'Destino':'Destination'}: <strong>{translated?.destination||plan.destination}</strong></div>{r.status==='reviewing'&&<form action={approveSetupPlan}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="lang" value={lang}/><SetupActionButton kind="approve" lang={lang} label={es?'Aprobar este plan':plan.approveLabel||'Approve plan'}/><div className="small muted" style={{marginTop:8}}>{es?'Toca Aprobar una sola vez y mantén esta página abierta. Nada se publica automáticamente; los cursos creados quedan como borradores.':'Tap Approve once and keep this page open. Nothing is published automatically; any course created stays as a draft.'}</div></form>}{r.status==='ready'&&<div className="notice success" role="status">{es?'Aprobado. Listo para el siguiente paso.':'Approved. Ready for the next step.'}{r.created_record_type==='course'&&r.created_record_id&&<> <Link href={l(`/learning/admin/course-builder/${r.created_record_id}`)}>{es?'Abrir Constructor de Cursos →':'Open Course Builder →'}</Link></>}</div>}</div>}
 <small className="muted" style={{display:'block',marginTop:10}}>{new Date(r.created_at).toLocaleString(lang==='es'?'es-US':'en-US')}</small></article>})}{!rows?.length&&<div className="card" style={{padding:24}}><h3>{es?'Todavía no hay archivos.':'No files yet.'}</h3><p className="muted">{es?'Sube un documento a la derecha. No necesitas organizarlo primero.':'Upload something on the right. You do not have to organize it first.'}</p></div>}</div></section>
 <aside><SetupUploader churchId={m.church_id} userId={userId} lang={lang}/><div className="card side"><div className="pill">{es?'FLUJO SIMPLE':'SIMPLE WORKFLOW'}</div><h3>{es?'Archivo → Plan → Aprobación → Constructor':'File → Plan → Approval → Builder'}</h3><p className="muted">{es?'El currículo aprobado entra a Constructor de Cursos como borrador para crear lecciones, evaluaciones y certificados. Nada se publica sin una decisión posterior.':'Approved curriculum enters Course Builder as a draft for lessons, assessments and certificates. Nothing is published without a later decision.'}</p></div></aside></div></main>
}