import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CheckCircle2,FileText,Languages,Sparkles,WandSparkles } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { SetupUploader } from './setup-uploader'
import { approveSetupPlan,generateAllSetupPlans,generateSetupPlan } from './actions'

export default async function SetupInbox({searchParams}:{searchParams:Promise<{lang?:string}>}){
 const q=await searchParams,lang=q.lang==='es'?'es':'en',es=lang==='es',l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
 const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect(l('/login'))
 const {data:m}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!m?.church_id||!['pastor','church_admin'].includes(m.role))redirect('/')
 const {data:rows}=await supabase.from('church_setup_uploads').select('*').eq('church_id',m.church_id).order('created_at',{ascending:false})
 const church:any=Array.isArray(m.churches)?m.churches[0]:m.churches
 const counts={received:(rows??[]).filter((x:any)=>x.status==='received').length,reviewing:(rows??[]).filter((x:any)=>x.status==='reviewing').length,ready:(rows??[]).filter((x:any)=>x.status==='ready').length}
 return <main className="shell"><header className="topbar"><div><div className="brand">Kingdom <span>Network</span></div><div className="small muted">{church?.name||'Church'} • {es?'Bandeja de Configuración':'Setup Inbox'}</div></div><div className="row"><Languages size={14}/><Link className="ghost" href="/church/setup-inbox?lang=en">English</Link><Link className="ghost" href="/church/setup-inbox?lang=es">Español</Link><Link className="ghost" href={l('/church/launch')}>← Church Builder</Link></div></header>
 <section className="hero card"><div><div className="pill"><Sparkles size={12}/> {es?'CONFIGURACIÓN ASISTIDA':'ASSISTED SETUP'}</div><h1>{es?'Sube lo que tu iglesia ya usa.':'Upload what your church already uses.'}</h1><p>{es?'Kingdom Network propone qué hacer con cada archivo y espera tu aprobación antes de crear algo.':'Kingdom Network proposes what to do with each file and waits for your approval before creating anything.'}</p></div>{counts.received>0&&<form action={generateAllSetupPlans}><button className="btn" type="submit"><WandSparkles size={14}/> {es?`Revisar los ${counts.received} archivos pendientes`:`Review all ${counts.received} waiting file${counts.received===1?'':'s'}`}</button></form>}</section>
 <section className="stat-grid"><div className="card stat-card"><FileText/><div><strong>{rows?.length||0}</strong><span>{es?'Archivos':'Files'}</span></div></div><div className="card stat-card"><Sparkles/><div><strong>{counts.received}</strong><span>{es?'Esperando revisión':'Awaiting review'}</span></div></div><div className="card stat-card"><WandSparkles/><div><strong>{counts.reviewing}</strong><span>{es?'Planes listos':'Plans ready'}</span></div></div><div className="card stat-card"><CheckCircle2/><div><strong>{counts.ready}</strong><span>{es?'Aprobados':'Approved'}</span></div></div></section>
 <div className="content-grid"><section><div style={{display:'grid',gap:12}}>{(rows??[]).map((r:any)=>{const plan:any=r.review_plan;return <article className="card" key={r.id} style={{padding:18}}><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><div className="pill">{String(r.category).replaceAll('_',' ').toUpperCase()}</div><h3>{r.file_name}</h3></div><span className="pill">{String(r.status).replaceAll('_',' ')}</span></div><p className="muted">{r.suggested_destination|| (es?'Pendiente de organización':'Awaiting organization')}</p>{r.notes&&<p>{r.notes}</p>}
 {!plan&&<form action={generateSetupPlan}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="lang" value={lang}/><button className="btn" type="submit"><WandSparkles size={14}/> {es?'Crear plan recomendado':'Create recommended plan'}</button></form>}
 {plan&&<div className="card" style={{marginTop:12,padding:14,background:'rgba(255,255,255,.025)'}}><div className="pill">{es?'PLAN RECOMENDADO':'RECOMMENDED PLAN'} • {String(plan.confidence||r.review_confidence||'').toUpperCase()}</div><h3 style={{marginBottom:6}}>{plan.title}</h3><p className="muted">{plan.summary}</p><div className="small muted" style={{marginBottom:10}}>{es?'Destino':'Destination'}: <strong>{plan.destination}</strong></div>{r.status==='reviewing'&&<form action={approveSetupPlan}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="lang" value={lang}/><button className="btn" type="submit"><CheckCircle2 size={14}/> {es?'Aprobar este plan':plan.approveLabel||'Approve plan'}</button><div className="small muted" style={{marginTop:8}}>{es?'Nada se publica automáticamente. Los cursos creados quedan como borradores.':'Nothing is published automatically. Any course created stays as a draft.'}</div></form>}{r.status==='ready'&&<div className="notice success">{es?'Aprobado. Listo para el siguiente paso.':'Approved. Ready for the next step.'}{r.created_record_type==='course'&&r.created_record_id&&<> <Link href={l(`/learning/admin/course-builder/${r.created_record_id}`)}>{es?'Abrir Course Builder →':'Open Course Builder →'}</Link></>}</div>}</div>}
 <small className="muted" style={{display:'block',marginTop:10}}>{new Date(r.created_at).toLocaleString()}</small></article>})}{!rows?.length&&<div className="card" style={{padding:24}}><h3>{es?'Todavía no hay archivos.':'No files yet.'}</h3><p className="muted">{es?'Sube un documento a la derecha. No necesitas organizarlo primero.':'Upload something on the right. You do not have to organize it first.'}</p></div>}</div></section>
 <aside><SetupUploader churchId={m.church_id} userId={userId} lang={lang}/><div className="card side"><div className="pill">{es?'NUEVO FLUJO':'NEW WORKFLOW'}</div><h3>{es?'Archivo → Plan → Aprobación → Constructor':'File → Plan → Approval → Builder'}</h3><p className="muted">{es?'El currículo aprobado ahora entra directamente a Course Builder para crear lecciones, evaluaciones y certificado sin publicar nada automáticamente.':'Approved curriculum now flows directly into Course Builder for lessons, assessments and certificate setup without publishing anything automatically.'}</p></div></aside></div></main>
}
