import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CalendarCheck,ShieldCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { updateNewBirthDates } from './actions'

const precision={en:[['unknown','Date unknown'],['exact','Exact date'],['approximate','Approximate date']],es:[['unknown','Fecha desconocida'],['exact','Fecha exacta'],['approximate','Fecha aproximada']]} as const
const personName=(p:any)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Member'

export default async function NewBirthDatesPage({searchParams}:{searchParams:Promise<{lang?:string;saved?:string;error?:string;q?:string}>}){
  const query=await searchParams,lang: 'en'|'es'=query.lang==='es'?'es':'en',es=lang==='es',t=(en:string,sp:string)=>es?sp:en
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect(es?'/login?lang=es':'/login')
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!membership?.church_id)redirect('/')
  let allowed=['pastor','church_admin'].includes(membership.role);if(!allowed){const {data}=await supabase.rpc('current_user_has_church_permission',{p_church_id:membership.church_id,p_permission_key:'manage_members'});allowed=Boolean(data)}if(!allowed)redirect('/')
  const churchId=membership.church_id,church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  const [{data:members},{data:milestones}]=await Promise.all([supabase.from('church_memberships').select('user_id').eq('church_id',churchId).eq('status','active'),supabase.from('member_milestones').select('user_id,baptized,baptism_date,baptism_date_precision,holy_ghost_received,holy_ghost_date,holy_ghost_date_precision').eq('church_id',churchId)])
  const ids=(members??[]).map((m:any)=>m.user_id);let profiles:any[]=[];if(ids.length){const {data}=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',ids);profiles=data??[]}
  const pm=new Map(profiles.map((p:any)=>[p.id,p])),mm=new Map((milestones??[]).map((m:any)=>[m.user_id,m])),q=String(query.q??'').trim().toLowerCase()
  const rows=ids.map((id:string)=>({id,name:personName(pm.get(id)),m:mm.get(id)??{}})).filter((r:any)=>!q||r.name.toLowerCase().includes(q)).sort((a:any,b:any)=>a.name.localeCompare(b.name))
  return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??t('Your Church','Su Iglesia')} • {t('New Birth Date Review','Revisión de Fechas del Nuevo Nacimiento')}</div></div><div className="row"><Link className="ghost" href={`/church/new-birth-dates?lang=${es?'en':'es'}`}>{es?'English':'Español'}</Link><Link className="ghost" href={`/church/member-records?lang=${lang}`}>← {t('Member Records','Registros')}</Link><Link className="ghost" href="/">{t('Home','Inicio')}</Link></div></header>
  <section className="hero card"><div><div className="pill"><CalendarCheck size={12}/> {t('DATE ACCURACY','PRECISIÓN DE FECHAS')}</div><h1>{t('Record what is known without inventing a date.','Registre lo que se sabe sin inventar una fecha.')}</h1><p>{t('If the church knows someone was baptized or received the Holy Ghost but does not know the date, mark the date unknown. Use approximate only when the entered date is an estimate.','Si la iglesia sabe que alguien fue bautizado o recibió el Espíritu Santo pero no conoce la fecha, marque fecha desconocida. Use aproximada solo cuando la fecha ingresada sea una estimación.')}</p></div><div className="hero-stat"><ShieldCheck size={22}/><span>{t('Leadership verified','Verificado por liderazgo')}</span></div></section>
  {query.saved&&<div className="notice success">{t('New Birth date accuracy saved.','Precisión de fechas guardada.')}</div>}{query.error&&<div className="notice error">{query.error}</div>}
  <section className="card" style={{padding:14,marginBottom:14}}><form method="get" className="row"><input type="hidden" name="lang" value={lang}/><input name="q" defaultValue={query.q??''} placeholder={t('Search member name…','Buscar nombre…')} style={{flex:1}}/><button className="ghost">{t('Search','Buscar')}</button>{q&&<Link className="ghost" href={`/church/new-birth-dates?lang=${lang}`}>{t('Clear','Limpiar')}</Link>}</form></section>
  <section style={{display:'grid',gap:10}}>{rows.map((r:any)=>{const m=r.m;return <article className="card" style={{padding:15}} key={r.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><Link href={`/church/members/${r.id}?lang=${lang}`} style={{fontWeight:800,textDecoration:'none'}}>{r.name}</Link><div className="small muted">{m.baptized?t('Baptism recorded','Bautismo registrado'):t('Baptism not recorded','Bautismo no registrado')} • {m.holy_ghost_received?t('Holy Ghost recorded','Espíritu Santo registrado'):t('Holy Ghost not recorded','Espíritu Santo no registrado')}</div></div></div><form action={updateNewBirthDates} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:8,marginTop:12,alignItems:'end'}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="user_id" value={r.id}/><input type="hidden" name="lang" value={lang}/><label className="field"><span>{t('Baptism date','Fecha de bautismo')}</span><input type="date" name="baptism_date" defaultValue={m.baptism_date??''} disabled={m.baptized!==true}/></label><label className="field"><span>{t('Baptism date accuracy','Precisión de bautismo')}</span><select name="baptism_date_precision" defaultValue={m.baptism_date_precision??'unknown'} disabled={m.baptized!==true}>{precision[lang].map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label><label className="field"><span>{t('Holy Ghost date','Fecha del Espíritu Santo')}</span><input type="date" name="holy_ghost_date" defaultValue={m.holy_ghost_date??''} disabled={m.holy_ghost_received!==true}/></label><label className="field"><span>{t('Holy Ghost date accuracy','Precisión del Espíritu Santo')}</span><select name="holy_ghost_date_precision" defaultValue={m.holy_ghost_date_precision??'unknown'} disabled={m.holy_ghost_received!==true}>{precision[lang].map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label><button className="btn">{t('Save accuracy','Guardar precisión')}</button></form>{(m.baptized!==true||m.holy_ghost_received!==true)&&<div className="small muted" style={{marginTop:8}}>{t('Date fields are disabled for milestones that are not recorded as received. Update the verified milestone first if needed.','Los campos de fecha están desactivados para hitos no registrados. Actualice primero el hito verificado si es necesario.')}</div>}</article>})}{!rows.length&&<div className="card" style={{padding:18}}>{t('No matching members.','No hay miembros coincidentes.')}</div>}</section></main>
}
