import Link from 'next/link'
import { redirect } from 'next/navigation'
import { AlertTriangle,CheckCircle2,Clock3,Mail,MessageSquareText,PauseCircle,Settings,ShieldCheck,XCircle } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { cancelQueuedCommunication,suppressContactCommunications,updateCommunicationTemplate } from './actions'

const statusLabel=(s:string,es:boolean)=>({queued:es?'En cola':'Queued',waiting_provider:es?'Esperando proveedor':'Waiting for provider',sending:es?'Enviando':'Sending',sent:es?'Enviado':'Sent',failed:es?'Falló':'Failed',cancelled:es?'Cancelado':'Cancelled',suppressed:es?'Suprimido':'Suppressed'} as Record<string,string>)[s]||s.replaceAll('_',' ')
const delayLabel=(m:number,es:boolean)=>m>=1440?(es?`${Math.round(m/1440)} día${Math.round(m/1440)===1?'':'s'}`:`${Math.round(m/1440)} day${Math.round(m/1440)===1?'':'s'}`):m>=60?(es?`${Math.round(m/60)} hora${Math.round(m/60)===1?'':'s'}`:`${Math.round(m/60)} hour${Math.round(m/60)===1?'':'s'}`):(es?`${m} minutos`:`${m} minutes`)
const personName=(c:any,es:boolean)=>[c?.first_name,c?.last_name].filter(Boolean).join(' ')||(es?'Persona de evangelismo':'Outreach contact')

export default async function CommunicationsPage({searchParams}:{searchParams:Promise<{lang?:string;status?:string;template_saved?:string;cancelled?:string;opted_out?:string;error?:string}>}){
  const params=await searchParams,es=params.lang==='es',lang=es?'es':'en'
  const l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const {data:customManage}=await supabase.rpc('current_user_has_church_permission',{p_church_id:membership.church_id,p_permission_key:'manage_outreach'})
  const isAdmin=['pastor','church_admin'].includes(membership.role)
  const canManage=isAdmin||['ministry_leader','minister'].includes(membership.role)||Boolean(customManage)
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  let outboxQuery=supabase.from('communication_outbox').select('*').eq('church_id',membership.church_id).order('due_at',{ascending:true}).limit(150)
  if(params.status&&params.status!=='all')outboxQuery=outboxQuery.eq('status',params.status)
  const [{data:outbox},{data:templates},{data:provider}]=await Promise.all([
    outboxQuery,
    canManage?supabase.from('communication_templates').select('*').eq('church_id',membership.church_id).order('template_key').order('channel').order('language_code'):Promise.resolve({data:[] as any[]}),
    canManage?supabase.from('church_communication_providers').select('email_provider,email_ready,email_from,sms_provider,sms_ready').eq('church_id',membership.church_id).maybeSingle():Promise.resolve({data:null as any})
  ])
  const contactIds=Array.from(new Set((outbox??[]).map((x:any)=>x.contact_id)));let contacts:any[]=[];if(contactIds.length){const r=await supabase.from('outreach_contacts').select('id,first_name,last_name,email,phone,email_consent,sms_consent,communication_opt_out_at').in('id',contactIds);contacts=r.data??[]}
  const cm=new Map(contacts.map((c:any)=>[c.id,c])),all=outbox??[]
  const counts={waiting:all.filter((x:any)=>x.status==='waiting_provider').length,suppressed:all.filter((x:any)=>x.status==='suppressed').length,sent:all.filter((x:any)=>x.status==='sent').length,failed:all.filter((x:any)=>x.status==='failed').length}
  const emailReady=Boolean(provider?.email_ready),smsReady=Boolean(provider?.sms_ready)
  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Church'} • {es?'Comunicaciones de Evangelismo':'Evangelism Communications'}</div></div><div className="row">{isAdmin&&<Link className="ghost" href={l('/outreach/communications/provider')}><Settings size={13}/> {es?'Proveedor':'Provider Setup'}</Link>}<Link className="ghost" href="/outreach/communications?lang=en">English</Link><Link className="ghost" href="/outreach/communications?lang=es">Español</Link><Link className="ghost" href={l('/outreach')}>{es?'← Evangelismo':'← Evangelism'}</Link></div></header>

    <section className="card" style={{padding:24,marginBottom:16}}><div className="pill">{es?'AUTOMATIZACIÓN DE SEGUIMIENTO':'FOLLOW-UP AUTOMATION'}</div><h1>{es?'Cada mensaje debe ser visible, consentido y rastreable.':'Every message should be visible, consented and traceable.'}</h1><p className="muted">{es?'Kingdom Network prepara los mensajes cuando ocurre el siguiente paso de evangelismo.':'Kingdom Network prepares messages when the next evangelism step happens.'}</p><div className={emailReady||smsReady?'notice success':'notice'} style={{marginTop:12}}>{emailReady||smsReady?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} <strong>{es?'Estado de entrega:':'Delivery status:'}</strong> Email — {emailReady?(es?'activo':'active'):(es?'desactivado':'off')} • SMS — {smsReady?(es?'activo':'active'):(es?'no conectado':'not connected')}. {!emailReady&&!smsReady&&(es?'Los mensajes con consentimiento esperan aquí; no se marcan como enviados.':'Consented messages wait here and are not marked sent.')}</div></section>
    {params.template_saved&&<div className="notice success">{es?'Plantilla guardada.':'Template saved.'}</div>}{params.cancelled&&<div className="notice success">{es?'Mensaje cancelado.':'Message cancelled.'}</div>}{params.opted_out&&<div className="notice success">{es?'Se registró que la persona no desea comunicaciones.':'Communication opt-out recorded.'}</div>}{params.error&&<div className="notice error">{params.error}</div>}

    <section className="stat-grid" style={{marginBottom:18}}><div className="card stat-card"><Clock3/><div><strong>{counts.waiting}</strong><span>{es?'esperando proveedor':'waiting for provider'}</span></div></div><div className="card stat-card"><PauseCircle/><div><strong>{counts.suppressed}</strong><span>{es?'suprimidos por consentimiento':'suppressed / no consent'}</span></div></div><div className="card stat-card"><CheckCircle2/><div><strong>{counts.sent}</strong><span>{es?'enviados':'sent'}</span></div></div><div className="card stat-card"><XCircle/><div><strong>{counts.failed}</strong><span>{es?'fallidos':'failed'}</span></div></div></section>

    <form className="card" style={{padding:14,marginBottom:18}}><div className="row" style={{gap:10,alignItems:'end',flexWrap:'wrap'}}><label className="field"><span>{es?'Estado':'Status'}</span><select name="status" defaultValue={params.status??'all'}><option value="all">{es?'Todos':'All'}</option><option value="waiting_provider">{es?'Esperando proveedor':'Waiting for provider'}</option><option value="suppressed">{es?'Suprimido':'Suppressed'}</option><option value="sent">{es?'Enviado':'Sent'}</option><option value="failed">{es?'Falló':'Failed'}</option><option value="cancelled">{es?'Cancelado':'Cancelled'}</option></select></label>{es&&<input type="hidden" name="lang" value="es"/>}<button className="ghost">{es?'Filtrar':'Filter'}</button></div></form>

    <section style={{display:'grid',gap:12,marginBottom:28}}>{all.map((item:any)=>{const c:any=cm.get(item.contact_id);return <article className="card" style={{padding:18}} key={item.id}><div className="row" style={{justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="row" style={{gap:7,flexWrap:'wrap'}}><span className="pill">{item.channel==='email'?<Mail size={10}/>:<MessageSquareText size={10}/>} {item.channel.toUpperCase()}</span><span className="pill">{statusLabel(item.status,es).toUpperCase()}</span></div><h3 style={{margin:'8px 0 3px'}}>{personName(c,es)} • {item.template_key.replaceAll('_',' ')}</h3><div className="small muted">{item.recipient} • {es?'programado':'due'} {new Date(item.due_at).toLocaleString()}</div></div>{canManage&&['queued','waiting_provider','failed'].includes(item.status)&&<form action={cancelQueuedCommunication}><input type="hidden" name="outbox_id" value={item.id}/><input type="hidden" name="lang" value={lang}/><button className="ghost">{es?'Cancelar':'Cancel'}</button></form>}</div>{item.subject_snapshot&&<div style={{marginTop:10}}><strong>{item.subject_snapshot}</strong></div>}<p style={{whiteSpace:'pre-wrap',lineHeight:1.6}}>{item.body_snapshot}</p>{item.error_message&&<div className="small muted">{item.error_message}</div>}{canManage&&c&&!c.communication_opt_out_at&&<details style={{marginTop:10}}><summary style={{cursor:'pointer',fontWeight:700}}>{es?'Opciones de contacto':'Contact options'}</summary><form action={suppressContactCommunications} style={{marginTop:10}}><input type="hidden" name="contact_id" value={item.contact_id}/><input type="hidden" name="lang" value={lang}/><button className="ghost">{es?'Registrar “no enviar más mensajes”':'Record “do not message” opt-out'}</button></form></details>}</article>})}{!all.length&&<div className="card" style={{padding:24,textAlign:'center'}}><ShieldCheck size={28}/><h3>{es?'No hay mensajes en esta vista.':'No messages in this view.'}</h3><p className="muted">{es?'Cuando un invitado avance en Evangelismo, los mensajes preparados aparecerán aquí.':'As guests move through Evangelism, prepared messages will appear here.'}</p></div>}</section>

    {canManage&&<section><div className="pill" style={{marginBottom:10}}>{es?'PLANTILLAS':'TEMPLATES'}</div><div style={{display:'grid',gap:12}}>{(templates??[]).map((t:any)=><details className="card" style={{padding:16}} key={t.id}><summary style={{cursor:'pointer',fontWeight:800}}>{t.name} • {t.channel.toUpperCase()} • {t.language_code.toUpperCase()} • {t.active?(es?'ACTIVA':'ACTIVE'):(es?'PAUSADA':'PAUSED')}</summary><form action={updateCommunicationTemplate} style={{display:'grid',gap:9,marginTop:12}}><input type="hidden" name="template_id" value={t.id}/><input type="hidden" name="lang" value={lang}/><label className="field"><span>{es?'Nombre interno':'Internal name'}</span><input name="name" defaultValue={t.name} required/></label>{t.channel==='email'&&<label className="field"><span>{es?'Asunto':'Subject'}</span><input name="subject" defaultValue={t.subject??''}/></label>}<label className="field"><span>{es?'Mensaje':'Message'}</span><textarea name="body" rows={5} defaultValue={t.body}/><small className="muted">{es?'Variables disponibles: {{first_name}}, {{church_name}}':'Available variables: {{first_name}}, {{church_name}}'}</small></label><label className="field"><span>{es?'Esperar antes de preparar':'Delay before preparing'}</span><input type="number" name="delay_minutes" min="0" defaultValue={t.delay_minutes}/><small className="muted">{delayLabel(Number(t.delay_minutes||0),es)}</small></label><label className="row"><input type="checkbox" name="active" defaultChecked={t.active}/> {es?'Automatización activa':'Automation active'}</label><button className="btn">{es?'Guardar plantilla':'Save template'}</button></form></details>)}</div></section>}
  </main>
}