import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BookOpen,CalendarDays,ClipboardPlus,Eye,EyeOff,PlusCircle,ShieldCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { addLesson,addQuestion,createAssessment,createCourse,createCourseSession,toggleCoursePublished } from '../admin/actions'

export default async function CurriculumManager({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const query=await searchParams
  const supabase=await createClient()
  const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub
  if(!userId)redirect('/login')
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/learning')
  const {data:customAccess}=await supabase.rpc('current_user_has_church_permission',{p_church_id:membership.church_id,p_permission_key:'manage_learning'})
  const canManage=['minister','pastor','church_admin'].includes(membership.role)||Boolean(customAccess)
  if(!canManage)redirect('/learning')
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  const {data:coursesData}=await supabase.from('courses').select('*').eq('church_id',membership.church_id).order('pathway_order').order('created_at',{ascending:false})
  const courses=coursesData??[],courseIds=courses.map((c:any)=>c.id)
  let modules:any[]=[],assessments:any[]=[]
  if(courseIds.length){const [m,a]=await Promise.all([supabase.from('course_modules').select('id,course_id,position,title').in('course_id',courseIds).order('position'),supabase.from('course_assessments').select('id,course_id,module_id,title,assessment_type,passing_score,published,required').in('course_id',courseIds).order('created_at')]);modules=m.data??[];assessments=a.data??[]}
  const assessmentIds=assessments.map((a:any)=>a.id);let questions:any[]=[];if(assessmentIds.length){const q=await supabase.from('assessment_questions').select('id,assessment_id').in('assessment_id',assessmentIds);questions=q.data??[]}
  const qCount=new Map<string,number>();for(const q of questions)qCount.set(q.assessment_id,(qCount.get(q.assessment_id)??0)+1)
  const modsBy=new Map<string,any[]>();for(const m of modules){const x=modsBy.get(m.course_id)??[];x.push(m);modsBy.set(m.course_id,x)}
  const assBy=new Map<string,any[]>();for(const a of assessments){const x=assBy.get(a.course_id)??[];x.push(a);assBy.set(a.course_id,x)}
  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Your Church'} • Curriculum Manager</div></div><div className="row"><Link className="ghost" href="/learning">← Learning</Link><Link className="ghost" href="/">Home</Link></div></header>
    <section className="card" style={{padding:24,marginBottom:16}}><div className="pill">CURRICULUM MANAGER</div><h1>Build classes without broad church-admin access.</h1><p className="muted">Create courses, lessons, checkpoint tests, finals and classroom sessions. Kingdom Network keeps the secure permission underneath your church-defined role.</p><div className="notice" style={{marginTop:12}}><strong>Assessment standard:</strong> checkpoint tests should contain 5–10 questions. Final exams should contain 20–25 questions. Learners must pass required checkpoints before advancing.</div></section>
    {query.error&&<div className="notice error">{query.error}</div>}
    <details className="card" style={{padding:18,marginBottom:18}}><summary style={{fontWeight:800,cursor:'pointer'}}><PlusCircle size={15}/> Create course draft</summary><form action={createCourse} style={{display:'grid',gap:10,marginTop:14}}><label className="field"><span>Course title</span><input name="title" required/></label><label className="field"><span>Description</span><textarea name="description" rows={3}/></label><div className="row"><label className="field" style={{flex:1}}><span>Language</span><select name="language_code" defaultValue="en"><option value="en">English</option><option value="es">Español</option></select></label><label className="field" style={{flex:1}}><span>Audience</span><select name="audience_level" defaultValue="member"><option value="new_convert">New convert</option><option value="member">Member</option><option value="teacher_training">Teacher training</option><option value="leadership">Leadership</option><option value="general">General</option></select></label><label className="field" style={{flex:1}}><span>Pathway</span><select name="pathway_stage" defaultValue="foundation"><option value="new_convert">New convert</option><option value="foundation">Foundation</option><option value="outreach">Outreach</option><option value="teaching">Teaching</option><option value="leadership">Leadership</option><option value="specialized">Specialized</option></select></label></div><input type="hidden" name="passing_score" value="80"/><button className="btn">Create draft</button></form></details>
    <section style={{display:'grid',gap:16}}>{courses.map((course:any)=>{const ms=modsBy.get(course.id)??[],as=assBy.get(course.id)??[];return <article className="card" style={{padding:20}} key={course.id}><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start',gap:12,flexWrap:'wrap'}}><div><div className="pill">{String(course.pathway_stage??'foundation').replaceAll('_',' ').toUpperCase()}</div><h2 style={{margin:'8px 0 4px'}}>{course.title}</h2><p className="small muted">{course.description||'No description yet.'}</p></div><form action={toggleCoursePublished}><input type="hidden" name="course_id" value={course.id}/><input type="hidden" name="published" value={course.published?'0':'1'}/><button className="ghost">{course.published?<><EyeOff size={13}/> Unpublish</>:<><Eye size={13}/> Publish</>}</button></form></div>
      <div className="row" style={{gap:10,flexWrap:'wrap',margin:'12px 0'}}><span className="pill"><BookOpen size={11}/> {ms.length} lessons</span><span className="pill"><ClipboardPlus size={11}/> {as.length} tests</span><Link className="ghost" href={`/learning/${course.id}`}>Preview course</Link></div>
      <details style={{marginTop:10}}><summary style={{fontWeight:750,cursor:'pointer'}}>Add lesson</summary><form action={addLesson} style={{display:'grid',gap:9,marginTop:10}}><input type="hidden" name="course_id" value={course.id}/><label className="field"><span>Lesson title</span><input name="title" required/></label><label className="field"><span>Summary</span><input name="summary"/></label><label className="field"><span>Lesson text</span><textarea name="body" rows={5}/></label><button className="ghost">Add lesson</button></form></details>
      <details style={{marginTop:10}}><summary style={{fontWeight:750,cursor:'pointer'}}>Add checkpoint or final</summary><form action={createAssessment} style={{display:'grid',gap:9,marginTop:10}}><input type="hidden" name="course_id" value={course.id}/><label className="field"><span>Title</span><input name="title" required placeholder="Checkpoint 1"/></label><label className="field"><span>Type</span><select name="assessment_type" defaultValue="lesson_quiz"><option value="lesson_quiz">Checkpoint test</option><option value="knowledge_check">Knowledge check</option><option value="final_exam">Final exam</option></select></label><label className="field"><span>Attach after lesson</span><select name="module_id" defaultValue=""><option value="">Whole course / final</option>{ms.map((m:any)=><option key={m.id} value={m.id}>{m.position}. {m.title}</option>)}</select></label><input type="hidden" name="passing_score" value="80"/><label className="row"><input type="checkbox" name="required" defaultChecked/> Required to continue</label><label className="row"><input type="checkbox" name="published" defaultChecked/> Published</label><button className="ghost">Create assessment</button></form></details>
      {as.length>0&&<div style={{display:'grid',gap:9,marginTop:14}}>{as.map((a:any)=>{const count=qCount.get(a.id)??0,target=a.assessment_type==='final_exam'?'20–25':'5–10';const good=a.assessment_type==='final_exam'?count>=20&&count<=25:count>=5&&count<=10;return <details className="card" style={{padding:14,background:'rgba(255,255,255,.025)'}} key={a.id}><summary style={{cursor:'pointer',fontWeight:750}}>{a.title} • {count} questions • target {target} {good?'✓':''}</summary><form action={addQuestion} style={{display:'grid',gap:8,marginTop:12}}><input type="hidden" name="assessment_id" value={a.id}/><label className="field"><span>Question</span><input name="prompt" required/></label><label className="field"><span>Type</span><select name="question_type" defaultValue="multiple_choice"><option value="multiple_choice">Multiple choice</option><option value="true_false">True / False</option><option value="multi_select">Select all that apply</option></select></label><label className="field"><span>Answer choices — one per line</span><textarea name="options" rows={4}/></label><label className="field"><span>Correct answer</span><input name="correct_answer" required placeholder="1, or 1,3; true/false"/></label><input type="hidden" name="points" value="1"/><button className="ghost">Add question</button></form></details>})}</div>}
      <details style={{marginTop:10}}><summary style={{fontWeight:750,cursor:'pointer'}}><CalendarDays size={13}/> Schedule classroom session</summary><form action={createCourseSession} style={{display:'grid',gap:9,marginTop:10}}><input type="hidden" name="course_id" value={course.id}/><label className="field"><span>Class name</span><input name="title" required/></label><label className="field"><span>Date</span><input name="session_date" type="date" required/></label><label className="field"><span>Start time</span><input name="starts_at" type="time"/></label><label className="field"><span>Teacher</span><input name="instructor_name"/></label><button className="ghost"><ShieldCheck size={13}/> Create session</button></form></details>
    </article>})}{!courses.length&&<div className="card" style={{padding:20}}><h3>No course drafts yet.</h3><p className="muted">Create the first one above.</p></div>}</section>
  </main>
}
