import Link from 'next/link'
import {redirect} from 'next/navigation'
import {AlertCircle,BriefcaseBusiness,ClipboardCheck,FileWarning,HandHeart,Megaphone} from 'lucide-react'
import {createClient} from '@/lib/supabase/server'
import {updateFormSubmissionWork} from './actions'

const name=(p:any)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Member'
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):''

export default async function ChurchInbox({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
 const q=await searchParams,supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect('/login')
 const {data:m}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!m?.church_id)redirect('/')
 const {data:permission}=await supabase.rpc('current_user_has_church_permission',{p_church_id:m.church_id,p_permission_key:'manage_members'});if(!['pastor','church_admin'].includes(m.role)&&!permission)redirect('/')
 const churchId=m.church_id,now=new Date().toISOString()
 const [{data:forms},{count:care},{count:docs},{count:ministry},{count:outreach},{data:members}]=await Promise.all([
  supabase.from('church_form_submissions').select('id,status,owner_user_id,next_action,due_at,leadership_note,created_at,answers,submitted_by,church_forms(title,form_schema)').eq('church_id',churchId).in('status',['new','in_review']).order('due_at',{ascending:true,nullsFirst:false}).order('created_at',{ascending:true}).limit(50),
  supabase.from('care_requests').select('*',{count:'exact',head:true}).eq('church_id',churchId).in('status',['new','in_review']),
  supabase.from('member_documents').select('*',{count:'exact',head:true}).eq('church_id',churchId).eq('verification_status','pending'),
  supabase.from('ministry_applications').select('id,ministries!inner(church_id)',{count:'exact',head:true}).eq('ministries.church_id',churchId).in('status',['submitted','under_review']),
  supabase.from('outreach_contacts').select('*',{count:'exact',head:true}).eq('church_id',churchId).lt('follow_up_due_at',now).not('stage','in','("inactive","serving")'),
  supabase.from('church_memberships').select('user_id,profiles(id,display_name,first_name,last_name)').eq('church_id',churchId).eq('status','active')
 ])
 const profiles=(members??[]).map((x:any)=>Array.isArray(x.profiles)?x.profiles[0]:x.profiles).filter(Boolean),profileById=new Map(profiles.map((p:any)=>[p.id,p]));const submitterIds=Array.from(new Set((forms??[]).map((x:any)=>x.submitted_by).filter(Boolean)));if(submitterIds.length){const r=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',submitterIds);for(const p of r.data??[])profileById.set(p.id,p)}
 const church:any=Array.isArray(m.churches)?m.churches[0]:m.churches,total=(forms?.length||0)+(care||0)+(docs||0)+(ministry||0)+(outreach||0)
 const queues=[['Pastoral care',care||0,'/help/admin',HandHeart],['Documents to verify',docs||0,'/documents',FileWarning],['Ministry applications',ministry||0,'/serve',BriefcaseBusiness],['Overdue outreach',outreach||0,'/outreach',Megaphone]] as const
 return <main className="shell"><header className="topbar"><div><Link href="/church" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name||'Church'} • Work Inbox</div></div><div className="row"><Link className="ghost" href="/church/forms">Forms & Workflows</Link><Link className="ghost" href="/church">← Admin</Link></div></header>
 <section className="hero card"><div><div className="pill"><ClipboardCheck size={12}/> ONE WORK INBOX</div><h1>What needs a leader?</h1><p>Use one starting place for form requests, pastoral care, document reviews, ministry applications and overdue outreach. Open the specialized tool only when you need its detail.</p></div><div className="hero-stat"><strong>{total}</strong><span>open items across queues</span></div></section>{q.saved&&<div className="notice success">{q.saved}</div>}{q.error&&<div className="notice error">{q.error}</div>}
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginBottom:18}}>{queues.map(([label,count,href,Icon])=><Link href={href} className="card" style={{padding:15,textDecoration:'none',border:count?'1px solid rgba(251,191,36,.38)':undefined}} key={label}><Icon size={18}/><strong style={{fontSize:26,display:'block',marginTop:6}}>{count}</strong><span className="small muted">{label}</span></Link>)}</section>
 <div className="section-heading"><div><div className="pill">FORM WORK</div><h2>Requests that need ownership</h2></div><span className="small muted">Owner • status • next action • due date</span></div><section style={{display:'grid',gap:12}}>{(forms??[]).map((row:any)=>{const form:any=Array.isArray(row.church_forms)?row.church_forms[0]:row.church_forms;const schema=Array.isArray(form?.form_schema)?form.form_schema:[];return <article className="card" key={row.id} style={{padding:16,border:row.due_at&&new Date(row.due_at)<new Date()?'1px solid rgba(248,113,113,.48)':undefined}}><div className="row" style={{justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="pill">{String(row.status).replaceAll('_',' ').toUpperCase()}</div><h3 style={{margin:'7px 0 3px'}}>{form?.title||'Church form'}</h3><div className="small muted">Submitted by {name(profileById.get(row.submitted_by))} • {date(row.created_at)}{row.due_at?` • due ${date(row.due_at)}`:''}</div></div>{row.due_at&&new Date(row.due_at)<new Date()&&<span className="pill urgent"><AlertCircle size={11}/> OVERDUE</span>}</div><details style={{marginTop:10}}><summary>View answers</summary><div style={{display:'grid',gap:7,marginTop:9}}>{schema.map((field:any)=><div key={field.key}><strong className="small">{field.label}</strong><div className="small muted">{String(row.answers?.[field.key]??'—')}</div></div>)}</div></details><form action={updateFormSubmissionWork} className="studio-grid" style={{marginTop:12}}><input type="hidden" name="submission_id" value={row.id}/><label><span>Status</span><select name="status" defaultValue={row.status}><option value="new">New</option><option value="in_review">In review</option><option value="approved">Approved</option><option value="declined">Declined</option><option value="completed">Completed</option></select></label><label><span>Owner</span><select name="owner_user_id" defaultValue={row.owner_user_id||''}><option value="">Unassigned</option>{profiles.map((p:any)=><option key={p.id} value={p.id}>{name(p)}</option>)}</select></label><label className="wide"><span>Next action</span><input name="next_action" defaultValue={row.next_action||''} placeholder="Call member, verify details, schedule meeting…"/></label><label><span>Due date</span><input type="date" name="due_at" defaultValue={row.due_at?String(row.due_at).slice(0,10):''}/></label><label className="wide"><span>Leadership note</span><textarea name="leadership_note" rows={2} defaultValue={row.leadership_note||''}/></label><button className="btn wide">Save work item</button></form></article>})}{!forms?.length&&<div className="card empty"><ClipboardCheck size={28}/><h3>No open form submissions.</h3><p className="muted">Published forms will route new work here when members submit them.</p></div>}</section>
 </main>
}
