import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BookOpen,CalendarDays,CheckCircle2,Church,HandHeart,Languages,MessageSquareWarning,Sparkles,UserRound,UsersRound,BriefcaseBusiness } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { completeOnboarding } from './actions'
import './start.css'

const copy={
 en:{title:'Welcome to Kingdom Network',subtitle:'You do not need to learn the whole platform today. Start with these three things and explore more when you are ready.',church:'Your church',member:'Your account is connected',walk:'START WITH THESE 3',more:'EXPLORE WHEN YOU ARE READY',help:'HELP & FEEDBACK',profile:'1. Check your profile',profileBody:'Make sure your name and basic information are right. Add a photo when you are ready.',journey:'2. See My Journey',journeyBody:'See your spiritual milestones and the next step in your walk with God.',today:'3. Open My Today',todayBody:'This is your simple everyday screen for what matters now: classes, assignments and next steps.',learning:'Learning',learningBody:'Take church classes and track completion.',groups:'Friendship Groups',groupsBody:'Find your group, meeting information and people you are growing with.',serve:'Serve',serveBody:'Explore ministries and opportunities to serve.',calendar:'Calendar',calendarBody:'See services, classes and upcoming events.',guide:'Kingdom Guide',guideBody:'Not sure where to go? Kingdom Guide helps you find the right place and trusted church resources.',care:'Prayer or help',careBody:'Send a private prayer or pastoral-care request.',feedback:'Share an idea',feedbackBody:'Tell us what is confusing, broken, useful or missing.',note:'That is enough for your first visit. You can always come back to Start Here.',finish:'I’m ready — take me Home',spanish:'Español',english:'English',ready:'Your account is ready.',error:'Something needs attention',start:'Start Here',adminPill:'SETTING UP THE CHURCH?',adminTitle:'Continue Church Builder',adminBody:'Church Builder walks authorized leaders through setup one clear step at a time.',adminButton:'Open Church Builder'},
 es:{title:'Bienvenido a Kingdom Network',subtitle:'No necesitas aprender toda la plataforma hoy. Comienza con estas tres cosas y explora más cuando estés listo.',church:'Tu iglesia',member:'Tu cuenta está conectada',walk:'COMIENZA CON ESTOS 3',more:'EXPLORA CUANDO ESTÉS LISTO',help:'AYUDA Y COMENTARIOS',profile:'1. Revisa tu perfil',profileBody:'Asegúrate de que tu nombre y datos básicos estén correctos. Agrega una foto cuando quieras.',journey:'2. Mira Mi Jornada',journeyBody:'Mira tus pasos espirituales y el próximo paso en tu caminar con Dios.',today:'3. Abre Mi Día',todayBody:'Esta es tu pantalla sencilla para ver lo importante ahora: clases, asignaciones y próximos pasos.',learning:'Aprendizaje',learningBody:'Toma clases de la iglesia y mira tu progreso.',groups:'Grupos de Amistad',groupsBody:'Encuentra tu grupo, reuniones y personas con quienes estás creciendo.',serve:'Servir',serveBody:'Explora ministerios y oportunidades para servir.',calendar:'Calendario',calendarBody:'Mira servicios, clases y próximos eventos.',guide:'Kingdom Guide',guideBody:'¿No sabes dónde ir? Kingdom Guide te ayuda a encontrar el lugar correcto y recursos confiables de la iglesia.',care:'Oración o ayuda',careBody:'Envía una solicitud privada de oración o cuidado pastoral.',feedback:'Comparte una idea',feedbackBody:'Dinos qué es confuso, qué no funciona, qué te ayuda o qué falta.',note:'Eso es suficiente para tu primera visita. Siempre puedes volver a Empieza Aquí.',finish:'Estoy listo — ir a Inicio',spanish:'Español',english:'English',ready:'Tu cuenta está lista.',error:'Algo necesita atención',start:'Empieza Aquí',adminPill:'¿ESTÁS CONFIGURANDO LA IGLESIA?',adminTitle:'Continuar Church Builder',adminBody:'Church Builder guía a los líderes autorizados paso por paso de forma sencilla.',adminButton:'Abrir Church Builder'}
} as const

export default async function StartPage({searchParams}:{searchParams:Promise<{lang?:string;error?:string}>}){
 const params=await searchParams,supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();const preferred=user?.user_metadata?.preferred_language==='es'?'es':'en';const lang=params.lang==='es'?'es':params.lang==='en'?'en':preferred,t=copy[lang],suffix=lang==='es'?'?lang=es':'';const withLang=(path:string)=>lang==='es'?`${path}${path.includes('?')?'&':'?'}lang=es`:path;const userId=user?.id;if(!userId)redirect(`/login${suffix}`)
 const [{data:profile},{data:membership}]=await Promise.all([supabase.from('profiles').select('display_name,first_name,last_name').eq('id',userId).maybeSingle(),supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).maybeSingle()]);if(!membership?.church_id)redirect('/');const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches;const name=profile?.display_name||[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||(lang==='es'?'Miembro':'Member'),isAdmin=['pastor','church_admin'].includes(String(membership.role))
 const first=[
  [UserRound,t.profile,t.profileBody,'/profile'],[Sparkles,t.journey,t.journeyBody,'/journey'],[CheckCircle2,t.today,t.todayBody,'/today']
 ] as const
 const explore=[
  [BookOpen,t.learning,t.learningBody,'/learning'],[UsersRound,t.groups,t.groupsBody,'/groups'],[BriefcaseBusiness,t.serve,t.serveBody,'/serve'],[CalendarDays,t.calendar,t.calendarBody,'/calendar']
 ] as const
 return <main className="shell start-shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??t.church} • {t.start}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/start?lang=en">{t.english}</Link><Link className="ghost" href="/start?lang=es">{t.spanish}</Link></div></header>
 <section className="card start-hero"><div><div className="pill">START HERE • EMPIEZA AQUÍ</div><h1>{t.title}</h1><p className="muted">{t.subtitle}</p></div><div className="start-ready"><CheckCircle2 size={28}/><strong>{t.ready}</strong></div></section>{params.error&&<div className="notice error"><strong>{t.error}:</strong> {params.error}</div>}
 <section className="card start-account"><div><div className="pill">{t.member.toUpperCase()}</div><h2>{name}</h2><p className="muted">{church?.name??t.church} • {String(membership.role||'member').replaceAll('_',' ')}</p></div><CheckCircle2 size={34}/></section>
 {isAdmin&&<section className="card" style={{padding:20,marginBottom:18,display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',flexWrap:'wrap'}}><div style={{display:'flex',gap:12,alignItems:'flex-start',maxWidth:760}}><div className="start-icon"><Church size={20}/></div><div><div className="pill">{t.adminPill}</div><h2 style={{margin:'7px 0 5px'}}>{t.adminTitle}</h2><p className="muted" style={{margin:0}}>{t.adminBody}</p></div></div><Link className="btn" href={withLang('/church/launch')}>{t.adminButton}</Link></section>}
 <section><div className="pill" style={{marginBottom:12}}>{t.walk}</div><div style={{display:'grid',gap:12}}>{first.map(([Icon,title,body,path])=><Link key={path} className="card start-step" href={withLang(path)} style={{padding:20}}><div className="start-icon"><Icon size={20}/></div><div><strong style={{fontSize:'1.08rem'}}>{title}</strong><span>{body}</span></div></Link>)}</div></section>
 <section style={{marginTop:24}}><div className="pill" style={{marginBottom:12}}>{t.more}</div><div className="start-grid">{explore.map(([Icon,title,body,path])=><Link key={path} className="card start-step" href={withLang(path)}><div className="start-icon"><Icon size={19}/></div><div><strong>{title}</strong><span>{body}</span></div></Link>)}</div></section>
 <section style={{marginTop:24}}><div className="pill" style={{marginBottom:12}}>{t.help}</div><div className="start-grid"><Link className="card start-step" href={withLang('/guide')}><div className="start-icon"><Sparkles size={19}/></div><div><strong>{t.guide}</strong><span>{t.guideBody}</span></div></Link><Link className="card start-step" href={withLang('/help')}><div className="start-icon"><HandHeart size={19}/></div><div><strong>{t.care}</strong><span>{t.careBody}</span></div></Link><Link className="card start-step" href={withLang('/feedback')}><div className="start-icon"><MessageSquareWarning size={19}/></div><div><strong>{t.feedback}</strong><span>{t.feedbackBody}</span></div></Link></div></section>
 <section className="card start-note"><p>{t.note}</p><form action={completeOnboarding}><input type="hidden" name="lang" value={lang}/><button className="btn" type="submit">{t.finish}</button></form></section></main>
}
