import Link from 'next/link'
import { notFound } from 'next/navigation'
import { CheckCircle2,Church,Languages,ShieldCheck } from 'lucide-react'
import { createClient as createPublicClient } from '@supabase/supabase-js'
import { SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL } from '@/lib/supabase/config'
import { joinChurch } from './actions'
import { JoinSubmitButton } from './join-submit-button'

const copy={
  en:{join:'JOIN YOUR CHURCH',title:'Welcome to',body:'Create your account in about a minute. You do not need to fill out your whole profile today — Kingdom Network will help you one step at a time.',first:'First name',last:'Last name',phone:'Mobile phone (optional)',email:'Email',password:'Create password',confirm:'Type password again',updates:'Stay connected (optional)',emailOk:'I’m okay receiving church follow-up by email.',smsOk:'I’m okay receiving church follow-up by text message.',consent:'Only choose channels you actually want. You can change this later.',create:'Join & create my account',creating:'Creating your account…',signin:'Already have an account? Sign in',full:'Public signup is currently paused for this church.',remaining:'pilot spots remaining',next:'After signup',one:'Confirm your email',two:'Open Start Here',three:'Complete the rest when you are ready',private:'Your account connects to this church. Private Journey notes remain private unless you intentionally share something.'},
  es:{join:'ÚNETE A TU IGLESIA',title:'Bienvenido a',body:'Crea tu cuenta en aproximadamente un minuto. No tienes que completar todo tu perfil hoy — Kingdom Network te ayudará paso a paso.',first:'Nombre',last:'Apellido',phone:'Teléfono móvil (opcional)',email:'Correo electrónico',password:'Crear contraseña',confirm:'Escribe la contraseña otra vez',updates:'Mantente conectado (opcional)',emailOk:'Acepto recibir seguimiento de la iglesia por correo.',smsOk:'Acepto recibir seguimiento de la iglesia por mensaje de texto.',consent:'Marca solamente los canales que realmente quieres recibir. Puedes cambiar esto después.',create:'Unirme y crear mi cuenta',creating:'Creando tu cuenta…',signin:'¿Ya tienes una cuenta? Inicia sesión',full:'El registro público está pausado para esta iglesia.',remaining:'lugares del piloto disponibles',next:'Después de registrarte',one:'Confirma tu correo',two:'Abre Empieza Aquí',three:'Completa lo demás cuando estés listo',private:'Tu cuenta se conecta con esta iglesia. Tus notas privadas de Mi Jornada permanecen privadas a menos que tú elijas compartir algo.'}
} as const

export default async function JoinChurchPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{lang?:string;error?:string}>}){
  const [{slug},query]=await Promise.all([params,searchParams])
  const lang=query.lang==='es'?'es':'en',t=copy[lang]
  const supabase=createPublicClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
  const {data}=await supabase.rpc('get_public_signup_status_for_church',{p_church_slug:slug})
  const church:any=Array.isArray(data)?data[0]:data
  if(!church?.church_id)notFound()
  const swap=(next:'en'|'es')=>`/join/${encodeURIComponent(slug)}?lang=${next}`
  return <main className="login-wrap"><div className="login card" style={{maxWidth:620}}>
    <div className="row" style={{justifyContent:'space-between',alignItems:'center',marginBottom:8}}><div className="pill">{t.join}</div><div className="row" style={{gap:6}}><Languages size={14}/><Link className="ghost" href={swap('en')}>English</Link><Link className="ghost" href={swap('es')}>Español</Link></div></div>
    <div style={{textAlign:'center',margin:'16px 0 20px'}}><Church size={38}/><h1 style={{margin:'10px 0 5px'}}>{t.title} {church.church_name}</h1><p className="muted" style={{lineHeight:1.6}}>{t.body}</p>{church.remaining!=null&&<div className="pill" style={{display:'inline-flex',marginTop:8}}>{church.remaining} {t.remaining}</div>}</div>
    {query.error&&<div className="notice error">{query.error}</div>}
    {!church.open?<div className="notice"><strong>{t.full}</strong></div>:<form action={joinChurch} style={{display:'grid',gap:10}}><input type="hidden" name="church_slug" value={slug}/><input type="hidden" name="lang" value={lang}/><div className="row" style={{gap:10,flexWrap:'wrap'}}><label className="field" style={{flex:'1 1 180px'}}><span>{t.first}</span><input name="first_name" autoComplete="given-name" required/></label><label className="field" style={{flex:'1 1 180px'}}><span>{t.last}</span><input name="last_name" autoComplete="family-name" required/></label></div><label className="field"><span>{t.phone}</span><input name="phone" type="tel" inputMode="tel" autoComplete="tel"/></label><label className="field"><span>{t.email}</span><input name="email" type="email" inputMode="email" autoComplete="email" required/></label><div className="row" style={{gap:10,flexWrap:'wrap'}}><label className="field" style={{flex:'1 1 220px'}}><span>{t.password}</span><input name="password" type="password" minLength={8} autoComplete="new-password" required/></label><label className="field" style={{flex:'1 1 220px'}}><span>{t.confirm}</span><input name="confirm_password" type="password" minLength={8} autoComplete="new-password" required/></label></div><div className="card" style={{padding:14,background:'rgba(255,255,255,.025)'}}><strong>{t.updates}</strong><div style={{display:'grid',gap:8,marginTop:9}}><label className="row" style={{gap:8,alignItems:'flex-start'}}><input type="checkbox" name="email_consent"/><span className="small">{t.emailOk}</span></label><label className="row" style={{gap:8,alignItems:'flex-start'}}><input type="checkbox" name="sms_consent"/><span className="small">{t.smsOk}</span></label></div><div className="small muted" style={{marginTop:8}}>{t.consent}</div></div><JoinSubmitButton label={t.create} workingLabel={t.creating}/></form>}
    <Link className="ghost" href={`/login?lang=${lang}&mode=signin`} style={{display:'block',textAlign:'center',marginTop:14}}>{t.signin}</Link>
    <div className="card" style={{padding:14,marginTop:18,background:'rgba(255,255,255,.02)'}}><div className="pill">{t.next.toUpperCase()}</div><div style={{display:'grid',gap:7,marginTop:10}}><div className="row"><CheckCircle2 size={14}/><span className="small">1. {t.one}</span></div><div className="row"><CheckCircle2 size={14}/><span className="small">2. {t.two}</span></div><div className="row"><CheckCircle2 size={14}/><span className="small">3. {t.three}</span></div></div></div>
    <div className="small muted" style={{display:'flex',gap:7,alignItems:'flex-start',marginTop:14}}><ShieldCheck size={14}/><span>{t.private}</span></div>
  </div></main>
}
