import Link from 'next/link'
import { notFound } from 'next/navigation'
import { CheckCircle2,Languages,ShieldCheck,Users } from 'lucide-react'
import { createClient as createPublicClient } from '@supabase/supabase-js'
import { SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL } from '@/lib/supabase/config'
import { joinThroughGroup } from './actions'

const copy={
  en:{pill:'JOIN THROUGH A FRIENDSHIP GROUP',joining:'You’re joining through',body:'Create your Kingdom Network account in about a minute. Your Friendship Group connection will be remembered so the right leader can follow up with you.',first:'First name',last:'Last name',phone:'Mobile phone (optional)',email:'Email',password:'Create password',confirm:'Type password again',updates:'Stay connected (optional)',emailOk:'I’m okay receiving church follow-up by email.',smsOk:'I’m okay receiving church follow-up by text message.',consent:'Only choose channels you actually want. You can change this later.',create:'Join Kingdom Network',signin:'Already have an account? Sign in',full:'Public signup is currently paused for this church.',remaining:'pilot spots remaining',next:'What happens next',one:'Confirm your email',two:'Your account connects to this church',three:'Your Friendship Group source is attached to follow-up',four:'Start Here helps you finish the rest gradually',private:'Private Journey notes stay private unless you intentionally share something.'},
  es:{pill:'ÚNETE POR UN GRUPO DE AMISTAD',joining:'Te estás uniendo por medio de',body:'Crea tu cuenta de Kingdom Network en aproximadamente un minuto. Se guardará tu conexión con el Grupo de Amistad para que el líder correcto pueda darte seguimiento.',first:'Nombre',last:'Apellido',phone:'Teléfono móvil (opcional)',email:'Correo electrónico',password:'Crear contraseña',confirm:'Escribe la contraseña otra vez',updates:'Mantente conectado (opcional)',emailOk:'Acepto recibir seguimiento de la iglesia por correo.',smsOk:'Acepto recibir seguimiento de la iglesia por mensaje de texto.',consent:'Marca solamente los canales que realmente quieres recibir. Puedes cambiar esto después.',create:'Unirme a Kingdom Network',signin:'¿Ya tienes una cuenta? Inicia sesión',full:'El registro público está pausado para esta iglesia.',remaining:'lugares del piloto disponibles',next:'Qué sucede después',one:'Confirma tu correo',two:'Tu cuenta se conecta con esta iglesia',three:'Tu Grupo de Amistad queda conectado al seguimiento',four:'Empieza Aquí te ayuda a completar lo demás poco a poco',private:'Tus notas privadas de Mi Jornada permanecen privadas a menos que tú elijas compartir algo.'}
} as const

export default async function GroupJoinPage({params,searchParams}:{params:Promise<{slug:string;groupId:string}>;searchParams:Promise<{lang?:string;error?:string}>}){
  const [{slug,groupId},query]=await Promise.all([params,searchParams])
  const lang=query.lang==='es'?'es':'en',es=lang==='es',t=copy[lang]
  const supabase=createPublicClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
  const {data}=await supabase.rpc('get_public_friendship_group_join',{p_church_slug:slug,p_group_id:groupId})
  const join:any=Array.isArray(data)?data[0]:data
  if(!join?.church_id||!join?.group_id)notFound()
  const swap=(next:'en'|'es')=>`/join/${encodeURIComponent(slug)}/group/${encodeURIComponent(groupId)}?lang=${next}`
  return <main className="login-wrap"><div className="login card" style={{maxWidth:620}}>
    <div className="row" style={{justifyContent:'space-between',alignItems:'center',marginBottom:8}}><div className="pill">{t.pill}</div><div className="row" style={{gap:6}}><Languages size={14}/><Link className="ghost" href={swap('en')}>English</Link><Link className="ghost" href={swap('es')}>Español</Link></div></div>
    <div style={{textAlign:'center',margin:'16px 0 20px'}}><Users size={40}/><p className="small muted" style={{margin:'10px 0 2px'}}>{t.joining}</p><h1 style={{margin:'2px 0 4px'}}>{join.group_name}</h1><div className="small muted">{join.church_name}</div><p className="muted" style={{lineHeight:1.6}}>{t.body}</p>{join.remaining!=null&&<div className="pill" style={{display:'inline-flex',marginTop:8}}>{join.remaining} {t.remaining}</div>}</div>
    {query.error&&<div className="notice error">{query.error}</div>}
    {!join.open?<div className="notice"><strong>{t.full}</strong></div>:<form action={joinThroughGroup} style={{display:'grid',gap:10}}><input type="hidden" name="church_slug" value={slug}/><input type="hidden" name="group_id" value={groupId}/><input type="hidden" name="lang" value={lang}/><div className="row" style={{gap:10,flexWrap:'wrap'}}><label className="field" style={{flex:'1 1 180px'}}><span>{t.first}</span><input name="first_name" autoComplete="given-name" required/></label><label className="field" style={{flex:'1 1 180px'}}><span>{t.last}</span><input name="last_name" autoComplete="family-name" required/></label></div><label className="field"><span>{t.phone}</span><input name="phone" type="tel" inputMode="tel" autoComplete="tel"/></label><label className="field"><span>{t.email}</span><input name="email" type="email" inputMode="email" autoComplete="email" required/></label><div className="row" style={{gap:10,flexWrap:'wrap'}}><label className="field" style={{flex:'1 1 220px'}}><span>{t.password}</span><input name="password" type="password" minLength={8} autoComplete="new-password" required/></label><label className="field" style={{flex:'1 1 220px'}}><span>{t.confirm}</span><input name="confirm_password" type="password" minLength={8} autoComplete="new-password" required/></label></div><div className="card" style={{padding:14,background:'rgba(255,255,255,.025)'}}><strong>{t.updates}</strong><div style={{display:'grid',gap:8,marginTop:9}}><label className="row" style={{gap:8,alignItems:'flex-start'}}><input type="checkbox" name="email_consent"/><span className="small">{t.emailOk}</span></label><label className="row" style={{gap:8,alignItems:'flex-start'}}><input type="checkbox" name="sms_consent"/><span className="small">{t.smsOk}</span></label></div><div className="small muted" style={{marginTop:8}}>{t.consent}</div></div><button className="btn" type="submit" style={{width:'100%',minHeight:48}}>{t.create}</button></form>}
    <Link className="ghost" href={`/login?lang=${lang}&mode=signin`} style={{display:'block',textAlign:'center',marginTop:14}}>{t.signin}</Link>
    <div className="card" style={{padding:14,marginTop:18,background:'rgba(255,255,255,.02)'}}><div className="pill">{t.next.toUpperCase()}</div><div style={{display:'grid',gap:7,marginTop:10}}>{[t.one,t.two,t.three,t.four].map((x,i)=><div className="row" key={x}><CheckCircle2 size={14}/><span className="small">{i+1}. {x}</span></div>)}</div></div>
    <div className="small muted" style={{display:'flex',gap:7,alignItems:'flex-start',marginTop:14}}><ShieldCheck size={14}/><span>{t.private}</span></div>
  </div></main>
}
