import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Archive,BookOpen,Languages,PlusCircle,Settings2 } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { createBuilderCourse } from './actions'

export default async function ClassBuilderHome({searchParams}:{searchParams:Promise<{lang?:string;error?:string}>}){
  const q=await searchParams,language=q.lang==='es'?'es':'en',es=language==='es',l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!membership?.church_id)redirect('/learning')
  const {data:customLearningAccess}=await supabase.rpc('current_user_has_church_permission',{p_church_id:membership.church_id,p_permission_key:'manage_learning'})
  if(!['minister','pastor','church_admin'].includes(membership.role)&&!customLearningAccess)redirect('/learning')
  const {data:courses}=await supabase.from('courses').select('id,title,description,language_code,published,archived_at,created_at,curriculum_version').eq('church_id',membership.church_id).order('created_at',{ascending:false})
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  const active=(courses??[]).filter((c:any)=>!c.archived_at),archived=(courses??[]).filter((c:any)=>c.archived_at)
  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Class <span>Builder</span></Link><div className="small muted">{church?.name||'Church'} • {es?'Clases configurables':'Configurable learning'}</div></div><div className="row"><Languages size={14}/><Link className="ghost" href="/learning/admin/course-builder?lang=en">English</Link><Link className="ghost" href="/learning/admin/course-builder?lang=es">Español</Link><Link className="ghost" href={l('/learning')}>← {es?'Aprendizaje':'Learning'}</Link></div></header>

    <section className="hero card"><div><div className="pill"><Settings2 size={12}/> {es?'SIN CÓDIGO':'NO CODE'}</div><h1>{es?'Construye tus propias clases.':'Build your church’s own classes.'}</h1><p>{es?'Crea una clase, agrega lecciones y pruebas, cambia el orden y publica cuando esté lista. No necesitas pedir un cambio de código.':'Create a class, add lessons and assessments, change the order, and publish when it is ready. No code change is required.'}</p></div><div className="hero-stat"><strong>{active.length}</strong><span>{es?'clases activas / borradores':'active / draft classes'}</span></div></section>
    {q.error&&<div className="notice error">{q.error}</div>}

    <section style={{display:'grid',gridTemplateColumns:'minmax(280px,380px) 1fr',gap:18,alignItems:'start'}}>
      <aside className="card" style={{padding:20}}><div className="pill"><PlusCircle size={12}/> {es?'NUEVA CLASE':'NEW CLASS'}</div><h2>{es?'Empieza desde cero':'Start from scratch'}</h2><p className="small muted">{es?'Todo comienza como borrador privado.':'Everything starts as a private draft.'}</p><form action={createBuilderCourse} style={{display:'grid',gap:10}}><input type="hidden" name="lang" value={language}/><label className="field"><span>{es?'Título de la clase':'Class title'}</span><input name="title" required placeholder={es?'Fundamentos Bíblicos':'Bible Foundations'}/></label><label className="field"><span>{es?'Descripción':'Description'}</span><textarea name="description" rows={3}/></label><div className="row"><label className="field" style={{flex:1}}><span>{es?'Idioma':'Language'}</span><select name="language_code" defaultValue={language}><option value="en">English</option><option value="es">Español</option></select></label><label className="field" style={{flex:1}}><span>{es?'Puntaje mínimo':'Passing score'}</span><input name="passing_score" type="number" min="80" max="100" defaultValue="80"/></label></div><label className="field"><span>{es?'Audiencia':'Audience'}</span><select name="audience_level" defaultValue="general"><option value="general">General</option><option value="new_convert">New convert</option><option value="member">Member</option><option value="teacher_training">Teacher training</option><option value="leadership">Leadership</option></select></label><label className="field"><span>{es?'Etapa del camino':'Pathway stage'}</span><select name="pathway_stage" defaultValue="foundation"><option value="new_convert">New convert</option><option value="foundation">Foundation</option><option value="outreach">Outreach</option><option value="teaching">Teaching</option><option value="leadership">Leadership</option><option value="specialized">Specialized</option></select></label><label className="field"><span>{es?'Nombre del certificado / insignia':'Certificate / badge name'}</span><input name="badge_name"/></label><button className="btn"><PlusCircle size={14}/> {es?'Crear borrador':'Create draft'}</button></form></aside>

      <section style={{display:'grid',gap:12}}><div className="section-heading"><div><div className="pill">{es?'MIS CLASES':'MY CLASSES'}</div><h2>{es?'Abrir y editar':'Open and edit'}</h2></div></div>{active.map((course:any)=><article className="card" key={course.id} style={{padding:16}}><div className="row" style={{justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="row" style={{gap:6,flexWrap:'wrap'}}><span className="pill">{course.published?(es?'PUBLICADA':'PUBLISHED'):(es?'BORRADOR':'DRAFT')}</span><span className="pill">{course.language_code==='es'?'ES':'EN'}</span><span className="pill">v{course.curriculum_version||'1.0'}</span></div><h3 style={{margin:'8px 0 4px'}}>{course.title}</h3><p className="small muted" style={{margin:0}}>{course.description||(es?'Sin descripción todavía.':'No description yet.')}</p></div><Link className="btn" href={l(`/learning/admin/course-builder/${course.id}`)}><BookOpen size={14}/> {es?'Abrir Builder':'Open Builder'}</Link></div></article>)}{!active.length&&<div className="card empty"><h3>{es?'Todavía no hay clases.':'No classes yet.'}</h3><p className="muted">{es?'Crea el primer borrador con el formulario de la izquierda.':'Create the first draft with the form on the left.'}</p></div>}
      {archived.length>0&&<details className="card" style={{padding:16}}><summary><Archive size={14}/> {es?'Clases archivadas':'Archived classes'} ({archived.length})</summary><div style={{display:'grid',gap:9,marginTop:12}}>{archived.map((course:any)=><div className="row" key={course.id} style={{justifyContent:'space-between',gap:10}}><div><strong>{course.title}</strong><div className="small muted">{es?'Oculta de los miembros':'Hidden from members'}</div></div><Link className="ghost" href={l(`/learning/admin/course-builder/${course.id}`)}>{es?'Abrir / restaurar':'Open / restore'}</Link></div>)}</div></details>}</section>
    </section>
  </main>
}
