import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { login,signup,requestPasswordReset,resendConfirmation } from './actions'

const copy={
  en:{invited:'You’re invited.',home:'Welcome back.',inviteCreate:(name:string)=>`Create your ${name} account.`,homeBody:'Sign in to Kingdom Network.',first:'First name',last:'Last name',email:'Email',createPassword:'Create password',password:'Password',again:'Type password again',signIn:'Sign in',accept:'Create my account',inviteHelp:'Use the exact email address this invitation was made for. Create one password you will remember, confirm the email we send, then sign in.',memberHelp:'Need an account? Ask your church leader for an invitation link.',trouble:'Can’t get in?',resetHelp:'Choose the problem that matches what you need. Request only one email, then use the newest email you receive.',accountEmail:'Your account email',forgot:'I forgot my password',resend:'I need a new confirmation email',invalid:'This invitation is no longer available. If you already created your account, sign in below. Otherwise ask your church leader for a fresh invitation.',for:'For',as:'invited as',expires:'expires',english:'English',spanish:'Español',resetTip:'Password reset: use this if you already confirmed your account but cannot remember your password.',confirmTip:'Confirmation email: use this if you created an account but never confirmed your email.',emailTip:'After requesting an email, check Inbox and Spam/Junk. Open only the newest Kingdom Network email. Wait at least one minute before requesting another.'},
  es:{invited:'Estás invitado.',home:'Bienvenido de nuevo.',inviteCreate:(name:string)=>`Crea tu cuenta de ${name}.`,homeBody:'Inicia sesión en Kingdom Network.',first:'Nombre',last:'Apellido',email:'Correo electrónico',createPassword:'Crear contraseña',password:'Contraseña',again:'Escribe la contraseña otra vez',signIn:'Iniciar sesión',accept:'Crear mi cuenta',inviteHelp:'Usa exactamente el correo para el que se creó esta invitación. Crea una contraseña que recuerdes, confirma el correo que te enviamos y luego inicia sesión.',memberHelp:'¿Necesitas una cuenta? Pide a un líder de tu iglesia un enlace de invitación.',trouble:'¿No puedes entrar?',resetHelp:'Elige el problema que necesitas resolver. Solicita solamente un correo y usa el correo más reciente que recibas.',accountEmail:'Correo de tu cuenta',forgot:'Olvidé mi contraseña',resend:'Necesito otro correo de confirmación',invalid:'Esta invitación ya no está disponible. Si ya creaste tu cuenta, inicia sesión abajo. Si no, pide a un líder una invitación nueva.',for:'Para',as:'invitado como',expires:'vence',english:'English',spanish:'Español',resetTip:'Contraseña: usa esta opción si ya confirmaste tu cuenta pero no recuerdas tu contraseña.',confirmTip:'Confirmación: usa esta opción si creaste tu cuenta pero nunca confirmaste tu correo.',emailTip:'Después de solicitar un correo, revisa Recibidos y Spam/Correo no deseado. Abre solamente el correo más reciente de Kingdom Network. Espera por lo menos un minuto antes de pedir otro.'}
} as const

export default async function LoginPage({searchParams}:{searchParams:Promise<{error?:string;message?:string;invite?:string;lang?:string}>}){
  const params=await searchParams
  const lang=params.lang==='es'?'es':'en'
  const t=copy[lang]
  const supabase=await createClient()
  let invite:any=null
  if(params.invite){
    const {data}=await supabase.rpc('get_invite_preview',{p_invite_id:params.invite})
    invite=Array.isArray(data)?data[0]:data
  }
  const validInvite=Boolean(invite?.valid)
  const langHref=(nextLang:'en'|'es')=>`/login?lang=${nextLang}${params.invite?`&invite=${encodeURIComponent(params.invite)}`:''}`

  return <main className="login-wrap"><div className="login card"><div className="row" style={{justifyContent:'space-between',alignItems:'center',marginBottom:8}}><div className="pill">KINGDOM NETWORK • PILOT</div><div className="row" style={{gap:6}}><Link className="ghost" href={langHref('en')}>{t.english}</Link><Link className="ghost" href={langHref('es')}>{t.spanish}</Link></div></div><h1>{validInvite?t.invited:t.home}</h1><p className="muted">{validInvite?t.inviteCreate(invite.church_name):t.homeBody}</p>
    {params.error&&<div className="notice error">{params.error}</div>}{params.message&&<div className="notice success">{params.message}</div>}
    {validInvite&&<div className="notice success"><strong>{lang==='es'?'Invitación a':'Invitation to'} {invite.church_name}</strong><div className="small" style={{marginTop:4}}>{t.for} {invite.masked_email} • {t.as} {String(invite.role).replaceAll('_',' ')} • {t.expires} {new Date(invite.expires_at).toLocaleDateString(lang==='es'?'es-US':'en-US')}</div></div>}
    {params.invite&&!validInvite&&<div className="notice error">{t.invalid}</div>}
    <form><input type="hidden" name="lang" value={lang}/><input type="hidden" name="invite_id" value={validInvite?params.invite??'':''}/>{validInvite&&<><div className="row"><label className="field" style={{flex:1}}><span>{t.first}</span><input name="first_name" autoComplete="given-name" required/></label><label className="field" style={{flex:1}}><span>{t.last}</span><input name="last_name" autoComplete="family-name" required/></label></div></>}<label className="field"><span>{t.email}</span><input name="email" type="email" autoComplete="email" required/></label><label className="field"><span>{validInvite?t.createPassword:t.password}</span><input name="password" type="password" minLength={8} autoComplete={validInvite?'new-password':'current-password'} required/></label>{validInvite&&<label className="field"><span>{t.again}</span><input name="confirm_password" type="password" minLength={8} autoComplete="new-password" required/></label>}<div className="row"><button className="btn" formAction={login}>{t.signIn}</button>{validInvite&&<button className="btn secondary" formAction={signup}>{t.accept}</button>}</div></form>
    <p className="small muted" style={{marginTop:16}}>{validInvite?t.inviteHelp:t.memberHelp}</p>
    <div style={{marginTop:20,paddingTop:16,borderTop:'1px solid rgba(255,255,255,.12)'}}><strong>{t.trouble}</strong><p className="small muted">{t.resetHelp}</p><form><input type="hidden" name="lang" value={lang}/><label className="field"><span>{t.accountEmail}</span><input name="reset_email" type="email" autoComplete="email" required/></label><div style={{display:'grid',gap:8}}><button className="btn secondary" formAction={requestPasswordReset}>{t.forgot}</button><div className="small muted">{t.resetTip}</div><button className="btn secondary" formAction={resendConfirmation}>{t.resend}</button><div className="small muted">{t.confirmTip}</div></div><div className="notice" style={{marginTop:12}}>{t.emailTip}</div></form></div>
  </div></main>
}
