import Link from 'next/link'
import { createClient as createPublicClient } from '@supabase/supabase-js'
import { SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL } from '@/lib/supabase/config'
import { PasswordField } from '@/components/password-field'
import { login,signup,requestPasswordReset,resendConfirmation } from './actions'
import { PendingSubmit } from './pending-submit'
import { PendingAction } from './pending-action'

const copy={
  en:{home:'Welcome to One Kingdom.',homeBody:'One simple place to grow, connect, serve and walk with God.',first:'First name',last:'Last name',email:'Email',createPassword:'Create password',password:'Password',again:'Type password again',showPassword:'Show password',hidePassword:'Hide password',signIn:'Sign in',accept:'Create my account',publicHelp:'Anyone interested in the pilot can create an account. No invitation is needed.',closed:'Public signup is temporarily unavailable. Existing users can still sign in.',trouble:'Can’t get in?',resetHelp:'Use one option below, then open only the newest email we send.',accountEmail:'Your account email',forgot:'I forgot my password',resend:'I never confirmed my email',invalid:'That old invitation is no longer available, but public signup is open below.',english:'English',spanish:'Español',resetTip:'Use this if you already confirmed your account but forgot your password.',confirmTip:'Use this if you created an account but never confirmed your email.',emailTip:'Check Inbox and Spam/Junk. After requesting an email, the button will wait one minute so you do not accidentally trigger the email cooldown.',step1:'Create your account',step2:'Confirm the email we send',step3:'Come back and sign in',create:'Create account',signinTitle:'Sign in',newHere:'New here?',returning:'Already have an account?',existingAccount:'If you have used One Kingdom before, do not create another account. Sign in with the account you already have.',joinReturning:'You already have an account. Sign in here and we will return you to the church join page so you can finish joining without making a duplicate account.',creating:'Creating account…',signing:'Signing in…',sending:'Sending…',wait:'Wait {seconds}s before requesting another email',returnJoin:'← Return to the church join page'},
  es:{home:'Bienvenido a One Kingdom.',homeBody:'Un lugar sencillo para crecer, conectarte, servir y caminar con Dios.',first:'Nombre',last:'Apellido',email:'Correo electrónico',createPassword:'Crear contraseña',password:'Contraseña',again:'Escribe la contraseña otra vez',showPassword:'Mostrar contraseña',hidePassword:'Ocultar contraseña',signIn:'Iniciar sesión',accept:'Crear mi cuenta',publicHelp:'Cualquier persona interesada en el piloto puede crear una cuenta. No necesitas invitación.',closed:'El registro público no está disponible temporalmente. Los usuarios existentes todavía pueden iniciar sesión.',trouble:'¿No puedes entrar?',resetHelp:'Usa una opción abajo y abre solamente el correo más reciente que enviemos.',accountEmail:'Correo de tu cuenta',forgot:'Olvidé mi contraseña',resend:'Nunca confirmé mi correo',invalid:'Esa invitación anterior ya no está disponible, pero el registro público está abierto abajo.',english:'English',spanish:'Español',resetTip:'Usa esto si ya confirmaste tu cuenta pero olvidaste tu contraseña.',confirmTip:'Usa esto si creaste una cuenta pero nunca confirmaste tu correo.',emailTip:'Revisa Recibidos y Spam/Correo no deseado. Después de pedir un correo, el botón esperará un minuto para evitar activar el límite de envío.',step1:'Crea tu cuenta',step2:'Confirma el correo que enviamos',step3:'Regresa e inicia sesión',create:'Crear cuenta',signinTitle:'Iniciar sesión',newHere:'¿Eres nuevo?',returning:'¿Ya tienes una cuenta?',existingAccount:'Si ya has usado One Kingdom, no crees otra cuenta. Inicia sesión con la cuenta que ya tienes.',joinReturning:'Ya tienes una cuenta. Inicia sesión aquí y te regresaremos a la página de la iglesia para terminar de unirte sin crear una cuenta duplicada.',creating:'Creando cuenta…',signing:'Iniciando sesión…',sending:'Enviando…',wait:'Espera {seconds}s antes de pedir otro correo',returnJoin:'← Regresar a la página para unirte a la iglesia'}
} as const

const boundedStatus=(value?:string)=>value?.trim().slice(0,320)||''

export default async function LoginPage({searchParams}:{searchParams:Promise<{error?:string;message?:string;invite?:string;lang?:string;mode?:string;next?:string}>}){
  const params=await searchParams
  const lang=params.lang==='es'?'es':'en',t=copy[lang]
  const joinNext=params.next?.startsWith('/join/')&&!params.next.startsWith('//')&&!params.next.includes('..')?params.next:''
  const statusError=boundedStatus(params.error),statusMessage=boundedStatus(params.message)
  const supabase=createPublicClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
  let invite:any=null
  if(params.invite){const {data}=await supabase.rpc('get_invite_preview',{p_invite_id:params.invite});invite=Array.isArray(data)?data[0]:data}
  const {data:publicStatusData}=await supabase.rpc('get_public_signup_status')
  const publicStatus:any=Array.isArray(publicStatusData)?publicStatusData[0]:publicStatusData
  const publicOpen=Boolean(publicStatus?.open),validInvite=Boolean(invite?.valid),canCreate=validInvite||publicOpen
  const mode=params.mode==='signin'||!canCreate?'signin':'signup'
  const query=(nextMode:string,nextLang=lang)=>`/login?lang=${nextLang}&mode=${nextMode}${params.invite?`&invite=${encodeURIComponent(params.invite)}`:''}${joinNext?`&next=${encodeURIComponent(joinNext)}`:''}`

  return <main className="login-wrap"><div className="login card">
    <div className="row" style={{justifyContent:'space-between',alignItems:'center',marginBottom:8}}><div className="pill">ONE KINGDOM • PILOT</div><div className="row" style={{gap:6}}><Link className="ghost" href={query(mode,'en')}>{t.english}</Link><Link className="ghost" href={query(mode,'es')}>{t.spanish}</Link></div></div>
    <h1>{t.home}</h1><p className="muted">{t.homeBody}</p>
    {statusError&&<div className="notice error" role="alert">{statusError}</div>}{statusMessage&&<div className="notice success" role="status" aria-live="polite">{statusMessage}</div>}
    {params.invite&&!validInvite&&<div className="notice">{t.invalid}</div>}
    <div className="row" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,margin:'18px 0'}}><Link className={mode==='signup'?'btn':'ghost'} href={query('signup')}>{t.create}</Link><Link className={mode==='signin'?'btn':'ghost'} href={query('signin')}>{t.signinTitle}</Link></div>
    {mode==='signup'&&canCreate&&<>
      <div className="notice success"><strong>{validInvite?(lang==='es'?`Invitación a ${invite.church_name}`:`Invitation to ${invite.church_name}`):(lang==='es'?'REGISTRO ABIERTO':'OPEN SIGNUP')}</strong><div className="small" style={{marginTop:4}}>{validInvite?(lang==='es'?'Esta invitación te conectará con tu iglesia.':'This invitation will connect you with your church.'):t.publicHelp}</div></div>
      <div className="notice" style={{marginTop:12}}><strong>{t.returning}</strong><div className="small" style={{marginTop:4}}>{t.existingAccount} <Link href={query('signin')} style={{textDecoration:'underline'}}>{t.signIn}</Link></div></div>
      <div className="card" style={{padding:14,margin:'12px 0',background:'rgba(255,255,255,.025)'}}><strong>{t.step1}</strong><div className="small muted" style={{marginTop:5}}>{t.step2} → {t.step3}</div></div>
      <form action={signup}><input type="hidden" name="lang" value={lang}/>{validInvite&&<input type="hidden" name="invite_id" value={params.invite??''}/>}<div className="row"><label className="field" style={{flex:1}}><span>{t.first}</span><input name="first_name" autoComplete="given-name" required/></label><label className="field" style={{flex:1}}><span>{t.last}</span><input name="last_name" autoComplete="family-name" required/></label></div><label className="field"><span>{t.email}</span><input name="email" type="email" inputMode="email" autoComplete="email" required/></label><PasswordField name="password" label={t.createPassword} minLength={8} autoComplete="new-password" required showLabel={t.showPassword} hideLabel={t.hidePassword}/><PasswordField name="confirm_password" label={t.again} minLength={8} autoComplete="new-password" required showLabel={t.showPassword} hideLabel={t.hidePassword}/><PendingSubmit label={t.accept} pendingLabel={t.creating}/></form>
      <p className="small muted" style={{textAlign:'center',marginTop:14}}>{t.returning} <Link href={query('signin')} style={{textDecoration:'underline'}}>{t.signIn}</Link></p>
    </>}
    {mode==='signin'&&<>
      {joinNext&&<div className="notice success" style={{marginBottom:12}}>{t.joinReturning}</div>}
      <form action={login}><input type="hidden" name="lang" value={lang}/>{joinNext&&<input type="hidden" name="next" value={joinNext}/>}<label className="field"><span>{t.email}</span><input name="email" type="email" inputMode="email" autoComplete="email" required/></label><PasswordField name="password" label={t.password} autoComplete="current-password" required showLabel={t.showPassword} hideLabel={t.hidePassword}/><PendingSubmit label={t.signIn} pendingLabel={t.signing}/></form>
      {joinNext?<p className="small muted" style={{textAlign:'center',marginTop:14}}><Link href={joinNext} style={{textDecoration:'underline'}}>{t.returnJoin}</Link></p>:canCreate&&<p className="small muted" style={{textAlign:'center',marginTop:14}}>{t.newHere} <Link href={query('signup')} style={{textDecoration:'underline'}}>{t.create}</Link></p>}
      <details style={{marginTop:22,paddingTop:14,borderTop:'1px solid rgba(255,255,255,.12)'}}><summary style={{fontWeight:800,cursor:'pointer'}}>{t.trouble}</summary><p className="small muted">{t.resetHelp}</p><form><input type="hidden" name="lang" value={lang}/>{joinNext&&<input type="hidden" name="next" value={joinNext}/>}<label className="field"><span>{t.accountEmail}</span><input name="reset_email" type="email" inputMode="email" autoComplete="email" required/></label><div style={{display:'grid',gap:8}}><PendingAction action={requestPasswordReset} label={t.forgot} pendingLabel={t.sending} cooldownLabel={t.wait} cooldownKey="password-reset"/><div className="small muted">{t.resetTip}</div><PendingAction action={resendConfirmation} label={t.resend} pendingLabel={t.sending} cooldownLabel={t.wait} cooldownKey="confirmation-resend"/><div className="small muted">{t.confirmTip}</div></div><div className="notice" style={{marginTop:12}}>{t.emailTip}</div></form></details>
    </>}
  </div></main>
}