import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CheckCircle2,ExternalLink,MailPlus,QrCode,ShieldCheck,Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { CopyJoinLink } from './copy-join-link'
import { JoinQr } from './join-qr'

const siteUrl=(process.env.NEXT_PUBLIC_SITE_URL||'https://kingdom-network.vercel.app').replace(/\/$/,'')
const boundedCode=(value:unknown)=>String(value??'unknown').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,48)||'unknown'
type Lang='en'|'es'

function AccessRecovery({lang,kind}:{lang:Lang;kind:'unavailable'|'unauthorized'}){
  const es=lang==='es'
  return <main className="shell"><header className="topbar"><Link href="/" className="brand">Kingdom <span>Network</span></Link></header><section className="card" style={{padding:24,maxWidth:720,margin:'30px auto'}}><div className="pill">{es?'CENTRO DE INGRESO':'JOIN CENTER'}</div><h1>{kind==='unavailable'?(es?'No pudimos verificar el Centro de Ingreso.':'We could not verify Join Center.'):(es?'Acceso no disponible':'Access not available')}</h1><p className="muted">{kind==='unavailable'?(es?'Puede ser un problema temporal de conexión. No asumas que el registro está abierto o pausado y no compartas un enlace nuevo hasta que esta página cargue correctamente.':'This may be a temporary connection problem. Do not assume signup is open or paused, and do not share a new link until this page loads correctly.'):(es?'Esta cuenta no tiene permiso para administrar el Centro de Ingreso.':'This account does not have permission to manage Join Center.')}</p><div className="row" style={{gap:10,flexWrap:'wrap'}}><Link className="btn" href={`/church/join-center?lang=${lang}`}>{es?'Intentar de nuevo':'Try again'}</Link><Link className="ghost" href={`/?lang=${lang}`}>{es?'Inicio':'Home'}</Link><Link className="ghost" href={`/help?lang=${lang}`}>{es?'Ayuda':'Help'}</Link></div></section></main>
}

export default async function JoinCenterPage({searchParams}:{searchParams:Promise<{lang?:string}>}){
  const params=await searchParams,es=params.lang==='es',lang:Lang=es?'es':'en';const l=(p:string)=>`${p}${p.includes('?')?'&':'?'}lang=${lang}`
  const supabase=await createClient();const {data:claims,error:claimsError}=await supabase.auth.getClaims();const userId=claims?.claims?.sub
  if(claimsError){console.error('join center auth lookup failed',{errorCode:boundedCode(claimsError.code)});return <AccessRecovery lang={lang} kind="unavailable"/>}
  if(!userId)redirect(`/login?lang=${lang}&next=${encodeURIComponent(l('/church/join-center'))}`)
  const {data:membership,error:membershipError}=await supabase.from('church_memberships').select('church_id,role,churches(name,slug,public_signup_enabled)').eq('user_id',userId).eq('status','active').limit(1).maybeSingle()
  if(membershipError){console.error('join center membership lookup failed',{errorCode:boundedCode(membershipError.code)});return <AccessRecovery lang={lang} kind="unavailable"/>}
  if(!membership?.church_id||!['pastor','church_admin'].includes(membership.role))return <AccessRecovery lang={lang} kind="unauthorized"/>
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches;const slug=church?.slug;if(!slug)redirect(l('/church/settings'))
  const {data:statusData,error:statusError}=await supabase.rpc('get_public_signup_status_for_church',{p_church_slug:slug})
  const status:any=!statusError?(Array.isArray(statusData)?statusData[0]:statusData):null
  if(statusError)console.error('join center public signup status failed',{errorCode:boundedCode(statusError.code)})
  if(!statusError&&!status)console.error('join center public signup status empty',{errorCode:'empty_status'})
  const statusUnavailable=Boolean(statusError)||!status
  const joinUrl=`${siteUrl}/join/${slug}`,joinUrlEs=`${joinUrl}?lang=es`,activeJoinUrl=es?joinUrlEs:joinUrl
  return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Church'} • {es?'Centro de Ingreso':'Join Center'}</div></div><div className="row"><Link className="ghost" href="/church/join-center?lang=en">English</Link><Link className="ghost" href="/church/join-center?lang=es">Español</Link><Link className="ghost" href={l('/church')}>{es?'← Administración':'← Church Admin'}</Link></div></header>
  <section className="card" style={{padding:24,marginBottom:18}}><div className="pill">{es?'PUERTA DE ENTRADA':'FRONT DOOR'}</div><h1>{es?'Un enlace. Un QR. Una forma sencilla de entrar.':'One link. One QR. One simple way in.'}</h1><p className="muted">{es?'Comparte el enlace en el idioma que la persona prefiera. Si ya tiene una cuenta, debe usar esa misma cuenta; nunca necesita crear otra.':'Share the link in the person’s preferred language. If they already have an account, they should use that same account; they never need to create another one.'}</p></section>
  {statusUnavailable&&<section className="card" style={{padding:20,marginBottom:18}} role="alert"><h2>{es?'No pudimos comprobar el estado del registro.':'We could not check signup status.'}</h2><p className="muted">{es?'No asumas que el registro está pausado o abierto. No se cambió nada. Actualiza antes de compartir un enlace nuevo.':'Do not assume signup is paused or open. Nothing was changed. Refresh before sharing a new link.'}</p><Link className="btn" href={l('/church/join-center')}>{es?'Intentar otra vez':'Try again'}</Link></section>}
  {!statusUnavailable&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16,marginBottom:18}}><section className="card" style={{padding:22}}><div className="pill"><QrCode size={11}/> {es?'QR DE INGRESO':'JOIN QR'}</div><div style={{marginTop:18}}><JoinQr url={activeJoinUrl} label={es?'Escanea para unirte a Kingdom Network en esta iglesia en español.':'Scan to join Kingdom Network at this church.'} es={es}/></div><div className="row" style={{justifyContent:'center',gap:8,flexWrap:'wrap',marginTop:16}}><CopyJoinLink url={activeJoinUrl} label={es?'Copiar enlace':'Copy join link'}/><Link className="ghost" href={l(`/join/${slug}`)} target="_blank"><ExternalLink size={13}/> {es?'Vista previa':'Preview'}</Link></div></section>
  <section className="card" style={{padding:22}}><div className="pill">{es?'ESTADO':'STATUS'}</div><h2>{church?.name}</h2><div style={{display:'grid',gap:10,margin:'14px 0'}}><div className="row"><CheckCircle2 size={16}/><span>{es?'Registro público':'Public signup'}: <strong>{status.open?(es?'Abierto':'Open'):(es?'Pausado':'Paused')}</strong></span></div><div className="row"><Users size={16}/><span>{es?'Registros del piloto':'Pilot registrations'}: <strong>{status.registration_count??0}</strong>{status.signup_limit?` / ${status.signup_limit}`:''}</span></div>{status.remaining!=null&&<div className="row"><ShieldCheck size={16}/><span><strong>{status.remaining}</strong> {es?'lugares disponibles':'spots remaining'}</span></div>}</div><div className="small muted" style={{wordBreak:'break-all'}}>{activeJoinUrl}</div><div className="row" style={{gap:8,flexWrap:'wrap',marginTop:14}}><CopyJoinLink url={joinUrl} label={es?'Copiar enlace en inglés':'Copy English link'}/><CopyJoinLink url={joinUrlEs} label={es?'Copiar enlace en español':'Copy Spanish link'}/></div></section></div>}
  <section className="card" style={{padding:20,marginBottom:16}}><div className="pill">{es?'DOS FORMAS DE ENTRAR':'TWO WAYS IN'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14,marginTop:12}}><div><h3>{es?'1. QR / enlace público':'1. Public QR / link'}</h3><p className="muted">{es?'Para invitados y personas locales que necesitan entrar rápido.':'For guests and local people who need to get in quickly.'}</p></div><div><h3>{es?'2. Invitación privada':'2. Private invitation'}</h3><p className="muted">{es?'Para personas que liderazgo ya conoce o cuando se necesita un acceso inicial específico.':'For people leadership already knows or when specific starting access is needed.'}</p><Link className="btn" href={l('/church/invites')}><MailPlus size={14}/> {es?'Abrir Invitaciones':'Open Invitations'}</Link></div></div></section>
  <section className="card" style={{padding:18}}><div className="pill">{es?'FLUJO DEL INVITADO':'GUEST FLOW'}</div><p style={{lineHeight:1.7,marginBottom:0}}><strong>{es?'Escanear QR':'Scan QR'}</strong> → {es?'crear cuenta rápida o iniciar sesión con la cuenta existente':'quick account or sign in with the existing account'} → <strong>{es?'Empieza Aquí':'Start Here'}</strong>.</p></section></main>
}