import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Award,BookOpen,Clock,FileText,Gamepad2,Languages,LockKeyhole,Settings2,Trophy } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { startCourse } from './actions'
import './learning.css'

const audienceLabel=(v?:string|null)=>({new_convert:'New Convert',member:'Member',teacher_training:'Teacher Training',leadership:'Leadership',general:'General'} as Record<string,string>)[v??'general']??String(v??'general').replaceAll('_',' ')
const awardTier=(score?:number|null)=>score===100?'Platinum':score!=null&&score>=90?'Gold':score!=null&&score>=80?'Silver':null
const stages=[
  {key:'new_convert',en:'New Convert',es:'Nuevo Convertido',descEn:'Bible basics and preparation for the next biblical response.',descEs:'Fundamentos bíblicos y preparación para el próximo paso bíblico.'},
  {key:'foundation',en:'Foundation',es:'Fundamento',descEn:'Build the habits and understanding every growing member needs.',descEs:'Desarrolla los hábitos y la comprensión que todo miembro necesita.'},
  {key:'outreach',en:'Outreach',es:'Evangelismo',descEn:'Learn to share faith and intentionally reach people.',descEs:'Aprende a compartir la fe y alcanzar a otros intencionalmente.'},
  {key:'teaching',en:'Teaching',es:'Enseñanza',descEn:'Prepare to guide others through Scripture responsibly.',descEs:'Prepárate para guiar a otros por las Escrituras responsablemente.'},
  {key:'leadership',en:'Leadership',es:'Liderazgo',descEn:'Develop ministry knowledge, accountability and leadership readiness.',descEs:'Desarrolla conocimiento ministerial, responsabilidad y preparación para liderar.'}
] as const

export default async function LearningPage({searchParams}:{searchParams:Promise<{error?:string;lang?:string}>}){
  const params=await searchParams
  const lang=params.lang==='es'?'es':params.lang==='all'?'all':'en'
  const rewardLang=lang==='es'?'es':'en'
  const supabase=await createClient()
  const {data:claimsData}=await supabase.auth.getClaims()
  const userId=claimsData?.claims?.sub
  if(!userId)redirect('/login')
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const [{data:allCourses},{data:enrollments},{data:xpEvents},{data:badgeRows},{data:prerequisites},{data:milestones}]=await Promise.all([
    supabase.from('courses').select('*').eq('published',true).order('pathway_order').order('created_at'),
    supabase.from('course_enrollments').select('course_id,progress,final_score,completed_at,credential_earned,curriculum_version').eq('user_id',userId),
    supabase.from('learning_xp_events').select('points').eq('user_id',userId),
    supabase.from('member_badges').select('badge_id,badges(category)').eq('user_id',userId),
    supabase.from('course_prerequisites').select('course_id,prerequisite_type,required_course_id,milestone_key,required_value,allowed_roles,display_text,hard_block'),
    supabase.from('member_milestones').select('*').eq('church_id',membership.church_id).eq('user_id',userId).maybeSingle()
  ])
  const courses=(allCourses??[]).filter((c:any)=>lang==='all'||(c.language_code??'en')===lang)
  const em=new Map((enrollments??[]).map((e:any)=>[e.course_id,e]))
  const prereqBy=new Map<string,any[]>();for(const r of prerequisites??[]){const list=prereqBy.get(r.course_id)??[];list.push(r);prereqBy.set(r.course_id,list)}
  const missingFor=(courseId:string)=>{const reqs=prereqBy.get(courseId)??[];return reqs.filter((r:any)=>{if(!r.hard_block)return false;if(r.prerequisite_type==='course')return !em.get(r.required_course_id)?.credential_earned;if(r.prerequisite_type==='role')return !(r.allowed_roles??[]).includes(membership.role);if(r.prerequisite_type==='milestone')return String((milestones as any)?.[r.milestone_key]??'')!==String(r.required_value??'');return false})}
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  const completed=(enrollments??[]).filter((e:any)=>e.credential_earned).length
  const xp=(xpEvents??[]).reduce((sum:number,e:any)=>sum+Number(e.points??0),0)
  const trophies=(badgeRows??[]).filter((r:any)=>{const b=Array.isArray(r.badges)?r.badges[0]:r.badges;return b?.category==='learning'}).length
  const canManage=['minister','pastor','church_admin'].includes(membership.role)
  const visibleCourseIds=new Set(courses.map((c:any)=>c.id))
  const visibleEnrollments=(enrollments??[]).filter((e:any)=>visibleCourseIds.has(e.course_id))
  const enrolledCount=visibleEnrollments.length
  const inProgressCount=visibleEnrollments.filter((e:any)=>!e.credential_earned).length
  const completedVisible=visibleEnrollments.filter((e:any)=>e.credential_earned).length
  const availableCount=courses.filter((c:any)=>!em.has(c.id)&&missingFor(c.id).length===0).length
  const schoolCourses=courses.filter((c:any)=>c.category==='School of Discipleship').sort((a:any,b:any)=>(a.pathway_order??0)-(b.pathway_order??0))
  const dydCourses=courses.filter((c:any)=>c.category==='Disciple Your Disciplers').sort((a:any,b:any)=>(a.pathway_order??0)-(b.pathway_order??0))
  const standardCourses=courses.filter((c:any)=>c.category!=='School of Discipleship'&&c.category!=='Disciple Your Disciplers')

  const card=(course:any)=>{const enrollment:any=em.get(course.id);const progress=enrollment?.progress??0;const finalScore=enrollment?.final_score==null?null:Number(enrollment.final_score);const tier=awardTier(finalScore);const isEs=(course.language_code??'en')==='es';const missing=missingFor(course.id);const locked=!enrollment&&missing.length>0;return <article className="card course-card" key={course.id}><div className="row" style={{gap:6,flexWrap:'wrap'}}><div className="pill">{course.category||'COURSE'}</div><div className="pill">{isEs?'ESPAÑOL':'ENGLISH'}</div><div className="pill">{audienceLabel(course.audience_level).toUpperCase()}</div>{enrollment?.credential_earned&&tier&&<div className="pill">{tier.toUpperCase()} OVERALL</div>}{locked&&<div className="pill"><LockKeyhole size={10}/> LOCKED</div>}</div><h2>{course.title}</h2><p>{course.description}</p><div className="course-meta"><span><Clock size={13}/> {course.estimated_minutes?Math.round(course.estimated_minutes/60)+' hrs':'Self paced'}</span><span><Award size={13}/> {course.badge_name||'Completion'}</span><span><Trophy size={13}/> 80% required tests</span><span>v{course.curriculum_version??'1.0'}</span></div>{locked&&<div className="notice" style={{margin:'12px 0 0'}}><strong>{isEs?'Requisito pendiente':'Prerequisite needed'}:</strong> {missing.map((r:any)=>r.display_text).join(' • ')}</div>}<div className="progress-track"><div className="progress-fill" style={{width:`${progress}%`}}/></div><div className="progress-row"><span>{progress}% class progress</span><span>{enrollment?.credential_earned?(tier&&finalScore!=null?`${tier} overall • ${finalScore}%`:'Completed'):enrollment?'In progress':locked?'Locked':'Not started'}</span></div>{enrollment?<Link className="btn" href={`/learning/${course.id}`} style={{display:'inline-block',marginTop:14}}>{progress?'Continue course':'Open course'}</Link>:locked?<button className="ghost" style={{marginTop:14}} disabled><LockKeyhole size={14}/> {isEs?'Completa el requisito primero':'Complete prerequisite first'}</button>:<form action={startCourse}><input type="hidden" name="course_id" value={course.id}/><button className="btn" style={{marginTop:14}}><BookOpen size={15}/> {isEs?'Comenzar curso':'Start course'}</button></form>}</article>}

  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Your Church'} • Learning</div></div><div className="row"><Link className="ghost" href="/learning/transcript"><Award size={14}/> My Transcript</Link><Link className="ghost" href={`/learning/rewards?lang=${rewardLang}`}><Gamepad2 size={14}/> Rewards & Games</Link><Link className="ghost" href="/resources"><FileText size={14}/> Resource Library</Link>{canManage&&<Link className="ghost" href="/learning/admin/first-steps"><BookOpen size={14}/> First Steps Roster</Link>}{canManage&&<Link className="ghost" href="/learning/admin"><Settings2 size={14}/> Learning Studio</Link>}<Link className="ghost" href="/">← Home</Link></div></header>
    <section className="learning-hero card"><div><div className="pill">LEARNING CENTER</div><h1>{lang==='es'?'Crece con propósito.':'Grow on purpose.'}</h1><p className="muted">{lang==='es'?'Cursos, capacitación, práctica, juegos y preparación ministerial en un solo lugar.':'Courses, training, practice, games and ministry preparation in one place.'}</p></div><div className="learning-stat"><strong>{completed}</strong><span>{lang==='es'?'credenciales obtenidas':'credentials earned'}</span></div></section>

    <section className="card" style={{padding:18,marginBottom:16}}><div className="row" style={{justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'flex-start'}}><div><div className="pill">MY LEARNING</div><h2 style={{margin:'8px 0 12px'}}>{lang==='es'?'Tu progreso de un vistazo.':'Your progress at a glance.'}</h2></div><Link className="btn" href="/learning/transcript"><Award size={14}/> Open my transcript</Link></div><div className="row" style={{gap:10,flexWrap:'wrap'}}><div className="card" style={{padding:'12px 16px',minWidth:145}}><strong style={{fontSize:22}}>{enrolledCount}</strong><div className="small muted">Enrolled</div></div><div className="card" style={{padding:'12px 16px',minWidth:145}}><strong style={{fontSize:22}}>{inProgressCount}</strong><div className="small muted">In progress</div></div><div className="card" style={{padding:'12px 16px',minWidth:145}}><strong style={{fontSize:22}}>{completedVisible}</strong><div className="small muted">Completed</div></div><div className="card" style={{padding:'12px 16px',minWidth:145}}><strong style={{fontSize:22}}>{availableCount}</strong><div className="small muted">Available now</div></div></div></section>

    <section className="card" style={{padding:18,marginBottom:16}}><div className="pill">CLASS TEST AWARDS</div><h2 style={{margin:'8px 0 6px'}}>Pass the test. Earn the level.</h2><p className="muted" style={{margin:'0 0 12px'}}>Required class tests must score at least 80% to count as complete. The score earned on the test determines the class award.</p><div className="row" style={{gap:10,flexWrap:'wrap'}}><div className="card" style={{padding:'10px 14px',minWidth:150}}><strong>Silver</strong><div className="small muted">80–89%</div></div><div className="card" style={{padding:'10px 14px',minWidth:150}}><strong>Gold</strong><div className="small muted">90–99%</div></div><div className="card" style={{padding:'10px 14px',minWidth:150}}><strong>Platinum</strong><div className="small muted">100%</div></div></div></section>

    <section className="row" style={{gap:10,marginBottom:16,flexWrap:'wrap'}}><Link href={`/learning/rewards?lang=${rewardLang}`} className="card" style={{padding:'12px 14px',display:'flex',alignItems:'center',gap:10,minWidth:190}}><Trophy size={18}/><div><strong style={{display:'block'}}>{trophies} trophies</strong><span className="small muted">{xp} Learning XP</span></div></Link><Link href="/resources" className="card" style={{padding:'12px 14px',display:'flex',alignItems:'center',gap:10,minWidth:210}}><FileText size={18}/><div><strong style={{display:'block'}}>Resource Library</strong><span className="small muted">Current + legacy lessons</span></div></Link></section>

    <div className="row" style={{gap:8,marginBottom:16,flexWrap:'wrap'}}><Languages size={16}/><Link className={lang==='en'?'btn':'ghost'} href="/learning?lang=en">English</Link><Link className={lang==='es'?'btn':'ghost'} href="/learning?lang=es">Español</Link><Link className={lang==='all'?'btn':'ghost'} href="/learning?lang=all">All</Link></div>
    {params.error&&<div className="notice error">{params.error}</div>}

    {schoolCourses.length>0&&<section className="pathway-section" style={{marginBottom:22}}><div className="pathway-head"><div className="pathway-number">4</div><div><div className="pill">SCHOOL OF DISCIPLESHIP</div><h2>{lang==='es'?'Una ruta. Cuatro niveles.':'One path. Four levels.'}</h2><p>{lang==='es'?'Comienza con Nuevo Nacimiento y avanza en orden: Crecer, Madurar y Multiplicar. Los niveles posteriores permanecen bloqueados hasta completar el anterior.':'Start with New Birth and move in order: Grow, Mature and Multiply. Later levels stay locked until the previous level is completed.'}</p></div></div><div className="row" style={{gap:8,flexWrap:'wrap',marginBottom:14}}>{schoolCourses.map((course:any,i:number)=><div className="pill" key={course.id}>{i+1}. {course.title.replace(/^Strategy of Jesus — Level \d+: /,'')}</div>)}</div><div className="course-grid">{schoolCourses.map(card)}</div></section>}

    {dydCourses.length>0&&<section className="pathway-section" style={{marginBottom:22}}><div className="pathway-head"><div className="pathway-number">8</div><div><div className="pill">DISCIPLE YOUR DISCIPLERS</div><h2>{lang==='es'?'Desarrollo avanzado de líderes.':'Advanced leader development.'}</h2><p>{lang==='es'?'Ocho cursos enfocados en carácter, santidad, perseverancia, liderazgo en el hogar, mentoría, Grupos de Amistad, desarrollo de líderes y mayordomía.':'Eight focused courses covering character, holiness, perseverance, leadership at home, mentoring, Friendship Groups, developing leaders and stewardship.'}</p></div></div><div className="row" style={{gap:8,flexWrap:'wrap',marginBottom:14}}>{dydCourses.map((course:any,i:number)=><div className="pill" key={course.id}>{i+1}. {course.title.replace(/^Disciple Your Disciplers \d+ — /,'')}</div>)}</div><div className="course-grid">{dydCourses.map(card)}</div></section>}

    {standardCourses.length>0&&<><section className="card" style={{padding:18,marginBottom:16}}><div className="pill">MORE LEARNING</div><h2 style={{margin:'8px 0 6px'}}>{lang==='es'?'Cursos adicionales por etapa.':'Additional courses by growth stage.'}</h2><p className="muted" style={{margin:0}}>{lang==='es'?'Explora fundamentos, evangelismo, enseñanza y capacitación ministerial adicional.':'Explore foundations, outreach, teaching and additional ministry training.'}</p></section><section className="pathway-rail" aria-label="Learning pathway">{stages.map((stage,i)=><div className="pathway-step" key={stage.key}><span>{i+1}</span><div><strong>{lang==='es'?stage.es:stage.en}</strong><small>{lang==='es'?stage.descEs:stage.descEn}</small></div></div>)}</section><div className="pathway-sections">{stages.map(stage=>{const stageCourses=standardCourses.filter((c:any)=>(c.pathway_stage??'foundation')===stage.key);if(!stageCourses.length)return null;return <section className="pathway-section" key={stage.key}><div className="pathway-head"><div className="pathway-number">{stages.findIndex(s=>s.key===stage.key)+1}</div><div><div className="pill">{lang==='es'?'RUTA DE CRECIMIENTO':'GROWTH PATH'}</div><h2>{lang==='es'?stage.es:stage.en}</h2><p>{lang==='es'?stage.descEs:stage.descEn}</p></div></div><div className="course-grid">{stageCourses.map(card)}</div></section>})}</div></>}
    {!courses.length&&<div className="card empty"><h3>{lang==='es'?'Todavía no hay cursos publicados en español.':'No published courses in this view yet.'}</h3><p className="muted">{lang==='es'?'Los cursos en español aparecerán aquí cuando el liderazgo los publique.':'Training added by church leadership will appear here.'}</p></div>}
  </main>
}
