import Link from 'next/link'
import { redirect } from 'next/navigation'
import { ArrowRight,Bell,BookOpen,CalendarDays,CheckCircle2,Clock3,Sparkles } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { getNextStep } from '@/lib/journey'
import { formatChurchDay,formatChurchTime } from '@/lib/church-time'

export default async function MyTodayPage({searchParams}:{searchParams:Promise<{lang?:string}>}){
  const params=await searchParams,es=params.lang==='es'
  const l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
  const supabase=await createClient()
  const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const [{data:profile},{data:membership}]=await Promise.all([
    supabase.from('profiles').select('display_name,first_name,last_name').eq('id',userId).single(),
    supabase.from('church_memberships').select('church_id,role,churches(name,timezone)').eq('user_id',userId).eq('status','active').limit(1).single()
  ])
  if(!membership?.church_id)redirect('/')
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches,timeZone=church?.timezone||'UTC'
  const now=new Date(),nowIso=now.toISOString(),weekIso=new Date(now.getTime()+7*86400000).toISOString()
  const [{data:milestones},{count:groupCount},{data:assignments},{data:enrollments},{data:newConvertCourses},{count:unread},{data:ledGroups},{data:groupRoles},{data:overdueOutreach}]=await Promise.all([
    supabase.from('member_milestones').select('holy_ghost_received,baptized,first_steps_status,soul_winning_status,bible_study_teacher_status').eq('church_id',membership.church_id).eq('user_id',userId).maybeSingle(),
    supabase.from('group_memberships').select('*',{count:'exact',head:true}).eq('user_id',userId),
    supabase.from('team_assignments').select('id,title,starts_at,call_time,confirmation_required,ministries(name)').eq('church_id',membership.church_id).eq('assigned_user_id',userId).gte('starts_at',nowIso).lte('starts_at',weekIso).order('starts_at').limit(12),
    supabase.from('course_enrollments').select('course_id,credential_earned').eq('user_id',userId),
    supabase.from('courses').select('id').eq('church_id',membership.church_id).eq('published',true).eq('pathway_stage','new_convert'),
    supabase.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',userId).is('read_at',null),
    supabase.from('groups').select('id,name,active').eq('church_id',membership.church_id).eq('leader_id',userId).eq('active',true),
    supabase.from('group_memberships').select('group_id,role,groups(id,name,active)').eq('user_id',userId).in('role',['leader','assistant']),
    supabase.from('outreach_contacts').select('id,first_name,last_name,stage,follow_up_due_at').eq('church_id',membership.church_id).eq('assigned_to',userId).lt('follow_up_due_at',nowIso).not('stage','in','("inactive","serving")').order('follow_up_due_at').limit(8)
  ])
  const assignmentRows=assignments??[],outreachRows=overdueOutreach??[]
  const assignmentIds=assignmentRows.map((a:any)=>a.id),courseIds=(enrollments??[]).filter((e:any)=>!e.credential_earned).map((e:any)=>e.course_id)
  const [{data:responses},{data:sessions}]=await Promise.all([
    assignmentIds.length?supabase.from('team_assignment_responses').select('assignment_id,response').eq('user_id',userId).in('assignment_id',assignmentIds):Promise.resolve({data:[] as any[]}),
    courseIds.length?supabase.from('course_sessions').select('id,course_id,title,session_date,starts_at,courses(title)').eq('church_id',membership.church_id).in('course_id',courseIds).gte('session_date',nowIso.slice(0,10)).lte('session_date',weekIso.slice(0,10)).eq('status','scheduled').order('session_date').limit(12):Promise.resolve({data:[] as any[]})
  ])
  const sessionRows=sessions??[]
  const responded=new Set((responses??[]).map((r:any)=>r.assignment_id)),pending=assignmentRows.filter((a:any)=>a.confirmation_required&&!responded.has(a.id))
  const leaderGroupMap=new Map<string,any>();for(const g of ledGroups??[])leaderGroupMap.set((g as any).id,g);for(const row of groupRoles??[]){const g:any=Array.isArray((row as any).groups)?(row as any).groups[0]:(row as any).groups;if(g?.active)leaderGroupMap.set(g.id,g)}
  const leaderGroups=Array.from(leaderGroupMap.values()),leaderGroupIds=leaderGroups.map((g:any)=>g.id)
  let reports:any[]=[];if(leaderGroupIds.length){const r=await supabase.from('group_reports').select('group_id,meeting_date').in('group_id',leaderGroupIds).order('meeting_date',{ascending:false});reports=r.data??[]}
  const lastReportBy=new Map<string,string>();for(const r of reports){if(!lastReportBy.has(r.group_id))lastReportBy.set(r.group_id,r.meeting_date)}
  const overdueGroups=leaderGroups.filter((g:any)=>{const last=lastReportBy.get(g.id);return !last||Date.now()-new Date(`${last}T12:00:00`).getTime()>8*86400000})
  const newConvertIds=(newConvertCourses??[]).map((c:any)=>c.id),newConvertCompleted=(enrollments??[]).some((e:any)=>newConvertIds.includes(e.course_id)&&e.credential_earned)
  const accepted=await supabase.from('ministry_applications').select('*',{count:'exact',head:true}).eq('user_id',userId).eq('status','accepted')
  const m:any=milestones??{},nextStep=getNextStep({holyGhost:m.holy_ghost_received,baptized:m.baptized,newConvertAvailable:newConvertIds.length>0,newConvertCompleted,firstSteps:m.first_steps_status,soulWinning:m.soul_winning_status,bibleStudyTeacher:m.bible_study_teacher_status,groupCount:groupCount??0,serveCount:assignmentRows.length+(accepted.count??0)})
  const name=profile?.display_name||profile?.first_name|| (es?'Miembro':'Member')
  const clear=pending.length===0&&sessionRows.length===0&&(unread??0)===0&&overdueGroups.length===0&&outreachRows.length===0
  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Church'} • {es?'Mi Día':'My Today'}</div></div><div className="row"><Link className="ghost" href="/today?lang=en">English</Link><Link className="ghost" href="/today?lang=es">Español</Link><Link className="ghost" href={l('/prophet')}>{es?'El Profeta':'The Prophet'}</Link><Link className="ghost" href="/">{es?'Inicio':'Home'}</Link></div></header>
    <section className="hero card"><div><div className="pill">{es?'MI DÍA':'MY TODAY'}</div><h1>{es?`Hola, ${name}. Esto es lo que importa ahora.`:`Hi, ${name}. Here’s what matters now.`}</h1><p>{es?'Un lugar sencillo para ver responsabilidades, aprendizaje y el siguiente paso sin buscar por toda la plataforma.':'One simple place to see responsibilities, learning and your next step without hunting through the platform.'}</p></div><div className="hero-stat"><Sparkles size={22}/><span>{clear?(es?'Todo al día':'All caught up'):(es?'Enfócate en esto primero':'Focus here first')}</span></div></section>
    {outreachRows.length>0&&<section className="card" style={{padding:18,marginBottom:16}}><div className="pill">{es?'SEGUIMIENTO VENCIDO':'FOLLOW-UP OVERDUE'}</div><h2>{es?'Hay personas esperando seguimiento':'People are waiting for follow-up'}</h2><p className="muted">{es?'No dejes que un invitado se pierda por falta de tiempo. Estas personas ya pasaron su fecha de seguimiento.':'Do not let a guest slip through because leadership is busy. These people are already past their follow-up time.'}</p>{outreachRows.slice(0,5).map((o:any)=><div key={o.id} style={{padding:'12px 0',borderBottom:'1px solid var(--line)',display:'flex',justifyContent:'space-between',gap:14,alignItems:'center'}}><div><strong>{[o.first_name,o.last_name].filter(Boolean).join(' ')}</strong><div className="small muted">{String(o.stage||'new contact').replaceAll('_',' ')}</div></div><Link className="btn" href={l('/outreach')}>{es?'Dar seguimiento':'Follow up'} <ArrowRight size={13}/></Link></div>)}</section>}
    {pending.length>0&&<section className="card" style={{padding:18,marginBottom:16}}><div className="pill">{es?'NECESITA RESPUESTA':'NEEDS A RESPONSE'}</div><h2>{es?'Confirma tus asignaciones':'Confirm your assignments'}</h2>{pending.map((a:any)=><div key={a.id} style={{padding:'12px 0',borderBottom:'1px solid var(--line)',display:'flex',justifyContent:'space-between',gap:14,alignItems:'center'}}><div><strong>{a.title}</strong><div className="small muted"><Clock3 size={12} style={{verticalAlign:'middle'}}/> {formatChurchDay(a.starts_at,timeZone)} • {formatChurchTime(a.call_time||a.starts_at,timeZone)}</div></div><Link className="btn" href={l('/teams')}>{es?'Responder':'Respond'} <ArrowRight size={13}/></Link></div>)}</section>}
    {overdueGroups.length>0&&<section className="card" style={{padding:18,marginBottom:16}}><div className="pill">{es?'LIDERAZGO DE GRUPO':'GROUP LEADERSHIP'}</div><h2>{es?'Tienes un reporte de grupo pendiente':'You have a group report to finish'}</h2><p className="muted">{es?'Hazlo una vez y Kingdom Network reutiliza esos datos para invitados, evangelismo, seguimiento y salud de la iglesia.':'Enter it once and Kingdom Network reuses the data for guests, evangelism, follow-up and church health.'}</p>{overdueGroups.map((g:any)=><div key={g.id} style={{padding:'12px 0',borderBottom:'1px solid var(--line)',display:'flex',justifyContent:'space-between',gap:14,alignItems:'center'}}><div><strong>{g.name}</strong><div className="small muted">{lastReportBy.get(g.id)?(es?`Último reporte: ${lastReportBy.get(g.id)}`:`Last report: ${lastReportBy.get(g.id)}`):(es?'No hay reporte todavía':'No report yet')}</div></div><Link className="btn" href={l(`/groups/${g.id}`)}>{es?'Hacer reporte':'Report meeting'} <ArrowRight size={13}/></Link></div>)}</section>}
    <section className="card" style={{padding:18,marginBottom:16}}><div className="pill">{es?'SIGUIENTE PASO':'NEXT STEP'}</div><h2>{nextStep.title}</h2><p className="muted">{nextStep.body}</p><Link className="btn" href={l(nextStep.href)}>{nextStep.action} <ArrowRight size={13}/></Link></section>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:14}}><section className="card" style={{padding:18}}><CalendarDays size={20}/><h3>{es?'Esta semana':'This week'}</h3>{assignmentRows.length?assignmentRows.map((a:any)=><div key={a.id} style={{padding:'9px 0',borderBottom:'1px solid var(--line)'}}><strong>{a.title}</strong><div className="small muted">{formatChurchDay(a.starts_at,timeZone)} • {formatChurchTime(a.call_time||a.starts_at,timeZone)}</div></div>):<p className="small muted">{es?'No tienes asignaciones de equipo esta semana.':'No team assignments this week.'}</p>}<Link className="record-link" href={l('/calendar/my')}>{es?'Abrir Mi Horario →':'Open My Schedule →'}</Link></section><section className="card" style={{padding:18}}><BookOpen size={20}/><h3>{es?'Clases próximas':'Upcoming classes'}</h3>{sessionRows.length?sessionRows.map((s:any)=><div key={s.id} style={{padding:'9px 0',borderBottom:'1px solid var(--line)'}}><strong>{s.title}</strong><div className="small muted">{s.session_date}{s.starts_at?` • ${String(s.starts_at).slice(0,5)}`:''}</div></div>):<p className="small muted">{es?'No hay sesiones de tus cursos programadas esta semana.':'No sessions from your active courses are scheduled this week.'}</p>}<Link className="record-link" href={l('/learning')}>{es?'Abrir Aprendizaje →':'Open Learning →'}</Link></section><section className="card" style={{padding:18}}><Bell size={20}/><h3>{es?'Notificaciones':'Notifications'}</h3><strong style={{fontSize:28}}>{unread??0}</strong><p className="small muted">{es?'notificaciones sin leer':'unread notifications'}</p><Link className="record-link" href={l('/notifications')}>{es?'Revisar notificaciones →':'Review notifications →'}</Link></section></div>
    {clear&&<section className="card" style={{padding:18,marginTop:16,textAlign:'center'}}><CheckCircle2 size={28}/><h2>{es?'Estás al día.':'You’re caught up.'}</h2><p className="muted">{es?'No hay respuestas urgentes, seguimientos vencidos, reportes pendientes ni clases programadas para esta semana. Puedes enfocarte en tu siguiente paso de crecimiento.':'No urgent responses, overdue follow-ups, group reports, or scheduled classes are waiting this week. You can focus on your next growth step.'}</p></section>}
  </main>
}
