import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CheckCircle2,KeyRound,Mail,MessageSquareText,ShieldCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { saveEmailProvider } from './actions'

export default async function ProviderSetupPage({searchParams}:{searchParams:Promise<{lang?:string;saved?:string;error?:string}>}){
  const params=await searchParams,es=params.lang==='es',lang=es?'es':'en'
  const l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id||!['pastor','church_admin'].includes(membership.role))redirect('/')
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  const {data:provider}=await supabase.from('church_communication_providers').select('email_provider,email_ready,email_from,email_reply_to,email_secret_name,sms_provider,sms_ready,updated_at').eq('church_id',membership.church_id).maybeSingle()
  const credentialConfigured=Boolean(provider?.email_secret_name)
  return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Church'} • {es?'Proveedor de Comunicaciones':'Communication Provider'}</div></div><div className="row"><Link className="ghost" href="/outreach/communications/provider?lang=en">English</Link><Link className="ghost" href="/outreach/communications/provider?lang=es">Español</Link><Link className="ghost" href={l('/outreach/communications')}>{es?'← Comunicaciones':'← Communications'}</Link></div></header>
  <section className="card" style={{padding:24,marginBottom:18}}><div className="pill">{es?'CONFIGURACIÓN SEGURA':'SECURE SETUP'}</div><h1>{es?'Conecta el correo sin poner secretos en el código.':'Connect email without putting secrets in code.'}</h1><p className="muted">{es?'La clave se envía directamente a Supabase Vault. Después de guardarla, Kingdom Network nunca muestra el valor otra vez.':'The key is sent directly to Supabase Vault. After saving it, Kingdom Network never displays the value again.'}</p></section>
  {params.saved&&<div className="notice success">{es?'Configuración del proveedor guardada.':'Provider settings saved.'}</div>}{params.error&&<div className="notice error">{params.error}</div>}
  <section className="card" style={{padding:20,marginBottom:16}}><div className="row" style={{justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="pill"><Mail size={11}/> RESEND EMAIL</div><h2>{es?'Correo automatizado':'Automated email'}</h2></div><span className="pill">{provider?.email_ready?(es?'ACTIVO':'ACTIVE'):(es?'DESACTIVADO':'OFF')}</span></div><div className="row" style={{gap:10,flexWrap:'wrap',margin:'10px 0'}}><span className="pill"><KeyRound size={10}/> {credentialConfigured?(es?'Credencial configurada':'Credential configured'):(es?'Falta credencial':'Credential missing')}</span><span className="pill"><ShieldCheck size={10}/> {provider?.email_from||(es?'Falta remitente':'Sender missing')}</span></div><form action={saveEmailProvider} style={{display:'grid',gap:10}}><input type="hidden" name="lang" value={lang}/><label className="field"><span>{es?'Clave API de Resend':'Resend API key'}</span><input name="api_key" type="password" autoComplete="off" placeholder={credentialConfigured?(es?'Déjala vacía para conservar la clave guardada':'Leave blank to keep stored key'):'re_…'}/><small className="muted">{es?'Use una clave con permiso de envío. Se guarda cifrada en Vault.':'Use a sending-access key. It is encrypted in Vault.'}</small></label><label className="field"><span>{es?'Correo remitente verificado':'Verified sender email'}</span><input name="email_from" type="email" defaultValue={provider?.email_from??''} placeholder="hello@yourchurch.org"/></label><label className="field"><span>{es?'Responder a (opcional)':'Reply-to (optional)'}</span><input name="reply_to" type="email" defaultValue={provider?.email_reply_to??''}/></label><label className="row" style={{gap:8,alignItems:'flex-start'}}><input type="checkbox" name="enable" defaultChecked={Boolean(provider?.email_ready)}/><span><strong>{es?'Activar envío automático de correo':'Enable automatic email delivery'}</strong><div className="small muted">{es?'Actívalo solamente después de verificar el dominio/remitente en Resend.':'Turn this on only after the sender/domain is verified in Resend.'}</div></span></label><button className="btn">{es?'Guardar configuración de correo':'Save email setup'}</button></form></section>
  <section className="card" style={{padding:20}}><div className="row" style={{justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><div className="pill"><MessageSquareText size={11}/> SMS</div><h2>{es?'Mensajes de texto':'Text messaging'}</h2><p className="muted">{es?'La cola, consentimiento y plantillas SMS ya existen. Todavía falta conectar un proveedor SMS real antes de enviar.':'SMS queueing, consent and templates already exist. A real SMS transport still needs to be connected before sending.'}</p></div><span className="pill">{provider?.sms_ready?(es?'ACTIVO':'ACTIVE'):(es?'NO CONECTADO':'NOT CONNECTED')}</span></div>{provider?.sms_ready&&<div className="notice success"><CheckCircle2 size={14}/> {es?'Proveedor SMS conectado.':'SMS provider connected.'}</div>}</section>
  </main>
}