import Link from 'next/link'
import { redirect } from 'next/navigation'
import { KeyRound,LogOut,Mail,MessageSquareWarning,ShieldCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { changeLoginEmail,changePassword,signOutEverywhere } from './actions'
import './security.css'

export default async function AccountSecurityPage({searchParams}:{searchParams:Promise<{email?:string;password?:string;error?:string;lang?:string}>}){
  const query=await searchParams,es=query.lang==='es',t=(en:string,sp:string)=>es?sp:en,l=(path:string)=>es?`${path}${path.includes('?')?'&':'?'}lang=es`:path
  const supabase=await createClient(),{data:claims}=await supabase.auth.getClaims(),userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:userData}=await supabase.auth.getUser(),loginEmail=userData.user?.email||String(claims?.claims?.email??'')

  return <main className="shell">
    <header className="topbar"><div><Link href={l('/')} className="brand">Kingdom <span>Network</span></Link><div className="small muted">{t('My Account • Security','Mi Cuenta • Seguridad')}</div></div><div className="row"><Link className="ghost" href="/account/security?lang=en">English</Link><Link className="ghost" href="/account/security?lang=es">Español</Link><Link className="ghost" href={l('/account/privacy')}>{t('Privacy','Privacidad')}</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/> {t('Feedback','Comentarios')}</Link><Link className="ghost" href={l('/profile')}>{t('Profile','Perfil')}</Link><Link className="ghost" href={l('/')}>← {t('Home','Inicio')}</Link></div></header>

    <section className="security-hero card"><div><div className="pill">{t('LOGIN & SECURITY','ACCESO Y SEGURIDAD')}</div><h1>{t('Manage how you sign in.','Administra cómo inicias sesión.')}</h1><p className="muted">{t('Change your login email or password, or sign out of every device if you need to.','Cambia tu correo de acceso o contraseña, o cierra sesión en todos tus dispositivos si lo necesitas.')}</p></div><div className="hero-stat"><ShieldCheck size={24}/><span>{t('Your account','Tu cuenta')}</span></div></section>
    {query.email&&<div className="notice success">{t('Login email change requested. Check your email and follow the confirmation instructions.','Cambio de correo solicitado. Revisa tu correo y sigue las instrucciones de confirmación.')}</div>}{query.password&&<div className="notice success">{t('Password updated.','Contraseña actualizada.')}</div>}{query.error&&<div className="notice error">{query.error}</div>}

    <section className="security-grid"><article className="card security-card"><div className="pill">{t('LOGIN EMAIL','CORREO DE ACCESO')}</div><h2><Mail size={15}/> {t('Change sign-in email','Cambiar correo de acceso')}</h2><div className="security-current"><strong>{t('Current login email','Correo actual')}</strong><span>{loginEmail||t('Not available','No disponible')}</span></div><form action={changeLoginEmail} className="security-form"><input type="hidden" name="lang" value={es?'es':'en'}/><label><span>{t('New login email','Nuevo correo de acceso')}</span><input name="email" type="email" required autoComplete="email"/></label><button className="btn">{t('Request email change','Solicitar cambio')}</button></form></article>

      <article className="card security-card"><div className="pill">{t('PASSWORD','CONTRASEÑA')}</div><h2><KeyRound size={15}/> {t('Change password','Cambiar contraseña')}</h2><p className="small muted">{t('Use a password you do not reuse on another account.','Usa una contraseña que no reutilices en otra cuenta.')}</p><form action={changePassword} className="security-form"><input type="hidden" name="lang" value={es?'es':'en'}/><label><span>{t('New password','Nueva contraseña')}</span><input name="password" type="password" minLength={12} required autoComplete="new-password"/></label><label><span>{t('Confirm new password','Confirmar contraseña')}</span><input name="confirm_password" type="password" minLength={12} required autoComplete="new-password"/></label><button className="btn">{t('Update password','Actualizar contraseña')}</button></form><div className="security-current"><strong>{t('Minimum','Mínimo')}</strong><span>{t('12 characters','12 caracteres')}</span></div></article>

      <article className="card security-card security-danger"><div className="pill">{t('DEVICES','DISPOSITIVOS')}</div><h2><LogOut size={15}/> {t('Sign out everywhere','Cerrar sesión en todos lados')}</h2><p className="small muted">{t('Use this if you signed in on a device you no longer control or think someone else may have access.','Úsalo si iniciaste sesión en un dispositivo que ya no controlas o crees que otra persona puede tener acceso.')}</p><form action={signOutEverywhere}><input type="hidden" name="lang" value={es?'es':'en'}/><button className="btn">{t('Sign out all devices','Cerrar sesión en todos los dispositivos')}</button></form></article>

      <article className="card security-card"><div className="pill">{t('CONTACT EMAIL','CORREO DE CONTACTO')}</div><h2>{t('What church members may see','Lo que los miembros pueden ver')}</h2><p className="small muted">{t('Your optional Contact Email lives on your profile and has its own Show/Hide privacy setting. It is separate from the email you use to sign in.','Tu Correo de Contacto opcional está en tu perfil y tiene su propio control Mostrar/Ocultar. Es diferente al correo que usas para iniciar sesión.')}</p><div className="row"><Link className="ghost" href={l('/profile')}>{t('Edit contact email','Editar correo de contacto')}</Link><Link className="ghost" href={l('/account/privacy')}>{t('Privacy settings','Privacidad')}</Link></div></article></section>
  </main>
}