import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CalendarDays,Flag,HeartHandshake,Languages,MessageSquareWarning,Plus,Star } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { formatChurchDate } from '@/lib/church-time'
import { createCampaign,updateCampaign } from './actions'
import './fundraising.css'

const types=[['camp','Camp','Campamento'],['convention','Convention','Convención'],['missions','Missions','Misiones'],['building','Building Project','Proyecto de Construcción'],['emergency','Emergency','Emergencia'],['youth','Youth','Jóvenes'],['general','General','General']] as const
const statuses=[['draft','Draft','Borrador'],['active','Active','Activo'],['completed','Completed','Completado'],['cancelled','Cancelled','Cancelado']] as const
const cash=(v:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v)||0)

export default async function FundraisingPage({searchParams}:{searchParams:Promise<{created?:string;saved?:string;error?:string;lang?:string}>}){
  const query=await searchParams,es=query.lang==='es',t=(en:string,sp:string)=>es?sp:en,l=(path:string)=>es?`${path}${path.includes('?')?'&':'?'}lang=es`:path
  const label=(rows:readonly (readonly [string,string,string])[],v:string)=>rows.find(([k])=>k===v)?.[es?2:1]??v.replaceAll('_',' ')
  const supabase=await createClient()
  const {data:claims}=await supabase.auth.getClaims(),userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name,timezone)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const churchId=membership.church_id,church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches,timeZone=church?.timezone||'America/Los_Angeles'
  const canCreate=['ministry_leader','pastor','church_admin','finance_admin'].includes(membership.role),canOversee=['pastor','church_admin','finance_admin'].includes(membership.role)
  const {data:campaigns}=await supabase.from('fundraising_campaigns').select('*').eq('church_id',churchId).order('featured',{ascending:false}).order('created_at',{ascending:false})
  const rows=[...(campaigns??[])].sort((a:any,b:any)=>Number(b.status==='active')-Number(a.status==='active')||Number(Boolean(b.featured))-Number(Boolean(a.featured))||new Date(b.created_at).getTime()-new Date(a.created_at).getTime())
  const active=rows.filter((c:any)=>c.status==='active'),totalGoals=active.reduce((sum:number,c:any)=>sum+Number(c.goal_amount||0),0),totalRaised=active.reduce((sum:number,c:any)=>sum+Number(c.raised_amount||0),0)

  return <main className="shell">
    <header className="topbar"><div><Link href={l('/')} className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??t('Your Church','Tu Iglesia')} • {t('Fundraising','Recaudación')}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/fundraising?lang=en">English</Link><Link className="ghost" href="/fundraising?lang=es">Español</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/> {t('Feedback','Comentarios')}</Link><Link className="ghost" href={l('/')}>← {t('Home','Inicio')}</Link></div></header>

    <section className="fund-hero card"><div><div className="pill">{t('CAMPAIGNS & GOALS','CAMPAÑAS Y METAS')}</div><h1>{t('See what we’re building together.','Mira lo que estamos logrando juntos.')}</h1><p className="muted">{t('Track confirmed progress for camps, conventions, missions, projects and urgent needs.','Mira el progreso confirmado de campamentos, convenciones, misiones, proyectos y necesidades urgentes.')}</p></div><div className="hero-stat"><strong>{active.length}</strong><span>{t(`${active.length===1?'active campaign':'active campaigns'} • ${cash(totalRaised)} of ${cash(totalGoals)}`,`${active.length===1?'campaña activa':'campañas activas'} • ${cash(totalRaised)} de ${cash(totalGoals)}`)}</span></div></section>

    {query.created&&<div className="notice success">{t('Fundraising campaign created.','Campaña de recaudación creada.')}</div>}{query.saved&&<div className="notice success">{t('Campaign progress updated.','Progreso de campaña actualizado.')}</div>}{query.error&&<div className="notice error">{query.error}</div>}

    <section style={{marginBottom:22}}><div className="pill" style={{marginBottom:12}}>{t('CURRENT CAMPAIGNS','CAMPAÑAS ACTUALES')}</div><section className="campaign-list">{rows.map((c:any)=>{const goal=Number(c.goal_amount)||0,raised=Number(c.raised_amount)||0,pct=goal>0?Math.min(100,Math.round((raised/goal)*100)):0,canManage=canOversee||c.created_by===userId;return <article className={`card campaign-card ${c.featured?'featured':''}`} key={c.id}><div className="campaign-head"><div><div className="campaign-tags"><span className="campaign-tag">{label(types,c.campaign_type)}</span>{c.featured&&<span className="campaign-tag featured"><Star size={10}/> {t('Featured','Destacada')}</span>}{c.status!=='active'&&<span className="campaign-tag">{label(statuses,c.status)}</span>}</div><h2>{c.title}</h2></div><strong>{pct}%</strong></div>{c.description&&<p className="campaign-copy">{c.description}</p>}<div className="progress-track"><div className="progress-fill" style={{width:`${pct}%`}}/></div><div className="money-row"><strong>{cash(raised)} {t('raised','recaudados')}</strong><span>{t('Goal','Meta')} {cash(goal)} • {cash(Math.max(0,goal-raised))} {t('remaining','restantes')}</span></div><div className="campaign-meta">{c.ends_at&&<span><CalendarDays size={12}/>{t('Ends','Termina')} {formatChurchDate(c.ends_at,timeZone,{month:'short',day:'numeric',year:'numeric'})}</span>}<span><Flag size={12}/>{label(statuses,c.status)}</span></div>{canManage&&<details style={{marginTop:12}}><summary className="ghost" style={{display:'inline-flex',cursor:'pointer'}}>{t('Update campaign','Actualizar campaña')}</summary><form action={updateCampaign} className="manage-campaign" style={{marginTop:12}}><input type="hidden" name="campaign_id" value={c.id}/><input type="hidden" name="lang" value={es?'es':'en'}/><label><span>{t('Confirmed total raised','Total confirmado recaudado')}</span><input name="raised_amount" type="number" min="0" step="0.01" defaultValue={raised}/></label><label><span>{t('Status','Estado')}</span><select name="status" defaultValue={c.status}>{statuses.map(([v,en,sp])=><option key={v} value={v}>{es?sp:en}</option>)}</select></label><label><span>{t('Featured','Destacada')}</span><input name="featured" type="checkbox" defaultChecked={c.featured}/></label><button className="btn">{t('Save progress','Guardar progreso')}</button></form></details>}</article>})}{!rows.length&&<div className="card fund-empty"><h3>{t('No fundraising campaigns yet.','Todavía no hay campañas de recaudación.')}</h3><p className="muted">{t('When leadership creates a campaign, its goal and confirmed progress will appear here.','Cuando liderazgo cree una campaña, su meta y progreso confirmado aparecerán aquí.')}</p></div>}</section></section>

    {canCreate&&<details className="card fund-create" style={{padding:18}}><summary style={{fontWeight:800,cursor:'pointer'}}><Plus size={15}/> {t('Leadership Tools • Create campaign','Herramientas de Liderazgo • Crear campaña')}</summary><div style={{marginTop:16}}><p className="small muted">{t('Kingdom Network tracks the goal and confirmed total. Online payment processing is not enabled in this pilot.','Kingdom Network registra la meta y el total confirmado. Los pagos en línea no están habilitados durante este piloto.')}</p><form action={createCampaign} className="create-campaign"><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="lang" value={es?'es':'en'}/><label className="wide"><span>{t('Campaign title','Título de campaña')}</span><input name="title" required placeholder={t('Youth Camp 2027','Campamento Juvenil 2027')}/></label><label><span>{t('Type','Tipo')}</span><select name="campaign_type" defaultValue="general">{types.map(([v,en,sp])=><option key={v} value={v}>{es?sp:en}</option>)}</select></label><label><span>{t('Goal amount','Cantidad meta')}</span><input name="goal_amount" type="number" min="0.01" step="0.01" required/></label><label><span>{t('Starts','Empieza')}</span><input name="starts_at" type="datetime-local"/></label><label><span>{t('Ends','Termina')}</span><input name="ends_at" type="datetime-local"/></label><label><span>{t('Status','Estado')}</span><select name="status" defaultValue="draft"><option value="draft">{t('Draft','Borrador')}</option><option value="active">{t('Active','Activo')}</option></select></label><label><span>{t('Featured','Destacada')}</span><input name="featured" type="checkbox"/></label><label className="wide"><span>{t('Description','Descripción')}</span><textarea name="description" rows={5} placeholder={t('What are we raising for, who does it help, and what will the funds make possible?','¿Para qué estamos recaudando, a quién ayuda y qué hará posible el dinero?')}/></label><button className="btn wide"><HeartHandshake size={14}/> {t('Create campaign','Crear campaña')}</button></form></div></details>}
  </main>
}