import { BookOpen,Church,HandHeart,Mail,MapPin,MessageCircle,Phone,StickyNote,UserPlus } from 'lucide-react'
import { formatChurchDate } from '@/lib/church-time'
import { logOutreachInteraction } from './actions'
import styles from './outreach-history.module.css'

const types=[['call','Call','Llamada'],['text','Text','Mensaje de texto'],['visit','Visit','Visita'],['invitation','Invitation','Invitación'],['bible_study','Bible Study','Estudio bíblico'],['service_attendance','Service Attendance','Asistencia al servicio'],['prayer','Prayer','Oración'],['follow_up','Follow-up','Seguimiento'],['note','Note','Nota']] as const
const icon=(type:string)=>{const p={size:13};switch(type){case'call':return <Phone {...p}/>;case'text':return <MessageCircle {...p}/>;case'visit':return <MapPin {...p}/>;case'invitation':return <UserPlus {...p}/>;case'bible_study':return <BookOpen {...p}/>;case'service_attendance':return <Church {...p}/>;case'prayer':return <HandHeart {...p}/>;case'follow_up':return <Mail {...p}/>;default:return <StickyNote {...p}/>}}
const label=(type:string,es:boolean)=>{const row=types.find(([v])=>v===type);return row?(es?row[2]:row[1]):type.replaceAll('_',' ')}
const personName=(p:any,es:boolean)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||(es?'Miembro de la iglesia':'Church member')

export function OutreachHistory({contactId,interactions,timeZone,lang='en'}:{contactId:string;interactions:any[];timeZone:string;lang?:'en'|'es'}){
  const es=lang==='es'
  return <details className={styles.panel}><summary><StickyNote size={13}/> {es?'Historial de seguimiento':'Follow-up history'} • {interactions.length} {es?(interactions.length===1?'registro':'registros'):(interactions.length===1?'entry':'entries')}</summary>
    <form action={logOutreachInteraction} className={styles.form}><input type="hidden" name="contact_id" value={contactId}/><input type="hidden" name="lang" value={lang}/><label><span>{es?'Interacción':'Interaction'}</span><select name="interaction_type" defaultValue="follow_up">{types.map(([v,en,sp])=><option value={v} key={v}>{es?sp:en}</option>)}</select></label><label><span>{es?'Lección de estudio bíblico':'Bible study lesson'}</span><input type="number" min="0" name="bible_study_lesson" placeholder="#"/></label><label><span>{es?'¿Qué pasó?':'What happened?'}</span><input name="summary" required maxLength={2000} placeholder={es?'Llamó, oró, programó la Lección 2…':'Called, prayed, scheduled Lesson 2…'}/></label><button>{es?'Registrar interacción':'Log interaction'}</button></form>
    {interactions.length?<div className={styles.timeline}>{interactions.slice(0,8).map((row:any)=>{const p=Array.isArray(row.profiles)?row.profiles[0]:row.profiles;return <div className={styles.event} key={row.id}><div className={styles.icon}>{icon(row.interaction_type)}</div><div className={styles.eventBody}><div className={styles.eventHead}><strong>{label(row.interaction_type,es)}</strong><time>{formatChurchDate(row.occurred_at,timeZone,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}</time></div><p>{row.summary}</p><div className={styles.eventMeta}>{personName(p,es)}{row.bible_study_lesson!=null?` • ${es?'Lección':'Lesson'} ${row.bible_study_lesson}`:''}</div></div></div>})}</div>:<div className={styles.empty}>{es?'Todavía no hay interacciones registradas. El primer seguimiento aparecerá aquí.':'No logged interactions yet. The first follow-up you record will appear here.'}</div>}
  </details>
}
