import Link from 'next/link'
import { redirect } from 'next/navigation'
import { ArrowRight,BookOpen,BriefcaseBusiness,CalendarDays,Church,FileText,Globe2,GraduationCap,HandHeart,HeartHandshake,Images,MessageCircle,Megaphone,ShieldCheck,Sparkles,Store,Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { CommunityFeed } from '@/components/community-feed'
import { NotificationBell } from '@/components/notification-bell'
import { OfficialUpdates } from '@/components/official-updates'
import { UpcomingSnapshot } from '@/components/upcoming-snapshot'
import { FeaturedEvents } from '@/components/featured-events'
import { getNextStep } from '@/lib/journey'

const modules=[
  {title:'Start Here',desc:'Simple first-time guide • English / Español',Icon:Sparkles,href:'/start'},
  {title:'My Journey',desc:'Your discipleship pathway',Icon:Sparkles,href:'/journey'},
  {title:'Learning',desc:'Courses, badges & growth',Icon:GraduationCap,href:'/learning'},
  {title:'Kingdom Guide',desc:'Navigation & trusted resources',Icon:BookOpen,href:'/guide'},
  {title:'Groups',desc:'Friendship groups & reports',Icon:Users,href:'/groups'},
  {title:'Prayer & Testimony',desc:'Share prayer and victories',Icon:HandHeart,href:'/prayer'},
  {title:'Messages',desc:'Private member conversations',Icon:MessageCircle,href:'/messages'},
  {title:'Serve',desc:'Ministries & applications',Icon:HandHeart,href:'/serve'},
  {title:'Outreach',desc:'Guests & Bible studies',Icon:Megaphone,href:'/outreach'},
  {title:'Calendar',desc:'Church & district events',Icon:CalendarDays,href:'/calendar'},
  {title:'Documents',desc:'Certificates & records',Icon:FileText,href:'/documents'},
  {title:'Media Library',desc:'Flyers, photos & reusable graphics',Icon:Images,href:'/media'},
  {title:'Teams',desc:'Schedules & assignments',Icon:BriefcaseBusiness,href:'/teams'},
  {title:'Business Partners',desc:'Support member-owned businesses',Icon:Store,href:'/business'},
  {title:'Fundraising',desc:'Campaigns & goal tracking',Icon:HeartHandshake,href:'/fundraising'},
  {title:'Network',desc:'Organization & district',Icon:Globe2,href:'/network'},
  {title:'Church',desc:'Member directory',Icon:Church,href:'/directory'},
  {title:'Private Care',desc:'Prayer & pastoral support',Icon:HandHeart,href:'/help'}
] as const

export default async function Home(){
  const supabase=await createClient();const {data:claimsData}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub;if(!userId)redirect('/login')
  const [{data:profile},{data:membership}]=await Promise.all([supabase.from('profiles').select('display_name,first_name,last_name').eq('id',userId).single(),supabase.from('church_memberships').select('church_id,role,churches(name,city,state,logo_path,brand_color,welcome_message)').eq('user_id',userId).eq('status','active').limit(1).single()])
  if(!membership?.church_id)return <main className="shell"><div className="card" style={{padding:24}}><h1>Account created.</h1><p>Your church membership has not been connected yet. If you were invited, make sure you used the invited email address.</p><form action="/auth/signout" method="post"><button className="btn">Sign out</button></form></div></main>
  const isAdmin=['pastor','church_admin'].includes(membership.role),nowIso=new Date().toISOString()
  const [{data:milestones},{count:groupCount},{count:teamCount},{count:acceptedCount},{data:newConvertCourses}]=await Promise.all([supabase.from('member_milestones').select('holy_ghost_received,baptized,first_steps_status,soul_winning_status,bible_study_teacher_status').eq('church_id',membership.church_id).eq('user_id',userId).maybeSingle(),supabase.from('group_memberships').select('*',{count:'exact',head:true}).eq('user_id',userId),supabase.from('team_assignments').select('*',{count:'exact',head:true}).eq('assigned_user_id',userId),supabase.from('ministry_applications').select('*',{count:'exact',head:true}).eq('user_id',userId).eq('status','accepted'),supabase.from('courses').select('id').eq('church_id',membership.church_id).eq('published',true).eq('pathway_stage','new_convert')])
  let leadershipNeeds=0;if(isAdmin){const [{count:care},{count:reports},{count:outreach},{count:docs},{count:applications}]=await Promise.all([supabase.from('care_requests').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).in('status',['new','in_review']),supabase.from('message_reports').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).eq('status','open'),supabase.from('outreach_contacts').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).lt('follow_up_due_at',nowIso).not('stage','in','("inactive","serving")'),supabase.from('member_documents').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).eq('verification_status','pending'),supabase.from('ministry_applications').select('id,ministries!inner(church_id)',{count:'exact',head:true}).eq('ministries.church_id',membership.church_id).in('status',['submitted','under_review'])]);leadershipNeeds=(care??0)+(reports??0)+(outreach??0)+(docs??0)+(applications??0)}
  const newConvertIds=(newConvertCourses??[]).map((c:any)=>c.id);let newConvertCompleted=false;if(newConvertIds.length){const {data:completedRows}=await supabase.from('course_enrollments').select('course_id').eq('user_id',userId).eq('credential_earned',true).in('course_id',newConvertIds).limit(1);newConvertCompleted=Boolean(completedRows?.length)}
  const m:any=milestones??{},nextStep=getNextStep({holyGhost:m.holy_ghost_received,baptized:m.baptized,newConvertAvailable:newConvertIds.length>0,newConvertCompleted,firstSteps:m.first_steps_status,soulWinning:m.soul_winning_status,bibleStudyTeacher:m.bible_study_teacher_status,groupCount:groupCount??0,serveCount:(teamCount??0)+(acceptedCount??0)}),church=Array.isArray(membership.churches)?membership.churches[0]:membership.churches as any,name=profile?.display_name||[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||'Member',churchLogo=church?.logo_path?supabase.storage.from('church-branding').getPublicUrl(church.logo_path).data.publicUrl:null,accent=church?.brand_color||'#5a3a7d'
  return <main className="shell"><header className="topbar"><div><div className="brand">Kingdom <span>Network</span></div><div className="small muted">{church?.name??'Your Church'} • {membership.role.replaceAll('_',' ')}</div></div><div className="row"><NotificationBell userId={userId}/>{isAdmin&&<Link className="ghost" href="/church/leadership">Leadership today</Link>}{isAdmin&&<Link className="ghost" href="/church">Church admin</Link>}<Link className="ghost" href="/start">Start here</Link><Link className="ghost" href="/journey">My journey</Link><Link className="ghost" href="/profile">My profile</Link><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div></header>
  <section className="hero card" style={{borderColor:accent}}><div style={{display:'flex',alignItems:'center',gap:14}}>{churchLogo&&<img src={churchLogo} alt={`${church?.name??'Church'} logo`} style={{width:64,height:64,borderRadius:16,objectFit:'contain',background:'#100c14',padding:6,border:'1px solid #3b3043'}}/>}<div><div className="pill">WELCOME BACK</div><h1>{name}</h1><p>{church?.welcome_message||'Connect. Grow. Serve. Reach.'}</p></div></div><div className="hero-stat"><strong>{church?.name??'Kingdom Network'}</strong><span>{[church?.city,church?.state].filter(Boolean).join(', ')||'Local church community'}</span></div></section>
  {isAdmin&&<section className="card" style={{padding:20,marginBottom:18,borderColor:accent,display:'flex',justifyContent:'space-between',alignItems:'center',gap:18,flexWrap:'wrap'}}><div style={{display:'flex',gap:13}}><ShieldCheck size={28}/><div><div className="pill">LEADERSHIP TODAY</div><h2>{leadershipNeeds>0?`${leadershipNeeds} item${leadershipNeeds===1?'':'s'} need attention`:'Leadership queue is clear'}</h2><p className="muted">{leadershipNeeds>0?'Pastoral care, outreach, reports, documents and ministry applications are waiting.':'Nothing urgent is waiting in the main leadership queues.'}</p></div></div><Link className="btn" href="/church/leadership">{leadershipNeeds>0?'Do this first':'Open leadership'} <ArrowRight size={15}/></Link></section>}
  <section className="card" style={{padding:20,marginBottom:18,borderColor:accent,display:'flex',justifyContent:'space-between',alignItems:'center',gap:18,flexWrap:'wrap'}}><div><div className="pill">MY NEXT STEP • {nextStep.reason.toUpperCase()}</div><h2>{nextStep.title}</h2><p className="muted">{nextStep.body}</p></div><Link className="btn" href={nextStep.href}>{nextStep.action} <ArrowRight size={15}/></Link></section>
  <UpcomingSnapshot churchId={membership.church_id} userId={userId}/><FeaturedEvents churchId={membership.church_id}/><section className="module-grid">{modules.map(({title,desc,Icon,href})=><Link className="module card module-link" href={href} key={title}><Icon size={22}/><strong>{title}</strong><span>{desc}</span><small>Open module</small></Link>)}</section><OfficialUpdates churchId={membership.church_id}/><div className="content-grid"><CommunityFeed churchId={membership.church_id} userId={userId}/><aside><div className="card side"><div className="pill">ACTIVE NOW</div><h3>Kingdom Network Alpha</h3><ul><li>Bilingual member onboarding</li><li>Personalized Journey & next steps</li><li>Leadership Today priority queue</li><li>Kingdom Guide</li><li>Learning Center</li><li>Groups & outreach follow-up</li><li>Serve & team scheduling</li><li>Media Library & reusable church assets</li><li>Business Partners member directory</li><li>Events, fundraising & documents</li><li>Community feed & private messaging</li></ul></div><div className="card side"><div className="pill">CURRENT BUILD FOCUS</div><h3>Pilot readiness & validation</h3><p className="muted">Connect the strongest workflows, keep setup simple, validate auth on real devices, and prepare the system to become repeatable for additional churches.</p></div></aside></div></main>
}
