import Link from 'next/link'
import { redirect } from 'next/navigation'
import { ArrowRight,BookOpen,BriefcaseBusiness,CalendarDays,CheckCircle2,Church,FileText,Globe2,GraduationCap,HandHeart,HeartHandshake,Images,MessageCircle,MessageSquareWarning,Megaphone,ShieldCheck,Sparkles,Store,Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { CommunityFeed } from '@/components/community-feed'
import { NotificationBell } from '@/components/notification-bell'
import { OfficialUpdates } from '@/components/official-updates'
import { UpcomingSnapshot } from '@/components/upcoming-snapshot'
import { FeaturedEvents } from '@/components/featured-events'
import { getNextStep } from '@/lib/journey'

const everyday=[
  {title:'Learning',desc:'Classes & progress',Icon:GraduationCap,href:'/learning'},
  {title:'Groups',desc:'Friendship Group & community',Icon:Users,href:'/groups'},
  {title:'Calendar',desc:'Services, classes & events',Icon:CalendarDays,href:'/calendar'},
  {title:'Prayer & Testimony',desc:'Prayer needs & victories',Icon:HandHeart,href:'/prayer'}
] as const

const explore=[
  {title:'Kingdom Guide',desc:'Help finding anything',Icon:BookOpen,href:'/guide'},
  {title:'Messages',desc:'Private conversations',Icon:MessageCircle,href:'/messages'},
  {title:'Serve',desc:'Ministries & opportunities',Icon:HandHeart,href:'/serve'},
  {title:'Teams',desc:'Schedules & assignments',Icon:BriefcaseBusiness,href:'/teams'},
  {title:'Documents',desc:'Certificates & records',Icon:FileText,href:'/documents'},
  {title:'Media Library',desc:'Flyers, photos & graphics',Icon:Images,href:'/media'},
  {title:'Business Partners',desc:'Support member businesses',Icon:Store,href:'/business'},
  {title:'Fundraising',desc:'Campaigns & goals',Icon:HeartHandshake,href:'/fundraising'},
  {title:'Network',desc:'District & organization',Icon:Globe2,href:'/network'},
  {title:'Church Directory',desc:'Find church family',Icon:Church,href:'/directory'},
  {title:'Private Care',desc:'Private prayer & pastoral help',Icon:HandHeart,href:'/help'}
] as const

export default async function Home(){
  const supabase=await createClient();const {data:claimsData}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub;if(!userId)redirect('/login')
  const [{data:profile},{data:membership}]=await Promise.all([supabase.from('profiles').select('display_name,first_name,last_name').eq('id',userId).single(),supabase.from('church_memberships').select('church_id,role,churches(name,city,state,logo_path,brand_color,welcome_message)').eq('user_id',userId).eq('status','active').limit(1).single()])
  if(!membership?.church_id)return <main className="shell"><div className="card" style={{padding:24}}><h1>Account created.</h1><p>Your account is not connected to an active church yet. If this should already be connected, use Feedback below and tell us what happened.</p><div className="row"><Link className="btn" href="/feedback">Give feedback</Link><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div></div></main>
  const isAdmin=['pastor','church_admin'].includes(membership.role),nowIso=new Date().toISOString()
  const [{data:milestones},{count:groupCount},{count:teamCount},{count:acceptedCount},{data:newConvertCourses}]=await Promise.all([supabase.from('member_milestones').select('holy_ghost_received,baptized,first_steps_status,soul_winning_status,bible_study_teacher_status').eq('church_id',membership.church_id).eq('user_id',userId).maybeSingle(),supabase.from('group_memberships').select('*',{count:'exact',head:true}).eq('user_id',userId),supabase.from('team_assignments').select('*',{count:'exact',head:true}).eq('assigned_user_id',userId),supabase.from('ministry_applications').select('*',{count:'exact',head:true}).eq('user_id',userId).eq('status','accepted'),supabase.from('courses').select('id').eq('church_id',membership.church_id).eq('published',true).eq('pathway_stage','new_convert')])
  let leadershipNeeds=0;if(isAdmin){const [{count:care},{count:reports},{count:outreach},{count:docs},{count:applications}]=await Promise.all([supabase.from('care_requests').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).in('status',['new','in_review']),supabase.from('message_reports').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).eq('status','open'),supabase.from('outreach_contacts').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).lt('follow_up_due_at',nowIso).not('stage','in','("inactive","serving")'),supabase.from('member_documents').select('*',{count:'exact',head:true}).eq('church_id',membership.church_id).eq('verification_status','pending'),supabase.from('ministry_applications').select('id,ministries!inner(church_id)',{count:'exact',head:true}).eq('ministries.church_id',membership.church_id).in('status',['submitted','under_review'])]);leadershipNeeds=(care??0)+(reports??0)+(outreach??0)+(docs??0)+(applications??0)}
  const newConvertIds=(newConvertCourses??[]).map((c:any)=>c.id);let newConvertCompleted=false;if(newConvertIds.length){const {data:completedRows}=await supabase.from('course_enrollments').select('course_id').eq('user_id',userId).eq('credential_earned',true).in('course_id',newConvertIds).limit(1);newConvertCompleted=Boolean(completedRows?.length)}
  const m:any=milestones??{},nextStep=getNextStep({holyGhost:m.holy_ghost_received,baptized:m.baptized,newConvertAvailable:newConvertIds.length>0,newConvertCompleted,firstSteps:m.first_steps_status,soulWinning:m.soul_winning_status,bibleStudyTeacher:m.bible_study_teacher_status,groupCount:groupCount??0,serveCount:(teamCount??0)+(acceptedCount??0)}),church=Array.isArray(membership.churches)?membership.churches[0]:membership.churches as any,name=profile?.display_name||[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||'Member',churchLogo=church?.logo_path?supabase.storage.from('church-branding').getPublicUrl(church.logo_path).data.publicUrl:null,accent=church?.brand_color||'#5a3a7d'
  return <main className="shell"><header className="topbar"><div><div className="brand">Kingdom <span>Network</span></div><div className="small muted">{church?.name??'Your Church'}</div></div><div className="row"><NotificationBell userId={userId}/>{isAdmin&&<Link className="ghost" href="/church/leadership">Leadership</Link>}{isAdmin&&<Link className="ghost" href="/church">Admin</Link>}<Link className="ghost" href="/start">Start Here</Link><Link className="ghost" href="/feedback">Feedback</Link><Link className="ghost" href="/profile">Profile</Link><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div></header>
  <section className="hero card" style={{borderColor:accent}}><div style={{display:'flex',alignItems:'center',gap:14}}>{churchLogo&&<img src={churchLogo} alt={`${church?.name??'Church'} logo`} style={{width:64,height:64,borderRadius:16,objectFit:'contain',background:'#100c14',padding:6,border:'1px solid #3b3043'}}/>}<div><div className="pill">WELCOME BACK</div><h1>{name}</h1><p>{church?.welcome_message||'One place to grow, connect, serve and walk with God.'}</p></div></div><div className="hero-stat"><strong>{church?.name??'Kingdom Network'}</strong><span>{[church?.city,church?.state].filter(Boolean).join(', ')||'Church community'}</span></div></section>
  {isAdmin&&<section className="card" style={{padding:18,marginBottom:16,borderColor:accent,display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div style={{display:'flex',gap:12}}><ShieldCheck size={26}/><div><div className="pill">LEADERSHIP</div><h2 style={{margin:'6px 0'}}>{leadershipNeeds>0?`${leadershipNeeds} item${leadershipNeeds===1?'':'s'} need attention`:'Leadership queue is clear'}</h2><p className="muted" style={{margin:0}}>{leadershipNeeds>0?'Start with the most important leadership item.':'Nothing urgent is waiting right now.'}</p></div></div><Link className="btn" href="/church/leadership">{leadershipNeeds>0?'Do this first':'Open leadership'} <ArrowRight size={15}/></Link></section>}
  <section className="card" style={{padding:20,marginBottom:16,border:'1px solid rgba(125,211,252,.34)',display:'flex',justifyContent:'space-between',alignItems:'center',gap:18,flexWrap:'wrap'}}><div><div className="pill">TODAY</div><h2 style={{margin:'7px 0'}}>What needs my attention?</h2><p className="muted" style={{margin:0}}>Assignments, classes, notifications and your next step—all in one simple daily view.</p></div><Link className="btn" href="/today">Open My Today <ArrowRight size={15}/></Link></section>
  <section className="card" style={{padding:18,marginBottom:18,display:'flex',justifyContent:'space-between',alignItems:'center',gap:18,flexWrap:'wrap'}}><div><div className="pill">MY NEXT STEP</div><h2 style={{margin:'7px 0'}}>{nextStep.title}</h2><p className="muted" style={{margin:0}}>{nextStep.body}</p></div><div className="row"><Link className="btn secondary" href={nextStep.href}>{nextStep.action}</Link><Link className="ghost" href="/journey">View My Journey</Link></div></section>
  <UpcomingSnapshot churchId={membership.church_id} userId={userId}/><FeaturedEvents churchId={membership.church_id}/>
  <section style={{margin:'22px 0'}}><div className="pill" style={{marginBottom:12}}>EVERYDAY</div><section className="module-grid">{everyday.map(({title,desc,Icon,href})=><Link className="module card module-link" href={href} key={title}><Icon size={22}/><strong>{title}</strong><span>{desc}</span><small>Open</small></Link>)}</section></section>
  <details className="card" style={{padding:18,marginBottom:22}}><summary style={{cursor:'pointer',fontWeight:700,fontSize:'1.05rem'}}>Explore more Kingdom Network tools</summary><p className="small muted">These are here when you need them. You do not need to learn everything at once.</p><section className="module-grid" style={{marginTop:14}}>{explore.map(({title,desc,Icon,href})=><Link className="module card module-link" href={href} key={title}><Icon size={22}/><strong>{title}</strong><span>{desc}</span><small>Open</small></Link>)}{isAdmin&&<Link className="module card module-link" href="/outreach"><Megaphone size={22}/><strong>Outreach</strong><span>Guests, Bible studies & follow-up</span><small>Open</small></Link>}</section></details>
  <section className="card" style={{padding:18,marginBottom:22,display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap'}}><div style={{display:'flex',gap:12,alignItems:'center'}}><MessageSquareWarning size={22}/><div><strong>Help us improve Kingdom Network</strong><div className="small muted">Something confusing, broken, useful or missing? Tell us.</div></div></div><Link className="ghost" href="/feedback">Share feedback →</Link></section>
  <OfficialUpdates churchId={membership.church_id}/><div className="content-grid"><CommunityFeed churchId={membership.church_id} userId={userId}/><aside><div className="card side"><div className="pill">NEED HELP?</div><h3>Not sure where something is?</h3><p className="muted">Start with My Today for what matters now, or use Kingdom Guide to find the right place.</p><div style={{display:'grid',gap:8}}><Link className="btn" href="/today">Open My Today</Link><Link className="ghost" href="/guide">Open Kingdom Guide</Link></div></div></aside></div></main>
}
