import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BookHeart,CheckCircle2,Church,NotebookPen,Quote,Trash2 } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { createJourneyEntry,deleteJourneyEntry,markPrayerAnswered } from './actions'

const label=(type:string,es:boolean)=>({prayer:es?'Oración':'Prayer',journal:es?'Diario':'Journal',testimony:es?'Testimonio':'Testimony',spiritual_note:es?'Nota espiritual':'Spiritual Note'} as Record<string,string>)[type]||type
const fmt=(v?:string|null,es=false)=>v?new Date(`${v}T12:00:00`).toLocaleDateString(es?'es-US':'en-US',{month:'short',day:'numeric',year:'numeric'}):''

export default async function JourneyMemoriesPage({searchParams}:{searchParams:Promise<{lang?:string;type?:string;saved?:string;answered?:string;deleted?:string;error?:string}>}){
  const params=await searchParams,es=params.lang==='es',lang=es?'es':'en',suffix=es?'?lang=es':''
  const l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub
  if(!userId)redirect(`/login${suffix}`)
  const {data:membership}=await supabase.from('church_memberships').select('church_id,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  let query=supabase.from('journey_entries').select('*').eq('church_id',membership.church_id).eq('user_id',userId).order('occurred_on',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false})
  if(params.type&&['prayer','journal','testimony','spiritual_note'].includes(params.type))query=query.eq('entry_type',params.type)
  const {data:rowsData}=await query
  const rows=rowsData??[]
  const {data:allData}=await supabase.from('journey_entries').select('entry_type,prayer_status').eq('church_id',membership.church_id).eq('user_id',userId)
  const all=allData??[],prayers=all.filter((x:any)=>x.entry_type==='prayer'),answered=prayers.filter((x:any)=>x.prayer_status==='answered').length,testimonies=all.filter((x:any)=>x.entry_type==='testimony').length,journals=all.filter((x:any)=>x.entry_type==='journal').length
  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??(es?'Tu Iglesia':'Your Church')} • {es?'Mi Jornada Personal':'My Personal Journey'}</div></div><div className="row"><Link className="ghost" href="/journey/memories?lang=en">English</Link><Link className="ghost" href="/journey/memories?lang=es">Español</Link><Link className="ghost" href={l('/journey')}>{es?'← Mi Camino':'← My Journey'}</Link><Link className="ghost" href="/">{es?'Inicio':'Home'}</Link></div></header>

    <section className="card" style={{padding:24,marginBottom:16}}><div className="pill">{es?'RECUERDA LO QUE DIOS HA HECHO':'REMEMBER WHAT GOD HAS DONE'}</div><h1>{es?'Oraciones, diario, testimonios y momentos que no quieres olvidar.':'Prayers, journal entries, testimonies and moments you do not want to forget.'}</h1><p className="muted">{es?'Tus entradas son privadas por defecto. Un testimonio solo entra al proceso de compartir si tú lo eliges.':'Your entries are private by default. A testimony only enters the church-sharing process if you choose it.'}</p></section>
    {params.saved&&<div className="notice success">{es?'Guardado en Mi Jornada.':'Saved to My Journey.'}</div>}{params.answered&&<div className="notice success">{es?'Oración marcada como contestada.':'Prayer marked answered.'}</div>}{params.deleted&&<div className="notice success">{es?'Entrada eliminada.':'Entry deleted.'}</div>}{params.error&&<div className="notice error">{params.error}</div>}

    <section className="stat-grid" style={{marginBottom:18}}><div className="card stat-card"><BookHeart/><div><strong>{prayers.length}</strong><span>{es?'oraciones guardadas':'saved prayers'}</span></div></div><div className="card stat-card"><CheckCircle2/><div><strong>{answered}</strong><span>{es?'oraciones contestadas':'answered prayers'}</span></div></div><div className="card stat-card"><Quote/><div><strong>{testimonies}</strong><span>{es?'testimonios':'testimonies'}</span></div></div><div className="card stat-card"><NotebookPen/><div><strong>{journals}</strong><span>{es?'entradas de diario':'journal entries'}</span></div></div></section>

    <details className="card" open style={{padding:18,marginBottom:18}}><summary style={{fontWeight:800,cursor:'pointer'}}>{es?'Agregar algo a Mi Jornada':'Add something to My Journey'}</summary><form action={createJourneyEntry} style={{display:'grid',gap:10,marginTop:14}}><input type="hidden" name="lang" value={lang}/><label className="field"><span>{es?'Tipo':'Type'}</span><select name="entry_type" defaultValue="prayer"><option value="prayer">{es?'Oración':'Prayer'}</option><option value="journal">{es?'Diario privado':'Private journal'}</option><option value="testimony">{es?'Testimonio':'Testimony'}</option><option value="spiritual_note">{es?'Nota espiritual':'Spiritual note'}</option></select></label><label className="field"><span>{es?'Título opcional':'Optional title'}</span><input name="title" placeholder={es?'Una oración por mi familia…':'A prayer for my family…'}/></label><label className="field"><span>{es?'Lo que quiero recordar':'What I want to remember'}</span><textarea name="body" rows={5} required/></label><div className="row" style={{gap:10,flexWrap:'wrap'}}><label className="field" style={{flex:'1 1 180px'}}><span>{es?'Fecha':'Date'}</span><input type="date" name="occurred_on" defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="field" style={{flex:'2 1 240px'}}><span>{es?'Escritura relacionada':'Related Scripture'}</span><input name="scripture_ref" placeholder="Psalm 46:1"/></label></div><label className="row small" style={{gap:8,alignItems:'flex-start'}}><input type="checkbox" name="share_with_church"/><span>{es?'Si esto es un testimonio, enviarlo para revisión antes de compartirlo con la iglesia. Las oraciones y diarios permanecen privados.':'If this is a testimony, submit it for review before sharing it with the church. Prayers and journals remain private.'}</span></label><button className="btn">{es?'Guardar en Mi Jornada':'Save to My Journey'}</button></form></details>

    <div className="row" style={{gap:8,flexWrap:'wrap',marginBottom:14}}><Link className={!params.type?'btn':'ghost'} href={l('/journey/memories')}>{es?'Todo':'All'}</Link><Link className={params.type==='prayer'?'btn':'ghost'} href={l('/journey/memories?type=prayer')}>{es?'Oraciones':'Prayers'}</Link><Link className={params.type==='journal'?'btn':'ghost'} href={l('/journey/memories?type=journal')}>{es?'Diario':'Journal'}</Link><Link className={params.type==='testimony'?'btn':'ghost'} href={l('/journey/memories?type=testimony')}>{es?'Testimonios':'Testimonies'}</Link><Link className={params.type==='spiritual_note'?'btn':'ghost'} href={l('/journey/memories?type=spiritual_note')}>{es?'Notas':'Notes'}</Link></div>

    <section style={{display:'grid',gap:12}}>{rows.map((entry:any)=><article className="card" style={{padding:18}} key={entry.id}><div className="row" style={{justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="row" style={{gap:7,flexWrap:'wrap'}}><span className="pill">{label(entry.entry_type,es).toUpperCase()}</span>{entry.entry_type==='prayer'&&<span className="pill">{entry.prayer_status==='answered'?(es?'CONTESTADA':'ANSWERED'):(es?'ORANDO':'PRAYING')}</span>}{entry.visibility==='church_share'&&<span className="pill">{es?'COMPARTIR: ':'SHARE: '}{String(entry.share_status).replaceAll('_',' ')}</span>}</div><h2 style={{margin:'8px 0 4px'}}>{entry.title||label(entry.entry_type,es)}</h2><div className="small muted">{fmt(entry.occurred_on||entry.created_at?.slice(0,10),es)}{entry.scripture_ref?` • ${entry.scripture_ref}`:''}</div></div><form action={deleteJourneyEntry}><input type="hidden" name="entry_id" value={entry.id}/><input type="hidden" name="lang" value={lang}/><button className="ghost" title={es?'Eliminar':'Delete'}><Trash2 size={14}/></button></form></div><p style={{whiteSpace:'pre-wrap',lineHeight:1.65}}>{entry.body}</p>{entry.entry_type==='prayer'&&entry.prayer_status==='answered'&&<div className="notice success" style={{marginTop:10}}><strong>{es?'Dios contestó esta oración':'Answered prayer'}{entry.answered_on?` • ${fmt(entry.answered_on,es)}`:''}</strong>{entry.answer_note&&<p style={{margin:'6px 0 0',whiteSpace:'pre-wrap'}}>{entry.answer_note}</p>}</div>}{entry.entry_type==='prayer'&&entry.prayer_status!=='answered'&&<details style={{marginTop:10}}><summary style={{cursor:'pointer',fontWeight:750}}>{es?'Marcar como oración contestada':'Mark this prayer answered'}</summary><form action={markPrayerAnswered} style={{display:'grid',gap:8,marginTop:10}}><input type="hidden" name="entry_id" value={entry.id}/><input type="hidden" name="lang" value={lang}/><label className="field"><span>{es?'Fecha contestada':'Answered date'}</span><input type="date" name="answered_on" defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="field"><span>{es?'¿Qué hizo Dios?':'What happened?'}</span><textarea name="answer_note" rows={3} placeholder={es?'Quiero recordar cómo fue contestada…':'I want to remember how this was answered…'}/></label><button className="btn"><CheckCircle2 size={14}/> {es?'Marcar contestada':'Mark answered'}</button></form></details>}</article>)}{!rows.length&&<div className="card" style={{padding:24,textAlign:'center'}}><Church size={28}/><h3>{es?'Tu historia empieza aquí.':'Your record starts here.'}</h3><p className="muted">{es?'Guarda una oración, un testimonio o algo que no quieras olvidar.':'Save a prayer, testimony, or moment you do not want to forget.'}</p></div>}</section>
  </main>
}
