import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Home,Plus,Trash2,Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { addHouseholdMember,createHousehold,deleteHousehold,removeHouseholdMember,updateHousehold,updateHouseholdMember } from './actions'

const roleOptions={
  en:[['adult','Adult'],['spouse','Spouse'],['child','Child'],['dependent','Dependent'],['other','Other']],
  es:[['adult','Adulto'],['spouse','Cónyuge'],['child','Hijo/a'],['dependent','Dependiente'],['other','Otro']]
} as const
const personName=(p:any)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Member'

export default async function HouseholdsPage({searchParams}:{searchParams:Promise<{lang?:string;error?:string;created?:string;saved?:string;member_added?:string;member_saved?:string;member_removed?:string;deleted?:string}>}){
  const query=await searchParams,lang: 'en'|'es'=query.lang==='es'?'es':'en',es=lang==='es'
  const t=(en:string,sp:string)=>es?sp:en
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect(es?'/login?lang=es':'/login')
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  let allowed=['pastor','church_admin'].includes(membership.role)
  if(!allowed){const {data}=await supabase.rpc('current_user_has_church_permission',{p_church_id:membership.church_id,p_permission_key:'manage_members'});allowed=Boolean(data)}
  if(!allowed)redirect('/')
  const churchId=membership.church_id,church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  const [{data:households},{data:householdMembers},{data:activeMembers}]=await Promise.all([
    supabase.from('households').select('id,name,notes,created_at').eq('church_id',churchId).order('name'),
    supabase.from('household_members').select('household_id,user_id,relationship_role,primary_contact,created_at').eq('church_id',churchId).order('created_at'),
    supabase.from('church_memberships').select('user_id').eq('church_id',churchId).eq('status','active')
  ])
  const ids=(activeMembers??[]).map((m:any)=>m.user_id)
  let profiles:any[]=[];if(ids.length){const {data}=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',ids);profiles=data??[]}
  const pm=new Map(profiles.map((p:any)=>[p.id,p])),assigned=new Set((householdMembers??[]).map((m:any)=>m.user_id))
  const available=ids.filter((id:string)=>!assigned.has(id)).map((id:string)=>({id,name:personName(pm.get(id))})).sort((a:any,b:any)=>a.name.localeCompare(b.name))
  const memberMap=new Map<string,any[]>();for(const row of householdMembers??[]){const list=memberMap.get((row as any).household_id)??[];list.push(row);memberMap.set((row as any).household_id,list)}
  const withLang=(href:string)=>`${href}${href.includes('?')?'&':'?'}lang=${lang}`
  const success=query.created||query.saved||query.member_added||query.member_saved||query.member_removed||query.deleted

  return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??t('Your Church','Su Iglesia')} • {t('Households','Hogares')}</div></div><div className="row"><Link className="ghost" href={`/church/households?lang=${es?'en':'es'}`}>{es?'English':'Español'}</Link><Link className="ghost" href={withLang('/church/member-records')}>← {t('Member Records','Registros')}</Link><Link className="ghost" href="/">{t('Home','Inicio')}</Link></div></header>
  <section className="hero card"><div><div className="pill"><Home size={12}/> {t('HOUSEHOLD RELATIONSHIPS','RELACIONES DEL HOGAR')}</div><h1>{t('Keep families connected without duplicating people.','Mantenga a las familias conectadas sin duplicar personas.')}</h1><p>{t('Each active member can belong to one household in this church. Household grouping helps leadership understand spouses, children and dependents while the individual member record stays authoritative.','Cada miembro activo puede pertenecer a un hogar en esta iglesia. La agrupación ayuda a entender cónyuges, hijos y dependientes mientras el registro individual sigue siendo la fuente principal.')}</p></div><div className="hero-stat"><strong>{households?.length??0}</strong><span>{t('households','hogares')}</span></div></section>
  {query.error&&<div className="notice error">{query.error}</div>}{success&&<div className="notice success">{t('Household records updated.','Registros del hogar actualizados.')}</div>}

  <div style={{display:'grid',gridTemplateColumns:'minmax(260px,340px) minmax(0,1fr)',gap:18,alignItems:'start'}}><aside className="card" style={{padding:18}}><div className="pill">{t('NEW HOUSEHOLD','NUEVO HOGAR')}</div><h2>{t('Create a household','Crear un hogar')}</h2><form action={createHousehold} style={{display:'grid',gap:10}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="lang" value={lang}/><label className="field"><span>{t('Household name','Nombre del hogar')}</span><input name="name" required placeholder={t('Kelting Household','Hogar Kelting')}/></label><label className="field"><span>{t('Leadership note (optional)','Nota de liderazgo (opcional)')}</span><textarea name="notes" rows={3}/></label><button className="btn"><Plus size={14}/> {t('Create household','Crear hogar')}</button></form><div className="notice" style={{marginTop:14}}>{available.length} {t('active members are not assigned to a household yet.','miembros activos todavía no están asignados a un hogar.')}</div></aside>

  <section style={{display:'grid',gap:14}}>{(households??[]).map((house:any)=>{const members=memberMap.get(house.id)??[];return <article className="card" style={{padding:18}} key={house.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="pill"><Users size={12}/> {members.length} {t('MEMBERS','MIEMBROS')}</div><h2 style={{margin:'7px 0'}}>{house.name}</h2>{house.notes&&<p className="small muted" style={{margin:0}}>{house.notes}</p>}</div><form action={deleteHousehold}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="household_id" value={house.id}/><input type="hidden" name="lang" value={lang}/><button className="ghost" title={t('Delete household','Eliminar hogar')}><Trash2 size={14}/></button></form></div>
    <details style={{marginTop:12}}><summary style={{cursor:'pointer',fontWeight:700}}>{t('Edit household name / note','Editar nombre / nota')}</summary><form action={updateHousehold} style={{display:'grid',gap:8,marginTop:10}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="household_id" value={house.id}/><input type="hidden" name="lang" value={lang}/><label className="field"><span>{t('Name','Nombre')}</span><input name="name" defaultValue={house.name} required/></label><label className="field"><span>{t('Note','Nota')}</span><textarea name="notes" rows={2} defaultValue={house.notes??''}/></label><button className="ghost">{t('Save household','Guardar hogar')}</button></form></details>
    <div style={{display:'grid',gap:8,marginTop:14}}>{members.map((m:any)=>{const name=personName(pm.get(m.user_id));return <div className="card" style={{padding:12}} key={m.user_id}><form action={updateHouseholdMember} style={{display:'grid',gridTemplateColumns:'minmax(160px,1fr) minmax(130px,180px) auto auto',gap:8,alignItems:'end'}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="household_id" value={house.id}/><input type="hidden" name="user_id" value={m.user_id}/><input type="hidden" name="lang" value={lang}/><div><Link href={`/church/members/${m.user_id}?lang=${lang}`} style={{fontWeight:800,textDecoration:'none'}}>{name}</Link><div className="small muted">{m.primary_contact?t('Primary household contact','Contacto principal del hogar'):t('Household member','Miembro del hogar')}</div></div><label className="field" style={{margin:0}}><span>{t('Relationship','Relación')}</span><select name="relationship_role" defaultValue={m.relationship_role}>{roleOptions[lang].map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label><label className="checkrow" style={{marginBottom:7}}><input type="checkbox" name="primary_contact" defaultChecked={m.primary_contact}/> {t('Primary','Principal')}</label><button className="ghost">{t('Save','Guardar')}</button></form><form action={removeHouseholdMember} style={{marginTop:7}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="household_id" value={house.id}/><input type="hidden" name="user_id" value={m.user_id}/><input type="hidden" name="lang" value={lang}/><button className="ghost" style={{fontSize:12}}>{t('Remove from household','Quitar del hogar')}</button></form></div>})}{!members.length&&<div className="small muted">{t('No members assigned yet.','Todavía no hay miembros asignados.')}</div>}</div>
    {available.length>0&&<form action={addHouseholdMember} className="card" style={{display:'grid',gridTemplateColumns:'minmax(180px,1fr) minmax(130px,180px) auto auto',gap:8,alignItems:'end',padding:12,marginTop:12}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="household_id" value={house.id}/><input type="hidden" name="lang" value={lang}/><label className="field" style={{margin:0}}><span>{t('Add active member','Agregar miembro activo')}</span><select name="user_id" defaultValue="" required><option value="" disabled>{t('Choose member','Seleccione miembro')}</option>{available.map((m:any)=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="field" style={{margin:0}}><span>{t('Relationship','Relación')}</span><select name="relationship_role" defaultValue="adult">{roleOptions[lang].map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label><label className="checkrow" style={{marginBottom:7}}><input type="checkbox" name="primary_contact"/> {t('Primary','Principal')}</label><button className="btn"><Plus size={13}/> {t('Add','Agregar')}</button></form>}</article>})}{!(households??[]).length&&<div className="card" style={{padding:20}}><h3>{t('No households yet.','Todavía no hay hogares.')}</h3><p className="muted">{t('Create the first household, then add active church members to it.','Cree el primer hogar y luego agregue miembros activos de la iglesia.')}</p></div>}</section></div></main>
}
