'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export function CreatePost({churchId,userId,lang='en'}:{churchId:string;userId:string;lang?:'en'|'es'}){
  const es=lang==='es',t=(en:string,sp:string)=>es?sp:en
  const [body,setBody]=useState(''),[type,setType]=useState('life_update'),[status,setStatus]=useState(''),[saving,setSaving]=useState(false)
  async function publish(){if(!body.trim())return;setSaving(true);setStatus('');const supabase=createClient();const {error}=await supabase.from('community_posts').insert({church_id:churchId,author_id:userId,body:body.trim(),post_type:type,visibility:'church'});if(error)setStatus(error.message);else{setBody('');setStatus(t('Posted! Refreshing…','¡Publicado! Actualizando…'));window.location.reload()}setSaving(false)}
  return <div className="card composer"><div className="row" style={{justifyContent:'space-between'}}><h2 className="section-title">{t('Share with your church','Comparte con tu iglesia')}</h2><select value={type} onChange={e=>setType(e.target.value)}><option value="life_update">{t('Life update','Actualización personal')}</option><option value="prayer_request">{t('Prayer request','Petición de oración')}</option><option value="testimony">{t('Testimony','Testimonio')}</option><option value="encouragement">{t('Encouragement','Ánimo')}</option></select></div><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={t('Share what’s happening, encourage someone, or tell your church what God is doing…','Comparte lo que está pasando, anima a alguien o cuéntale a tu iglesia lo que Dios está haciendo…')}/><div className="row" style={{marginTop:10,justifyContent:'space-between'}}><span className="small muted">{t('Visible to signed-in members of your church.','Visible para miembros de tu iglesia que hayan iniciado sesión.')}</span><button className="btn" onClick={publish} disabled={saving}>{saving?t('Posting…','Publicando…'):t('Post','Publicar')}</button></div>{status&&<div className="small" style={{marginTop:8}}>{status}</div>}</div>
}