'use client'

import { useEffect,useMemo,useState } from 'react'
import { usePathname,useSearchParams } from 'next/navigation'
import { HelpCircle,X } from 'lucide-react'
import styles from './page-guide.module.css'

type Guide={title:string;body:string;tips:string[]}
type Pair={en:Guide;es:Guide}

const g=(title:string,body:string,tips:string[],titulo:string,cuerpo:string,consejos:string[]):Pair=>({en:{title,body,tips},es:{title:titulo,body:cuerpo,tips:consejos}})
const guides:Record<string,Pair>={
 '/':g('Home','This is your everyday starting point. See what matters now, your next step, upcoming events and church updates.',['Start with My Today when you want a simple daily view.','Use My Next Step when you are not sure what to do next.'],'Inicio','Este es tu punto de partida diario. Mira lo importante ahora, tu próximo paso, próximos eventos y actualizaciones de la iglesia.',['Comienza con Mi Día cuando quieras una vista sencilla de hoy.','Usa Mi Próximo Paso cuando no sepas qué hacer después.']),
 '/learning':g('Learning Center','Take church classes, continue courses you already started and track your progress.',['Open a course to see lessons, sessions and assessments.','Your completed work connects back to My Journey.'],'Centro de Aprendizaje','Toma clases de la iglesia, continúa cursos que ya empezaste y sigue tu progreso.',['Abre un curso para ver lecciones, sesiones y evaluaciones.','Tu trabajo completado se refleja en Mi Jornada.']),
 '/journey':g('My Journey','See your spiritual milestones, discipleship progress and the next step in your walk with God.',['This page shows where you are, not just what classes exist.','Use the recommended next step when you are unsure where to begin.'],'Mi Jornada','Mira tus pasos espirituales, progreso de discipulado y el próximo paso en tu caminar con Dios.',['Esta página muestra dónde estás, no solo qué clases existen.','Usa el próximo paso recomendado cuando no sepas por dónde comenzar.']),
 '/today':g('My Today','This is the simple daily screen for assignments, classes, alerts and what needs your attention now.',['Start here when you only have a minute.','Items here should point you directly to the page where you can act.'],'Mi Día','Esta es la pantalla diaria sencilla para asignaciones, clases, alertas y lo que necesita tu atención ahora.',['Empieza aquí cuando solo tengas un minuto.','Cada elemento debe llevarte directamente al lugar donde puedes actuar.']),
 '/groups':g('Friendship Groups','Find your Friendship Group, meeting information and the people you are growing with.',['Open a group to see its details and current activity.','If you are not in a group yet, use this page to find the right one.'],'Grupos de Amistad','Encuentra tu Grupo de Amistad, información de reuniones y las personas con quienes estás creciendo.',['Abre un grupo para ver sus detalles y actividad actual.','Si todavía no estás en un grupo, usa esta página para encontrar el indicado.']),
 '/calendar':g('Calendar','See services, classes, meetings and church events in one place.',['Use the calendar to see what is coming next.','Events connected to you should be the easiest to spot.'],'Calendario','Mira servicios, clases, reuniones y eventos de la iglesia en un solo lugar.',['Usa el calendario para ver lo que viene después.','Los eventos relacionados contigo deben ser los más fáciles de identificar.']),
 '/guide':g('Kingdom Guide','Ask for help finding something, understanding what to do next or locating trusted church resources.',['Ask in plain language.','Use it whenever you are unsure which tab you need.'],'Kingdom Guide','Pide ayuda para encontrar algo, entender qué hacer después o localizar recursos confiables de la iglesia.',['Pregunta con palabras sencillas.','Úsalo cuando no sepas qué sección necesitas.']),
 '/prayer':g('Prayer & Testimony','Share prayer needs, celebrate testimonies and encourage your church family.',['Choose the appropriate privacy level before sharing.','Private pastoral-care needs belong in Private Care.'],'Oración y Testimonio','Comparte necesidades de oración, celebra testimonios y anima a tu familia de iglesia.',['Elige el nivel de privacidad correcto antes de compartir.','Las necesidades pastorales privadas van en Cuidado Privado.']),
 '/messages':g('Messages','Have private conversations with people you are connected to in Kingdom Network.',['Use this for direct conversation, not official church announcements.','Report anything inappropriate instead of engaging with it.'],'Mensajes','Ten conversaciones privadas con personas conectadas contigo en Kingdom Network.',['Usa esto para conversaciones directas, no para anuncios oficiales.','Reporta cualquier contenido inapropiado en vez de responderle.']),
 '/serve':g('Serve','Explore ministries, see what each team does and learn what is required before you serve.',['This is the place to discover where you can help.','Kingdom Network can show what training or steps you still need.'],'Servir','Explora ministerios, mira lo que hace cada equipo y aprende lo que necesitas antes de servir.',['Aquí puedes descubrir dónde puedes ayudar.','Kingdom Network puede mostrarte qué entrenamiento o pasos te faltan.']),
 '/teams':g('Teams','See ministry teams you already belong to, upcoming assignments and team responsibilities.',['Serve is for discovering ministries; Teams is for active team members.','Check assignments here before services and events.'],'Equipos','Mira los equipos donde ya sirves, próximas asignaciones y responsabilidades.',['Servir es para descubrir ministerios; Equipos es para miembros activos.','Revisa tus asignaciones aquí antes de servicios y eventos.']),
 '/outreach':g('Outreach','Keep track of guests, Bible studies, follow-up and evangelism connections.',['Use follow-up dates so people do not get forgotten.','Keep sensitive notes limited to the people who need them.'],'Evangelismo','Da seguimiento a invitados, estudios bíblicos, seguimiento y conexiones de evangelismo.',['Usa fechas de seguimiento para que nadie sea olvidado.','Mantén notas sensibles limitadas a quienes realmente las necesitan.']),
 '/documents':g('Documents','Keep important church certificates and verified records in your personal document vault.',['Use this for certificates and official records.','Only you and properly authorized leaders should see private documents.'],'Documentos','Guarda certificados importantes y registros verificados de la iglesia en tu archivo personal.',['Usa esto para certificados y registros oficiales.','Solo tú y líderes autorizados deben ver documentos privados.']),
 '/directory':g('Directory','Find people and approved directory information within your church community.',['Only information a person has chosen to share should appear here.','Use Messages when you want to contact someone privately.'],'Directorio','Encuentra personas e información aprobada dentro de tu comunidad de iglesia.',['Solo debe aparecer la información que una persona decidió compartir.','Usa Mensajes cuando quieras contactar a alguien en privado.']),
 '/updates':g('Official Updates','Read official church and leadership announcements without mixing them into the member community feed.',['Look here for information coming from church leadership.','Community conversation belongs on the Home feed.'],'Actualizaciones Oficiales','Lee anuncios oficiales de la iglesia y liderazgo sin mezclarlos con la comunidad de miembros.',['Busca aquí información que viene del liderazgo de la iglesia.','La conversación de la comunidad pertenece al feed de Inicio.']),
 '/help':g('Private Care','Send a private prayer, pastoral-care or support request to the appropriate church leaders.',['Use this when the matter should not be public.','Explain what kind of help you need so it reaches the right person.'],'Cuidado Privado','Envía una solicitud privada de oración, cuidado pastoral o apoyo a los líderes apropiados.',['Usa esto cuando el asunto no debe ser público.','Explica qué tipo de ayuda necesitas para que llegue a la persona correcta.']),
 '/resources':g('Resources','Find reusable church materials, teaching resources and other helpful files.',['Use search or categories when the library grows.','Save commonly used materials so they are easy to find again.'],'Recursos','Encuentra materiales reutilizables de la iglesia, recursos de enseñanza y otros archivos útiles.',['Usa búsqueda o categorías cuando la biblioteca crezca.','Guarda materiales de uso frecuente para encontrarlos fácilmente después.']),
 '/profile':g('Profile','Keep your basic information, photo and the information you choose to share with your church community up to date.',['Start by checking your name and contact information.','Review privacy settings before sharing directory information.'],'Perfil','Mantén actualizados tus datos básicos, foto y la información que eliges compartir con tu comunidad de iglesia.',['Comienza revisando tu nombre e información de contacto.','Revisa la privacidad antes de compartir información en el directorio.'])
}

export function PageGuide(){
 const pathname=usePathname(),search=useSearchParams(),lang=search.get('lang')==='es'?'es':'en'
 const guide=useMemo(()=>{const pair=Object.entries(guides).filter(([path])=>path==='/'?pathname==='/':pathname===path||pathname.startsWith(path+'/')).sort((a,b)=>b[0].length-a[0].length)[0]?.[1];return pair?.[lang]},[pathname,lang])
 const [open,setOpen]=useState(false)
 useEffect(()=>{if(!guide)return;const key=`kingdom-network:page-guide:${pathname.split('/').slice(0,2).join('/')||'/'}`;if(window.localStorage.getItem(key)!=='seen')setOpen(true)},[guide,pathname])
 if(!guide)return null
 const key=`kingdom-network:page-guide:${pathname.split('/').slice(0,2).join('/')||'/'}`
 const dismiss=()=>{window.localStorage.setItem(key,'seen');setOpen(false)}
 const text=lang==='es'?{eyebrow:'GUÍA DE PRIMERA VISITA',done:'Entendido — muéstrame la página',help:'Cómo funciona esta página',close:'Cerrar guía'}:{eyebrow:'FIRST-TIME GUIDE',done:'Got it — show me the page',help:'How this page works',close:'Close page guide'}
 return <>{open&&<div className={styles.backdrop} onClick={dismiss}><section className={styles.sheet} role="dialog" aria-modal="true" aria-labelledby="page-guide-title" onClick={e=>e.stopPropagation()}><div className={styles.head}><div><div className={styles.eyebrow}>{text.eyebrow}</div><h2 id="page-guide-title">{guide.title}</h2></div><button className={styles.close} onClick={dismiss} aria-label={text.close}><X size={18}/></button></div><p className={styles.body}>{guide.body}</p><div className={styles.tips}>{guide.tips.map((tip,index)=><div className={styles.tip} key={tip}><span>{index+1}</span><p>{tip}</p></div>)}</div><button className={styles.done} onClick={dismiss}>{text.done}</button></section></div>}{!open&&<button className={styles.help} onClick={()=>setOpen(true)} aria-label={`${text.help}: ${guide.title}`}><HelpCircle size={18}/><span>{text.help}</span></button>}</>
}
