import Link from 'next/link'
import { redirect } from 'next/navigation'
import { MailPlus,ShieldCheck,UserPlus } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { createKnownPersonInvite } from './actions'
import { CopyKnownInvite } from './copy-invite'

const siteUrl=(process.env.NEXT_PUBLIC_SITE_URL||'https://kingdom-network.vercel.app').replace(/\/$/,'')

export default async function InvitePersonPage({searchParams}:{searchParams:Promise<{lang?:string;created?:string;error?:string}>}){
  const params=await searchParams,es=params.lang==='es',lang=es?'es':'en'
  const l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
  const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const {data:custom}=await supabase.rpc('current_user_has_church_permission',{p_church_id:membership.church_id,p_permission_key:'manage_members'})
  const canInvite=['pastor','church_admin'].includes(membership.role)||Boolean(custom)
  if(!canInvite)redirect('/')
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  let invite:any=null
  if(params.created){const r=await supabase.from('church_invites').select('id,email,first_name,last_name,phone,role,expires_at').eq('id',params.created).eq('church_id',membership.church_id).maybeSingle();invite=r.data}
  const inviteUrl=invite?`${siteUrl}/login?invite=${encodeURIComponent(invite.id)}&lang=${lang}`:''
  const roleOptions=membership.role==='pastor'?[['member',es?'Acceso estándar':'Standard access'],['group_leader',es?'Líder de grupo':'Group leader'],['ministry_leader',es?'Líder de ministerio':'Ministry leader'],['minister',es?'Ministro':'Minister'],['church_admin',es?'Administrador de iglesia':'Church admin'],['pastor',es?'Pastor':'Pastor']]:['pastor','church_admin'].includes(membership.role)?[['member',es?'Acceso estándar':'Standard access'],['group_leader',es?'Líder de grupo':'Group leader'],['ministry_leader',es?'Líder de ministerio':'Ministry leader'],['minister',es?'Ministro':'Minister']]:[['member',es?'Acceso estándar':'Standard access']]
  return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Church'} • {es?'Invitar Persona':'Invite Person'}</div></div><div className="row"><Link className="ghost" href="/church/invite-person?lang=en">English</Link><Link className="ghost" href="/church/invite-person?lang=es">Español</Link><Link className="ghost" href={l('/church/join-center')}>{es?'Centro de Ingreso':'Join Center'}</Link><Link className="ghost" href="/">{es?'← Inicio':'← Home'}</Link></div></header>
  <section className="card" style={{padding:24,marginBottom:18}}><div className="pill">{es?'INVITACIÓN PRIVADA':'PRIVATE INVITATION'}</div><h1>{es?'Para alguien que liderazgo ya conoce.':'For someone leadership already knows.'}</h1><p className="muted">{es?'Agrega suficiente información para identificar bien a la persona y crear un enlace seguro de siete días. Para invitados generales, usa el QR público en el Centro de Ingreso.':'Add enough information to identify the person and create a secure seven-day link. For general guests, use the public QR in Join Center.'}</p></section>
  {params.error&&<div className="notice error">{params.error}</div>}
  {invite&&<section className="card" style={{padding:20,marginBottom:18,border:'1px solid rgba(34,197,94,.35)'}}><div className="pill">{es?'INVITACIÓN LISTA':'INVITATION READY'}</div><h2>{[invite.first_name,invite.last_name].filter(Boolean).join(' ')||invite.email}</h2><div className="small muted">{invite.email}{invite.phone?` • ${invite.phone}`:''} • {es?'vence':'expires'} ${new Date(invite.expires_at).toLocaleString()}</div><div className="small muted" style={{wordBreak:'break-all',margin:'12px 0'}}>{inviteUrl}</div><CopyKnownInvite url={inviteUrl} label={es?'Copiar invitación':'Copy invitation'}/></section>}
  <form action={createKnownPersonInvite} className="card" style={{padding:20,display:'grid',gap:10}}><input type="hidden" name="lang" value={lang}/><div className="row" style={{gap:10,flexWrap:'wrap'}}><label className="field" style={{flex:'1 1 180px'}}><span>{es?'Nombre':'First name'}</span><input name="first_name" autoComplete="given-name"/></label><label className="field" style={{flex:'1 1 180px'}}><span>{es?'Apellido':'Last name'}</span><input name="last_name" autoComplete="family-name"/></label></div><label className="field"><span>{es?'Teléfono':'Phone'}</span><input name="phone" type="tel" autoComplete="tel"/></label><label className="field"><span>{es?'Correo electrónico':'Email'}</span><input name="email" type="email" autoComplete="email" required/></label><label className="field"><span>{es?'Acceso inicial':'Starting access'}</span><select name="role" defaultValue="member">{roleOptions.map(([v,label])=><option value={v} key={v}>{label}</option>)}</select><small className="muted">{es?'El acceso no es lo mismo que la relación con la iglesia. La persona invitada entra como Miembro formal solamente por esta ruta privada aprobada.':'Access is separate from church relationship. A person invited through this approved private route enters as a formal Member.'}</small></label><div className="notice"><ShieldCheck size={14}/><span>{es?'Los líderes de registros pueden invitar acceso estándar. Pastor/Admin controlan el acceso de liderazgo; solamente un Pastor puede preasignar Pastor/Admin.':'Records leaders can invite standard access. Pastor/Admin control leadership access; only a Pastor can preassign Pastor/Admin.'}</span></div><button className="btn" type="submit"><UserPlus size={14}/> {es?'Crear invitación':'Create invitation'}</button></form>
  <section className="card" style={{padding:16,marginTop:16}}><div className="row" style={{gap:9,alignItems:'flex-start'}}><MailPlus size={17}/><div><strong>{es?'Entrega manual por ahora':'Manual delivery for now'}</strong><div className="small muted">{es?'Copia el enlace y envíalo por texto o correo. Más adelante Kingdom Network podrá entregar invitaciones automáticamente cuando el proveedor externo esté completamente conectado.':'Copy the link and send it by text or email. Later Kingdom Network can deliver invitations automatically when the external provider is fully connected.'}</div></div></div></section>
  </main>
}