import { CheckCircle2,ClipboardList,Plane } from 'lucide-react'
import { createMemberTask,setMemberTaskStatus,submitTimeOff } from '../actions'
import { formatChurchDate,formatChurchTime } from '@/lib/church-time'

export function PersonalPlanning({churchId,tasks,timeOff,lang,timeZone}:{churchId:string;tasks:any[];timeOff:any[];lang:'en'|'es';timeZone:string}){
  const es=lang==='es'
  return <div style={{display:'grid',gap:18,marginBottom:18}}>
    <section className="card" style={{padding:18}}><div className="pill"><ClipboardList size={11}/> {es?'MIS TAREAS':'MY TASKS'}</div><h2 style={{margin:'8px 0 4px'}}>{es?'Lo que necesito terminar':'What I need to finish'}</h2><p className="small muted" style={{marginTop:0}}>{es?'Las tareas personales y las asignadas por líderes aparecen juntas aquí.':'Personal tasks and leader-assigned tasks stay together here.'}</p>
      <div style={{display:'grid',gap:8,margin:'12px 0'}}>{tasks.map(task=><article className="notice" style={{margin:0}} key={task.id}><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start',gap:10}}><div><strong>{task.title}</strong><div className="small muted">{task.priority==='high'?(es?'Alta prioridad':'High priority'):task.priority==='low'?(es?'Baja prioridad':'Low priority'):(es?'Prioridad normal':'Normal priority')}{task.due_at?` • ${formatChurchDate(task.due_at,timeZone,{month:'short',day:'numeric'})} ${formatChurchTime(task.due_at,timeZone)}`:''}</div>{task.notes&&<div className="small" style={{marginTop:4}}>{task.notes}</div>}</div><form action={setMemberTaskStatus}><input type="hidden" name="task_id" value={task.id}/><input type="hidden" name="status" value="completed"/><input type="hidden" name="back" value="/calendar/my"/><input type="hidden" name="lang" value={lang}/><button className="ghost"><CheckCircle2 size={13}/> {es?'Terminar':'Complete'}</button></form></div></article>)}{!tasks.length&&<p className="muted">{es?'No tienes tareas abiertas.':'No open tasks.'}</p>}</div>
      <details><summary style={{cursor:'pointer',fontWeight:800}}>{es?'+ Agregar tarea personal':'+ Add personal task'}</summary><form action={createMemberTask} style={{display:'grid',gap:10,marginTop:12}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="back" value="/calendar/my"/><input type="hidden" name="lang" value={lang}/><label className="field"><span>{es?'Tarea':'Task'}</span><input name="title" required maxLength={180}/></label><div className="report-grid"><label className="field"><span>{es?'Fecha límite':'Due'}</span><input type="datetime-local" name="due_at"/></label><label className="field"><span>{es?'Prioridad':'Priority'}</span><select name="priority" defaultValue="normal"><option value="low">{es?'Baja':'Low'}</option><option value="normal">{es?'Normal':'Normal'}</option><option value="high">{es?'Alta':'High'}</option></select></label></div><label className="field"><span>{es?'Notas':'Notes'}</span><textarea name="notes" rows={2}/></label><button className="btn">{es?'Guardar tarea':'Save task'}</button></form></details>
    </section>

    <section className="card" style={{padding:18}}><div className="pill"><Plane size={11}/> {es?'TIEMPO NO DISPONIBLE':'TIME OFF / UNAVAILABLE'}</div><h2 style={{margin:'8px 0 4px'}}>{es?'Avísale a tus líderes antes de programar':'Let leaders know before scheduling'}</h2><p className="small muted" style={{marginTop:0}}>{es?'Registra vacaciones u otras fechas en las que no puedes servir.':'Record vacations or other dates when you cannot serve.'}</p>
      <div style={{display:'grid',gap:7,margin:'12px 0'}}>{timeOff.map(r=><div className="notice" style={{margin:0}} key={r.id}><strong>{r.starts_on===r.ends_on?r.starts_on:`${r.starts_on} → ${r.ends_on}`}</strong> • <span>{r.status}</span>{r.notes&&<div className="small muted">{r.notes}</div>}</div>)}{!timeOff.length&&<p className="muted">{es?'No tienes fechas registradas.':'No unavailable dates submitted.'}</p>}</div>
      <details><summary style={{cursor:'pointer',fontWeight:800}}>{es?'+ Agregar fechas no disponibles':'+ Add unavailable dates'}</summary><form action={submitTimeOff} style={{display:'grid',gap:10,marginTop:12}}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="back" value="/calendar/my"/><input type="hidden" name="lang" value={lang}/><div className="report-grid"><label className="field"><span>{es?'Desde':'From'}</span><input type="date" name="starts_on" required/></label><label className="field"><span>{es?'Hasta':'Through'}</span><input type="date" name="ends_on" required/></label></div><label className="field"><span>{es?'Nota opcional':'Optional note'}</span><textarea name="notes" rows={2}/></label><button className="btn">{es?'Enviar fechas':'Submit dates'}</button></form></details>
    </section>
  </div>
}