import Link from 'next/link'
import { redirect } from 'next/navigation'
import { AlertTriangle,BellRing,Megaphone,Pin,ShieldCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { formatChurchDate } from '@/lib/church-time'
import { createOfficialUpdate,deleteOfficialUpdate,expireOfficialUpdate,toggleOfficialUpdatePin } from './actions'
import './updates.css'

const copy={
  en:{page:'Official Updates',hero:'Church updates from leadership.',body:'Pastoral notes, service changes, training announcements and important church information stay separate from the Community feed.',active:'ACTIVE',latest:'Latest church updates',latestHelp:'Pinned and urgent updates stay easy to find.',none:'No active official updates.',noneBody:'Leadership announcements will appear here.',published:'Published',by:'By',expires:'Expires',expired:'Expired',pinned:'Pinned',leadership:'Leadership Tools',publish:'Publish official update',publishHelp:'Create an official church update only when members should recognize it as leadership communication.',title:'Title',type:'Update type',priority:'Priority',expiration:'Expires',message:'Message',pin:'Pin this update near the top',notify:'Notify every active member in-app',notifyHelp:'Use alerts for service changes, urgent notices and information people should not miss. Normal announcements can stay quiet.',publishButton:'Publish update',history:'Expired update history',historyHelp:'Older updates stay available to leadership without crowding the member view.',unpin:'Unpin',pinAction:'Pin',expireNow:'Expire now',delete:'Delete permanently',created:'Official update published.',saved:'Official update changed.',expiredMsg:'Official update expired.',deleted:'Official update permanently deleted.',home:'← Home',leadershipBadge:'Leadership'},
  es:{page:'Actualizaciones Oficiales',hero:'Actualizaciones de la iglesia por el liderazgo.',body:'Notas pastorales, cambios de servicio, anuncios de capacitación e información importante se mantienen separados del muro de la comunidad.',active:'ACTIVAS',latest:'Últimas actualizaciones de la iglesia',latestHelp:'Las actualizaciones fijadas y urgentes son fáciles de encontrar.',none:'No hay actualizaciones oficiales activas.',noneBody:'Los anuncios del liderazgo aparecerán aquí.',published:'Publicado',by:'Por',expires:'Vence',expired:'Vencida',pinned:'Fijada',leadership:'Herramientas de Liderazgo',publish:'Publicar actualización oficial',publishHelp:'Crea una actualización oficial solo cuando los miembros deban reconocerla como comunicación del liderazgo.',title:'Título',type:'Tipo de actualización',priority:'Prioridad',expiration:'Vence',message:'Mensaje',pin:'Fijar esta actualización cerca de la parte superior',notify:'Notificar a todos los miembros activos en la aplicación',notifyHelp:'Usa alertas para cambios de servicio, avisos urgentes e información que la gente no debe perder. Los anuncios normales pueden quedarse sin alerta.',publishButton:'Publicar actualización',history:'Historial de actualizaciones vencidas',historyHelp:'Las actualizaciones anteriores siguen disponibles para liderazgo sin llenar la vista del miembro.',unpin:'Quitar fijación',pinAction:'Fijar',expireNow:'Vencer ahora',delete:'Eliminar permanentemente',created:'Actualización oficial publicada.',saved:'Actualización oficial cambiada.',expiredMsg:'Actualización oficial vencida.',deleted:'Actualización oficial eliminada permanentemente.',home:'← Inicio',leadershipBadge:'Liderazgo'}
} as const

const typeLabels={
  en:{announcement:'Announcement',pastoral:'Pastoral',service_change:'Service change',event:'Event',training:'Training',district:'District',urgent:'Urgent'},
  es:{announcement:'Anuncio',pastoral:'Pastoral',service_change:'Cambio de servicio',event:'Evento',training:'Capacitación',district:'Distrito',urgent:'Urgente'}
} as const
const priorityLabels={en:{normal:'Normal',important:'Important',urgent:'Urgent'},es:{normal:'Normal',important:'Importante',urgent:'Urgente'}} as const
const personName=(p:any,fallback:string)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||fallback

export default async function UpdatesPage({searchParams}:{searchParams:Promise<{created?:string;saved?:string;expired?:string;deleted?:string;error?:string;lang?:string}>}){
  const query=await searchParams,lang:'en'|'es'=query.lang==='es'?'es':'en',t=copy[lang]
  const withLang=(href:string)=>lang==='es'?`${href}${href.includes('?')?'&':'?'}lang=es`:href
  const supabase=await createClient()
  const {data:claims}=await supabase.auth.getClaims()
  const userId=claims?.claims?.sub
  if(!userId)redirect(lang==='es'?'/login?lang=es':'/login')
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name,timezone)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect(withLang('/'))
  const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches
  const timeZone=church?.timezone||'UTC'
  const canManage=['minister','pastor','church_admin'].includes(membership.role)
  const canDelete=['pastor','church_admin'].includes(membership.role)
  const {data:updates}=await supabase.from('official_updates').select('id,title,body,update_type,priority,pinned,published_at,expires_at,created_by').eq('church_id',membership.church_id).order('pinned',{ascending:false}).order('published_at',{ascending:false}).limit(150)
  const authorIds=Array.from(new Set((updates??[]).map((u:any)=>u.created_by).filter(Boolean)))
  let profiles:any[]=[]
  if(authorIds.length){const r=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',authorIds);profiles=r.data??[]}
  const pm=new Map(profiles.map((p:any)=>[p.id,p]))
  const now=Date.now()
  const active=(updates??[]).filter((u:any)=>!u.expires_at||new Date(u.expires_at).getTime()>now)
  const history=canManage?(updates??[]).filter((u:any)=>u.expires_at&&new Date(u.expires_at).getTime()<=now):[]
  const stamp=(v:string)=>formatChurchDate(v,timeZone,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})
  const fallbackName=lang==='es'?'Liderazgo de la iglesia':'Church leadership'

  const card=(u:any,isExpired=false)=><article className={`card update-card ${u.priority} ${isExpired?'update-expired':''}`} key={u.id}><div className="update-head"><div className="update-title"><div className="update-tags"><span className="update-tag">{(typeLabels[lang] as any)[u.update_type]??u.update_type}</span><span className={`update-tag ${u.priority}`}>{(priorityLabels[lang] as any)[u.priority]??u.priority}</span>{u.pinned&&<span className="update-tag pinned"><Pin size={9}/> {t.pinned}</span>}{isExpired&&<span className="update-tag">{t.expired}</span>}</div><h2>{u.title}</h2><p>{u.body}</p></div>{u.priority==='urgent'?<AlertTriangle size={21}/>:u.pinned?<Pin size={19}/>:<Megaphone size={19}/>}</div><div className="update-meta"><span>{t.published} {stamp(u.published_at)}</span><span>{t.by} {personName(pm.get(u.created_by),fallbackName)}</span>{u.expires_at&&<span>{isExpired?t.expired:t.expires} {stamp(u.expires_at)}</span>}</div>{canManage&&!isExpired&&<details style={{marginTop:10}}><summary className="small" style={{cursor:'pointer',fontWeight:800}}>{t.leadership}</summary><div className="update-actions" style={{marginTop:8}}><form action={toggleOfficialUpdatePin}><input type="hidden" name="lang" value={lang}/><input type="hidden" name="update_id" value={u.id}/><input type="hidden" name="pinned" value={u.pinned?'0':'1'}/><button className="ghost">{u.pinned?t.unpin:t.pinAction}</button></form><form action={expireOfficialUpdate}><input type="hidden" name="lang" value={lang}/><input type="hidden" name="update_id" value={u.id}/><button className="ghost">{t.expireNow}</button></form>{canDelete&&<form action={deleteOfficialUpdate}><input type="hidden" name="lang" value={lang}/><input type="hidden" name="update_id" value={u.id}/><button className="ghost">{t.delete}</button></form>}</div></details>}{canDelete&&isExpired&&<form action={deleteOfficialUpdate} style={{marginTop:10}}><input type="hidden" name="lang" value={lang}/><input type="hidden" name="update_id" value={u.id}/><button className="ghost">{t.delete}</button></form>}</article>

  return <main className="shell">
    <header className="topbar"><div><Link href={withLang('/')} className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??(lang==='es'?'Tu Iglesia':'Your Church')} • {t.page}</div></div><div className="row"><Link className="ghost" href="/updates?lang=en">English</Link><Link className="ghost" href="/updates?lang=es">Español</Link>{canManage&&<span className="ghost"><ShieldCheck size={13}/> {t.leadershipBadge}</span>}<Link className="ghost" href={withLang('/')}>{t.home}</Link></div></header>
    <section className="updates-hero card"><div><div className="pill">{t.page.toUpperCase()}</div><h1>{t.hero}</h1><p className="muted">{t.body}</p></div><div className="admin-badge"><BellRing size={22}/><div><strong>{active.length}</strong><span>{lang==='es'?(active.length===1?'actualización activa':'actualizaciones activas'):`active update${active.length===1?'':'s'}`}</span></div></div></section>
    {query.created&&<div className="notice success">{t.created}</div>}{query.saved&&<div className="notice success">{t.saved}</div>}{query.expired&&<div className="notice success">{t.expiredMsg}</div>}{query.deleted&&<div className="notice success">{t.deleted}</div>}{query.error&&<div className="notice error">{query.error}</div>}

    <section><div className="section-heading"><div><div className="pill">{t.active}</div><h2>{t.latest}</h2></div><span className="small muted">{t.latestHelp}</span></div><div className="updates-list">{active.map(u=>card(u))}{!active.length&&<div className="card update-empty"><Megaphone/><h3>{t.none}</h3><p className="muted">{t.noneBody}</p></div>}</div></section>

    {canManage&&<details className="card" style={{marginTop:18,padding:16}}><summary style={{cursor:'pointer',fontWeight:800}}>{t.leadership} — {t.publish}</summary><p className="small muted">{t.publishHelp}</p><form action={createOfficialUpdate} className="update-form"><input type="hidden" name="lang" value={lang}/><label><span>{t.title}</span><input name="title" required maxLength={180} placeholder={lang==='es'?'Primeros Pasos comienza el 1 de octubre':'First Steps begins October 1'}/></label><label><span>{t.type}</span><select name="update_type" defaultValue="announcement"><option value="announcement">{typeLabels[lang].announcement}</option><option value="pastoral">{typeLabels[lang].pastoral}</option><option value="service_change">{typeLabels[lang].service_change}</option><option value="event">{typeLabels[lang].event}</option><option value="training">{typeLabels[lang].training}</option><option value="district">{typeLabels[lang].district}</option><option value="urgent">{typeLabels[lang].urgent}</option></select></label><label><span>{t.priority}</span><select name="priority" defaultValue="normal"><option value="normal">{priorityLabels[lang].normal}</option><option value="important">{priorityLabels[lang].important}</option><option value="urgent">{priorityLabels[lang].urgent}</option></select></label><label><span>{t.expiration}</span><input name="expires_at" type="datetime-local"/></label><label><span>{t.message}</span><textarea name="body" rows={7} required maxLength={5000} placeholder={lang==='es'?'Escribe el anuncio de la iglesia…':'Write the church announcement…'}/></label><label className="update-check"><input name="pinned" type="checkbox"/><span>{t.pin}</span></label><label className="update-check"><input name="notify_members" type="checkbox"/><span>{t.notify}</span></label><p className="small muted">{t.notifyHelp}</p><button className="btn">{t.publishButton}</button></form></details>}

    {canManage&&history.length>0&&<details className="card" style={{marginTop:18,padding:16}}><summary style={{cursor:'pointer',fontWeight:800}}>{t.history} ({history.length})</summary><p className="small muted">{t.historyHelp}</p><div className="updates-list" style={{marginTop:12}}>{history.map(u=>card(u,true))}</div></details>}
  </main>
}
