import Link from 'next/link'
import { redirect } from 'next/navigation'
import {Archive,ClipboardList,Eye,EyeOff,PlusCircle,Workflow} from 'lucide-react'
import {createClient} from '@/lib/supabase/server'
import {createChurchForm,createWorkflowTemplate,setChurchFormState,updateChurchForm} from './actions'

const lines=(schema:any)=>Array.isArray(schema)?schema.map((f:any)=>`${f.label} | ${f.type||'text'} | ${f.required?'required':'optional'}${Array.isArray(f.options)&&f.options.length?` | ${f.options.join(', ')}`:''}`).join('\n'):''

export default async function ChurchFormsPage({searchParams}:{searchParams:Promise<{edit?:string;saved?:string;error?:string}>}){
 const q=await searchParams,supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect('/login')
 const {data:m}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!m?.church_id)redirect('/')
 const {data:permission}=await supabase.rpc('current_user_has_church_permission',{p_church_id:m.church_id,p_permission_key:'manage_members'});if(!['pastor','church_admin'].includes(m.role)&&!permission)redirect('/')
 const [{data:forms},{data:workflows}]=await Promise.all([supabase.from('church_forms').select('*').eq('church_id',m.church_id).order('created_at',{ascending:false}),supabase.from('church_workflow_templates').select('*').eq('church_id',m.church_id).order('name')])
 const editing=(forms??[]).find((f:any)=>f.id===q.edit),church:any=Array.isArray(m.churches)?m.churches[0]:m.churches
 return <main className="shell"><header className="topbar"><div><Link href="/church" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name||'Church'} • Forms & Workflows</div></div><div className="row"><Link className="ghost" href="/church/inbox">Work Inbox</Link><Link className="ghost" href="/forms">Member Forms</Link><Link className="ghost" href="/church">← Admin</Link></div></header>
 <section className="hero card"><div><div className="pill"><ClipboardList size={12}/> FORMS & WORKFLOWS</div><h1>Build church forms without code.</h1><p>Create a simple form, connect a reusable workflow, publish it, and let Kingdom Network keep the submission owner, status, next action and due date together.</p></div><div className="hero-stat"><strong>{(forms??[]).filter((f:any)=>f.published&&!f.archived_at).length}</strong><span>published forms</span></div></section>
 {q.saved&&<div className="notice success">{q.saved}</div>}{q.error&&<div className="notice error">{q.error}</div>}
 <section style={{display:'grid',gridTemplateColumns:'minmax(300px,420px) 1fr',gap:18,alignItems:'start'}}><aside style={{display:'grid',gap:16}}><section className="card" style={{padding:18}}><div className="pill"><Workflow size={12}/> WORKFLOW TEMPLATE</div><h2>Save a repeatable process</h2><form action={createWorkflowTemplate} style={{display:'grid',gap:9}}><label className="field"><span>Name</span><input name="name" required placeholder="Member request review"/></label><label className="field"><span>Description</span><input name="description"/></label><label className="field"><span>Starting status</span><select name="default_status" defaultValue="new"><option value="new">New</option><option value="in_review">In review</option><option value="approved">Approved</option></select></label><label className="field"><span>Default next action</span><input name="default_next_action" placeholder="Review and contact person"/></label><label className="field"><span>Due in days</span><input name="due_days" type="number" min="0" max="365" placeholder="3"/></label><button className="ghost"><PlusCircle size={13}/> Save workflow template</button></form></section>
 <section className="card" style={{padding:18}}><div className="pill">{editing?'EDIT FORM':'NEW FORM'}</div><h2>{editing?'Update this form':'Create a draft'}</h2><form action={editing?updateChurchForm:createChurchForm} style={{display:'grid',gap:9}}>{editing&&<input type="hidden" name="form_id" value={editing.id}/>}<label className="field"><span>Title</span><input name="title" defaultValue={editing?.title||''} required/></label><label className="field"><span>Description</span><textarea name="description" rows={3} defaultValue={editing?.description||''}/></label><label className="field"><span>Workflow</span><select name="workflow_template_id" defaultValue={editing?.workflow_template_id||''}><option value="">No template / manual follow-up</option>{(workflows??[]).filter((w:any)=>w.active).map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="field"><span>Fields — one per line</span><textarea name="fields" rows={9} defaultValue={editing?lines(editing.form_schema):''} placeholder={'Full name | text | required\nPhone | phone | required\nPreferred date | date | optional\nArea | select | required | Prayer, Serve, Class'}/><small className="muted">Format: Label | type | required/optional | choices. Types: text, textarea, email, phone, date, number, select, checkbox.</small></label><button className="btn">{editing?'Save form':'Create draft form'}</button></form></section></aside>
 <section style={{display:'grid',gap:12}}><div className="section-heading"><div><div className="pill">YOUR FORMS</div><h2>Draft, publish or archive</h2></div></div>{(forms??[]).map((form:any)=><article className="card" key={form.id} style={{padding:16,opacity:form.archived_at?.75:1}}><div className="row" style={{justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="row" style={{gap:6,flexWrap:'wrap'}}><span className="pill">{form.archived_at?'ARCHIVED':form.published?'PUBLISHED':'DRAFT'}</span><span className="pill">{Array.isArray(form.form_schema)?form.form_schema.length:0} FIELDS</span></div><h3 style={{margin:'8px 0 4px'}}>{form.title}</h3><p className="small muted" style={{margin:0}}>{form.description||'No description yet.'}</p></div><div className="row" style={{gap:7,flexWrap:'wrap'}}><Link className="ghost" href={`/church/forms?edit=${form.id}`}>Edit</Link>{!form.archived_at&&<Link className="ghost" href={`/forms/${form.id}`} target="_blank">Preview</Link>}<form action={setChurchFormState}><input type="hidden" name="form_id" value={form.id}/><input type="hidden" name="action" value={form.archived_at?'restore':form.published?'unpublish':'publish'}/><button className="ghost">{form.archived_at?<><Archive size={12}/> Restore</>:form.published?<><EyeOff size={12}/> Unpublish</>:<><Eye size={12}/> Publish</>}</button></form>{!form.archived_at&&<form action={setChurchFormState}><input type="hidden" name="form_id" value={form.id}/><input type="hidden" name="action" value="archive"/><button className="ghost"><Archive size={12}/> Archive</button></form>}</div></div></article>)}{!(forms??[]).length&&<div className="card empty"><h3>No forms yet.</h3><p className="muted">Create a draft on the left. Nothing is visible to members until you publish it.</p></div>}</section></section>
 </main>
}
