import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Building2,CalendarDays,ExternalLink,Globe2,Languages,MapPin,MessageSquareWarning } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { formatChurchDay,formatChurchTime } from '@/lib/church-time'
import './network.css'

export default async function NetworkPage({searchParams}:{searchParams:Promise<{lang?:string}>}){
  const params=await searchParams,es=params.lang==='es',t=(en:string,sp:string)=>es?sp:en,l=(path:string)=>es?`${path}${path.includes('?')?'&':'?'}lang=es`:path
  const supabase=await createClient(),{data:claims}=await supabase.auth.getClaims(),userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,churches(id,name,city,state,district_id,organization_id,logo_path,brand_color,website_url,contact_email,contact_phone,timezone)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const home:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches;if(!home)redirect('/')
  const [{data:organization},{data:district},{data:churches},{data:districtEvents}]=await Promise.all([
    home.organization_id?supabase.from('organizations').select('id,name,slug').eq('id',home.organization_id).maybeSingle():Promise.resolve({data:null}),
    home.district_id?supabase.from('districts').select('id,name,slug').eq('id',home.district_id).maybeSingle():Promise.resolve({data:null}),
    home.district_id?supabase.from('churches').select('id,name,city,state,logo_path,brand_color,website_url,contact_email,contact_phone').eq('district_id',home.district_id).order('name'):supabase.from('churches').select('id,name,city,state,logo_path,brand_color,website_url,contact_email,contact_phone').eq('id',home.id),
    home.district_id?supabase.from('events').select('id,title,description,starts_at,location,registration_url').eq('district_id',home.district_id).gte('starts_at',new Date().toISOString()).order('starts_at').limit(8):Promise.resolve({data:[] as any[]})
  ])
  const tz=home.timezone||'America/Los_Angeles',rows=churches??[]

  return <main className="shell">
    <header className="topbar"><div><Link href={l('/')} className="brand">Kingdom <span>Network</span></Link><div className="small muted">{t('Church Network','Red de Iglesias')}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/network?lang=en">English</Link><Link className="ghost" href="/network?lang=es">Español</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/> {t('Feedback','Comentarios')}</Link><Link className="ghost" href={l('/')}>← {t('Home','Inicio')}</Link></div></header>

    <section className="network-hero card"><div><div className="pill">KINGDOM NETWORK</div><h1>{t('Your church is part of something bigger.','Tu iglesia es parte de algo más grande.')}</h1><p className="muted">{t('See your local church, district connections and public events while each church keeps its members and internal work private.','Mira tu iglesia local, conexiones del distrito y eventos públicos mientras cada iglesia mantiene privados sus miembros y trabajo interno.')}</p></div><div className="hero-stat"><Globe2 size={24}/><span>{t('Church • District • Organization','Iglesia • Distrito • Organización')}</span></div></section>

    <section className="network-path"><div className="card path-card"><span>{t('My Church','Mi Iglesia')}</span><strong>{home.name}</strong><div className="path-arrow">{[home.city,home.state].filter(Boolean).join(', ')||t('Local church','Iglesia local')}</div></div><div className="card path-card"><span>{t('My District','Mi Distrito')}</span><strong>{district?.name??t('Not assigned yet','Aún no asignado')}</strong><div className="path-arrow">{t('Churches connected in our region','Iglesias conectadas en nuestra región')}</div></div><div className="card path-card"><span>{t('Our Organization','Nuestra Organización')}</span><strong>{organization?.name??t('Not assigned yet','Aún no asignada')}</strong><div className="path-arrow">{t('The larger church family','La familia de iglesias más amplia')}</div></div></section>

    <section className="network-section"><div className="network-section-head"><div><div className="pill">{t('DISTRICT CHURCHES','IGLESIAS DEL DISTRITO')}</div><h2>{district?.name??t('Your church','Tu iglesia')}</h2></div><span className="small muted">{t('Public church information only.','Solo información pública de las iglesias.')}</span></div><div className="church-grid">{rows.map((c:any)=>{const logo=c.logo_path?supabase.storage.from('church-branding').getPublicUrl(c.logo_path).data.publicUrl:null,isHome=c.id===home.id;return <article className={`card network-church ${isHome?'home':''}`} key={c.id}><div className="church-logo" style={{color:c.brand_color||'#b98add'}}>{logo?<img src={logo} alt={`${c.name} logo`}/>:c.name.slice(0,1).toUpperCase()}</div><div className="church-copy"><div className="small muted">{isHome?t('YOUR CHURCH','TU IGLESIA'):t('DISTRICT CHURCH','IGLESIA DEL DISTRITO')}</div><h3>{c.name}</h3><p><MapPin size={10}/> {[c.city,c.state].filter(Boolean).join(', ')||t('Location not listed','Ubicación no disponible')}</p><div className="church-links">{c.website_url&&<a href={c.website_url} target="_blank" rel="noreferrer"><ExternalLink size={9}/> {t('Website','Sitio web')}</a>}{c.contact_email&&<a href={`mailto:${c.contact_email}`}>{c.contact_email}</a>}{c.contact_phone&&<a href={`tel:${c.contact_phone}`}>{c.contact_phone}</a>}</div></div></article>})}</div></section>

    <section className="network-section"><div className="network-section-head"><div><div className="pill">{t('DISTRICT EVENTS','EVENTOS DEL DISTRITO')}</div><h2>{t('What’s happening beyond your local church','Lo que está pasando más allá de tu iglesia local')}</h2></div><Link className="ghost" href={l('/calendar')}>{t('Full calendar','Calendario completo')}</Link></div><div className="district-events">{(districtEvents??[]).map((e:any)=><article className="card district-event" key={e.id}><div><h3>{e.title}</h3><span><CalendarDays size={11}/> {formatChurchDay(e.starts_at,tz)} • {formatChurchTime(e.starts_at,tz)}{e.location?` • ${e.location}`:''}</span></div>{e.registration_url&&<a className="ghost" href={e.registration_url} target="_blank" rel="noreferrer">{t('Details','Detalles')} <ExternalLink size={11}/></a>}</article>)}{!districtEvents?.length&&<div className="card" style={{padding:18}}><div className="small muted">{t('No upcoming district-wide events are published yet.','Todavía no hay eventos del distrito publicados.')}</div></div>}</div></section>

    <details className="card" style={{padding:18,marginTop:18}}><summary style={{fontWeight:800,cursor:'pointer'}}>{t('How church privacy works','Cómo funciona la privacidad entre iglesias')}</summary><p className="small muted" style={{lineHeight:1.55,marginTop:12}}><Building2 size={12}/> {t('This page shows only organization, district, public church information and public events. Member lists, pastoral care, documents, finances, private group addresses and leadership records remain inside each local church.','Esta página muestra solo organización, distrito, información pública de iglesias y eventos públicos. Listas de miembros, cuidado pastoral, documentos, finanzas, direcciones privadas de grupos y registros de liderazgo permanecen dentro de cada iglesia local.')}</p></details>
  </main>
}