import Link from 'next/link'
import {redirect} from 'next/navigation'
import {CheckCircle2,ClipboardList} from 'lucide-react'
import {createClient} from '@/lib/supabase/server'
import {submitChurchFormAction} from './actions'

export default async function FormPage({params,searchParams}:{params:Promise<{formId:string}>,searchParams:Promise<{sent?:string;error?:string}>}){
 const {formId}=await params,q=await searchParams,supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)redirect('/login')
 const {data:form}=await supabase.from('church_forms').select('id,title,description,form_schema,churches(name)').eq('id',formId).eq('published',true).is('archived_at',null).single();if(!form)redirect('/forms?error=Form+not+available')
 const fields=Array.isArray(form.form_schema)?form.form_schema:[],church:any=Array.isArray(form.churches)?form.churches[0]:form.churches
 if(q.sent)return <main className="shell"><header className="topbar"><Link href="/" className="brand">Kingdom <span>Network</span></Link><Link className="ghost" href="/forms">← Forms</Link></header><section className="card" style={{padding:28,textAlign:'center',maxWidth:680,margin:'50px auto'}}><CheckCircle2 size={38}/><h1>Form sent.</h1><p className="muted">Your church has received your submission. If follow-up is needed, leadership can track the owner, next action and due date from the work inbox.</p><Link className="btn" href="/forms">Back to forms</Link></section></main>
 return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name||'Church'} • Form</div></div><Link className="ghost" href="/forms">← Forms</Link></header><section className="card" style={{padding:24,maxWidth:760,margin:'0 auto'}}><div className="pill"><ClipboardList size={12}/> CHURCH FORM</div><h1>{form.title}</h1>{form.description&&<p className="muted">{form.description}</p>}{q.error&&<div className="notice error">{q.error}</div>}<form action={submitChurchFormAction} style={{display:'grid',gap:14}}><input type="hidden" name="form_id" value={form.id}/>{fields.map((field:any)=>{const common={name:String(field.key),required:Boolean(field.required)};return <label className="field" key={field.key}><span>{field.label}{field.required?' *':''}</span>{field.type==='textarea'?<textarea {...common} rows={4}/>:field.type==='select'?<select {...common} defaultValue=""><option value="" disabled>Choose one</option>{(field.options??[]).map((o:string)=><option key={o} value={o}>{o}</option>)}</select>:field.type==='checkbox'?<span className="row" style={{justifyContent:'flex-start',gap:8}}><input type="checkbox" name={String(field.key)}/><span>Yes</span></span>:<input {...common} type={field.type==='phone'?'tel':field.type||'text'}/>}</label>})}<button className="btn" type="submit">Send form</button></form></section></main>
}
