import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BriefcaseBusiness,Clock,MessageSquareWarning,UserCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { formatChurchDate } from '@/lib/church-time'
import { createAssignment,respondToAssignment } from './actions'
import './teams.css'

export default async function TeamsPage({searchParams}:{searchParams:Promise<{created?:string;responded?:string;error?:string;member?:string;ministry?:string;lang?:string}>}){
  const query=await searchParams,es=query.lang==='es',t=(en:string,sp:string)=>es?sp:en,l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
  const personName=(p:any)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||t('Church member','Miembro de la iglesia')
  const supabase=await createClient(),{data:claims}=await supabase.auth.getClaims(),userId=claims?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name,timezone)').eq('user_id',userId).eq('status','active').limit(1).single();if(!membership?.church_id)redirect('/')
  const churchId=membership.church_id,{data:customManage}=await supabase.rpc('current_user_has_church_permission',{p_church_id:churchId,p_permission_key:'manage_teams'}),canManage=['ministry_leader','minister','pastor','church_admin'].includes(membership.role)||Boolean(customManage)
  let assignmentQuery=supabase.from('team_assignments').select('*').eq('church_id',churchId).gte('starts_at',new Date(Date.now()-24*60*60*1000).toISOString()).order('starts_at').limit(100);if(!canManage)assignmentQuery=assignmentQuery.eq('assigned_user_id',userId)
  const [{data:assignments},{data:responses},{data:ministries},{data:churchMembers}]=await Promise.all([assignmentQuery,supabase.from('team_assignment_responses').select('*'),supabase.from('ministries').select('id,name').eq('church_id',churchId).eq('active',true).order('name'),canManage?supabase.from('church_memberships').select('user_id,role').eq('church_id',churchId).eq('status','active'):Promise.resolve({data:[] as any[]})])
  const ids=Array.from(new Set([...(assignments??[]).map((a:any)=>a.assigned_user_id),...(churchMembers??[]).map((m:any)=>m.user_id)]));let profiles:any[]=[];if(ids.length){const r=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',ids);profiles=r.data??[]}
  const pm=new Map(profiles.map((p:any)=>[p.id,p])),responseBy=new Map((responses??[]).map((r:any)=>[r.assignment_id,r])),ministryBy=new Map((ministries??[]).map((m:any)=>[m.id,m.name])),church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches,timeZone=church?.timezone||'UTC',dateTime=(v:string)=>formatChurchDate(v,timeZone,{weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})
  const memberOptions=(churchMembers??[]).map((m:any)=>({id:m.user_id,name:personName(pm.get(m.user_id))})).sort((a:any,b:any)=>a.name.localeCompare(b.name)),preselectedMember=memberOptions.some((m:any)=>m.id===query.member)?query.member??'':'',preselectedMinistry=(ministries??[]).some((m:any)=>m.id===query.ministry)?query.ministry??'':'',handoffLoaded=Boolean(preselectedMember&&preselectedMinistry),pendingMine=(assignments??[]).filter((a:any)=>a.assigned_user_id===userId&&a.confirmation_required&&!responseBy.get(a.id)).length

  return <main className="shell"><header className="topbar"><div><Link href={l('/')} className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??t('Your Church','Tu Iglesia')} • {t('Teams','Equipos')}</div></div><div className="row"><Link className="ghost" href="/teams?lang=en">English</Link><Link className="ghost" href="/teams?lang=es">Español</Link><Link className="ghost" href={l('/today')}>{t('My Today','Mi Día')}</Link><Link className="ghost" href={l('/calendar/my')}>{t('My Schedule','Mi Horario')}</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/>{t('Feedback','Comentarios')}</Link><Link className="ghost" href={l('/')}>← {t('Home','Inicio')}</Link></div></header>
  <section className="teams-hero card"><div><div className="pill">{canManage?t('TEAM SCHEDULES','HORARIOS DE EQUIPOS'):t('MY RESPONSIBILITIES','MIS RESPONSABILIDADES')}</div><h1>{canManage?t('See the schedule first.','Mira primero el horario.'):t('Know when you’re serving.','Sabe cuándo te toca servir.')}</h1><p className="muted">{t('Assignments, call times and responses in one clear place.','Asignaciones, horarios de llegada y respuestas en un solo lugar claro.')}</p></div><div className="hero-stat"><strong>{canManage?(assignments?.length??0):pendingMine}</strong><span>{canManage?t('upcoming assignments','asignaciones próximas'):t('need a response','necesitan respuesta')}</span></div></section>
  {query.created&&<div className="notice success">{t('Assignment created.','Asignación creada.')}</div>}{query.responded&&<div className="notice success">{t('Your response was saved.','Tu respuesta fue guardada.')}</div>}{handoffLoaded&&<div className="notice success">{t('Accepted ministry applicant loaded. Open Leadership Tools below to add service details.','Miembro y ministerio cargados. Abre Herramientas de Liderazgo abajo para agregar los detalles.')}</div>}{query.error&&<div className="notice error">{query.error}</div>}

  <section className="assignment-list">{(assignments??[]).map((a:any)=>{const response:any=responseBy.get(a.id),mine=a.assigned_user_id===userId;return <article className="card assignment-card" key={a.id}><div className="assignment-head"><div><div className="assignment-person"><div className="avatar">{personName(pm.get(a.assigned_user_id)).slice(0,1).toUpperCase()}</div><div><strong>{canManage?personName(pm.get(a.assigned_user_id)):t('You','Tú')}</strong><div className="small muted">{a.ministry_id?ministryBy.get(a.ministry_id)||t('Ministry','Ministerio'):t('Church team','Equipo de la iglesia')}</div></div></div><h2>{a.title}</h2></div><span className={`response-chip ${response?.response??''}`}>{response?.response==='confirmed'?t('confirmed','confirmado'):response?.response==='declined'?t('declined','no disponible'):a.confirmation_required?t('awaiting response','esperando respuesta'):t('scheduled','programado')}</span></div><div className="assignment-meta"><span><BriefcaseBusiness size={13}/>{dateTime(a.starts_at)}</span>{a.call_time&&<span><Clock size={13}/>{t('Call time','Llegada')} {dateTime(a.call_time)}</span>}</div>{a.notes&&<p className="muted">{a.notes}</p>}{mine&&a.confirmation_required&&<form action={respondToAssignment} className="response-actions"><input type="hidden" name="assignment_id" value={a.id}/><input type="hidden" name="lang" value={es?'es':'en'}/><label className="field"><span>{t('Optional note','Nota opcional')}</span><input name="note" defaultValue={response?.note??''} placeholder={t('Anything leadership should know','Algo que el líder debe saber')}/></label><button className="btn" name="response" value="confirmed"><UserCheck size={14}/> {t('Yes, I can serve','Sí, puedo servir')}</button><button className="ghost" name="response" value="declined">{t('I can’t serve','No puedo servir')}</button></form>}</article>})}{!assignments?.length&&<div className="card team-empty"><h3>{t('No upcoming assignments.','No tienes asignaciones próximas.')}</h3><p className="muted">{t('When you are scheduled, it will appear here.','Cuando te programen, aparecerá aquí.')}</p></div>}</section>

  {canManage&&<details className="card" style={{padding:18,marginTop:22}} open={handoffLoaded}><summary style={{fontWeight:800,cursor:'pointer'}}>{t('Leadership Tools • Schedule a member','Herramientas de Liderazgo • Programar miembro')}</summary><section className="create-assignment" style={{marginTop:16}}><p className="small muted">{t(`Times are entered in ${timeZone.replaceAll('_',' ')}.`,`Las horas se ingresan en ${timeZone.replaceAll('_',' ')}.`)}</p><form action={createAssignment}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="lang" value={es?'es':'en'}/><label className="field"><span>{t('Person','Persona')}</span><select name="assigned_user_id" required defaultValue={preselectedMember}><option value="" disabled>{t('Choose member','Escoger miembro')}</option>{memberOptions.map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field"><span>{t('Ministry','Ministerio')}</span><select name="ministry_id" defaultValue={preselectedMinistry}><option value="">{t('General church team','Equipo general')}</option>{(ministries??[]).map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field"><span>{t('Assignment','Asignación')}</span><input name="title" required placeholder={t('e.g. Sound Booth – Sunday AM','Ej. Sonido – Domingo AM')}/></label><label className="field"><span>{t('Service / event time','Hora del servicio / evento')}</span><input type="datetime-local" name="starts_at" required/></label><label className="field"><span>{t('Call time','Hora de llegada')}</span><input type="datetime-local" name="call_time"/></label><label className="field"><span>{t('Notes','Notas')}</span><textarea name="notes" rows={3} placeholder={t('Dress, location, setup instructions, etc.','Ropa, lugar, instrucciones, etc.')}/></label><button className="btn">{t('Create assignment','Crear asignación')}</button></form></section></details>}
  {!canManage&&<section className="card side" style={{marginTop:18}}><div className="pill">{t('MY TEAM','MI EQUIPO')}</div><h3>{t('One simple response.','Una respuesta sencilla.')}</h3><p className="muted">{t('When you’re assigned, confirm or say you can’t serve. Your leader sees it right away.','Cuando te asignen, confirma o indica que no puedes servir. Tu líder lo verá inmediatamente.')}</p></section>}
  </main>
}