import Link from 'next/link'
import {redirect} from 'next/navigation'
import {BookOpen,CalendarDays,CheckCircle2,FileText} from 'lucide-react'
import {createClient} from '@/lib/supabase/server'
import {formatRecurringMeeting} from '@/lib/church-time'
import {LessonAssetUploader} from './lesson-asset-uploader'
import {archiveGroupLesson,assignGroupLesson,cancelGroupLessonAssignment,createGroupLesson,updateGroupLesson} from './actions'
import '../../groups.css'

const fmt=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})
const list=(v:any)=>Array.isArray(v)?v:[]

export default async function GroupLessonsPage({params,searchParams}:{params:Promise<{groupId:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const [{groupId},query]=await Promise.all([params,searchParams]),supabase=await createClient(),{data:claims}=await supabase.auth.getClaims(),userId=claims?.claims?.sub
 if(!userId)redirect('/login')
 const {data:churchMembership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!churchMembership?.church_id)redirect('/')
 const {data:group}=await supabase.from('groups').select('id,name,description,group_type,leader_id,meeting_day,meeting_time,meeting_frequency').eq('id',groupId).eq('church_id',churchMembership.church_id).single();if(!group)redirect('/groups?error='+encodeURIComponent('Group not found.'))
 const {data:myGroupMembership}=await supabase.from('group_memberships').select('role').eq('group_id',groupId).eq('user_id',userId).maybeSingle(),canManage=group.leader_id===userId||myGroupMembership?.role==='leader'||['minister','pastor','church_admin'].includes(churchMembership.role),canView=canManage||Boolean(myGroupMembership)
 if(!canView)redirect(`/groups/${groupId}?error=`+encodeURIComponent('Join this group to view its lessons.'))
 let lessonQuery=supabase.from('friendship_group_lessons').select('id,lesson_number,title,opening_question,content,source_label,source_asset_path,owner_group_id,published,created_at,updated_at').eq('church_id',churchMembership.church_id).or(`owner_group_id.is.null,owner_group_id.eq.${groupId}`).order('lesson_number')
 if(!canManage)lessonQuery=lessonQuery.eq('published',true)
 const [{data:lessonRowsRaw},{data:assignmentRows}]=await Promise.all([lessonQuery,supabase.from('group_lesson_assignments').select('id,lesson_id,scheduled_for,status,teaching_note,created_at,updated_at').eq('group_id',groupId).order('scheduled_for',{ascending:false}).limit(100)])
 const lessons:any[]=lessonRowsRaw??[],assignments:any[]=assignmentRows??[],lessonMap=new Map(lessons.map((l:any)=>[l.id,l])),today=new Date().toISOString().slice(0,10),upcoming=assignments.filter((a:any)=>a.status==='scheduled'&&a.scheduled_for>=today).sort((a:any,b:any)=>a.scheduled_for.localeCompare(b.scheduled_for)),history=assignments.filter((a:any)=>a.scheduled_for<today||a.status==='completed').sort((a:any,b:any)=>b.scheduled_for.localeCompare(a.scheduled_for)),activeAssignment=upcoming[0]??history[0]??null,activeLesson:any=activeAssignment?lessonMap.get(activeAssignment.lesson_id):null
 const signed=new Map<string,string>();for(const lesson of lessons){if(lesson.source_asset_path){const {data}=await supabase.storage.from('group-lesson-assets').createSignedUrl(lesson.source_asset_path,3600);if(data?.signedUrl)signed.set(lesson.id,data.signedUrl)}}
 const church:any=Array.isArray(churchMembership.churches)?churchMembership.churches[0]:churchMembership.churches,schedule=formatRecurringMeeting(group.meeting_frequency,group.meeting_day,group.meeting_time,'en')
 return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Your Church'} • Friendship Group Lessons</div></div><div className="row"><Link className="ghost" href={`/groups/${groupId}`}>← {group.name}</Link><Link className="ghost" href="/groups">All groups</Link></div></header>
 <section className="group-detail-hero card"><div><div className="pill">LESSON PLAN</div><h1>{group.name} Lessons</h1><p className="muted">Each lesson is tied to a real meeting date, so members can prepare ahead and look back later.</p><div className="group-detail-meta"><span><BookOpen size={15}/>{lessons.filter(l=>l.published).length} available lessons</span><span><CalendarDays size={15}/>{schedule}</span></div></div>{canManage&&<div className="leader-badge">Leader lesson tools</div>}</section>
 {query.created&&<div className="notice success">Lesson created and ready for this group.</div>}{query.updated&&<div className="notice success">Lesson updated.</div>}{query.archived&&<div className="notice success">Lesson archived. Existing meeting history was preserved.</div>}{query.assigned&&<div className="notice success">Lesson scheduled. Members can open it now.</div>}{query.cancelled&&<div className="notice success">Scheduled lesson cancelled.</div>}{query.error&&<div className="notice error">{query.error}</div>}
 {activeLesson?<section className="card group-section" style={{marginBottom:16}}><div className="section-heading"><div><div className="pill">{activeAssignment.scheduled_for>=today?'NEXT LESSON':'MOST RECENT LESSON'}</div><h2>{activeLesson.title}</h2></div><span className="small muted">{fmt(activeAssignment.scheduled_for)}</span></div>{activeAssignment.teaching_note&&<div className="notice"><strong>Leader note:</strong> {activeAssignment.teaching_note}</div>}{activeLesson.opening_question&&<div className="card" style={{padding:14,background:'rgba(255,255,255,.03)'}}><strong>Opening question</strong><p>{activeLesson.opening_question}</p></div>}{list(activeLesson.content?.sections).map((section:any,i:number)=><div key={i} style={{marginTop:14}}><h3>{section.heading}</h3><p className="muted" style={{whiteSpace:'pre-wrap',lineHeight:1.65}}>{section.body}</p></div>)}{list(activeLesson.content?.scripture_refs).length>0&&<p><strong>Scriptures:</strong> {list(activeLesson.content.scripture_refs).join(' • ')}</p>}{list(activeLesson.content?.leader_discussion_prompts).length>0&&<div className="card" style={{padding:14}}><strong>Discussion</strong><ol>{list(activeLesson.content.leader_discussion_prompts).map((p:any,i:number)=><li key={i}>{p}</li>)}</ol></div>}{signed.get(activeLesson.id)&&<a className="btn secondary" href={signed.get(activeLesson.id)} target="_blank" rel="noreferrer"><FileText size={15}/> Open lesson file</a>}</section>:<section className="card group-section" style={{marginBottom:16}}><div className="pill">NEXT LESSON</div><h2>No lesson scheduled yet</h2><p className="muted">{canManage?'Create or choose a lesson below and assign it to a meeting date.':'Your group leader has not scheduled the next lesson yet.'}</p></section>}
 {canManage&&<section className="card group-section" style={{marginBottom:16}}><div className="pill">CREATE FOR THIS GROUP</div><h2>Add a lesson</h2><p className="small muted">Type the lesson, upload a source file, or do both. This material is owned by this Friendship Group and cannot be edited by leaders of another group.</p><form action={createGroupLesson} className="group-settings-grid"><input type="hidden" name="group_id" value={groupId}/><label className="wide"><span>Lesson title</span><input name="title" required/></label><label><span>Meeting date (optional)</span><input type="date" name="scheduled_for"/></label><label className="wide"><span>Opening question</span><input name="opening_question"/></label><label className="wide"><span>Lesson material</span><textarea name="body" rows={8} placeholder="Paste or type the lesson content here…"/></label><label className="wide"><span>Scripture references</span><input name="scripture_refs" placeholder="Acts 2:38, John 3:5…"/></label><label className="wide"><span>Discussion questions</span><textarea name="discussion_prompts" rows={3} placeholder="One per line"/></label><label className="wide"><span>Leader note for this meeting</span><textarea name="teaching_note" rows={2}/></label><div className="wide"><LessonAssetUploader churchId={churchMembership.church_id} groupId={groupId} userId={userId}/></div><button className="btn wide">Create lesson</button></form></section>}
 {canManage&&lessons.some(l=>l.published)&&<section className="card group-section" style={{marginBottom:16}}><div className="pill">SCHEDULE AHEAD</div><h2>Assign a lesson to a meeting date</h2><form action={assignGroupLesson} className="group-settings-grid"><input type="hidden" name="group_id" value={groupId}/><label><span>Meeting date</span><input type="date" name="scheduled_for" required/></label><label className="wide"><span>Lesson</span><select name="lesson_id" defaultValue="" required><option value="" disabled>Choose a lesson</option>{lessons.filter(l=>l.published).map(l=><option value={l.id} key={l.id}>{l.title}</option>)}</select></label><label className="wide"><span>Meeting-specific note</span><textarea name="teaching_note" rows={2}/></label><button className="btn wide">Schedule lesson</button></form></section>}
 <section className="card group-section" style={{marginBottom:16}}><div className="pill">LESSON CALENDAR</div><h2>Upcoming and past meetings</h2><div className="report-history">{assignments.filter(a=>a.status!=='cancelled').map(a=>{const lesson:any=lessonMap.get(a.lesson_id);return <article className="report-card" key={a.id}><div className="report-top"><strong>{fmt(a.scheduled_for)}</strong><span>{lesson?.title||'Archived lesson'}</span></div><div className="row" style={{justifyContent:'space-between',gap:8,flexWrap:'wrap'}}><span className={a.status==='completed'?'complete-chip':'role-chip'}>{a.status==='completed'?<><CheckCircle2 size={12}/> Completed</>:a.scheduled_for>=today?'Upcoming':'Past'}</span>{canManage&&a.status==='scheduled'&&a.scheduled_for>=today&&<form action={cancelGroupLessonAssignment}><input type="hidden" name="group_id" value={groupId}/><input type="hidden" name="assignment_id" value={a.id}/><button className="ghost">Cancel</button></form>}</div></article>})}{!assignments.length&&<p className="muted">No lesson dates have been scheduled yet.</p>}</div></section>
 {canManage&&lessons.some(l=>l.owner_group_id===groupId)&&<section className="card group-section"><div className="pill">EDIT GROUP LESSONS</div><h2>Material created for this group</h2><div style={{display:'grid',gap:10}}>{lessons.filter(l=>l.owner_group_id===groupId).map(lesson=><details className="card" style={{padding:14}} key={lesson.id}><summary style={{fontWeight:800,cursor:'pointer'}}>{lesson.title} {!lesson.published&&<span className="mini-pill">ARCHIVED</span>}</summary><form action={updateGroupLesson} className="group-settings-grid" style={{marginTop:12}}><input type="hidden" name="group_id" value={groupId}/><input type="hidden" name="lesson_id" value={lesson.id}/><input type="hidden" name="source_asset_path" value={lesson.source_asset_path??''}/><label className="wide"><span>Title</span><input name="title" defaultValue={lesson.title} required/></label><label className="wide"><span>Opening question</span><input name="opening_question" defaultValue={lesson.opening_question??''}/></label><label className="wide"><span>Lesson material</span><textarea name="body" rows={7} defaultValue={list(lesson.content?.sections)[0]?.body??''}/></label><label className="wide"><span>Scriptures</span><input name="scripture_refs" defaultValue={list(lesson.content?.scripture_refs).join(', ')}/></label><label className="wide"><span>Discussion questions</span><textarea name="discussion_prompts" rows={3} defaultValue={list(lesson.content?.leader_discussion_prompts).join('\n')}/></label><button className="btn secondary wide">Save edits</button></form>{lesson.published&&<form action={archiveGroupLesson} style={{marginTop:8}}><input type="hidden" name="group_id" value={groupId}/><input type="hidden" name="lesson_id" value={lesson.id}/><button className="ghost">Archive lesson</button></form>}</details>)}</div></section>}
 </main>
}
