import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CalendarDays,Languages,MessageSquareWarning,Plus,Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { formatRecurringMeeting } from '@/lib/church-time'
import { createGroup } from './actions'
import './groups.css'

const copy={
  en:{home:'← Home',builder:'← Church Builder',section:'GROUP LIFE',title:'Friendship Groups',subtitle:'Your Friendship Group is your weekly place to connect, learn, pray and grow together.',active:'active groups',my:'MY GROUP',members:'members',leader:'Leader',unassigned:'Leader not assigned',community:'Church community group',empty:'No active groups yet.',emptyBody:'Authorized leaders can create the first group below.',create:'Create a group',name:'Group name',namePh:'e.g. North Madera Friendship Group',type:'Group type',friendship:'Friendship',youth:'Youth',college:'College & Career',men:'Men',women:'Women',juniors:'Juniors',miracle:'Miracle Land',other:'Other',assign:'Leader',later:'Assign later',day:'Meeting day',time:'Meeting time',frequency:'Frequency',weekly:'Weekly',biweekly:'Every other week',monthly:'Monthly',seasonal:'Seasonal',address:'Meeting Address',addressPh:'Street address / meeting location',description:'Description',descriptionPh:'Who this group serves, neighborhood, or purpose',submit:'Create group',monday:'Monday',tuesday:'Tuesday',wednesday:'Wednesday',thursday:'Thursday',friday:'Friday',saturday:'Saturday',sunday:'Sunday'},
  es:{home:'← Inicio',builder:'← Church Builder',section:'VIDA EN GRUPOS',title:'Grupos de Amistad',subtitle:'Tu Grupo de Amistad es tu lugar semanal para conectarte, aprender, orar y crecer juntos.',active:'grupos activos',my:'MI GRUPO',members:'miembros',leader:'Líder',unassigned:'Líder no asignado',community:'Grupo de comunidad de la iglesia',empty:'Todavía no hay grupos activos.',emptyBody:'Los líderes autorizados pueden crear el primer grupo abajo.',create:'Crear un grupo',name:'Nombre del grupo',namePh:'ej. Grupo de Amistad Norte de Madera',type:'Tipo de grupo',friendship:'Amistad',youth:'Jóvenes',college:'Universitarios y Jóvenes Adultos',men:'Hombres',women:'Mujeres',juniors:'Juniors',miracle:'Miracle Land',other:'Otro',assign:'Líder',later:'Asignar después',day:'Día de reunión',time:'Hora de reunión',frequency:'Frecuencia',weekly:'Cada semana',biweekly:'Cada dos semanas',monthly:'Mensual',seasonal:'Por temporada',address:'Dirección de Reunión',addressPh:'Dirección / lugar de reunión',description:'Descripción',descriptionPh:'A quién sirve este grupo, vecindario o propósito',submit:'Crear grupo',monday:'Lunes',tuesday:'Martes',wednesday:'Miércoles',thursday:'Jueves',friday:'Viernes',saturday:'Sábado',sunday:'Domingo'}
} as const

export default async function GroupsPage({searchParams}:{searchParams:Promise<{error?:string;lang?:string}>}){
  const params=await searchParams,lang=params.lang==='es'?'es':'en',es=lang==='es',t=copy[lang],l=(path:string)=>es?`${path}${path.includes('?')?'&':'?'}lang=es`:path
  const supabase=await createClient(),{data:claimsData}=await supabase.auth.getClaims(),userId=claimsData?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const churchId=membership.church_id,isAdmin=['pastor','church_admin'].includes(membership.role)
  const {data:customGroupAccess}=await supabase.rpc('current_user_has_church_permission',{p_church_id:churchId,p_permission_key:'manage_groups'}),canManage=isAdmin||Boolean(customGroupAccess)
  const [{data:groups},{data:groupMemberships},{data:churchMembers}]=await Promise.all([
    supabase.from('groups').select('*').eq('church_id',churchId).eq('active',true).order('name'),
    supabase.from('group_memberships').select('group_id,user_id,role'),
    canManage?supabase.from('church_memberships').select('user_id,role').eq('church_id',churchId).eq('status','active'):Promise.resolve({data:[] as any[]})
  ])
  const leaderIds=(groups??[]).map((g:any)=>g.leader_id).filter(Boolean),churchUserIds=(churchMembers??[]).map((m:any)=>m.user_id),ids=Array.from(new Set([...leaderIds,...churchUserIds]))
  let profiles:any[]=[];if(ids.length){const result=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',ids);profiles=result.data??[]}
  const pm=new Map(profiles.map((p:any)=>[p.id,p])),counts=new Map<string,number>();for(const gm of groupMemberships??[])counts.set(gm.group_id,(counts.get(gm.group_id)??0)+1)
  const myGroupIds=new Set((groupMemberships??[]).filter((gm:any)=>gm.user_id===userId).map((gm:any)=>gm.group_id)),myGroups=(groups??[]).filter((g:any)=>myGroupIds.has(g.id)),otherGroups=(groups??[]).filter((g:any)=>!myGroupIds.has(g.id))
  const church=Array.isArray(membership.churches)?membership.churches[0]:membership.churches as any
  const memberOptions=(churchMembers??[]).map((m:any)=>{const p=pm.get(m.user_id);return {id:m.user_id,name:p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Member'}}).sort((a:any,b:any)=>a.name.localeCompare(b.name))
  const groupCard=(g:any,mine=false)=>{const p=pm.get(g.leader_id),leader=p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||t.unassigned;return <Link href={l(`/groups/${g.id}`)} className="card group-card" key={g.id}><div className="group-card-head"><div className="group-icon"><Users size={20}/></div>{mine&&<span className="mini-pill">{t.my}</span>}</div><h2>{g.name}</h2><p>{g.description||t.community}</p><div className="group-meta"><span><CalendarDays size={14}/>{formatRecurringMeeting(g.meeting_frequency,g.meeting_day,g.meeting_time,lang)}</span><span><Users size={14}/>{counts.get(g.id)??0} {t.members}</span></div><div className="group-leader">{t.leader}: <strong>{leader}</strong></div></Link>}
  return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Your Church'} • {t.title}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/groups?lang=en">English</Link><Link className="ghost" href="/groups?lang=es">Español</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/> {es?'Comentarios':'Feedback'}</Link>{isAdmin&&<Link className="ghost" href={l('/church/launch')}>{t.builder}</Link>}<Link className="ghost" href={l('/')}>{t.home}</Link></div></header>
  <section className="groups-hero card"><div><div className="pill">{t.section}</div><h1>{t.title}</h1><p className="muted">{t.subtitle}</p></div><div className="groups-stat"><strong>{groups?.length??0}</strong><span>{t.active}</span></div></section>{params.error&&<div className="notice error">{params.error}</div>}
  {myGroups.length>0?<section style={{marginBottom:24}}><div className="pill" style={{marginBottom:12}}>{t.my}</div><div className="groups-grid">{myGroups.map((g:any)=>groupCard(g,true))}</div></section>:<section className="card" style={{padding:20,marginBottom:22,border:'1px solid rgba(125,211,252,.28)'}}><div className="pill">{es?'CONÉCTATE':'GET CONNECTED'}</div><h2>{es?'Todavía no estás conectado a un Grupo de Amistad.':'You are not connected to a Friendship Group yet.'}</h2><p className="muted">{es?'Mira los grupos abajo. Solo puedes pertenecer a un Grupo de Amistad activo a la vez.':'Browse the groups below. You can belong to only one active Friendship Group at a time.'}</p></section>}
  {otherGroups.length>0&&<section style={{marginBottom:22}}><div className="pill" style={{marginBottom:12}}>{es?'OTROS GRUPOS':'OTHER GROUPS'}</div><div className="groups-grid">{otherGroups.map((g:any)=>groupCard(g,false))}</div></section>}{!groups?.length&&<div className="card empty"><h3>{t.empty}</h3><p className="muted">{t.emptyBody}</p></div>}
  {canManage&&<details className="card create-group" style={{padding:18}}><summary style={{fontWeight:800,cursor:'pointer'}}><Plus size={16}/> {t.create}</summary><div style={{marginTop:16}}><form action={createGroup}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="lang" value={lang}/><div className="group-form-grid"><label className="field"><span>{t.name}</span><input name="name" required placeholder={t.namePh}/></label><label className="field"><span>{t.type}</span><select name="group_type" defaultValue="friendship"><option value="friendship">{t.friendship}</option><option value="youth">{t.youth}</option><option value="college_career">{t.college}</option><option value="men">{t.men}</option><option value="women">{t.women}</option><option value="juniors">{t.juniors}</option><option value="miracle_land">{t.miracle}</option><option value="other">{t.other}</option></select></label><label className="field"><span>{t.assign}</span><select name="leader_id" defaultValue=""><option value="">{t.later}</option>{memberOptions.map((m:any)=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="field"><span>{t.day}</span><select name="meeting_day" defaultValue="Tuesday"><option value="Monday">{t.monday}</option><option value="Tuesday">{t.tuesday}</option><option value="Wednesday">{t.wednesday}</option><option value="Thursday">{t.thursday}</option><option value="Friday">{t.friday}</option><option value="Saturday">{t.saturday}</option><option value="Sunday">{t.sunday}</option></select></label><label className="field"><span>{t.time}</span><input name="meeting_time" type="time"/></label><label className="field"><span>{t.frequency}</span><select name="meeting_frequency" defaultValue="weekly"><option value="weekly">{t.weekly}</option><option value="biweekly">{t.biweekly}</option><option value="monthly">{t.monthly}</option><option value="seasonal">{t.seasonal}</option><option value="other">{t.other}</option></select></label><label className="field" style={{gridColumn:'1/-1'}}><span>{t.address}</span><input name="meeting_address" placeholder={t.addressPh}/><small className="muted">{es?'La dirección exacta solo se muestra a miembros del grupo y liderazgo autorizado.':'The exact address is shown only to group members and authorized leadership.'}</small></label></div><label className="field"><span>{t.description}</span><textarea name="description" rows={3} placeholder={t.descriptionPh}/></label><button className="btn">{t.submit}</button></form></div></details>}
  </main>
}
