import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CalendarDays,Languages,MapPin,MessageSquareWarning,Plus,Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { createGroup } from './actions'
import './groups.css'

const copy={
  en:{home:'← Home',builder:'← Church Builder',section:'GROUP LIFE',title:'Friendship Groups',subtitle:'Your group first. Other groups are here when you need them.',active:'active groups',my:'MY GROUP',open:'OPEN',full:'FULL',paused:'PAUSED',members:'members',leader:'Leader',unassigned:'Leader not assigned',community:'Church community group',empty:'No active groups yet.',emptyBody:'Authorized leaders can create the first group below.',admin:'ADMIN',create:'Create a group',name:'Group name',namePh:'e.g. North Madera Friendship Group',type:'Group type',friendship:'Friendship',youth:'Youth',college:'College & Career',men:'Men',women:'Women',juniors:'Juniors',miracle:'Miracle Land',other:'Other',assign:'Leader',later:'Assign later',day:'Meeting day',time:'Meeting time',frequency:'Frequency',weekly:'Weekly',biweekly:'Every other week',monthly:'Monthly',seasonal:'Seasonal',language:'Language',english:'English',spanish:'Spanish',bilingual:'Bilingual',area:'Public area',areaPh:'Neighborhood / city area',capacity:'Capacity',capacityPh:'Blank = open',description:'Description',descriptionPh:'Who this group serves, neighborhood, or purpose',accepting:'Accepting new members',submit:'Create group',monday:'Monday',tuesday:'Tuesday',wednesday:'Wednesday',thursday:'Thursday',friday:'Friday',saturday:'Saturday',sunday:'Sunday'},
  es:{home:'← Inicio',builder:'← Church Builder',section:'VIDA EN GRUPOS',title:'Grupos de Amistad',subtitle:'Tu grupo primero. Los demás grupos están aquí cuando los necesites.',active:'grupos activos',my:'MI GRUPO',open:'ABIERTO',full:'LLENO',paused:'PAUSADO',members:'miembros',leader:'Líder',unassigned:'Líder no asignado',community:'Grupo de comunidad de la iglesia',empty:'Todavía no hay grupos activos.',emptyBody:'Los líderes autorizados pueden crear el primer grupo abajo.',admin:'ADMINISTRACIÓN',create:'Crear un grupo',name:'Nombre del grupo',namePh:'ej. Grupo de Amistad Norte de Madera',type:'Tipo de grupo',friendship:'Amistad',youth:'Jóvenes',college:'Universitarios y Jóvenes Adultos',men:'Hombres',women:'Mujeres',juniors:'Juniors',miracle:'Miracle Land',other:'Otro',assign:'Líder',later:'Asignar después',day:'Día de reunión',time:'Hora de reunión',frequency:'Frecuencia',weekly:'Cada semana',biweekly:'Cada dos semanas',monthly:'Mensual',seasonal:'Por temporada',language:'Idioma',english:'Inglés',spanish:'Español',bilingual:'Bilingüe',area:'Zona pública',areaPh:'Vecindario / zona de la ciudad',capacity:'Capacidad',capacityPh:'Vacío = sin límite',description:'Descripción',descriptionPh:'A quién sirve este grupo, vecindario o propósito',accepting:'Aceptando nuevos miembros',submit:'Crear grupo',monday:'Lunes',tuesday:'Martes',wednesday:'Miércoles',thursday:'Jueves',friday:'Viernes',saturday:'Sábado',sunday:'Domingo'}
} as const

export default async function GroupsPage({searchParams}:{searchParams:Promise<{error?:string;lang?:string}>}){
  const params=await searchParams
  const lang=params.lang==='es'?'es':'en',es=lang==='es'
  const t=copy[lang]
  const l=(path:string)=>lang==='es'?`${path}${path.includes('?')?'&':'?'}lang=es`:path
  const languageLabel=(v:string)=>v==='es'?t.spanish:v==='bilingual'?t.bilingual:t.english
  const frequencyLabel=(v:string)=>v==='biweekly'?t.biweekly:v==='monthly'?t.monthly:v==='seasonal'?t.seasonal:v==='other'?t.other:t.weekly
  const supabase=await createClient()
  const {data:claimsData}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id)redirect('/')
  const churchId=membership.church_id,isAdmin=['pastor','church_admin'].includes(membership.role)
  const {data:customGroupAccess}=await supabase.rpc('current_user_has_church_permission',{p_church_id:churchId,p_permission_key:'manage_groups'})
  const canManage=isAdmin||Boolean(customGroupAccess)
  const [{data:groups},{data:groupMemberships},{data:churchMembers}]=await Promise.all([
    supabase.from('groups').select('*').eq('church_id',churchId).eq('active',true).order('name'),
    supabase.from('group_memberships').select('group_id,user_id,role'),
    canManage?supabase.from('church_memberships').select('user_id,role').eq('church_id',churchId).eq('status','active'):Promise.resolve({data:[] as any[]})
  ])
  const leaderIds=(groups??[]).map((g:any)=>g.leader_id).filter(Boolean),churchUserIds=(churchMembers??[]).map((m:any)=>m.user_id),ids=Array.from(new Set([...leaderIds,...churchUserIds]))
  let profiles:any[]=[];if(ids.length){const result=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',ids);profiles=result.data??[]}
  const pm=new Map(profiles.map((p:any)=>[p.id,p])),counts=new Map<string,number>()
  for(const gm of groupMemberships??[])counts.set(gm.group_id,(counts.get(gm.group_id)??0)+1)
  const myGroupIds=new Set((groupMemberships??[]).filter((gm:any)=>gm.user_id===userId).map((gm:any)=>gm.group_id))
  const myGroups=(groups??[]).filter((g:any)=>myGroupIds.has(g.id)),otherGroups=(groups??[]).filter((g:any)=>!myGroupIds.has(g.id))
  const church=Array.isArray(membership.churches)?membership.churches[0]:membership.churches as any
  const memberOptions=(churchMembers??[]).map((m:any)=>{const p=pm.get(m.user_id);return {id:m.user_id,name:p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Member'}}).sort((a:any,b:any)=>a.name.localeCompare(b.name))
  const groupCard=(g:any,mine=false)=>{const p=pm.get(g.leader_id);const leader=p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||t.unassigned;const memberCount=counts.get(g.id)??0;const full=Boolean(g.capacity&&memberCount>=g.capacity);const accepting=Boolean(g.accepting_members&&!full);return <Link href={l(`/groups/${g.id}`)} className="card group-card" key={g.id}><div className="group-card-head"><div className="group-icon"><Users size={20}/></div><div className="row">{mine&&<span className="mini-pill">{t.my}</span>}<span className="mini-pill">{accepting?t.open:full?t.full:t.paused}</span></div></div><h2>{g.name}</h2><p>{g.description||t.community}</p><div className="group-meta"><span><CalendarDays size={14}/>{g.meeting_day||'TBD'} {g.meeting_time?String(g.meeting_time).slice(0,5):''} • {frequencyLabel(g.meeting_frequency||'weekly')}</span>{g.location_label&&<span><MapPin size={14}/>{g.location_label}</span>}<span><Languages size={14}/>{languageLabel(g.language_code||'en')}</span><span><Users size={14}/>{memberCount}{g.capacity?` / ${g.capacity}`:''} {t.members}</span></div><div className="group-leader">{t.leader}: <strong>{leader}</strong></div></Link>}

  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Your Church'} • {t.title}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/groups?lang=en">English</Link><Link className="ghost" href="/groups?lang=es">Español</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/> {es?'Comentarios':'Feedback'}</Link>{isAdmin&&<Link className="ghost" href={l('/church/launch')}>{t.builder}</Link>}<Link className="ghost" href="/">{t.home}</Link></div></header>
    <section className="groups-hero card"><div><div className="pill">{t.section}</div><h1>{t.title}</h1><p className="muted">{t.subtitle}</p></div><div className="groups-stat"><strong>{groups?.length??0}</strong><span>{t.active}</span></div></section>
    {params.error&&<div className="notice error">{params.error}</div>}

    {myGroups.length>0?<section style={{marginBottom:24}}><div className="pill" style={{marginBottom:12}}>{es?'MI GRUPO':'MY GROUP'}</div><div className="groups-grid">{myGroups.map((g:any)=>groupCard(g,true))}</div></section>:<section className="card" style={{padding:20,marginBottom:22,border:'1px solid rgba(125,211,252,.28)'}}><div className="pill">{es?'CONÉCTATE':'GET CONNECTED'}</div><h2>{es?'Todavía no estás conectado a un grupo.':'You are not connected to a group yet.'}</h2><p className="muted">{es?'Mira los grupos disponibles abajo y abre uno para conocer el horario, líder y detalles.':'Browse the available groups below and open one to see the schedule, leader and details.'}</p></section>}

    {otherGroups.length>0&&<section style={{marginBottom:22}}><div className="pill" style={{marginBottom:12}}>{es?'OTROS GRUPOS':'OTHER GROUPS'}</div><div className="groups-grid">{otherGroups.map((g:any)=>groupCard(g,false))}</div></section>}
    {!groups?.length&&<div className="card empty"><h3>{t.empty}</h3><p className="muted">{t.emptyBody}</p></div>}

    {canManage&&<details className="card create-group" style={{padding:18}}><summary style={{fontWeight:800,cursor:'pointer'}}><Plus size={16}/> {t.create}</summary><div style={{marginTop:16}}><form action={createGroup}><input type="hidden" name="church_id" value={churchId}/><input type="hidden" name="lang" value={lang}/><div className="group-form-grid"><label className="field"><span>{t.name}</span><input name="name" required placeholder={t.namePh}/></label><label className="field"><span>{t.type}</span><select name="group_type" defaultValue="friendship"><option value="friendship">{t.friendship}</option><option value="youth">{t.youth}</option><option value="college_career">{t.college}</option><option value="men">{t.men}</option><option value="women">{t.women}</option><option value="juniors">{t.juniors}</option><option value="miracle_land">{t.miracle}</option><option value="other">{t.other}</option></select></label><label className="field"><span>{t.assign}</span><select name="leader_id" defaultValue=""><option value="">{t.later}</option>{memberOptions.map((m:any)=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="field"><span>{t.day}</span><select name="meeting_day" defaultValue="Tuesday"><option value="Monday">{t.monday}</option><option value="Tuesday">{t.tuesday}</option><option value="Wednesday">{t.wednesday}</option><option value="Thursday">{t.thursday}</option><option value="Friday">{t.friday}</option><option value="Saturday">{t.saturday}</option><option value="Sunday">{t.sunday}</option></select></label><label className="field"><span>{t.time}</span><input name="meeting_time" type="time"/></label><label className="field"><span>{t.frequency}</span><select name="meeting_frequency" defaultValue="weekly"><option value="weekly">{t.weekly}</option><option value="biweekly">{t.biweekly}</option><option value="monthly">{t.monthly}</option><option value="seasonal">{t.seasonal}</option><option value="other">{t.other}</option></select></label><label className="field"><span>{t.language}</span><select name="language_code" defaultValue="en"><option value="en">{t.english}</option><option value="es">{t.spanish}</option><option value="bilingual">{t.bilingual}</option></select></label><label className="field"><span>{t.area}</span><input name="location_label" placeholder={t.areaPh}/></label><label className="field"><span>{t.capacity}</span><input name="capacity" type="number" min="1" placeholder={t.capacityPh}/></label></div><label className="field"><span>{t.description}</span><textarea name="description" rows={3} placeholder={t.descriptionPh}/></label><label className="row small muted" style={{margin:'10px 0'}}><input type="checkbox" name="accepting_members" defaultChecked/> {t.accepting}</label><button className="btn">{t.submit}</button></form></div></details>}
  </main>
}
