import { LockKeyhole,MapPin,Settings } from 'lucide-react'
import { updateGroupDetails,updateGroupPrivateDetails } from '../actions'

const lang=(v:string)=>v==='es'?'Spanish':v==='bilingual'?'Bilingual':'English'
const freq=(v:string)=>v==='biweekly'?'Every other week':v.charAt(0).toUpperCase()+v.slice(1)

export function GroupSettings({group,privateDetails,canManage,canViewPrivate}:{group:any;privateDetails:any|null;canManage:boolean;canViewPrivate:boolean}){
  return <section className="card group-section group-settings"><div className="section-heading"><div><div className="pill">GROUP DETAILS</div><h2>Meeting & discovery information</h2></div>{canManage&&<span className="small muted"><Settings size={12}/> Leader editable</span>}</div>
    <div className="group-facts"><div><span>Public area</span><strong>{group.location_label||'Not added'}</strong></div><div><span>Frequency</span><strong>{freq(group.meeting_frequency||'weekly')}</strong></div><div><span>Language</span><strong>{lang(group.language_code||'en')}</strong></div><div><span>Capacity</span><strong>{group.capacity??'Open'}</strong></div><div><span>New members</span><strong>{group.accepting_members?'Accepting':'Not currently accepting'}</strong></div></div>
    {canManage&&<details className="group-edit"><summary>Edit public group details</summary><form action={updateGroupDetails} className="group-settings-grid"><input type="hidden" name="group_id" value={group.id}/><label className="wide"><span>Group name</span><input name="name" required defaultValue={group.name}/></label><label><span>Meeting day</span><input name="meeting_day" defaultValue={group.meeting_day??''}/></label><label><span>Meeting time</span><input type="time" name="meeting_time" defaultValue={group.meeting_time?String(group.meeting_time).slice(0,5):''}/></label><label><span>Frequency</span><select name="meeting_frequency" defaultValue={group.meeting_frequency||'weekly'}><option value="weekly">Weekly</option><option value="biweekly">Every other week</option><option value="monthly">Monthly</option><option value="seasonal">Seasonal</option><option value="other">Other</option></select></label><label><span>Language</span><select name="language_code" defaultValue={group.language_code||'en'}><option value="en">English</option><option value="es">Spanish</option><option value="bilingual">Bilingual</option></select></label><label><span>Public area / neighborhood</span><input name="location_label" defaultValue={group.location_label??''} placeholder="Chowchilla / East Madera / etc."/></label><label><span>Capacity</span><input type="number" min="1" name="capacity" defaultValue={group.capacity??''} placeholder="Blank = open"/></label><label className="wide"><span>Description</span><textarea name="description" rows={4} defaultValue={group.description??''}/></label><label className="wide inline-check"><input type="checkbox" name="accepting_members" defaultChecked={group.accepting_members}/><span>Currently accepting new members</span></label><button className="btn wide">Save group details</button></form></details>}
    {canViewPrivate&&<div className="private-meeting"><div className="private-head"><div><LockKeyhole size={14}/><strong>Member-only meeting details</strong></div><span>Not shown in group discovery</span></div>{canManage?<form action={updateGroupPrivateDetails} className="group-settings-grid"><input type="hidden" name="group_id" value={group.id}/><label className="wide"><span>Exact meeting address</span><input name="meeting_address" defaultValue={privateDetails?.meeting_address??''} placeholder="Street address / meeting location"/></label><label className="wide"><span>Access / arrival instructions</span><textarea name="access_notes" rows={3} defaultValue={privateDetails?.access_notes??''} placeholder="Parking, gate, which door, what to bring, etc."/></label><button className="ghost wide">Save private meeting details</button></form>:<div className="private-copy"><p><MapPin size={13}/> {privateDetails?.meeting_address||'Exact address has not been added yet.'}</p>{privateDetails?.access_notes&&<p>{privateDetails.access_notes}</p>}</div>}</div>}
  </section>
}
