'use client'

import Link from 'next/link'
import { BookOpen,LockKeyhole,MapPin,Settings } from 'lucide-react'
import { useSearchParams } from 'next/navigation'
import { useFormStatus } from 'react-dom'
import { formatRecurringMeeting } from '@/lib/church-time'
import { updateGroupDetails,updateGroupPrivateDetails } from '../actions'

function SaveButton({kind='primary',label,pendingLabel}:{kind?:'primary'|'ghost';label:string;pendingLabel:string}){
  const {pending}=useFormStatus()
  return <button className={`${kind==='ghost'?'ghost':'btn'} wide`} disabled={pending} aria-disabled={pending}>{pending?pendingLabel:label}</button>
}

export function GroupSettings({group,privateDetails,canManage,canViewPrivate}:{group:any;privateDetails:any|null;canManage:boolean;canViewPrivate:boolean}){
  const searchParams=useSearchParams(),es=searchParams.get('lang')==='es',t=(en:string,spanish:string)=>es?spanish:en
  const schedule=formatRecurringMeeting(group.meeting_frequency,group.meeting_day,group.meeting_time,es?'es':'en')
  return <section className="card group-section group-settings"><div className="section-heading"><div><div className="pill">{t('GROUP DETAILS','DETALLES DEL GRUPO')}</div><h2>{t('Meeting information','Información de la reunión')}</h2></div>{canManage&&<span className="small muted"><Settings size={12}/> {t('Leader editable','Editable por el líder')}</span>}</div>
    <div className="group-facts"><div><span>{t('Meeting schedule','Horario')}</span><strong>{schedule}</strong></div><div><span>{t('Members','Miembros')}</span><strong>{group.member_count??0}</strong></div></div>
    {canViewPrivate&&<div className="card" style={{padding:14,margin:'14px 0',background:'rgba(255,255,255,.03)'}}><div className="row" style={{alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div className="pill">{t('WEEKLY TEACHING','ENSEÑANZA SEMANAL')}</div><h3 style={{margin:'8px 0 4px'}}>{t('Friendship Group lessons','Lecciones del Grupo de Amistad')}</h3><p className="small muted" style={{margin:0}}>{t('Open this week’s lesson or review a past lesson.','Abre la lección de esta semana o revisa una lección anterior.')}</p></div><Link className="btn" href={`/groups/${group.id}/lessons${es?'?lang=es':''}`}><BookOpen size={15}/> {canManage?t('Schedule lessons','Programar lecciones'):t('Open this week’s lesson','Abrir la lección de esta semana')}</Link></div></div>}
    {canManage&&<details className="group-edit"><summary>{t('Edit group schedule','Editar horario del grupo')}</summary><form action={updateGroupDetails} className="group-settings-grid"><input type="hidden" name="group_id" value={group.id}/><input type="hidden" name="lang" value={es?'es':'en'}/><label className="wide"><span>{t('Group name','Nombre del grupo')}</span><input name="name" required defaultValue={group.name}/></label><label><span>{t('Meeting day','Día de reunión')}</span><select name="meeting_day" defaultValue={group.meeting_day??'Tuesday'}><option value="Monday">{t('Monday','Lunes')}</option><option value="Tuesday">{t('Tuesday','Martes')}</option><option value="Wednesday">{t('Wednesday','Miércoles')}</option><option value="Thursday">{t('Thursday','Jueves')}</option><option value="Friday">{t('Friday','Viernes')}</option><option value="Saturday">{t('Saturday','Sábado')}</option><option value="Sunday">{t('Sunday','Domingo')}</option></select></label><label><span>{t('Meeting time','Hora')}</span><input type="time" name="meeting_time" defaultValue={group.meeting_time?String(group.meeting_time).slice(0,5):''}/></label><label><span>{t('Frequency','Frecuencia')}</span><select name="meeting_frequency" defaultValue={group.meeting_frequency||'weekly'}><option value="weekly">{t('Weekly','Cada semana')}</option><option value="biweekly">{t('Every other week','Cada dos semanas')}</option><option value="monthly">{t('Monthly','Mensual')}</option><option value="seasonal">{t('Seasonal','Por temporada')}</option><option value="other">{t('Other recurring schedule','Otro horario recurrente')}</option></select></label><label className="wide"><span>{t('Description','Descripción')}</span><textarea name="description" rows={4} defaultValue={group.description??''}/></label><SaveButton label={t('Save group details','Guardar detalles del grupo')} pendingLabel={t('Saving…','Guardando…')}/><p className="small muted wide">{t('Tap Save once. Keep this page open until saving finishes.','Toca Guardar una sola vez. Mantén esta página abierta hasta que termine de guardar.')}</p></form></details>}
    {canViewPrivate&&<div className="private-meeting"><div className="private-head"><div><LockKeyhole size={14}/><strong>{t('Meeting address','Dirección de la reunión')}</strong></div><span>{t('Group members and authorized leadership only','Solo miembros del grupo y liderazgo autorizado')}</span></div>{canManage?<form action={updateGroupPrivateDetails} className="group-settings-grid"><input type="hidden" name="group_id" value={group.id}/><input type="hidden" name="lang" value={es?'es':'en'}/><label className="wide"><span>{t('Meeting address','Dirección de la reunión')}</span><input name="meeting_address" defaultValue={privateDetails?.meeting_address??''} placeholder={t('Street address / meeting location','Dirección / lugar de reunión')}/></label><label className="wide"><span>{t('Access / arrival instructions','Instrucciones para llegar')}</span><textarea name="access_notes" rows={3} defaultValue={privateDetails?.access_notes??''} placeholder={t('Parking, gate, which door, what to bring, etc.','Estacionamiento, puerta, entrada, qué traer, etc.')}/></label><SaveButton kind="ghost" label={t('Save meeting details','Guardar detalles de la reunión')} pendingLabel={t('Saving…','Guardando…')}/><p className="small muted wide">{t('The exact address stays visible only to group members and authorized leaders.','La dirección exacta solo es visible para miembros del grupo y líderes autorizados.')}</p></form>:<div className="private-copy"><p><MapPin size={13}/> {privateDetails?.meeting_address||t('Meeting address has not been added yet.','Todavía no se ha agregado la dirección de la reunión.')}</p>{privateDetails?.access_notes&&<p>{privateDetails.access_notes}</p>}</div>}</div>}
  </section>
}
