import Link from 'next/link'
import { BookOpen,LockKeyhole,MapPin,Settings } from 'lucide-react'
import { formatRecurringMeeting } from '@/lib/church-time'
import { updateGroupDetails,updateGroupPrivateDetails } from '../actions'

export function GroupSettings({group,privateDetails,canManage,canViewPrivate}:{group:any;privateDetails:any|null;canManage:boolean;canViewPrivate:boolean}){
  const schedule=formatRecurringMeeting(group.meeting_frequency,group.meeting_day,group.meeting_time,'en')
  return <section className="card group-section group-settings"><div className="section-heading"><div><div className="pill">GROUP DETAILS</div><h2>Meeting information</h2></div>{canManage&&<span className="small muted"><Settings size={12}/> Leader editable</span>}</div>
    <div className="group-facts"><div><span>Meeting schedule</span><strong>{schedule}</strong></div><div><span>Members</span><strong>{group.member_count??0}</strong></div></div>
    {canViewPrivate&&<div className="card" style={{padding:14,margin:'14px 0',background:'rgba(255,255,255,.03)'}}><div className="row" style={{alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div className="pill">WEEKLY TEACHING</div><h3 style={{margin:'8px 0 4px'}}>Friendship Group lessons</h3><p className="small muted" style={{margin:0}}>Open the scheduled lesson for this meeting or look back through past lessons.</p></div><Link className="btn" href={`/groups/${group.id}/lessons`}><BookOpen size={15}/> {canManage?'Schedule lessons':'Open this week’s lesson'}</Link></div></div>}
    {canManage&&<details className="group-edit"><summary>Edit group schedule</summary><form action={updateGroupDetails} className="group-settings-grid"><input type="hidden" name="group_id" value={group.id}/><label className="wide"><span>Group name</span><input name="name" required defaultValue={group.name}/></label><label><span>Meeting day</span><select name="meeting_day" defaultValue={group.meeting_day??'Tuesday'}><option>Monday</option><option>Tuesday</option><option>Wednesday</option><option>Thursday</option><option>Friday</option><option>Saturday</option><option>Sunday</option></select></label><label><span>Meeting time</span><input type="time" name="meeting_time" defaultValue={group.meeting_time?String(group.meeting_time).slice(0,5):''}/></label><label><span>Frequency</span><select name="meeting_frequency" defaultValue={group.meeting_frequency||'weekly'}><option value="weekly">Weekly</option><option value="biweekly">Every other week</option><option value="monthly">Monthly</option><option value="seasonal">Seasonal</option><option value="other">Other recurring schedule</option></select></label><label className="wide"><span>Description</span><textarea name="description" rows={4} defaultValue={group.description??''}/></label><button className="btn wide">Save group details</button></form></details>}
    {canViewPrivate&&<div className="private-meeting"><div className="private-head"><div><LockKeyhole size={14}/><strong>Meeting Address</strong></div><span>Group members and authorized leadership only</span></div>{canManage?<form action={updateGroupPrivateDetails} className="group-settings-grid"><input type="hidden" name="group_id" value={group.id}/><label className="wide"><span>Meeting Address</span><input name="meeting_address" defaultValue={privateDetails?.meeting_address??''} placeholder="Street address / meeting location"/></label><label className="wide"><span>Access / arrival instructions</span><textarea name="access_notes" rows={3} defaultValue={privateDetails?.access_notes??''} placeholder="Parking, gate, which door, what to bring, etc."/></label><button className="ghost wide">Save meeting details</button></form>:<div className="private-copy"><p><MapPin size={13}/> {privateDetails?.meeting_address||'Meeting address has not been added yet.'}</p>{privateDetails?.access_notes&&<p>{privateDetails.access_notes}</p>}</div>}</div>}
  </section>
}
