import { CheckCircle2,Clock3,UserPlus,XCircle } from 'lucide-react'
import { cancelGroupJoinRequest,requestGroupMembership,reviewGroupJoinRequest } from '../actions'

const personName=(p:any)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Church member'

export function JoinRequests({group,churchId,userIsMember,canManage,myPending,leaderRequests}:{group:any;churchId:string;userIsMember:boolean;canManage:boolean;myPending:any|null;leaderRequests:any[]}){
  const full=Boolean(group.capacity&&group.member_count>=group.capacity)
  return <section className="card group-section join-section">
    <div className="section-heading"><div><div className="pill">CONNECT</div><h2>{canManage?'Join requests':'Join this group'}</h2></div>{canManage&&leaderRequests.length>0&&<span className="mini-pill">{leaderRequests.length} PENDING</span>}</div>
    {canManage?<div className="join-request-list">{leaderRequests.map((r:any)=>{const p=Array.isArray(r.profiles)?r.profiles[0]:r.profiles;return <article className="join-request" key={r.id}><div className="join-person"><div className="avatar">{personName(p).slice(0,1).toUpperCase()}</div><div><strong>{personName(p)}</strong><span>Requested {new Date(r.created_at).toLocaleDateString()}</span></div></div>{r.message&&<p>{r.message}</p>}<form action={reviewGroupJoinRequest} className="join-actions"><input type="hidden" name="request_id" value={r.id}/><input type="hidden" name="group_id" value={group.id}/><button className="btn" name="decision" value="approved"><CheckCircle2 size={13}/> Approve</button><button className="ghost" name="decision" value="declined"><XCircle size={13}/> Decline</button></form></article>})}{!leaderRequests.length&&<div className="group-empty">No pending requests. New requests will appear here and notify group leadership.</div>}</div>:userIsMember?<div className="join-state"><CheckCircle2 size={17}/><div><strong>You’re connected to this group.</strong><span>Member-only meeting details are available above.</span></div></div>:myPending?<div className="join-state pending"><Clock3 size={17}/><div><strong>Your request is pending.</strong><span>Group leadership has been notified.</span></div><form action={cancelGroupJoinRequest}><input type="hidden" name="request_id" value={myPending.id}/><input type="hidden" name="group_id" value={group.id}/><button className="ghost">Cancel request</button></form></div>:(!group.accepting_members||full)?<div className="join-state"><XCircle size={17}/><div><strong>{full?'This group is currently full.':'This group is not accepting new members right now.'}</strong><span>You can check other Friendship Groups from the group directory.</span></div></div>:<form action={requestGroupMembership} className="join-form"><input type="hidden" name="group_id" value={group.id}/><input type="hidden" name="church_id" value={churchId}/><label className="field"><span>Optional note to the group leader</span><textarea name="message" rows={3} maxLength={1000} placeholder="Introduce yourself or share why you’d like to connect with this group."/></label><button className="btn"><UserPlus size={14}/> Request to join</button><p className="small muted">The leader/co-leader will review your request. Your exact meeting address stays private until you are added to the group.</p></form>}
  </section>
}
