'use client'

import Link from 'next/link'
import {useSearchParams} from 'next/navigation'
import {useMemo,useState} from 'react'
import {useFormStatus} from 'react-dom'
import {BookOpen,Calendar,Check,ChevronRight,Clock,Crown,FileText,HandHeart,Home,MapPin,MoreHorizontal,Play,Search,Send,UserPlus,Users,X} from 'lucide-react'
import {savePortalAttendance} from './attendance-actions'
import {saveGroupGuidelines} from './guidelines-actions'

type GroupInfo={id:string;name:string;description?:string|null;schedule:string;day?:string|null;time?:string|null;place:string;memberCount:number;attendanceAverage:number|null}
type RosterMember={userId:string;name:string;role:string;avatarPath?:string|null}
type Report={id:string;meeting_date:string;attendance_count:number;first_time_guests:number;prayer_needs?:string|null;general_notes?:string|null;created_at:string}
type Lesson={id:string;scheduledFor:string;status:string;teachingNote?:string|null;title:string;lessonNumber?:number|null;assetPath?:string|null}
type Prayer={id:string;user_id:string;name:string;body:string;status:string;created_at:string}
type BrowseGroup={id:string;name:string;leader:string;day?:string|null;time?:string|null;frequency?:string|null;place:string;members:number;capacity?:number|null;acceptingMembers:boolean}
type WeeklyRole={id:string;userId:string;name:string;roleLabel:string}
type AttendanceStatus='on_time'|'late'|'missing'
type LeaderSummary={reportSubmitted:boolean;nextLesson:{title:string;date:string}|null;openPrayerCount:number;weeklyRoleCount:number}
type Lang='en'|'es'

type Props={group:GroupInfo;roster:RosterMember[];reports:Report[];lessons:Lesson[];prayers:Prayer[];allGroups:BrowseGroup[];canManage:boolean;canReport:boolean;canViewPrivate:boolean;currentGroupId:string;attendanceDraft:Record<string,AttendanceStatus>;meetingDate:string;attendanceSaved:boolean;portalErrorCode:string|null;initialTab:string;guidelines:string;guidelinesSaved:boolean;weeklyRoles:WeeklyRole[];scheduleId:string|null;lang:Lang;leaderSummary:LeaderSummary}

const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()).join('')||'KN'
const fmtDate=(value:string,lang:Lang)=>new Date(value+'T12:00:00').toLocaleDateString(lang==='es'?'es-US':'en-US',{month:'short',day:'numeric',year:'numeric'})
const copy={
  en:{portal:'Friendship Group Portal',find:'Find a Group',lead:'You lead',belong:'You belong to',browseChurch:'Browse Friendship Groups in your church',myGroup:'My Group',leader:'Leader',browse:'Browse All Groups',overview:'Overview',attendance:'Attendance',report:'Report',lessons:'Lessons',members:'Members',prayer:'Prayer',saved:'SAVED',guidelinesUpdated:'Group guidelines updated.',attention:'ATTENTION',thisWeek:'THIS WEEK',edit:'Edit',membersLabel:'GROUP MEMBERS',avg:'AVG. ATTENDANCE',guidelines:'GROUP GUIDELINES / FOUR G\'S',grow:'How our group grows together',noGuidelines:'Your group leader has not added the group framework yet.',editGuidelines:'Edit guidelines',framework:'GROUP FRAMEWORK',saveGuidelines:'Save Group Guidelines',saving:'Saving…',quick:'QUICK ACTIONS',takeAttendance:'Take attendance for this week',fillReport:'Fill out & send weekly report',inviteRoles:'Invite someone / assign weekly roles',continue:'Continue',attendanceSaved:'Attendance saved for',weeklyAttendance:'Weekly Attendance',marked:'marked',editable:'Editable',viewOnly:'View only',present:'Mark present',absent:'Mark absent',saveAttendance:'Save Attendance',savingAttendance:'Saving Attendance…',attendancePrivacy:'Saved attendance stays private to authorized group leadership until the weekly report is finalized. Existing member self check-in still uses its protected time-window rules.',openRoll:'Open Leader Roll Sheet & History',weeklyReport:'WEEKLY REPORT',presentStat:'PRESENT',firstTime:'FIRST-TIME',prayerNotes:'PRAYER REQUESTS / NOTES',leadershipKnow:'Anything leadership should know about this week...',openReport:'Open Working Report Form',viewGroup:'View Group',pastReports:'PAST REPORTS',noReports:'No reports yet.',uploadLesson:'Upload / Schedule a Lesson',scheduled:'Scheduled',noLessons:'No lessons have been scheduled yet.',weeklyRoles:'THIS WEEK\'S ROLES',noRoles:'No weekly roles are assigned yet.',assignRoles:'Assign / Edit Weekly Roles',setupRoles:'Set Up Weekly Roles',groupMembers:'GROUP MEMBERS',inviteRoster:'Invite / Manage Roster',groupLeader:'Group Leader',assistant:'Assistant',member:'Member',noRoster:'No roster entries are visible for this account.',addPrayer:'Add a Prayer Request',answered:'ANSWERED',prayerChip:'PRAYER',noPrayer:'No group-shared prayer requests yet.',search:'Search groups...',ledBy:'Led by',dayTbd:'Day TBD',timeTbd:'Time TBD',openMyGroup:'Open My Group',viewJoin:'View / Join This Group',home:'Home',journey:'My Journey',connect:'Connect',events:'Events',more:'More',leaderWeek:'LEADER THIS WEEK',reportDone:'Report submitted',reportDue:'Weekly report due',lessonNext:'Next lesson',lessonNone:'No lesson scheduled',prayerOpen:'Prayer items',rolesCount:'Weekly roles',done:'Done',needsAction:'Needs action'},
  es:{portal:'Portal del Grupo de Amistad',find:'Buscar un grupo',lead:'Tú lideras',belong:'Perteneces a',browseChurch:'Explora los Grupos de Amistad de tu iglesia',myGroup:'Mi Grupo',leader:'Líder',browse:'Explorar Grupos',overview:'Resumen',attendance:'Asistencia',report:'Reporte',lessons:'Lecciones',members:'Miembros',prayer:'Oración',saved:'GUARDADO',guidelinesUpdated:'Las guías del grupo fueron actualizadas.',attention:'ATENCIÓN',thisWeek:'ESTA SEMANA',edit:'Editar',membersLabel:'MIEMBROS DEL GRUPO',avg:'ASISTENCIA PROMEDIO',guidelines:'GUÍAS DEL GRUPO / CUATRO G',grow:'Cómo crece nuestro grupo unido',noGuidelines:'El líder todavía no ha agregado las guías del grupo.',editGuidelines:'Editar guías',framework:'MARCO DEL GRUPO',saveGuidelines:'Guardar guías del grupo',saving:'Guardando…',quick:'ACCIONES RÁPIDAS',takeAttendance:'Tomar asistencia de esta semana',fillReport:'Completar y enviar reporte semanal',inviteRoles:'Invitar a alguien / asignar roles',continue:'Continuar',attendanceSaved:'Asistencia guardada para',weeklyAttendance:'Asistencia semanal',marked:'marcados',editable:'Editable',viewOnly:'Solo lectura',present:'Marcar presente',absent:'Marcar ausente',saveAttendance:'Guardar asistencia',savingAttendance:'Guardando asistencia…',attendancePrivacy:'La asistencia guardada permanece privada para líderes autorizados hasta finalizar el reporte semanal. El registro personal sigue usando sus reglas protegidas de horario.',openRoll:'Abrir lista del líder e historial',weeklyReport:'REPORTE SEMANAL',presentStat:'PRESENTES',firstTime:'PRIMERA VEZ',prayerNotes:'PETICIONES / NOTAS',leadershipKnow:'Algo que el liderazgo deba saber esta semana...',openReport:'Abrir formulario de reporte',viewGroup:'Ver grupo',pastReports:'REPORTES ANTERIORES',noReports:'Todavía no hay reportes.',uploadLesson:'Subir / programar una lección',scheduled:'Programada',noLessons:'Todavía no hay lecciones programadas.',weeklyRoles:'ROLES DE ESTA SEMANA',noRoles:'Todavía no hay roles semanales asignados.',assignRoles:'Asignar / editar roles',setupRoles:'Configurar roles semanales',groupMembers:'MIEMBROS DEL GRUPO',inviteRoster:'Invitar / administrar lista',groupLeader:'Líder del Grupo',assistant:'Asistente',member:'Miembro',noRoster:'No hay miembros visibles para esta cuenta.',addPrayer:'Agregar petición de oración',answered:'CONTESTADA',prayerChip:'ORACIÓN',noPrayer:'Todavía no hay peticiones compartidas con el grupo.',search:'Buscar grupos...',ledBy:'Liderado por',dayTbd:'Día pendiente',timeTbd:'Hora pendiente',openMyGroup:'Abrir Mi Grupo',viewJoin:'Ver / Unirme',home:'Inicio',journey:'Mi Camino',connect:'Conectar',events:'Eventos',more:'Más',leaderWeek:'LÍDER — ESTA SEMANA',reportDone:'Reporte enviado',reportDue:'Reporte semanal pendiente',lessonNext:'Próxima lección',lessonNone:'No hay lección programada',prayerOpen:'Peticiones activas',rolesCount:'Roles semanales',done:'Listo',needsAction:'Requiere acción'}
} as const

const errors:Record<Lang,Record<string,string>>={
  en:{attendance_access:'Leader or assistant access is required to save attendance.',attendance_empty:'Mark at least one person before saving attendance.',attendance_invalid:'No valid roster attendance was selected.',attendance_save:'We could not save attendance. Please try again.',guidelines_too_long:'Group guidelines must be 5,000 characters or fewer.',guidelines_access:'Group leader access is required to edit these guidelines.',guidelines_save:'We could not save the group guidelines. Please try again.'},
  es:{attendance_access:'Se requiere acceso de líder o asistente para guardar asistencia.',attendance_empty:'Marca por lo menos una persona antes de guardar la asistencia.',attendance_invalid:'No se seleccionó una asistencia válida de la lista.',attendance_save:'No pudimos guardar la asistencia. Inténtalo otra vez.',guidelines_too_long:'Las guías del grupo deben tener 5,000 caracteres o menos.',guidelines_access:'Se requiere acceso de líder para editar estas guías.',guidelines_save:'No pudimos guardar las guías del grupo. Inténtalo otra vez.'}
}

function AttendanceSaveButton({disabled,lang}:{disabled:boolean;lang:Lang}){const {pending}=useFormStatus(),t=copy[lang];return <button className="fgp-primary" disabled={disabled||pending} aria-disabled={disabled||pending}>{pending?t.savingAttendance:t.saveAttendance}</button>}
function GuidelinesSaveButton({lang}:{lang:Lang}){const {pending}=useFormStatus(),t=copy[lang];return <button className="fgp-primary" disabled={pending} aria-disabled={pending}>{pending?t.saving:t.saveGuidelines}</button>}

export function FriendshipPortalClient({group,roster,reports,lessons,prayers,allGroups,canManage,canReport,canViewPrivate,currentGroupId,attendanceDraft,meetingDate,attendanceSaved,portalErrorCode,initialTab,guidelines,guidelinesSaved,weeklyRoles,scheduleId,lang,leaderSummary}:Props){
  const searchParams=useSearchParams(),initialBrowse=searchParams.get('view')==='browse',initialQuery=(searchParams.get('q')||'').slice(0,80)
  const t=copy[lang],[mode,setMode]=useState(canViewPrivate&&!initialBrowse?'group':'browse'),[tab,setTab]=useState(canReport||!['attendance','report'].includes(initialTab)?initialTab:'overview'),[query,setQuery]=useState(initialQuery)
  const [attendance,setAttendance]=useState<Record<string,boolean|null>>(()=>Object.fromEntries(roster.map(r=>[r.userId,attendanceDraft[r.userId]?attendanceDraft[r.userId]!=='missing':null])))
  const marked=Object.values(attendance).filter(v=>v!==null).length,filtered=useMemo(()=>allGroups.filter(g=>g.name.toLowerCase().includes(query.toLowerCase())),[allGroups,query])
  const tabs=canReport?[[ 'overview',t.overview],['attendance',t.attendance],['report',t.report],['lessons',t.lessons],['members',t.members],['prayer',t.prayer]]:[['overview',t.overview],['lessons',t.lessons],['members',t.members],['prayer',t.prayer]],roleManageHref=scheduleId?`/calendar/manage?schedule=${scheduleId}&lang=${lang}`:`/calendar/manage?lang=${lang}`,portalError=portalErrorCode?errors[lang][portalErrorCode]??null:null
  const memberRole=(role:string)=>role==='leader'?t.groupLeader:role==='assistant'?t.assistant:t.member
  const languageHref=`?tab=${encodeURIComponent(tab)}&lang=${lang==='es'?'en':'es'}${mode==='browse'?'&view=browse':''}${mode==='browse'&&query.trim()?`&q=${encodeURIComponent(query.trim().slice(0,80))}`:''}`

  return <main className="fgp-root"><div className="fgp-phone">
    <header className="fgp-brand"><Crown size={17}/><span>KINGDOM NETWORK</span><Link href={languageHref} className="fgp-lang-toggle">{lang==='es'?'EN':'ES'}</Link></header>
    <section className="fgp-title-row"><div><h1>{mode==='group'?t.portal:t.find}</h1><p>{mode==='group'?`${canManage?t.lead:t.belong}: ${group.name}`:t.browseChurch}</p></div></section>
    <div className="fgp-mode-switch"><button type="button" className={mode==='group'?'active':''} onClick={()=>setMode('group')} disabled={!canViewPrivate}>{t.myGroup}{canManage?` (${t.leader})`:''}</button><button type="button" className={mode==='browse'?'active':''} onClick={()=>setMode('browse')}>{t.browse}</button></div>

    {mode==='group'?<>
      <nav className="fgp-tabs" aria-label={t.portal}>{tabs.map(([key,label])=><button key={key} type="button" className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
      {tab==='overview'&&<section className="fgp-section">
        {guidelinesSaved&&<article className="fgp-card"><span className="fgp-kicker">{t.saved}</span><strong>{t.guidelinesUpdated}</strong></article>}
        {portalError&&<article className="fgp-card" role="alert"><span className="fgp-kicker">{t.attention}</span><strong>{portalError}</strong></article>}
        <article className="fgp-week-card"><div className="fgp-week-head"><div><span className="fgp-kicker">{t.thisWeek}</span><h2>{group.name}</h2></div>{canManage&&<Link href={`/groups/${currentGroupId}?lang=${lang}`} className="fgp-subtle-button">{t.edit}</Link>}</div><div className="fgp-gold-divider"/><div className="fgp-facts"><span><Calendar size={15}/>{group.day||group.schedule}</span><span><Clock size={15}/>{group.time?String(group.time).slice(0,5):t.timeTbd}</span><span><MapPin size={15}/>{group.place}</span></div></article>
        {canReport&&<article className="fgp-card"><span className="fgp-kicker">{t.leaderWeek}</span><button type="button" className="fgp-action-row" onClick={()=>setTab('report')}><span>{leaderSummary.reportSubmitted?t.reportDone:t.reportDue}</span><span className="fgp-chip">{leaderSummary.reportSubmitted?t.done:t.needsAction}</span></button><button type="button" className="fgp-action-row" onClick={()=>setTab('lessons')}><span>{t.lessonNext}: {leaderSummary.nextLesson?.title||t.lessonNone}</span><ChevronRight size={15}/></button><button type="button" className="fgp-action-row" onClick={()=>setTab('prayer')}><span>{t.prayerOpen}</span><span className="fgp-chip">{leaderSummary.openPrayerCount}</span></button><button type="button" className="fgp-action-row" onClick={()=>setTab('members')}><span>{t.rolesCount}</span><span className="fgp-chip">{leaderSummary.weeklyRoleCount}</span></button></article>}
        <div className="fgp-stat-grid"><article className="fgp-card fgp-stat"><strong>{group.memberCount}</strong><span>{t.membersLabel}</span></article><article className="fgp-card fgp-stat"><strong>{group.attendanceAverage==null?'—':`${group.attendanceAverage}%`}</strong><span>{t.avg}</span></article></div>
        <article className="fgp-card"><span className="fgp-kicker">{t.guidelines}</span><h3>{t.grow}</h3><p className="fgp-guidelines-copy">{guidelines||t.noGuidelines}</p>{canManage&&<details className="fgp-editor"><summary className="fgp-subtle-button">{t.editGuidelines}</summary><form action={saveGroupGuidelines}><input type="hidden" name="group_id" value={currentGroupId}/><input type="hidden" name="lang" value={lang}/><label className="fgp-field"><span>{t.framework}</span><textarea name="body" rows={7} maxLength={5000} defaultValue={guidelines}/></label><GuidelinesSaveButton lang={lang}/></form></details>}</article>
        {canReport&&<><article className="fgp-card"><span className="fgp-kicker">{t.quick}</span><button type="button" className="fgp-action-row" onClick={()=>setTab('attendance')}><span className="fgp-action-icon"><Check size={14}/></span><span>{t.takeAttendance}</span><ChevronRight size={15}/></button><button type="button" className="fgp-action-row" onClick={()=>setTab('report')}><span className="fgp-action-icon"><Send size={14}/></span><span>{t.fillReport}</span><ChevronRight size={15}/></button><button type="button" className="fgp-action-row" onClick={()=>setTab('members')}><span className="fgp-action-icon"><UserPlus size={14}/></span><span>{t.inviteRoles}</span><ChevronRight size={15}/></button></article><button type="button" className="fgp-primary" onClick={()=>setTab('attendance')}>{t.continue}</button></>}
      </section>}

      {tab==='attendance'&&canReport&&<section className="fgp-section">{attendanceSaved&&<article className="fgp-card"><span className="fgp-kicker">{t.saved}</span><strong>{t.attendanceSaved} {fmtDate(meetingDate,lang)}.</strong></article>}{portalError&&<article className="fgp-card" role="alert"><span className="fgp-kicker">{t.attention}</span><strong>{portalError}</strong></article>}<form action={savePortalAttendance}><input type="hidden" name="group_id" value={currentGroupId}/><input type="hidden" name="meeting_date" value={meetingDate}/><input type="hidden" name="lang" value={lang}/><article className="fgp-card fgp-section-head"><div><strong>{t.weeklyAttendance} · {fmtDate(meetingDate,lang)}</strong><span>{marked} / {roster.length} {t.marked}</span></div><span className="fgp-chip">{t.editable}</span></article>{roster.map(member=><article className="fgp-card fgp-person" key={member.userId}><div className="fgp-person-main"><span className="fgp-avatar">{initials(member.name)}</span><div><strong>{member.name}</strong><span>{memberRole(member.role)}</span></div></div><div className="fgp-attendance-buttons"><button type="button" aria-label={`${t.present}: ${member.name}`} className={attendance[member.userId]===true?'yes active':'yes'} onClick={()=>setAttendance(s=>({...s,[member.userId]:true}))}><Check size={16}/></button><button type="button" aria-label={`${t.absent}: ${member.name}`} className={attendance[member.userId]===false?'no active':'no'} onClick={()=>setAttendance(s=>({...s,[member.userId]:false}))}><X size={16}/></button></div>{attendance[member.userId]!==null&&<input type="hidden" name={`attendance_${member.userId}`} value={attendance[member.userId]?'on_time':'missing'}/>}</article>)}<AttendanceSaveButton disabled={marked===0} lang={lang}/></form><p className="fgp-dev-note">{t.attendancePrivacy}</p>{canManage&&<Link className="fgp-secondary-action" href={`/groups/${currentGroupId}/roster?lang=${lang}`}><Users size={16}/> {t.openRoll}</Link>}</section>}

      {tab==='report'&&canReport&&<section className="fgp-section"><article className="fgp-card"><span className="fgp-kicker">{t.weeklyReport}</span><div className="fgp-report-stats"><div><strong>{reports[0]?.attendance_count??0}</strong><span>{t.presentStat}</span></div><div><strong>{reports[0]?.first_time_guests??0}</strong><span>{t.firstTime}</span></div></div><label className="fgp-field"><span>{t.prayerNotes}</span><textarea rows={4} defaultValue={reports[0]?.prayer_needs||''} placeholder={t.leadershipKnow}/></label><Link className="fgp-primary fgp-link-button" href={`/groups/${currentGroupId}?lang=${lang}`}>{t.openReport}</Link></article><span className="fgp-kicker fgp-history-title">{t.pastReports}</span>{reports.map(r=><article className="fgp-card fgp-report-row" key={r.id}><div><strong>{fmtDate(r.meeting_date,lang)}</strong><span>{r.attendance_count} {t.presentStat.toLowerCase()} · {r.first_time_guests} {t.firstTime.toLowerCase()}</span></div><FileText size={16}/></article>)}{!reports.length&&<article className="fgp-card fgp-empty">{t.noReports}</article>}</section>}

      {tab==='lessons'&&<section className="fgp-section">{canManage&&<Link className="fgp-secondary-action" href={`/groups/${currentGroupId}/lessons?lang=${lang}`}><BookOpen size={16}/> {t.uploadLesson}</Link>}{lessons.map(l=><article className="fgp-card fgp-lesson" key={l.id}><span className="fgp-lesson-icon"><Play size={16}/></span><div><strong>{l.title}</strong><span>{fmtDate(l.scheduledFor,lang)}{l.lessonNumber?` · ${lang==='es'?'Lección':'Lesson'} ${l.lessonNumber}`:''}</span></div>{l.status==='scheduled'&&<span className="fgp-chip">{t.scheduled}</span>}</article>)}{!lessons.length&&<article className="fgp-card fgp-empty">{t.noLessons}</article>}</section>}

      {tab==='members'&&<section className="fgp-section"><span className="fgp-kicker fgp-history-title">{t.weeklyRoles} · {fmtDate(meetingDate,lang)}</span>{weeklyRoles.map(role=><article className="fgp-card fgp-person" key={role.id}><div className="fgp-person-main"><span className="fgp-avatar">{initials(role.name)}</span><div><strong>{role.name}</strong><span>{role.roleLabel}</span></div></div><span className="fgp-chip">{role.roleLabel.toUpperCase()}</span></article>)}{!weeklyRoles.length&&<article className="fgp-card fgp-empty">{t.noRoles}</article>}{canReport&&<Link className="fgp-secondary-action" href={roleManageHref}><Calendar size={16}/>{scheduleId?t.assignRoles:t.setupRoles}</Link>}<span className="fgp-kicker fgp-history-title">{t.groupMembers}</span>{canManage&&<Link className="fgp-secondary-action" href={`/groups/${currentGroupId}/roster?lang=${lang}`}><UserPlus size={16}/> {t.inviteRoster}</Link>}{roster.map(member=><article className="fgp-card fgp-person" key={member.userId}><div className="fgp-person-main"><span className="fgp-avatar">{initials(member.name)}</span><div><strong>{member.name}</strong><span>{memberRole(member.role)}</span></div></div><span className="fgp-chip">{memberRole(member.role).toUpperCase()}</span></article>)}{!roster.length&&<article className="fgp-card fgp-empty">{t.noRoster}</article>}</section>}

      {tab==='prayer'&&<section className="fgp-section"><Link className="fgp-secondary-action" href={`/prayer?lang=${lang}`}><HandHeart size={16}/> {t.addPrayer}</Link>{prayers.map(p=><article className="fgp-card" key={p.id}><div className="fgp-prayer-head"><strong>{p.name}</strong><span className="fgp-chip">{p.status==='answered'?t.answered:t.prayerChip}</span></div><p className="fgp-prayer-body">{p.body}</p><span className="fgp-muted-small">{new Date(p.created_at).toLocaleString(lang==='es'?'es-US':'en-US')}</span></article>)}{!prayers.length&&<article className="fgp-card fgp-empty">{t.noPrayer}</article>}</section>}
    </>:<section className="fgp-section"><label className="fgp-search"><Search size={15}/><input value={query} maxLength={80} onChange={e=>setQuery(e.target.value.slice(0,80))} placeholder={t.search}/></label>{filtered.map(g=><article className="fgp-card" key={g.id}><div className="fgp-browse-head"><div><h2>{g.name}</h2><span>{t.ledBy} {g.leader}</span></div><span className="fgp-chip">{g.members} {t.members.toLowerCase()}</span></div><div className="fgp-facts browse"><span><Calendar size={13}/>{g.day||t.dayTbd}</span><span><Clock size={13}/>{g.time?String(g.time).slice(0,5):t.timeTbd}</span><span><MapPin size={13}/>{g.place}</span></div><Link className="fgp-primary fgp-link-button" href={`/groups/${g.id}?lang=${lang}`}>{g.id===currentGroupId&&canViewPrivate?t.openMyGroup:g.acceptingMembers?t.viewJoin:t.viewGroup}</Link></article>)}</section>}

    <nav className="fgp-bottom-nav" aria-label="Kingdom Network"><Link href={`/?lang=${lang}`}><Home size={18}/><span>{t.home}</span></Link><Link href={`/journey?lang=${lang}`}><BookOpen size={18}/><span>{t.journey}</span></Link><Link href={`/groups?lang=${lang}`} className="active"><Users size={18}/><span>{t.connect}</span></Link><Link href={`/events?lang=${lang}`}><Calendar size={18}/><span>{t.events}</span></Link><Link href={`/?lang=${lang}`}><MoreHorizontal size={18}/><span>{t.more}</span></Link></nav>
  </div></main>
}
