import Link from 'next/link'
import {redirect} from 'next/navigation'
import {BookOpen,CalendarDays,Church,Search,Users} from 'lucide-react'
import {createClient} from '@/lib/supabase/server'

const clean=(v:string)=>v.trim().replace(/\s+/g,' ').slice(0,120)
const terms=(q:string)=>{const words=q.toLowerCase().split(' ').filter(Boolean);const synonyms:Record<string,string[]>= {class:['course','learning'],classes:['course','learning'],lesson:['course','learning'],people:['member','person'],person:['member'],friend:['group'],groups:['group'],event:['calendar'],events:['calendar'],business:['business']};return Array.from(new Set([...words,...words.flatMap(w=>synonyms[w]??[])]))}
const match=(hay:string,q:string)=>{const h=hay.toLowerCase(),ts=terms(q);return ts.every(t=>h.includes(t))||h.includes(q.toLowerCase())}

export default async function UniversalSearch({searchParams}:{searchParams:Promise<{q?:string}>}){
 const query=clean((await searchParams).q||''),supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect('/login')
 const {data:m}=await supabase.from('church_memberships').select('church_id,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!m?.church_id)redirect('/')
 let people:any[]=[],courses:any[]=[],groups:any[]=[],events:any[]=[],businesses:any[]=[]
 if(query){const [directory,courseResult,groupResult,eventResult,businessResult]=await Promise.all([
   supabase.rpc('church_directory_members',{p_church_id:m.church_id}),
   supabase.from('courses').select('id,title,description,category').eq('church_id',m.church_id).eq('published',true).limit(100),
   supabase.from('groups').select('id,name,description,meeting_day,location_label').eq('church_id',m.church_id).eq('active',true).limit(100),
   supabase.from('events').select('id,title,description,starts_at,location').eq('church_id',m.church_id).gte('starts_at',new Date(Date.now()-86400000).toISOString()).order('starts_at').limit(100),
   supabase.from('business_listings').select('id,name,category,description,city,state,is_member_business,is_sponsored').eq('church_id',m.church_id).eq('status','approved').limit(100)
  ]);people=(directory.data??[]).filter((p:any)=>match([p.display_name,p.first_name,p.last_name,p.bio,p.role].filter(Boolean).join(' '),query)).slice(0,12);courses=(courseResult.data??[]).filter((x:any)=>match([x.title,x.description,x.category].filter(Boolean).join(' '),query)).slice(0,12);groups=(groupResult.data??[]).filter((x:any)=>match([x.name,x.description,x.meeting_day,x.location_label].filter(Boolean).join(' '),query)).slice(0,12);events=(eventResult.data??[]).filter((x:any)=>match([x.title,x.description,x.location,'event calendar'].filter(Boolean).join(' '),query)).slice(0,12);businesses=(businessResult.data??[]).filter((x:any)=>match([x.name,x.category,x.description,x.city,x.state,'business'].filter(Boolean).join(' '),query)).slice(0,12)}
 const total=people.length+courses.length+groups.length+events.length+businesses.length,church:any=Array.isArray(m.churches)?m.churches[0]:m.churches
 return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name||'Church'} • Search</div></div><Link className="ghost" href="/">← Home</Link></header><section className="hero card"><div><div className="pill"><Search size={12}/> UNIVERSAL SEARCH</div><h1>Find it without knowing the tab.</h1><p>Search people, classes, groups, events and approved businesses in plain language. Results still obey the same privacy and church permissions as their original screens.</p><form action="/search" method="get" className="row" style={{marginTop:14,gap:8}}><input name="q" defaultValue={query} placeholder="Try “Bible class”, “Tuesday group”, or a person’s name" style={{flex:1,minWidth:220}}/><button className="btn">Search</button></form></div>{query&&<div className="hero-stat"><strong>{total}</strong><span>results</span></div>}</section>
 {!query?<section className="card empty"><Search size={30}/><h3>What are you looking for?</h3><p className="muted">You can search naturally. You do not need to remember which Kingdom Network section owns the information.</p></section>:total===0?<section className="card empty"><Search size={30}/><h3>No results found.</h3><p className="muted">Try a shorter phrase or a person, class, group, event, ministry or business name.</p></section>:<div style={{display:'grid',gap:18}}>{people.length>0&&<section><div className="section-heading"><div><div className="pill">PEOPLE</div><h2>Church directory</h2></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10}}>{people.map((p:any)=><Link href="/directory" className="card" style={{padding:14,textDecoration:'none'}} key={p.user_id}><Users size={17}/><strong style={{display:'block',marginTop:5}}>{p.display_name||[p.first_name,p.last_name].filter(Boolean).join(' ')}</strong><span className="small muted">{p.role?.replaceAll('_',' ')||'Member'}</span></Link>)}</div></section>}{courses.length>0&&<section><div className="section-heading"><div><div className="pill">LEARNING</div><h2>Classes</h2></div></div><div style={{display:'grid',gap:9}}>{courses.map((x:any)=><Link href={`/learning/${x.id}`} className="card" style={{padding:14,textDecoration:'none'}} key={x.id}><BookOpen size={16}/><strong>{x.title}</strong><div className="small muted">{x.description||x.category}</div></Link>)}</div></section>}{groups.length>0&&<section><div className="section-heading"><div><div className="pill">GROUPS</div><h2>Friendship Groups</h2></div></div><div style={{display:'grid',gap:9}}>{groups.map((x:any)=><Link href={`/groups/${x.id}`} className="card" style={{padding:14,textDecoration:'none'}} key={x.id}><Users size={16}/><strong>{x.name}</strong><div className="small muted">{[x.meeting_day,x.location_label].filter(Boolean).join(' • ')}</div></Link>)}</div></section>}{events.length>0&&<section><div className="section-heading"><div><div className="pill">EVENTS</div><h2>Calendar</h2></div></div><div style={{display:'grid',gap:9}}>{events.map((x:any)=><Link href="/calendar" className="card" style={{padding:14,textDecoration:'none'}} key={x.id}><CalendarDays size={16}/><strong>{x.title}</strong><div className="small muted">{new Date(x.starts_at).toLocaleDateString()} {x.location?`• ${x.location}`:''}</div></Link>)}</div></section>}{businesses.length>0&&<section><div className="section-heading"><div><div className="pill">BUSINESS PARTNERS</div><h2>Member businesses</h2></div></div><div style={{display:'grid',gap:9}}>{businesses.map((x:any)=><Link href="/business" className="card" style={{padding:14,textDecoration:'none'}} key={x.id}><Church size={16}/><strong>{x.name}</strong><div className="small muted">{[x.category,x.city,x.state].filter(Boolean).join(' • ')}{x.is_sponsored?' • Sponsored':''}</div></Link>)}</div></section>}</div>}
 </main>
}
