import Link from 'next/link'
import { redirect } from 'next/navigation'
import { FileCheck2,FileText,Languages,MessageSquareWarning,ShieldCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { DocumentUploader } from './document-uploader'
import { verifyDocument } from './actions'
import './documents.css'

const pendingStatuses=new Set(['pending_review','member_uploaded','needs_review'])
const statusPriority=(v:string)=>pendingStatuses.has(v)?0:v==='rejected'?1:v==='verified'?2:3

export default async function DocumentsPage({searchParams}:{searchParams:Promise<{error?:string;reviewed?:string;lang?:string}>}){
  const query=await searchParams,es=query.lang==='es',t=(en:string,sp:string)=>es?sp:en,l=(path:string)=>es?`${path}${path.includes('?')?'&':'?'}lang=es`:path
  const fmt=(v?:string|null)=>v?new Date(`${v}T12:00:00`).toLocaleDateString(es?'es-US':'en-US',{month:'short',day:'numeric',year:'numeric'}):'—'
  const statusLabel=(v:string)=>pendingStatuses.has(v)?t('Pending review','Pendiente de revisión'):v==='verified'?t('Verified','Verificado'):v==='rejected'?t('Rejected','Rechazado'):v.replaceAll('_',' ')
  const typeLabel=(v:string)=>v==='training_certificate'?t('Training certificate','Certificado de capacitación'):v==='credential'?t('Credential / license','Credencial / licencia'):v==='ministry_form'?t('Ministry form','Formulario de ministerio'):v==='covenant'?t('Covenant','Pacto'):v==='baptism_record'?t('Baptism record','Registro de bautismo'):v==='course_certificate'?t('Course certificate','Certificado de curso'):t('Other','Otro')
  const supabase=await createClient(),{data:claimsData}=await supabase.auth.getClaims(),userId=claimsData?.claims?.sub
  if(!userId)redirect(l('/login'))
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!membership?.church_id)redirect('/')
  const isAdmin=['pastor','church_admin'].includes(membership.role),church=Array.isArray(membership.churches)?membership.churches[0]:membership.churches as any
  const base=supabase.from('member_documents').select('*').eq('church_id',membership.church_id).order('created_at',{ascending:false}),{data:docs}=isAdmin?await base:await base.eq('owner_user_id',userId)
  const profileIds=Array.from(new Set((docs??[]).flatMap((d:any)=>[d.owner_user_id,d.verified_by]).filter(Boolean)));let profiles:any[]=[];if(profileIds.length){const result=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',profileIds);profiles=result.data??[]}
  const pm=new Map(profiles.map((p:any)=>[p.id,p])),person=(id?:string|null)=>{const p=id?pm.get(id):null;return p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||t('Church leader','Líder de iglesia')}
  const signedRows=await Promise.all((docs??[]).map(async(d:any)=>{const signed=await supabase.storage.from('member-documents').createSignedUrl(d.storage_path,60*10);return {...d,url:signed.data?.signedUrl??null}})),rows=[...signedRows].sort((a:any,b:any)=>isAdmin?(statusPriority(a.verification_status)-statusPriority(b.verification_status)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime()):new Date(b.created_at).getTime()-new Date(a.created_at).getTime())
  const verified=rows.filter((d:any)=>d.verification_status==='verified').length,pending=rows.filter((d:any)=>pendingStatuses.has(d.verification_status)).length,now=new Date(),in30=new Date(now.getTime()+30*86400000)

  return <main className="shell"><header className="topbar"><div><Link href={l('/')} className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??t('Your Church','Tu Iglesia')} • {t('Documents','Documentos')}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/documents?lang=en">English</Link><Link className="ghost" href="/documents?lang=es">Español</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/>{t('Feedback','Comentarios')}</Link><Link className="ghost" href={l('/')}>← {t('Home','Inicio')}</Link></div></header>
    <section className="documents-hero card"><div><div className="pill">{t('DOCUMENT VAULT','BÓVEDA DE DOCUMENTOS')}</div><h1>{t('Your certificates & records.','Tus certificados y registros.')}</h1><p className="muted">{t('Private documents, training records, ministry forms and verified credentials in one place.','Documentos privados, registros de capacitación, formularios y credenciales verificadas en un solo lugar.')}</p></div><div className="documents-stat"><strong>{verified}</strong><span>{t(`${verified===1?'verified document':'verified documents'} • ${pending} awaiting review`,`${verified===1?'documento verificado':'documentos verificados'} • ${pending} pendientes`)}</span></div></section>
    {query.reviewed&&<div className="notice success">{t('Document review saved. The member has been notified.','Revisión guardada. El miembro fue notificado.')}</div>}{query.error&&<div className="notice error">{query.error}</div>}

    <DocumentUploader churchId={membership.church_id} userId={userId} lang={es?'es':'en'}/>

    <div className="section-heading"><div><div className="pill">{isAdmin?t('CHURCH RECORDS','REGISTROS DE LA IGLESIA'):t('MY RECORDS','MIS REGISTROS')}</div><h2>{isAdmin?t('Documents needing attention appear first','Los documentos que necesitan atención aparecen primero'):t('My documents','Mis documentos')}</h2></div><span className="small muted">{isAdmin?t('Open Review only when you need to verify an item.','Abre Revisar solo cuando necesites verificar algo.'):t('Private storage with church verification.','Almacenamiento privado con verificación de la iglesia.')}</span></div>

    <section className="document-list">{rows.map((d:any)=>{const owner=person(d.owner_user_id),exp=d.expires_at?new Date(`${d.expires_at}T12:00:00`):null,expiryClass=exp&&exp<now?'expired':exp&&exp<in30?'expiring':'',normalizedStatus=pendingStatuses.has(d.verification_status)?'pending_review':d.verification_status;return <article className="card document-card" key={d.id}><div style={{flex:1}}><div className="document-main"><div className="document-icon">{d.verification_status==='verified'?<FileCheck2/>:<FileText/>}</div><div className="document-copy"><div className="row" style={{justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><h3>{d.title}</h3><span className={`status-chip ${normalizedStatus}`}>{statusLabel(normalizedStatus)}</span></div>{isAdmin&&<div className="doc-owner">{t('Owner','Propietario')}: <strong>{owner}</strong></div>}<p>{typeLabel(String(d.document_type))}{d.issuer?` • ${d.issuer}`:''}</p><div className="document-meta"><span>{t('Issued','Emitido')} {fmt(d.issued_at)}</span>{d.expires_at&&<span className={expiryClass}>{t('Expires','Vence')} {fmt(d.expires_at)}</span>}<span>{t('Uploaded','Subido')} {new Date(d.created_at).toLocaleDateString(es?'es-US':'en-US')}</span></div>{d.notes&&<p style={{marginTop:9}}>{d.notes}</p>}{d.verification_notes&&<p style={{marginTop:9}}><strong>{t('Review','Revisión')}:</strong> {d.verification_notes}</p>}{d.verification_status==='verified'&&d.verified_at&&<p className="small muted" style={{marginTop:8}}>{t('Verified by','Verificado por')} {person(d.verified_by)} • {new Date(d.verified_at).toLocaleDateString(es?'es-US':'en-US')}</p>}</div></div>
      {isAdmin&&<details style={{marginTop:12}}><summary className="ghost" style={{cursor:'pointer',display:'inline-flex'}}>{t('Review document','Revisar documento')}</summary><form action={verifyDocument} className="review-form" style={{marginTop:12}}><input type="hidden" name="document_id" value={d.id}/><input type="hidden" name="lang" value={es?'es':'en'}/><label><span>{t('Review status','Estado de revisión')}</span><select name="verification_status" defaultValue={normalizedStatus}><option value="pending_review">{t('Pending review','Pendiente')}</option><option value="verified">{t('Verified','Verificado')}</option><option value="rejected">{t('Rejected','Rechazado')}</option></select></label><label><span>{t('Review notes','Notas de revisión')}</span><input name="verification_notes" defaultValue={d.verification_notes??''} placeholder={t('Required when rejecting','Obligatorio al rechazar')}/></label><button className="btn">{t('Save review','Guardar revisión')}</button></form></details>}</div><div className="document-actions">{d.url&&<a className="ghost" href={d.url} target="_blank" rel="noreferrer">{t('Open','Abrir')}</a>}{d.verification_status==='verified'&&<ShieldCheck size={18}/>}</div></article>})}{!rows.length&&<div className="card empty"><h3>{t('No documents yet.','Todavía no hay documentos.')}</h3><p className="muted">{t('Use Upload a Document above when you are ready to add a certificate, credential or ministry record.','Usa Subir un Documento arriba cuando quieras agregar un certificado, credencial o registro de ministerio.')}</p></div>}</section>
  </main>
}