import Link from 'next/link'
import {redirect} from 'next/navigation'
import {CheckCircle2,HandHeart,Languages,LockKeyhole,MessageSquareWarning,Sparkles} from 'lucide-react'
import {createClient} from '@/lib/supabase/server'
import {createPrayerOrTestimony,setPrayerAnswered} from './actions'
import {togglePraying} from './reaction-actions'
import {PrayerPendingButton} from './pending-button'
import './prayer.css'

const personName=(p:any,fallback:string)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||fallback

const errorMessages={
 choice_missing:['Choose Prayer Request or Testimony.','Elige Petición de Oración o Testimonio.'],
 body_invalid:['Please write between 3 and 5,000 characters.','Escribe entre 3 y 5,000 caracteres.'],
 testimony_failed:['We could not share the testimony. Please try again.','No pudimos compartir el testimonio. Inténtalo otra vez.'],
 prayer_failed:['We could not submit the prayer request. Please try again.','No pudimos enviar la petición de oración. Inténtalo otra vez.'],
 answer_failed:['We could not update that prayer request. Please try again.','No pudimos actualizar esa petición. Inténtalo otra vez.'],
} as const

const successMessages={
 testimony_shared:['Testimony shared with your church family.','Testimonio compartido con tu familia de iglesia.'],
 prayer_submitted:['Prayer request submitted using the visibility you selected.','Petición enviada con la visibilidad que elegiste.'],
 answered:['Prayer marked answered.','Oración marcada como contestada.'],
} as const

type ErrorCode=keyof typeof errorMessages
type SuccessCode=keyof typeof successMessages

export default async function PrayerPage({searchParams}:{searchParams:Promise<{view?:string;share?:string;message_code?:string;error_code?:string;lang?:string}>}){
 const query=await searchParams,es=query.lang==='es',lang=es?'es':'en',t=(en:string,sp:string)=>es?sp:en,l=(path:string)=>es?`${path}${path.includes('?')?'&':'?'}lang=es`:path,supabase=await createClient(),{data:claims}=await supabase.auth.getClaims(),userId=claims?.claims?.sub
 if(!userId)redirect(l('/login'))
 const {data:membership}=await supabase.from('church_memberships').select('church_id,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!membership?.church_id)redirect('/')
 const church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches,view=['prayer','testimony'].includes(String(query.view))?String(query.view):'all',share=query.share==='testimony'?'testimony':'prayer_request'
 let postsQuery=supabase.from('community_posts').select('id,author_id,body,post_type,created_at,answered_at').eq('church_id',membership.church_id).in('post_type',['prayer_request','testimony']).order('created_at',{ascending:false}).limit(120);if(view==='prayer')postsQuery=postsQuery.eq('post_type','prayer_request');if(view==='testimony')postsQuery=postsQuery.eq('post_type','testimony')
 const [{data:posts},{data:myGroup},{data:myPrayerRows}]=await Promise.all([postsQuery,supabase.from('group_memberships').select('group_id,groups(name,group_type,active)').eq('user_id',userId),supabase.from('prayer_requests').select('id,community_post_id,status').eq('user_id',userId)])
 const rows=posts??[],postIds=rows.map((p:any)=>p.id),authorIds=Array.from(new Set(rows.map((p:any)=>p.author_id))),activeFriendship=(myGroup??[]).find((r:any)=>{const g=Array.isArray(r.groups)?r.groups[0]:r.groups;return g?.active&&g?.group_type==='friendship'}) as any,groupObj=activeFriendship?(Array.isArray(activeFriendship.groups)?activeFriendship.groups[0]:activeFriendship.groups):null
 let profiles:any[]=[],reactions:any[]=[];if(authorIds.length){const r=await supabase.from('profiles').select('id,display_name,first_name,last_name,avatar_path').in('id',authorIds);profiles=r.data??[]}if(postIds.length){const r=await supabase.from('post_reactions').select('post_id,user_id,reaction_type').in('post_id',postIds).eq('reaction_type','praying');reactions=r.data??[]}
 const pm=new Map(profiles.map((p:any)=>[p.id,p])),prayingCounts=new Map<string,number>(),mine=new Set<string>(),requestByPost=new Map((myPrayerRows??[]).filter((r:any)=>r.community_post_id).map((r:any)=>[r.community_post_id,r]));for(const r of reactions){prayingCounts.set(r.post_id,(prayingCounts.get(r.post_id)??0)+1);if(r.user_id===userId)mine.add(r.post_id)}
 const prayerCount=rows.filter((p:any)=>p.post_type==='prayer_request').length,testimonyCount=rows.filter((p:any)=>p.post_type==='testimony').length,errorCode=(query.error_code&&query.error_code in errorMessages?query.error_code:null) as ErrorCode|null,successCode=(query.message_code&&query.message_code in successMessages?query.message_code:null) as SuccessCode|null,errorMessage=errorCode?errorMessages[errorCode][es?1:0]:null,successMessage=successCode?successMessages[successCode][es?1:0]:null
 return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??t('Your Church','Tu Iglesia')} • {t('Prayer & Testimony','Oración y Testimonio')}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/prayer?lang=en">English</Link><Link className="ghost" href="/prayer?lang=es">Español</Link><Link className="ghost" href={l('/feedback')}><MessageSquareWarning size={14}/> {t('Feedback','Comentarios')}</Link><Link className="ghost" href={l('/')}>← {t('Home','Inicio')}</Link></div></header>
 <section className="prayer-hero card"><div><div className="pill">{t('PRAYER & TESTIMONY','ORACIÓN Y TESTIMONIO')}</div><h1>{t('Pray together. Remember what God has done.','Oremos juntos. Recordemos lo que Dios ha hecho.')}</h1><p className="muted">{t('Prayer requests start Private. Choose Public only when you want the church prayer board to see it. Friendship Group sharing is a separate choice.','Las peticiones empiezan como Privadas. Elige Pública solo cuando quieras que aparezca en el tablero de oración de la iglesia. Compartir con tu Grupo de Amistad es una opción separada.')}</p></div><div className="hero-stat"><HandHeart size={23}/><span>{prayerCount} {t('public prayers','oraciones públicas')} • {testimonyCount} {t('testimonies','testimonios')}</span></div></section>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginBottom:18}}><Link className="card" href={l('/prayer?share=prayer')} style={{padding:18}}><HandHeart size={24}/><h3>{t('Submit a Prayer Request','Enviar una Petición de Oración')}</h3><p className="small muted">{t('Private is selected first. Change it only if you want broader sharing.','Privada está seleccionada primero. Cámbiala solo si quieres compartir más ampliamente.')}</p></Link><Link className="card" href={l('/prayer?share=testimony')} style={{padding:18}}><Sparkles size={24}/><h3>{t('Share a Testimony','Compartir un Testimonio')}</h3><p className="small muted">{t('Tell your church family what God has done.','Cuéntale a tu familia de iglesia lo que Dios ha hecho.')}</p></Link><Link className="card" href={l('/journey#my-prayers')} style={{padding:18}}><CheckCircle2 size={24}/><h3>{t('My Prayer History','Mi Historial de Oración')}</h3><p className="small muted">{t('Look back at your own requests and when you submitted them.','Mira tus propias peticiones y cuándo las enviaste.')}</p></Link><Link className="card" href={l('/help')} style={{padding:18,border:'1px solid rgba(125,211,252,.28)'}}><LockKeyhole size={24}/><h3>{t('Private Pastoral Help','Ayuda Pastoral Privada')}</h3><p className="small muted">{t('For sensitive care that should go directly to pastoral care.','Para cuidado sensible que debe ir directamente al cuidado pastoral.')}</p></Link></section>
 {successMessage&&<div className="notice success" role="status" aria-live="polite">{successMessage}</div>}{errorMessage&&<div className="notice error" role="alert">{errorMessage}</div>}
 <details className="card" style={{padding:18,marginBottom:20}} open={Boolean(query.share)}><summary style={{fontWeight:800,cursor:'pointer'}}>{share==='testimony'?t('Write a testimony','Escribir un testimonio'):t('Write a prayer request','Escribir una petición de oración')}</summary><div style={{marginTop:14}}><form action={createPrayerOrTestimony} className="share-form"><input type="hidden" name="lang" value={lang}/><input type="hidden" name="post_type" value={share}/>{share==='prayer_request'&&<><fieldset className="card" style={{padding:14,border:'1px solid var(--line)'}}><legend style={{fontWeight:800}}>{t('Who may see this request?','¿Quién puede ver esta petición?')}</legend><label className="row" style={{alignItems:'flex-start',margin:'8px 0'}}><input type="radio" name="visibility" value="private" defaultChecked/><span><strong>{t('Private — recommended','Privada — recomendada')}</strong><div className="small muted">{t('It will not appear on the public church board. Use the separate Friendship Group choice below if you want your group to see it.','No aparecerá en el tablero público. Usa la opción separada de Grupo de Amistad abajo si quieres que tu grupo la vea.')}</div></span></label><label className="row" style={{alignItems:'flex-start',margin:'8px 0'}}><input type="radio" name="visibility" value="public"/><span><strong>{t('Public','Pública')}</strong><div className="small muted">{t('Signed-in members of this church may see it on the prayer board.','Los miembros de esta iglesia que hayan iniciado sesión pueden verla en el tablero.')}</div></span></label></fieldset><label className="row" style={{alignItems:'flex-start',margin:'12px 0'}}><input type="checkbox" name="share_with_group" disabled={!groupObj}/><span><strong>{t('Share with my Friendship Group','Compartir con mi Grupo de Amistad')}</strong><div className="small muted">{groupObj?t(`This will put it on the private prayer wall for ${groupObj.name}.`,`Esto la pondrá en el muro privado de oración de ${groupObj.name}.`):t('You are not in a Friendship Group yet. This option will become available after you join one.','Todavía no estás en un Grupo de Amistad. Esta opción estará disponible después de que te unas a uno.')}</div></span></label></>}<label><span>{share==='testimony'?t('What would you like to share?','¿Qué te gustaría compartir?'):t('How can we pray?','¿Cómo podemos orar?')}</span><textarea name="body" rows={6} required minLength={3} maxLength={5000} placeholder={share==='testimony'?t('Share what God has done…','Comparte lo que Dios ha hecho…'):t('Share your prayer need…','Comparte tu necesidad de oración…')}/></label><PrayerPendingButton lang={lang} idle={share==='testimony'?t('Share testimony','Compartir testimonio'):t('Submit prayer request','Enviar petición')} pending={share==='testimony'?t('Sharing testimony…','Compartiendo testimonio…'):t('Submitting prayer…','Enviando petición…')}/></form></div></details>
 <div className="row" style={{marginBottom:12,flexWrap:'wrap'}}><Link className={view==='all'?'btn':'ghost'} href={l('/prayer')}>{t('All public posts','Todo lo público')}</Link><Link className={view==='prayer'?'btn':'ghost'} href={l('/prayer?view=prayer')}>{t('Public Prayer Requests','Peticiones Públicas')}</Link><Link className={view==='testimony'?'btn':'ghost'} href={l('/prayer?view=testimony')}>{t('Testimonies','Testimonios')}</Link></div>
 <section className="prayer-list">{rows.map((p:any)=>{const author=personName(pm.get(p.author_id),t('Church member','Miembro de la iglesia')),isPrayer=p.post_type==='prayer_request',answered=Boolean(p.answered_at),own=p.author_id===userId,count=prayingCounts.get(p.id)??0,myRequest:any=requestByPost.get(p.id);return <article className="card prayer-card" key={p.id}><div className="prayer-head"><div className="prayer-person"><div className="avatar">{author.slice(0,1).toUpperCase()}</div><div><strong>{author}</strong><span>{new Date(p.created_at).toLocaleDateString(es?'es-US':'en-US')}</span></div></div><div className="prayer-tags"><span className="prayer-tag">{isPrayer?t('Prayer Request','Petición de Oración'):t('Testimony','Testimonio')}</span>{answered&&<span className="prayer-tag answered"><CheckCircle2 size={9}/> {t('Answered','Contestada')}</span>}</div></div><p>{p.body}</p><div className="prayer-actions">{isPrayer&&<form action={togglePraying}><input type="hidden" name="post_id" value={p.id}/><input type="hidden" name="lang" value={lang}/><PrayerPendingButton lang={lang} className={mine.has(p.id)?'btn':'ghost'} help="" idle={`${mine.has(p.id)?t('Praying','Orando'):t('I’m Praying','Estoy Orando')}${count?` • ${count}`:''}`} pending={t('Saving…','Guardando…')}/></form>}{isPrayer&&own&&myRequest&&!answered&&<form action={setPrayerAnswered}><input type="hidden" name="request_id" value={myRequest.id}/><input type="hidden" name="lang" value={lang}/><PrayerPendingButton lang={lang} className="ghost" help="" idle={t('Mark answered','Marcar contestada')} pending={t('Updating…','Actualizando…')}/></form>}{!isPrayer&&<span className="small muted"><Sparkles size={11}/> {t('Shared testimony','Testimonio compartido')}</span>}</div></article>})}{!rows.length&&<div className="card prayer-empty"><HandHeart size={24}/><h3>{t('Nothing public has been shared yet.','Todavía no se ha compartido nada público.')}</h3><p className="muted">{t('Private requests never appear in this public list.','Las peticiones privadas nunca aparecen en esta lista pública.')}</p></div>}</section>
 </main>
}
