import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CheckCircle2,ShieldCheck,UserPlus,Users,X } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { assignRole,createRole,removeRoleAssignment,updateRole } from './actions'

const permissionOptions=[
 ['view_leadership','View leadership tools',false],['manage_outreach','Manage evangelism & follow-up',false],['lead_own_group','Lead assigned Friendship Group',false],['manage_groups','Manage all Friendship Groups',false],['manage_learning','Manage classes & learning',false],['manage_calendar','Manage church calendar',false],['manage_ministries','Manage ministries & Serve',false],['manage_teams','Manage team schedules',false],['manage_members','Manage member records',false],['manage_media','Manage church media',false],['view_finance','View finance records',true],['manage_finance','Record & manage finance',true],['approve_finance','Approve finance requests',true]
] as const
const financeKeys=['view_finance','manage_finance','approve_finance'] as const
const roleHasFinance=(r:any)=>financeKeys.some(k=>Boolean(r?.permissions?.[k]))
const personName=(p:any)=>p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||'Member'

export default async function ChurchRolesPage({searchParams}:{searchParams:Promise<{created?:string;saved?:string;assigned?:string;removed?:string;error?:string}>}){
 const query=await searchParams,supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect('/login')
 const {data:membership}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!membership?.church_id||!['pastor','church_admin'].includes(membership.role))redirect('/')
 const churchId=membership.church_id,church:any=Array.isArray(membership.churches)?membership.churches[0]:membership.churches,isPastor=membership.role==='pastor'
 const [{data:roles},{data:assignments},{data:memberships}]=await Promise.all([
  supabase.from('church_roles').select('*').eq('church_id',churchId).order('active',{ascending:false}).order('name'),
  supabase.from('church_role_assignments').select('id,role_id,user_id,assigned_at').eq('church_id',churchId).order('assigned_at'),
  supabase.from('church_memberships').select('user_id,role').eq('church_id',churchId).eq('status','active')
 ])
 const memberIds=(memberships??[]).map((m:any)=>m.user_id);let profiles:any[]=[];if(memberIds.length){const p=await supabase.from('profiles').select('id,display_name,first_name,last_name').in('id',memberIds);profiles=p.data??[]}
 const pm=new Map(profiles.map((p:any)=>[p.id,p])),roleMap=new Map((roles??[]).map((r:any)=>[r.id,r]))
 return <main className="shell"><header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{church?.name??'Church'} • Roles & permissions</div></div><div className="row"><Link className="ghost" href="/church">← Church Admin</Link><Link className="ghost" href="/">Home</Link></div></header>
 <section className="hero card"><div><div className="pill">ROLES & PERMISSIONS</div><h1>Give people the right access — not all access.</h1><p>Use church titles like Minister, First Steps Director or Youth Leader, then choose exactly what that role is allowed to manage.</p></div><div className="hero-stat"><ShieldCheck size={24}/><strong>{(roles??[]).filter((r:any)=>r.active).length}</strong><span>active custom roles</span></div></section>
 {query.created&&<div className="notice success">Role created.</div>}{query.saved&&<div className="notice success">Role updated.</div>}{query.assigned&&<div className="notice success">Role assigned.</div>}{query.removed&&<div className="notice success">Role assignment removed.</div>}{query.error&&<div className="notice error">{query.error}</div>}
 <section className="card" style={{padding:20,marginBottom:18}}><div className="pill">IMPORTANT</div><h2 style={{margin:'8px 0 5px'}}>Church title and system access are separate.</h2><p className="muted" style={{margin:0}}>Pastor and Church Admin remain protected system roles. Custom roles add specific permissions without automatically granting full administration. Friendship Group leadership is scoped to the leader&apos;s assigned group. Finance permissions are Pastor-controlled and do not automatically belong to Church Admin.</p></section>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:14}}>{(roles??[]).map((role:any)=><article className="card" style={{padding:20}} key={role.id}><div className="row" style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><div className="pill">{role.active?'ACTIVE ROLE':'INACTIVE ROLE'}</div><h2 style={{margin:'8px 0 5px'}}>{role.name}</h2><p className="muted">{role.description||'Church-defined leadership role.'}</p>{roleHasFinance(role)&&<p className="small" style={{fontWeight:700}}>Sensitive finance role • Pastor-controlled</p>}</div><ShieldCheck size={20}/></div>
 <form action={updateRole} style={{display:'grid',gap:10}}><input type="hidden" name="role_id" value={role.id}/><label className="field"><span>Role name</span><input name="name" defaultValue={role.name} required disabled={!isPastor&&roleHasFinance(role)}/></label><label className="field"><span>Description</span><input name="description" defaultValue={role.description??''} disabled={!isPastor&&roleHasFinance(role)}/></label><div><strong className="small">Permissions</strong><div style={{display:'grid',gap:7,marginTop:8}}>{permissionOptions.map(([key,label,sensitive])=><label className="publish-check" key={key}><input type="checkbox" name={key} defaultChecked={Boolean(role.permissions?.[key])} disabled={(!isPastor&&sensitive)||(!isPastor&&roleHasFinance(role))}/><span>{label}{sensitive?' • Pastor only':''}</span></label>)}</div></div><label className="publish-check"><input type="checkbox" name="active" defaultChecked={Boolean(role.active)} disabled={!isPastor&&roleHasFinance(role)}/><span>Role is active and assignable</span></label><button className="ghost" disabled={!isPastor&&roleHasFinance(role)}>Save role</button></form>
 <div style={{marginTop:16,borderTop:'1px solid var(--line)',paddingTop:14}}><strong className="small">Assigned members</strong>{(assignments??[]).filter((a:any)=>a.role_id===role.id).map((a:any)=><div key={a.id} className="row" style={{justifyContent:'space-between',padding:'9px 0'}}><span>{personName(pm.get(a.user_id))}</span>{isPastor||!roleHasFinance(roleMap.get(a.role_id))?<form action={removeRoleAssignment}><input type="hidden" name="assignment_id" value={a.id}/><button className="icon-btn" aria-label="Remove role"><X size={14}/></button></form>:<span className="small muted">Pastor-controlled</span>}</div>)}{!(assignments??[]).some((a:any)=>a.role_id===role.id)&&<p className="small muted">Nobody assigned yet.</p>}</div></article>)}</section>
 <section className="card" style={{padding:20,marginTop:18}}><div className="pill">ASSIGN A ROLE</div><h2>Give a member a church role.</h2><form action={assignRole} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,alignItems:'end'}}><label className="field"><span>Member</span><select name="user_id" required defaultValue=""><option value="" disabled>Choose member</option>{(memberships??[]).map((m:any)=><option key={m.user_id} value={m.user_id}>{personName(pm.get(m.user_id))} — system: {String(m.role).replaceAll('_',' ')}</option>)}</select></label><label className="field"><span>Church role</span><select name="role_id" required defaultValue=""><option value="" disabled>Choose role</option>{(roles??[]).filter((r:any)=>r.active&&(isPastor||!roleHasFinance(r))).map((r:any)=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><button className="btn"><UserPlus size={15}/> Assign role</button></form>{!isPastor&&<p className="small muted" style={{marginTop:10}}>Finance-capable roles can only be assigned or removed by a Pastor.</p>}</section>
 <section className="card" style={{padding:20,marginTop:18}}><div className="pill">CREATE ROLE</div><h2>Create another church role.</h2><form action={createRole} style={{display:'grid',gap:12}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}><label className="field"><span>Role name</span><input name="name" required placeholder="e.g. First Steps Director"/></label><label className="field"><span>Description</span><input name="description" placeholder="What this leader is responsible for"/></label></div><div><strong className="small">Allowed to manage</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:7,marginTop:8}}>{permissionOptions.map(([key,label,sensitive])=><label className="publish-check" key={key}><input type="checkbox" name={key} disabled={!isPastor&&sensitive}/><span>{label}{sensitive?' • Pastor only':''}</span></label>)}</div></div><button className="btn" style={{justifySelf:'start'}}><CheckCircle2 size={15}/> Create role</button></form></section>
 </main>
}
