import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BookOpen,CheckCircle2,ClipboardCheck,FileText,GraduationCap,Languages,Plus,Sparkles,WandSparkles } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { addBuilderLesson,applyExtractionPlan,createCourseAssessmentShell,createLessonShells,generateExtractionPlan,saveBuilderCourse,saveSourceText } from './actions'

export default async function CourseBuilder({params,searchParams}:{params:Promise<{courseId:string}>,searchParams:Promise<{lang?:string}>}){
 const {courseId}=await params;const q=await searchParams;const lang=q.lang==='es'?'es':'en';const es=lang==='es';const l=(p:string)=>es?`${p}${p.includes('?')?'&':'?'}lang=es`:p
 const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect(l('/login'))
 const {data:m}=await supabase.from('church_memberships').select('church_id,role,churches(name)').eq('user_id',userId).eq('status','active').limit(1).single();if(!m?.church_id||!['minister','pastor','church_admin'].includes(m.role))redirect('/learning')
 const [{data:course},{data:modules},{data:assessments},{data:source}]=await Promise.all([
  supabase.from('courses').select('*').eq('id',courseId).eq('church_id',m.church_id).single(),
  supabase.from('course_modules').select('*').eq('course_id',courseId).order('position'),
  supabase.from('course_assessments').select('*').eq('course_id',courseId).order('created_at'),
  supabase.from('church_setup_uploads').select('id,file_name,category,notes,review_plan,status,source_text,extraction_plan,extraction_status').eq('church_id',m.church_id).eq('created_record_id',courseId).maybeSingle()
 ])
 if(!course)redirect('/learning/admin')
 const church:any=Array.isArray(m.churches)?m.churches[0]:m.churches,plan:any=source?.extraction_plan
 const hasLessons=(modules?.length??0)>0,hasAssessment=(assessments?.length??0)>0,hasBadge=Boolean(course.badge_name),readyCount=[hasLessons,hasAssessment,hasBadge,Boolean(course.description)].filter(Boolean).length
 return <main className="shell"><header className="topbar"><div><div className="brand">Course <span>Builder</span></div><div className="small muted">{church?.name||'Church'} • {course.title}</div></div><div className="row"><Languages size={14}/><Link className="ghost" href={`/learning/admin/course-builder/${courseId}?lang=en`}>English</Link><Link className="ghost" href={`/learning/admin/course-builder/${courseId}?lang=es`}>Español</Link><Link className="ghost" href={l('/learning/admin')}>← {es?'Aprendizaje':'Learning Admin'}</Link></div></header>
 <section className="hero card"><div><div className="pill"><Sparkles size={12}/> {es?'BORRADOR GUIADO':'GUIDED DRAFT'}</div><h1>{course.title}</h1><p>{es?'Convierte material aprobado en una clase estructurada sin publicar nada antes de tiempo.':'Turn approved source material into a structured course without publishing anything too early.'}</p></div><div className="hero-stat"><strong>{readyCount}/4</strong><span>{es?'piezas básicas listas':'core pieces ready'}</span></div></section>
 {source&&<section className="card" style={{padding:20,marginBottom:18}}><div className="pill"><WandSparkles size={12}/> {es?'EXTRACCIÓN ASISTIDA':'SOURCE-ASSISTED EXTRACTION'}</div><h2>{es?'De documento a estructura de curso':'From document to course structure'}</h2><p className="muted">{es?'Pega el texto extraído del manual. Kingdom Network detectará encabezados y propondrá lecciones y un examen final de borrador para tu aprobación.':'Paste text from the approved manual. Kingdom Network will detect likely headings and propose lesson structure plus a draft final assessment for your approval.'}</p><div className="notice" style={{marginBottom:12}}>{es?'Esto todavía no reemplaza la revisión humana ni interpreta doctrina. Organiza la estructura del texto que tú proporcionas.':'This does not replace human review or interpret doctrine. It organizes structure from the text you provide.'}</div><form action={saveSourceText} style={{display:'grid',gap:10}}><input type="hidden" name="course_id" value={courseId}/><textarea name="source_text" rows={10} defaultValue={source.source_text||''} placeholder={es?'Pega aquí el texto del manual, incluyendo títulos como “Lección 1”, “Lección 2”…':'Paste manual text here, including headings such as “Lesson 1”, “Lesson 2”…'} required/><button className="ghost">{es?'Guardar texto fuente':'Save source text'}</button></form>{source.source_text&&<form action={generateExtractionPlan} style={{marginTop:10}}><input type="hidden" name="course_id" value={courseId}/><button className="btn"><WandSparkles size={14}/> {es?'Proponer estructura':'Propose course structure'}</button></form>}{plan&&<div className="card" style={{padding:16,marginTop:14,background:'rgba(255,255,255,.025)'}}><div className="pill">{es?'PROPUESTA PARA REVISAR':'PROPOSAL TO REVIEW'}</div><h3>{plan.lessons?.length||0} {es?'lecciones detectadas':'lessons detected'}</h3><div style={{display:'grid',gap:8}}>{(plan.lessons??[]).slice(0,40).map((lesson:any)=><div key={lesson.position}><strong>{lesson.position}. {lesson.title}</strong>{lesson.summary&&<div className="small muted">{lesson.summary}</div>}</div>)}</div><div className="small muted" style={{marginTop:12}}>{plan.notes}</div>{!hasLessons&&source.extraction_status!=='applied'&&<form action={applyExtractionPlan} style={{marginTop:12}}><input type="hidden" name="course_id" value={courseId}/><button className="btn"><CheckCircle2 size={14}/> {es?'Aprobar y crear borradores':'Approve and create drafts'}</button></form>}{source.extraction_status==='applied'&&<div className="notice success" style={{marginTop:12}}>{es?'Propuesta aplicada como borrador. Revisa cada lección antes de publicar.':'Proposal applied as drafts. Review every lesson before publishing.'}</div>}</div>}</section>}
 {source&&<section className="card" style={{padding:18,marginBottom:18}}><div className="pill"><FileText size={12}/> {es?'FUENTE ORIGINAL':'SOURCE MATERIAL'}</div><h3>{source.file_name}</h3><p className="muted">{source.notes|| (es?'Archivo aprobado desde la Bandeja de Configuración.':'Approved through the Setup Inbox.')}</p><Link className="ghost" href={l('/church/setup-inbox')}>{es?'Ver Bandeja de Configuración →':'View Setup Inbox →'}</Link></section>}
 <section className="stat-grid"><div className="card stat-card"><BookOpen/><div><strong>{modules?.length||0}</strong><span>{es?'Lecciones':'Lessons'}</span></div></div><div className="card stat-card"><ClipboardCheck/><div><strong>{assessments?.length||0}</strong><span>{es?'Pruebas':'Assessments'}</span></div></div><div className="card stat-card"><GraduationCap/><div><strong>{course.badge_name?'✓':'—'}</strong><span>{es?'Certificado / insignia':'Certificate / badge'}</span></div></div><div className="card stat-card"><CheckCircle2/><div><strong>{course.published?'LIVE':'DRAFT'}</strong><span>{es?'Estado':'Status'}</span></div></div></section>
 <div className="content-grid"><section style={{display:'grid',gap:16}}><form action={saveBuilderCourse} className="card" style={{padding:20,display:'grid',gap:10}}><div className="pill">1 • {es?'IDENTIDAD DEL CURSO':'COURSE IDENTITY'}</div><input type="hidden" name="course_id" value={courseId}/><label className="field"><span>{es?'Título':'Title'}</span><input name="title" defaultValue={course.title} required/></label><label className="field"><span>{es?'Descripción':'Description'}</span><textarea name="description" rows={4} defaultValue={course.description||''}/></label><div className="row"><label className="field" style={{flex:1}}><span>{es?'Idioma':'Language'}</span><select name="language_code" defaultValue={course.language_code||'en'}><option value="en">English</option><option value="es">Español</option></select></label><label className="field" style={{flex:1}}><span>{es?'Puntaje mínimo (80–100)':'Passing score (80–100)'}</span><input name="passing_score" type="number" min="80" max="100" defaultValue={Math.max(80,Number(course.passing_score||80))}/></label></div><label className="field"><span>{es?'Nombre del certificado / insignia':'Certificate / badge name'}</span><input name="badge_name" defaultValue={course.badge_name||''}/></label><button className="btn">{es?'Guardar curso':'Save course'}</button></form>
 <section className="card" style={{padding:20}}><div className="pill">2 • {es?'LECCIONES':'LESSONS'}</div><h2>{es?'Revisa la estructura.':'Review the structure.'}</h2><div style={{display:'grid',gap:9}}>{(modules??[]).map((mod:any)=><div className="card" key={mod.id} style={{padding:14}}><div className="row"><span className="pill">{mod.position}</span><strong>{mod.title}</strong></div><p className="small muted">{mod.content?.summary|| (es?'Borrador listo para contenido.':'Draft ready for content.')}</p></div>)}{!modules?.length&&<form action={createLessonShells} style={{display:'grid',gap:10}}><input type="hidden" name="course_id" value={courseId}/><textarea name="lesson_titles" rows={7} placeholder={es?'Orientación\nLa Gracia de Dios\nLa Biblia':'Orientation\nThe Grace of God\nThe Bible'} required/><button className="btn"><Sparkles size={14}/> {es?'Crear lecciones manualmente':'Create lesson shells manually'}</button></form>}</div><details style={{marginTop:16}}><summary>{es?'Agregar una sola lección':'Add one lesson manually'}</summary><form action={addBuilderLesson} style={{display:'grid',gap:8,marginTop:10}}><input type="hidden" name="course_id" value={courseId}/><input name="title" required/><input name="summary"/><textarea name="body" rows={4}/><button className="ghost"><Plus size={14}/> {es?'Agregar lección':'Add lesson'}</button></form></details></section>
 <section className="card" style={{padding:20}}><div className="pill">3 • {es?'PRUEBAS':'ASSESSMENTS'}</div><h2>{es?'Agrega la estructura de evaluación.':'Add the assessment structure.'}</h2><p className="small muted">{es?'Las pruebas obligatorias requieren 80% o más. Los exámenes finales publicados deben tener 20–25 preguntas; los controles obligatorios, 5–10.':'Required tests use an 80% minimum. Published finals must contain 20–25 questions; required checkpoints must contain 5–10.'}</p>{(assessments??[]).map((a:any)=><div className="card" style={{padding:12,marginBottom:8}} key={a.id}><strong>{a.title}</strong><div className="small muted">{String(a.assessment_type).replaceAll('_',' ')} • {a.passing_score}% • {a.published?(es?'Publicado':'Published'):(es?'Borrador':'Draft')}</div></div>)}{!hasAssessment&&<form action={createCourseAssessmentShell} style={{display:'grid',gap:8}}><input type="hidden" name="course_id" value={courseId}/><input name="title" defaultValue={es?'Examen Final del Curso':'Course Final Review'}/><input name="passing_score" type="number" min="80" max="100" defaultValue={80}/><button className="btn">{es?'Crear examen de borrador':'Create draft final assessment'}</button></form>}</section></section>
 <aside><div className="card side"><div className="pill">{es?'REGLA DE SEGURIDAD':'SAFETY RULE'}</div><h3>{es?'Nada se publica solo.':'Nothing publishes itself.'}</h3><p className="muted">{es?'Un líder debe revisar doctrina, contenido, preguntas y certificado antes de publicar.':'Leadership must review doctrine, content, questions and certificate settings before publishing.'}</p></div><div className="card side"><div className="pill">{es?'ESTÁNDAR':'STANDARD'}</div><h3>{es?'La calidad se valida antes de publicar.':'Quality is checked before publishing.'}</h3><p className="muted">{es?'Kingdom Network bloqueará la publicación si faltan lecciones, un examen final obligatorio o los conteos de preguntas requeridos.':'Kingdom Network blocks publication when lessons, a required final, or required question counts are missing.'}</p></div></aside></div></main>
}
