import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Building2,Globe2,Languages,MapPin,Palette } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { LogoUploader } from './logo-uploader'
import { updateChurchSettings } from './actions'
import './settings.css'

const copy={
  en:{title:'Identity, contact & branding.',subtitle:'Keep your local church information accurate. These settings control what members see and how church-local scheduling works.',admin:'← Church Admin',home:'Home',pill:'CHURCH SETTINGS',role:'Pastor / church-admin only',saved:'Church settings saved.',profile:'PUBLIC CHURCH PROFILE',info:'Church information',name:'Church name',address:'Address',suite:'Suite / unit',city:'City',state:'State / region',postal:'Postal code',timezone:'Timezone',email:'Public contact email',phone:'Public phone',website:'Website',color:'Brand accent color',welcome:'Welcome message',welcomePlaceholder:'A short welcome message for members and future church profile pages.',save:'Save church settings',note:'Timezone is used for Calendar, Teams, Outreach follow-ups and other church-local scheduling. District, organization and church slug are protected structural fields.',preview:'BRAND PREVIEW',organization:'Organization',district:'District',slug:'Slug',unassigned:'Not assigned',brandNote:'The local logo and accent color personalize the church experience without replacing the Kingdom Network product identity.',builder:'Back to Church Builder'},
  es:{title:'Identidad, contacto y estilo de tu iglesia.',subtitle:'Mantén actualizada la información de tu iglesia. Estos datos controlan lo que ven los miembros y los horarios locales.',admin:'← Administración',home:'Inicio',pill:'CONFIGURACIÓN DE IGLESIA',role:'Solo pastor / administrador',saved:'Configuración de la iglesia guardada.',profile:'PERFIL PÚBLICO DE LA IGLESIA',info:'Información de la iglesia',name:'Nombre de la iglesia',address:'Dirección',suite:'Suite / unidad',city:'Ciudad',state:'Estado / región',postal:'Código postal',timezone:'Zona horaria',email:'Correo público de contacto',phone:'Teléfono público',website:'Sitio web',color:'Color principal',welcome:'Mensaje de bienvenida',welcomePlaceholder:'Un mensaje corto de bienvenida para los miembros.',save:'Guardar configuración',note:'La zona horaria se usa para Calendario, Equipos, seguimiento de alcance y otros horarios de la iglesia. Distrito, organización y slug están protegidos.',preview:'VISTA PREVIA',organization:'Organización',district:'Distrito',slug:'Slug',unassigned:'No asignado',brandNote:'El logo y color local personalizan la experiencia sin reemplazar la identidad de Kingdom Network.',builder:'Volver a Church Builder'}
} as const

export default async function ChurchSettingsPage({searchParams}:{searchParams:Promise<{saved?:string;error?:string;lang?:string}>}){
  const query=await searchParams
  const lang=query.lang==='es'?'es':'en';const t=copy[lang];const qs=lang==='es'?'?lang=es':''
  const supabase=await createClient()
  const {data:claims}=await supabase.auth.getClaims()
  const userId=claims?.claims?.sub
  if(!userId)redirect(`/login${qs}`)
  const {data:membership}=await supabase.from('church_memberships').select('church_id,role').eq('user_id',userId).eq('status','active').limit(1).single()
  if(!membership?.church_id||!['pastor','church_admin'].includes(membership.role))redirect('/')
  const {data:church}=await supabase.from('churches').select('id,district_id,organization_id,name,slug,city,state,timezone,logo_path,brand_color,website_url,contact_email,contact_phone,address_line1,address_line2,postal_code,welcome_message').eq('id',membership.church_id).single()
  if(!church)redirect('/church')
  const [{data:org},{data:district}]=await Promise.all([
    church.organization_id?supabase.from('organizations').select('name').eq('id',church.organization_id).maybeSingle():Promise.resolve({data:null}),
    church.district_id?supabase.from('districts').select('name').eq('id',church.district_id).maybeSingle():Promise.resolve({data:null})
  ])
  const logoUrl=church.logo_path?supabase.storage.from('church-branding').getPublicUrl(church.logo_path).data.publicUrl:null
  const color=church.brand_color||'#7B50A0'

  return <main className="shell">
    <header className="topbar"><div><Link href="/" className="brand">Kingdom <span>Network</span></Link><div className="small muted">{t.pill} • {church.name}</div></div><div className="row"><Languages size={15}/><Link className="ghost" href="/church/settings?lang=en">English</Link><Link className="ghost" href="/church/settings?lang=es">Español</Link><Link className="ghost" href={`/church/launch${qs}`}>{t.builder}</Link><Link className="ghost" href={`/church${qs}`}>{t.admin}</Link></div></header>
    <section className="settings-hero card"><div><div className="pill">{t.pill}</div><h1>{t.title}</h1><p className="muted">{t.subtitle}</p></div><div className="hero-stat"><Palette size={22}/><span>{t.role}</span></div></section>
    {query.saved&&<div className="notice success">{t.saved}</div>}{query.error&&<div className="notice error">{query.error}</div>}

    <div className="settings-layout"><section className="card settings-card"><div className="pill">{t.profile}</div><h2>{t.info}</h2><form action={updateChurchSettings} className="settings-grid"><input type="hidden" name="church_id" value={church.id}/><input type="hidden" name="lang" value={lang}/><label className="wide"><span>{t.name}</span><input name="name" required defaultValue={church.name}/></label><label><span>{t.address}</span><input name="address_line1" defaultValue={church.address_line1??''}/></label><label><span>{t.suite}</span><input name="address_line2" defaultValue={church.address_line2??''}/></label><label><span>{t.city}</span><input name="city" defaultValue={church.city??''}/></label><label><span>{t.state}</span><input name="state" defaultValue={church.state??''}/></label><label><span>{t.postal}</span><input name="postal_code" defaultValue={church.postal_code??''}/></label><label><span>{t.timezone}</span><input name="timezone" list="timezones" defaultValue={church.timezone}/><datalist id="timezones"><option value="America/Los_Angeles"/><option value="America/Denver"/><option value="America/Phoenix"/><option value="America/Chicago"/><option value="America/New_York"/><option value="America/Anchorage"/><option value="Pacific/Honolulu"/></datalist></label><label><span>{t.email}</span><input name="contact_email" type="email" defaultValue={church.contact_email??''}/></label><label><span>{t.phone}</span><input name="contact_phone" type="tel" defaultValue={church.contact_phone??''}/></label><label className="wide"><span>{t.website}</span><input name="website_url" type="url" defaultValue={church.website_url??''} placeholder="https://..."/></label><label><span>{t.color}</span><input name="brand_color" type="color" defaultValue={color}/></label><label className="wide"><span>{t.welcome}</span><textarea name="welcome_message" rows={5} defaultValue={church.welcome_message??''} placeholder={t.welcomePlaceholder}/></label><button className="btn wide">{t.save}</button></form><div className="settings-note">{t.note}</div></section>

    <aside className="card brand-preview" style={{'--preview':color} as React.CSSProperties}><div className="pill">{t.preview}</div><div className="brand-mark">{logoUrl?<img src={logoUrl} alt={`${church.name} logo`}/>:<div className="fallback" style={{color}}>{church.name.slice(0,1).toUpperCase()}</div>}</div><h2>{church.name}</h2><p className="small muted">{church.city||t.city}{church.state?`, ${church.state}`:''}</p><div className="brand-line"/><LogoUploader churchId={church.id} currentPath={church.logo_path} lang={lang}/><div className="identity"><div className="identity-row"><span><Building2 size={12}/> {t.organization}</span><strong>{org?.name??t.unassigned}</strong></div><div className="identity-row"><span><MapPin size={12}/> {t.district}</span><strong>{district?.name??t.unassigned}</strong></div><div className="identity-row"><span><Globe2 size={12}/> {t.slug}</span><strong>{church.slug}</strong></div></div><div className="settings-note">{t.brandNote}</div></aside></div>
  </main>
}
